##################################
# priv/sv/__init__.py
#
# Registry and writer for the Sv* virtual-memory suite generators.
# SPDX-License-Identifier: Apache-2.0
##################################

"""Registry and writer for the declaratively generated Sv* virtual-memory suites.

Unlike the TestChunk-based generators in ``testgen.priv.extensions``, these suites
need per-file REQUIRED_EXTENSIONS/MARCH headers, local ``.macro`` blocks, and custom
data sections (page tables, an executable test region), so each suite is described
as a list of :class:`~testgen.priv.sv.model.FileSpec` and rendered directly to .S
files by :func:`~testgen.priv.sv.emit.render_file`.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from testgen.discovery import discover_and_import_modules
from testgen.priv.sv.emit import render_file
from testgen.priv.sv.model import FileSpec

SuiteBuilder = Callable[[], "list[FileSpec]"]

_SV_SUITES: dict[str, SuiteBuilder] = {}


def add_sv_suite(testsuite: str) -> Callable[[SuiteBuilder], SuiteBuilder]:
    """Decorator registering a builder that returns the FileSpecs for one Sv* suite."""

    def decorator(func: SuiteBuilder) -> SuiteBuilder:
        _SV_SUITES[testsuite] = func
        return func

    return decorator


def get_sv_suite_names() -> list[str]:
    """Names of all registered Sv* suites."""
    return list(_SV_SUITES.keys())


def is_sv_suite(testsuite: str) -> bool:
    """Whether ``testsuite`` is generated by the Sv* virtual-memory suite generator."""
    return testsuite in _SV_SUITES


def write_sv_suite(testsuite: str, output_test_dir: Path) -> None:
    """Render every file of one Sv* suite into ``<output_test_dir>/priv/<testsuite>/``."""
    specs = _SV_SUITES[testsuite]()
    output_path = output_test_dir / "priv" / testsuite
    output_path.mkdir(parents=True, exist_ok=True)
    for spec in specs:
        (output_path / spec.filename).write_text(render_file(spec))
    stale = sorted({p.name for p in output_path.glob("*.S")} - {spec.filename for spec in specs})
    if stale:
        print(
            f"WARNING: {output_path} contains files not produced by the {testsuite} generator "
            f"(stale ghosts — delete by name): {', '.join(stale)}"
        )


# Discover and import suite tables at module load to trigger decorator registration
discover_and_import_modules(Path(__file__).parent / "suites", "testgen.priv.sv.suites")
