##################################
# priv/sv/emit.py
#
# File renderer for the Sv* virtual-memory suite generators.
# SPDX-License-Identifier: Apache-2.0
##################################

"""Render :class:`FileSpec` descriptions into complete .S test files."""

from __future__ import annotations

from testgen.priv.sv.macros import DATA_REGION, HR
from testgen.priv.sv.model import FileSpec

_SIGUPD_MARGIN = 10
_TRAP_WORDS_PER_FAULT = 6
_TRAP_MARGIN = 10

_GENERATED_NOTICE = (
    "// This file was generated by testgen (generators/testgen/src/testgen/priv/sv); do not edit by hand."
)


def _round_up5(value: int) -> int:
    return ((value + 4) // 5) * 5


def _mode_letter(spec: FileSpec) -> str:
    return spec.priv_mode[0]  # "S" or "U"


def _perm_str(tokens: tuple[str, ...], umode: bool) -> str:
    """Join PTE permission tokens, inserting PTE_U before the X/W/R/V group for U-mode."""
    toks = list(tokens)
    if umode:
        anchor = next((i for i, t in enumerate(toks) if t in ("PTE_X", "PTE_W", "PTE_R", "PTE_V")), len(toks))
        toks.insert(anchor, "PTE_U")
    return " | ".join(toks)


def _total_faults(spec: FileSpec) -> int:
    return sum(c.faults for c in spec.cases) + sum(c.faults for c in spec.sv_cases)


def _total_sigupds(spec: FileSpec) -> int:
    if spec.cases:
        return len(spec.cases) * len(spec.sig_ops)
    return sum(c.sigupds if c.sigupds is not None else len(c.sig_strs) for c in spec.sv_cases)


def _render_banner(spec: FileSpec) -> list[str]:
    mode = _mode_letter(spec)
    lines = [HR]
    lines.extend(spec.banner_prefix.format(mode=mode).strip("\n").splitlines())
    if spec.banner_body is not None:
        lines.append(HR)
        lines.extend(spec.banner_body.format(mode=mode).strip("\n").splitlines())
        lines.append(HR)
        return lines
    lines.extend([HR, "// Test cases are as follows:", HR])
    for n, case in enumerate(spec.cases, start=1):
        desc = f"{case.banner_desc} at level {case.level}, RWX permissions (read, write, execute page):"
        lines.append(f"// {n}. {desc}")
        lines.append(f"//        {case.banner_result.format(mode=mode)}")
    for n, sv_case in enumerate(spec.sv_cases, start=1):
        first, *rest = sv_case.banner
        lines.append(f"// {n}. {first.format(mode=mode)}")
        lines.extend(f"//        {line.format(mode=mode)}" for line in rest)
    lines.append("//")
    lines.append(f"// Total Expected Faults :: {_total_faults(spec)}")
    lines.append(HR)
    return lines


def _render_header(spec: FileSpec) -> list[str]:
    sigupd = spec.sigupd_override
    if sigupd is None:
        sigupd = _round_up5(_total_sigupds(spec) + _SIGUPD_MARGIN)
    lines = [
        "",
        "##### START_TEST_CONFIG #####",
        f"# REQUIRED_EXTENSIONS: [{', '.join(spec.required_extensions)}]",
        *(["# params:", *(f"#   {p}" for p in spec.params)] if spec.params else []),
        f"# MARCH: {spec.march}",
        "##### END_TEST_CONFIG #####",
        "",
        f"#define SIGUPD_COUNT {sigupd}",
    ]
    if spec.emit_trap_count:
        trap = spec.trap_override
        if trap is None:
            trap = _round_up5(_total_faults(spec) * _TRAP_WORDS_PER_FAULT + _TRAP_MARGIN)
        lines.append(f"#define TRAP_SIGUPD_COUNT {trap}")
    lines.extend(spec.extra_defines)
    lines.extend(["", "", '#include "riscv_arch_test.h"', "", "RVTEST_BEGIN", ""])
    return lines


def _render_macros(spec: FileSpec) -> list[str]:
    lines: list[str] = []
    if spec.code_guard:
        lines.extend([f"#ifdef {spec.code_guard}", ""])
    lines.append(HR)
    for i, block in enumerate(spec.macro_blocks):
        if i:
            lines.append("")
        lines.extend(block.strip("\n").splitlines())
    lines.append("")
    return lines


def _render_prologue(spec: FileSpec) -> list[str]:
    sv = spec.svmode
    umode = spec.priv_mode == "Umode"
    top = sv.levels - 1
    code_perms = _perm_str(("PTE_D", "PTE_A", "PTE_X", "PTE_R", "PTE_V"), umode)
    va_defs = spec.va_defs if spec.va_defs is not None else (("va_data", sv.va_data),)
    lines = ["", "main:"]
    if spec.sig_init:
        lines.append(spec.sig_init)
    if spec.pre_va_asm:
        lines.append("")
        lines.extend(spec.pre_va_asm)
    lines += [
        "",
        HR,
        "//                                   Virtual addresses definition for code and test regions",
        HR,
        "",
        "  // Virtual Address of Test section (rvtest_data_1)",
    ]
    lines.extend(f"  .set {name + ',':<23}{value}" for name, value in va_defs)
    lines.extend(
        [
            "",
            "  // Virtual Address for code region",
            f"  .set {'va_rvtest_code_begin,':<23}{spec.va_code_override or sv.va_code}",
            "",
            "",
            "  // PTE setup for Code Region",
            f"  SUPERPAGE_PTE_SETUP_{sv.suffix}(rvtest_code_begin, ({code_perms}), va_rvtest_code_begin, LEVEL{top})",
        ]
    )
    if spec.code_pte_change_be:
        lines.append("  CHANGE_PTE_TO_BE")
    lines.extend(
        [
            "  sfence.vma",
            "",
            "  // Save area setup for code region",
            "  csrr a0, mscratch",
            f"  SAVE_AREA_SETUP(va_rvtest_code_begin, rvtest_code_begin, code, LEVEL{top})",
            "",
            HR,
            "//                                               Test Cases Start from here",
            HR,
            "",
            f"  {sv.satp_setup:<73}// Set SATP for virtualization",
            f"  {'sfence.vma':<73}// Flush TLB",
        ]
    )
    if spec.setup_asm:
        lines.append("")
        lines.extend(spec.setup_asm)
    lines.append("")
    return lines


def _level_header(spec: FileSpec, level: int, new_group: bool) -> list[str]:
    sv = spec.svmode
    lines: list[str] = []
    if new_group:
        level_title = f"TESTS AT LEVEL {level}"
        lines.extend([HR, HR, f"//{level_title:^129}".rstrip(), HR])
    else:
        lines.append(HR)
    page = f"{sv.page_names[level] + ' PAGE':<12}"
    region = f"Region 1 under test at level {level} -- RWX permissions given to the region"
    lines.extend([f"//                  {page}{region}", HR, ""])
    return lines


def _render_cases(spec: FileSpec) -> list[str]:
    sv = spec.svmode
    umode = spec.priv_mode == "Umode"
    mode = _mode_letter(spec)
    lines: list[str] = []
    prev_level: int | None = None
    for n, case in enumerate(spec.cases, start=1):
        lines.extend(_level_header(spec, case.level, case.level != prev_level))
        prev_level = case.level
        inline = f"{case.inline_desc} | Test in {mode}-Mode | RWX bit set | expected = {case.inline_result}"
        lines.append(f"  // Test case {n}: {inline}")
        for j in range(sv.levels - 2, case.level - 1, -1):
            lines.append(f"  PTE_SETUP_{sv.suffix}(rvtest_slvl{j}_pg_tbl, ({case.walk_perms}), va_data, LEVEL{j + 1})")
        leaf_macro = "SUPERPAGE_PTE_SETUP" if (case.superpage and case.level > 0) else "PTE_SETUP"
        leaf_perms = _perm_str(case.leaf_perms, umode)
        lines.append(f"  {leaf_macro}_{sv.suffix}(rvtest_data_1, ({leaf_perms}), va_data, LEVEL{case.level})")
        lines.append("  sfence.vma")
        lines.extend(case.pre_asm)
        lines.append("")
        lines.append(f"  TEST_CASES_RUNNER {spec.priv_mode}, va_data, LEVEL{case.level}, test{n}")
        lines.extend(case.post_asm)
        lines.append("")
    for n, sv_case in enumerate(spec.sv_cases, start=1):
        if sv_case.level is not None:
            lines.extend(_level_header(spec, sv_case.level, sv_case.level != prev_level))
            prev_level = sv_case.level
        elif n > 1:
            lines.append("")
        lines.extend(line.format(mode=mode) for line in sv_case.body)
        lines.append("")
    return lines


def _render_footer(spec: FileSpec) -> list[str]:
    sv = spec.svmode
    lines = ["", HR]
    if spec.code_guard:
        lines.extend(["#endif", ""])
    lines.extend(["RVTEST_CODE_END", "RVTEST_DATA_BEGIN", ""])
    if spec.cases:
        levels = sorted({c.level for c in spec.cases})
    else:
        levels = sorted({c.level for c in spec.sv_cases if c.level is not None})
    lines.extend(
        [
            HR,
            "//                                            PHYSICAL ADDRESS REGION FOR TESTING",
            HR,
        ]
    )
    if levels:
        level_txt = str(levels[0]) if len(levels) == 1 else f"{', '.join(map(str, levels[:-1]))} and {levels[-1]}"
        lines.append(f"// Physical Address region under testing for LEVEL {level_txt}")
    if spec.data_align != 12:
        lines.append(f"// Aligned to a {1 << spec.data_align} byte boundary")
    region = spec.data_region_body if spec.data_region_body is not None else DATA_REGION
    region = region.replace(".p2align 12", f".p2align {spec.data_align}", 1) if spec.data_align != 12 else region
    lines.extend(region.strip("\n").splitlines())
    if spec.emit_page_tables:
        lines.extend(["", HR, "", "// Page Tables", ".p2align 12"])
        for j in range(sv.levels - 1):
            lines.extend([f"rvtest_slvl{j}_pg_tbl:", "    .skip(4096)"])
    lines.append("")
    if spec.cases:
        for n in range(1, len(spec.cases) + 1):
            labels = [f"test{n}_{op}_str:" for op, _ in spec.sig_ops]
            width = max(map(len, labels)) + 1
            for (_, insn), label in zip(spec.sig_ops, labels, strict=True):
                lines.append(f'{label:<{width}}.string "\\"Mismatch during {insn} in Test Case {n}!\\""')
    else:
        all_labels = [f"{label}_str:" for c in spec.sv_cases for label, _ in c.sig_strs]
        width = max(map(len, all_labels), default=0) + 1
        for sv_case in spec.sv_cases:
            for label, message in sv_case.sig_strs:
                lines.append(f'{label + "_str:":<{width}}.string "\\"{message}\\""')
    lines.extend(["", "RVTEST_DATA_END", "RVTEST_SIG_SETUP", ""])
    return lines


def render_file(spec: FileSpec) -> str:
    """Render one complete .S test file from its FileSpec."""
    if spec.body_template is not None:
        mode = _mode_letter(spec)
        body = spec.body_template.format(mode=mode).strip("\n")
        parts = [_GENERATED_NOTICE, *_render_banner(spec), *_render_header(spec), body, ""]
        return "\n".join(parts)
    parts = [
        _GENERATED_NOTICE,
        *_render_banner(spec),
        *_render_header(spec),
        *_render_macros(spec),
        *_render_prologue(spec),
        *_render_cases(spec),
        *_render_footer(spec),
    ]
    return "\n".join(parts)
