# SPDX-License-Identifier: Apache-2.0
# Jordan Carlin jcarlin@hmc.edu April 2026
# CI configuration for Imperas simulator
# Imperas is proprietary and cannot run in public CI.

ci_enabled: false
exclude_extensions: # These exclusions don't affect CI because it doesn't run, but they help tracking incomplete features
  - Sm # Insufficient WARL configuration options.
  - SsstrictSm # Sail does not yet implement hypervisor instructions/CSRs.
  - SsstrictS # Sail does not yet implement hypervisor instructions/CSRs.
  - SsstrictU # Sail does not yet implement hypervisor instructions/CSRs.
  - SsstrictV # Sail does not yet implement SsstrictV.
  - Zkr # https://github.com/riscv/sail-riscv/issues/1829
  - ExceptionsSvZalrsc # Imperas raises load page fault before misaligned LR access fault under Sv39; no Imperas parameter changes this priority.
  - InterruptsSm # Imperas does not implement interrupts.
  - InterruptsS # Imperas does not implement interrupts.
  - InterruptsSSm # Imperas does not implement interrupts.
  - InterruptsU # Imperas does not implement interrupts.
  - Smstateen # Sail does not implement all state yet to match.
  - SdtrigSm # Sail does not yet support Sdtrig; Imperas also does not yet match Spike.
  - SdtrigS # Sail does not yet support Sdtrig; Imperas also does not yet match Spike.
  - SdtrigU # Sail does not yet support Sdtrig; Imperas also does not yet match Spike.
