#!/usr/bin/env python3
##################################
# run_tests.py
#
# jcarlin@hmc.edu Jan 2026
# SPDX-License-Identifier: Apache-2.0
#
# Run all ELFs for a spike configuration in parallel
##################################

from __future__ import annotations

import argparse
import os
import re
import shlex
import subprocess
import sys
from functools import partial
from multiprocessing import Pool
from pathlib import Path

_SUMMARY_RE = re.compile(r'RVCP-SUMMARY (PASSED|FAILED|SIGRUN): Test File ".*"')

# ANSI color codes — disabled when stdout is not a terminal
USE_COLOR = sys.stdout.isatty()


def _color(code: str, text: str) -> str:
    if USE_COLOR:
        return f"\033[{code}m{text}\033[0m"
    return text


def red(text: str) -> str:
    return _color("1;31", text)


def green(text: str) -> str:
    return _color("1;32", text)


def bold(text: str) -> str:
    return _color("1", text)


def dim(text: str) -> str:
    return _color("2", text)


def run_test(command: str, log_dir: Path, elf_path: Path, verbose: bool) -> bool:
    """Run a single ELF and return success indication."""

    # Split command, extracting leading KEY=VALUE env var assignments
    tokens = shlex.split(command)
    env_overrides: dict[str, str] = {}
    while tokens and "=" in tokens[0] and not tokens[0].startswith("-"):
        key, _, value = tokens.pop(0).partition("=")
        env_overrides[key] = value
    env = {**os.environ, **env_overrides} if env_overrides else None
    cmd = tokens

    # Create log file path
    log_file = log_dir / elf_path.parent.name / elf_path.with_suffix(".log").name
    log_file.parent.mkdir(parents=True, exist_ok=True)

    full_cmd = [*cmd, str(elf_path)]
    display_cmd = f"{command} {elf_path}"

    if verbose:
        print(f"\nRunning {display_cmd}")

    with log_file.open("w") as f:
        print("This log file generated by running:", file=f)
        print(f"{display_cmd}\n", file=f)
        f.flush()
        result = subprocess.run(
            full_cmd, stdin=subprocess.DEVNULL, stdout=f, stderr=subprocess.STDOUT, timeout=5 * 60, check=False, env=env
        )

    # Check exit code
    exit_failed = result.returncode != 0

    # Check log for RVCP-SUMMARY lines
    log_text = log_file.read_text(errors="replace")
    summaries = _SUMMARY_RE.findall(log_text)
    summary_failed = "TEST FAILED" in summaries
    summary_sigrun = "SIGRUN" in summaries
    no_summary = len(summaries) == 0

    # Overall failure for test
    failed = exit_failed or summary_failed or summary_sigrun

    # Print failure message for test
    if summary_sigrun:
        print(
            f"  {red('FAIL')}  {bold(elf_path.name)} — RVCP-SUMMARY reports SIGRUN"
            f"\n         ELF was not built with RVTEST_SELFCHECK enabled (non-selfchecking test)."
            f"\n         Log: {dim(str(log_file))}"
        )
    elif exit_failed and no_summary:
        print(
            f"  {red('FAIL')} {bold(elf_path.name)} — exit code {result.returncode} indicates failure, no RVCP-SUMMARY line found"
            f"\n         Likely abnormal termination (killed, crash, timeout) or bug in RVMODEL_IO_WRITE macro."
            f"\n         Log: {dim(str(log_file))}"
        )
    elif exit_failed and summary_failed:
        print(
            f"  {red('FAIL')}  {bold(elf_path.name)} — exit code {result.returncode}"
            f"\n         Log: {dim(str(log_file))}"
        )
    elif summary_failed and not exit_failed:
        print(
            f"  {red('FAIL')}  {bold(elf_path.name)} — RVCP-SUMMARY: TEST FAILED but exit code {result.returncode} indicates success"
            f"\n         If this is an ImperasFPM test, it is due to ImperasFPM not yet supporting failure exit code.  Otherwise likely bug in RVMODEL_HALT_FAIL macro."
            f"\n         Log: {dim(str(log_file))}"
        )
    elif exit_failed and not summary_failed:
        print(
            f"  {red('FAIL')}  {bold(elf_path.name)} — RVCP-SUMMARY: TEST PASSED but exit code {result.returncode} indicates failure"
            f"\n         Likely bug in RVMODEL_HALT_PASS macro."
            f"\n         Log: {dim(str(log_file))}"
        )

    return failed


def main() -> int:
    parser = argparse.ArgumentParser(description="Run all ELF files using the provided command")
    parser.add_argument(
        "command", type=str, help="Command to run each ELF (elf path will be appended). E.g., 'spike --isa=rv64gc'"
    )
    parser.add_argument("elf_dir", type=Path, help="Path to ELF directory (e.g., work/spike-rv64/elfs)")
    parser.add_argument("-j", "--jobs", type=int, default=os.cpu_count(), help="Number of parallel jobs")
    parser.add_argument("-v", "--verbose", action="store_true", help="Print the full command for every test")
    args = parser.parse_args()

    elf_dir = args.elf_dir.resolve()
    log_dir = elf_dir.parent / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    # Find all ELFs
    elf_files = sorted(elf_dir.rglob("*.elf"))
    if not elf_files:
        print(f"No ELF files found in {elf_dir}")
        sys.exit(1)

    partial_run_test = partial(run_test, args.command, log_dir, verbose=args.verbose)

    failed = 0

    print(f"\n{bold('Running')} {len(elf_files)} tests in {elf_dir}")
    print(f"  Command: {args.command}")

    # Run individual tests
    with Pool(args.jobs) as pool:
        for fail_status in pool.imap_unordered(partial_run_test, elf_files):
            if fail_status:
                failed += 1

    # Print overall results
    passed = len(elf_files) - failed
    print()
    if failed:
        print(red(f"RESULT: {failed} failed, {passed} passed out of {len(elf_files)} tests."))
    else:
        print(green(f"RESULT: All {len(elf_files)} tests passed."))

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
