// rvtest_config.h for cv64a60ax
#define CONFORMING_SM_SUPPORTED
#define RVMODEL_PMP_GRAIN 1
#define RVMODEL_NUM_PMPS 8
#define D_SUPPORTED
#define F_SUPPORTED
#define ZBB_SUPPORTED
#define ZBA_SUPPORTED
#define ZBS_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZCA_SUPPORTED
#define ZCB_SUPPORTED
#define ZCD_SUPPORTED
#define S_SUPPORTED
#define U_SUPPORTED
#define H_SUPPORTED
#define SV39_SUPPORTED

#define TIME_CSR_IMPLEMENTED 1
