#define RVMODEL_ACCESS_FAULT_ADDRESS 0x00000000
#define RVMODEL_PMP_GRAIN 4
#define RVMODEL_NUM_PMPS 0

#define D_SUPPORTED
#define F_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZCA_SUPPORTED
#define ZCD_SUPPORTED
#define ZCF_SUPPORTED
