
=== A Atomic Extension

The A extension is subdivided into Zaamo and Zalrsc.  It also has related Zabha and Zacas extensions.
 <<t-A-normative-rules>> lists the normative rules in the RV{32/64}A specification applicable to all instructions, and the unprivileged coverpoints that exercise them.

[[t-A-normative-rules]]
.A Normative Rules
[cols="1, 4, 2" options=header]
|===
|Unpriv Section|Normative Rule|Coverpoints
|===

<<t-A-priv-normative-rules>> summarizes normative rules relating to atomic instructions affecting privileged behavior.

==== Zaamo Atomic Memory Operations Extension

<<t-Zaamo-coverpoints>> summarizes the coverpoints for the Zaamo extension.

[[t-Zaamo-coverpoints]]
.Zaamo Instruction Coverpoints
include::{testplansdir}/Zaamo.adoc[]

[[t-Zaamo-normative-rules]]
.Zaamo Normative Rules
[cols="1, 4, 2" options=header]
|===

|===

*UDB Parameters:* None. The MISALIGNED_AMO parameter affects the expected results of ExceptionsZaamo/cp_amo_address_misaligned (<<t-ExceptionsZaamo-coverpoints>>), but not Zaamo.

==== Zalrsc Load-Reserved / Store-Conditional Extension

<<t-Zalrsc-coverpoints>> summarizes the coverpoints for the Zalrsc extension.

[[t-Zalrsc-coverpoints]]
.Zalrsc Instruction Coverpoints
include::{testplansdir}/Zalrsc.adoc[]

[[t-Zalrsc-coverpoint-definitions]]
.Zalrsc Coverpoint Definitions
[cols="2, 1, 4" options=header]
|===
|Coverpoint|Bins|Definition
3+^|cp_custom_lr coverpoints
|cp_custom_aqrl|3|none, aq, aqrl
|cp_custom_rd_edges|3|rd_value = 0, 1, -1
3+^|cp_custom_sc coverpoints
|cp_custom_aqrl|3|none, rl, aqrl
|cp_custom_sc_after_sc|2|sc followed by sc
|cp_custom_sc_after_store|4|store followed by sc
|cp_custom_sc_after_load|6|load followed by sc
|cp_custom_sc_lrsc|2|lr followed by sc that fails and passes
|cp_custom_sc_address|16|lr followed by sc at address of 0, 4, 8, ..., 60 offset from lr address
|===


[[t-Zalrsc-normative-rules]]
.Zalrsc Normative Rules
[cols="1, 4, 2" options=header]
|===
|===


TODO: On implementations that support the C extension, compressed forms of the
I instructions permitted inside constrained LR/SC sequences, as
described in <<sec:lrscseq>>, are also permitted.

*UDB Parameters:*

* LRSC_RESERVATION_STRATEGY affects the expected results of sc_w/cp_custom_sc_address.
* LRSC_FAIL_ON_NON_EXACT_LRSC affects the expected results of sc_d/cg_cp_custom_sc_lrsc and sc_w/cp_custom_sc_address.
* The LRSC_MISALIGNED_BEHAVIOR parameter affects the expected results of ExceptionsZalrsc/cp_{load/store}_address_misaligned (<<t-ExceptionsZalrsc-coverpoints>>).
* LRSC_FAIL_ON_VA_SYNONYM is not tested.
