
=== A Atomic Extension

The A extension is subdivided into Zaamo and Zalrsc.

This section exercises unprivileged tests that will not trap.  Privileged tests are in other sections, such as ExceptionsZaamo.

==== Zaamo Atomic Memory Operations Extension

<<t-Zaamo-coverpoints>> summarizes the coverpoints for the Zaamo extension.

[[t-Zaamo-coverpoints]]
.Zaamo Instruction Coverpoints
include::{testplansdir}/Zaamo.adoc[]

include::norm/Zaamo_norm_rules.adoc[]

[NOTE]
This test suite is unprivileged and does not perform misaligned accesses. The MISALIGNED_AMO parameter affects the expected results of ExceptionsZaamo/cp_amo_address_misaligned (<<t-ExceptionsZaamo-coverpoints>>).

==== Zalrsc Load-Reserved / Store-Conditional Extension

<<t-Zalrsc-coverpoints>> summarizes the coverpoints for the Zalrsc extension.

[[t-Zalrsc-coverpoints]]
.Zalrsc Instruction Coverpoints
include::{testplansdir}/Zalrsc.adoc[]

[[t-Zalrsc-coverpoint-definitions]]
.Zalrsc Coverpoint Definitions
[cols="2, 1, 4" options=header]
|===
|Coverpoint|Bins|Definition
3+^|cp_custom_lr coverpoints
|cp_custom_aqrl|3|none, aq, aqrl
|cp_custom_rd_edges|3|rd_value = 0, 1, -1
3+^|cp_custom_sc coverpoints
|cp_custom_aqrl|3|none, rl, aqrl
|cp_custom_sc_after_sc|2|sc followed by sc
|cp_custom_sc_after_store|4|store followed by sc
|cp_custom_sc_after_load|6|load followed by sc
|cp_custom_sc_lrsc|2|lr followed by sc that fails and passes
|cp_custom_sc_address|16*2|lr followed by sc at address of 0, 8, ..., 120 offset from lr address.  For RV64, exercise both lr.d and lr.w
|===

include::norm/Zalrsc_norm_rules.adoc[]

TODO: On implementations that support the C extension, compressed forms of the
I instructions permitted inside constrained LR/SC sequences, as
described in <<sec:lrscseq>>, are also permitted.
