
=== C Compressed Extension

The C extension is subdivided into Zca, Zcf, and Zcd.  All configurations supporting C contain Zca.  RV32CF configurations also contain Zcf, and RV{32/64}CD configurations also contain Zcd.  A configuration supporting C should test all of the applicable Zc* extensions.

<<t-C-priv-normative-rules>> summarizes normative rules relating to compressed instructions affecting privileged behavior. ***update

==== Zca Compressed Extension

<<t-Zca-coverpoints>> summarizes the coverpoints for the Zca extension.
These include standard compressed hints in the cp_custom_chint_* family (also called cp_chint_*).  Note that some of the hints are also compresssed
Zihintntl hints.  Custom compressed hints are not certified because they are custom.

include::{testplansdir}/Zca.adoc[]

Modified coverpoints for Zc* are summarized in <<t-Zc-modified-coverpoints>>.  As defined in <<t-unprivileged-coverpoints>>, the p versions of coverpoints work on registers x8-x15.

[[t-Zc-modified-coverpoints]]
.Zc Modified Coverpoints
[cols="2, 1, 4" options=header]
|===
|Modified Coverpoint|Bins|Definition
|cr_rs1_imm_edges_6bit|16*13|rs1 edges x Signed 6-bit immediates 0, 1, 2, 3, 4, 8 16, 30, 31, -32, -31, -2, -1
|cr_rs1_imm_edges_6bit_n0|16*12|rs1 edges x cp_rs1_imm_edges_6bit excluding 0
|cr_rs1_imm_edges_c|16*11|rs1 edges x unsigned 5 or 6-bit uimm 1, 2, 3, 4, 8, 14, 15, 16, 17, 30, 31. XLEN=64 adds 32, 33, 48, 62, 63
|cp_imm_edges_c_jal|21|Selected signed multiples of 2 from -2048 to 1024
|cmp_rs1_rs2_c|8|Same register x8-x15 for both rs1 and rs2 (and hence rd)
|cp_imm_mul|31|Multiples of 4 from 0 to 124
|cp_imm_mul_4sp|63|Multiples of 4 from 0 to 252
|cp_imm_mul_8|31|Multiples of 4 from 0 to 248
|cp_imm_mul_8sp|63|Multiples of 8 from 0 to 504
|cp_imm_mul_addi16sp|63|Multiples of 16 from -512 to 496
|cp_imm_mul_addi4spn|255|Multiples of 4 from 4 to 1020
|cp_offset_jr|2 + 4|cp_offset + rs1_val[1:0] affecting lsb of load/store address
|cp_custom_chint|63+31+64+63+31+31|Compressed standard hints using `c.nop`, `c.addi`, `c.li`, `c.lui`, `c.mv`, `c.add`
|===


include::norm/Zca_norm_rules.adoc[]

*** check that c-lui_hint and c-sra_hint normative rules in table above get populated when
https://github.com/RISC-V-Certification-Steering-Committee/riscv-isa-manual/pull/167/changes
is merged.



==== Zcf Compressed Floating-Point Extension

<<t-Zcf-coverpoints>> summarizes the coverpoints for the Zcf extension.

include::{testplansdir}/Zcf.adoc[]

include::norm/Zcf_norm_rules.adoc[]



==== Zcd Compressed Double-Precision FP Extension

<<t-Zcd-coverpoints>> summarizes the coverpoints for the Zcd extension.

include::{testplansdir}/Zcd.adoc[]

include::norm/Zcd_norm_rules.adoc[]



==== Zcb Additional Compressed Instructions

<<t-Zcb-coverpoints>> summarizes the coverpoints for the Zcb extension.

include::{testplansdir}/Zcb.adoc[]

include::norm/Zcb_norm_rules.adoc[]



===== ZcbM

When both Zcb and M are supported, add the instruction in <<t-ZcbM-coverpoints>> to the Zcb coverpoints.

include::{testplansdir}/ZcbM.adoc[]

include::norm/ZcbM_norm_rules.adoc[]



===== ZcbZba

When both Zcb and Zba are supported, add the instruction in <<t-ZcbZba-coverpoints>> to the Zcb coverpoints.

include::{testplansdir}/ZcbZba.adoc[]

include::norm/ZcbZba_norm_rules.adoc[]



===== ZcbZbb

When both Zcb and Zbb are supported, add the instructions in <<t-ZcbZbb-coverpoints>> to the Zcb coverpoints.

include::{testplansdir}/ZcbZbb.adoc[]

include::norm/ZcbZbb_norm_rules.adoc[]
