
=== C Compressed Extension

The C extension is subdivided into Zca, Zcf, and Zcd.  All configurations supporting C contain Zca.  RV32CF configurations also contain Zcf, and RV{32/64}CD configurations also contain Zcd.  A configuration supporting C should test all of the applicable Zc* extensions. <<t-C-normative-rules>> lists the normative rules in the RV{32/64}C specification applicable to all instructions, and the unprivileged coverpoints that exercise them.

[[t-C-normative-rules]]
.C Normative Rules
[cols="1, 4, 2" options=header]
|===
|Unpriv Section|Normative Rule|Coverpoints
|27.1|The C extension allows
16-bit instructions to be freely intermixed with 32-bit instructions, with the latter now able to start on
any 16-bit boundary, i.e., IALIGN=16.|***
|27.1|The compressed instruction encodings are mostly common across RV32C and
RV64C, but as shown in <<rvc-instr-table0, Table 34>>, a few opcodes are used for
different purposes depending on base ISA.|Run relevant test suites. ***drop
|27.1|If the C extension is implemented, the appropriate compressed
floating-point load and store instructions must be provided whenever the relevant standard floating-
point extension (F and/or D) is also implemented.|Run relevant test suites. ***drop
|27.2|CR, CI, and CSS can use any of the 32 RVI registers, but CIW,
CL, CS, CA, and CB are limited to just 8 of them.|cp_rs1p, cp_rs2p, cp_rdp
|27.2|Compressed register-based floating-point loads and stores also use the
CL and CS formats respectively, with the eight registers mapping to `f8` to `f15`.|cp_fdp, cp_fs2p
|27.2|For many RVC instructions, zero-valued immediates are disallowed and
`x0` is not a valid 5-bit register specifier.|cp_rs1_imm_edges,cp_imm_mul, _nx0 coverpoints
|27.4|As with base RVI instructions, the offsets of all RVC
control transfer instructions are in multiples of 2 bytes.|***
|27.7|A portion of the RVC encoding space is reserved for microarchitectural
HINTs. ...these instructions do not
modify any architectural state, except for advancing the `pc` and any
applicable performance counters. HINTs are executed as no-ops on
implementations that ignore them.|Hints are not tested
|===

<<t-C-priv-normative-rules>> summarizes normative rules relating to compressed instructions affecting privileged behavior.

==== Zca Compressed Extension

<<t-Zca-coverpoints>> summarizes the coverpoints for the Zca extension.

[[t-Zca-coverpoints]]
.Zca Instruction Coverpoints
include::{testplansdir}/Zca.adoc[]

include::norm/Zca_norm_rules.adoc[]

==== Zcf Compressed Floating-Point Extension

<<t-Zcf-coverpoints>> summarizes the coverpoints for the Zcf extension.

[[t-Zcf-coverpoints]]
.Zcf Instruction Coverpoints
include::{testplansdir}/Zcf.adoc[]

include::norm/Zcf_norm_rules.adoc[]

==== Zcd Compressed Double-Precision FP Extension

<<t-Zcd-coverpoints>> summarizes the coverpoints for the Zcd extension.

[[t-Zcd-coverpoints]]
.Zcd Instruction Coverpoints
include::{testplansdir}/Zcd.adoc[]

include::norm/Zcd_norm_rules.adoc[]

==== Zcb Additional Compressed Instructions

<<t-Zcb-coverpoints>> summarizes the coverpoints for the Zcb extension.

[[t-Zcb-coverpoints]]
.Zcb Instruction Coverpoints
include::{testplansdir}/Zcb.adoc[]

include::norm/Zcb_norm_rules.adoc[]

===== ZcbM

When both Zcb and M are supported, add the instruction in <<t-ZcbM-coverpoints>> to the Zcb coverpoints.

[[t-ZcbM-coverpoints]]
.ZcbM Instruction Coverpoints
include::{testplansdir}/ZcbM.adoc[]

include::norm/ZcbM_norm_rules.adoc[]

===== ZcbZba

When both Zcb and Zba are supported, add the instruction in <<t-ZcbZba-coverpoints>> to the Zcb coverpoints.

[[t-ZcbZba-coverpoints]]
.ZcbZba Instruction Coverpoints
include::{testplansdir}/ZcbZba.adoc[]

include::norm/ZcbZba_norm_rules.adoc[]

===== ZcbZbb

When both Zcb and Zbb are supported, add the instructions in <<t-ZcbZbb-coverpoints>> to the Zcb coverpoints.

[[t-ZcbZbb-coverpoints]]
.ZcbZbb Instruction Coverpoints
include::{testplansdir}/ZcbZbb.adoc[]

include::norm/ZcbZbb_norm_rules.adoc[]
