
=== C Compressed Extension

The C extension is subdivided into Zca, Zcf, and Zcd.  All configurations supporting C contain Zca.  RV32CF configurations also contain Zcf, and RV{32/64}CD configurations also contain Zcd.  A configuration supporting C should test all of the applicable Zc* extensions.

<<t-C-priv-normative-rules>> summarizes normative rules relating to compressed instructions affecting privileged behavior. ***update

==== Zca Compressed Extension

<<t-Zca-coverpoints>> summarizes the coverpoints for the Zca extension.

[[t-Zca-coverpoints]]
.Zca Instruction Coverpoints
include::{testplansdir}/Zca.adoc[]

include::norm/Zca_norm_rules.adoc[]

==== Zcf Compressed Floating-Point Extension

<<t-Zcf-coverpoints>> summarizes the coverpoints for the Zcf extension.

[[t-Zcf-coverpoints]]
.Zcf Instruction Coverpoints
include::{testplansdir}/Zcf.adoc[]

include::norm/Zcf_norm_rules.adoc[]

==== Zcd Compressed Double-Precision FP Extension

<<t-Zcd-coverpoints>> summarizes the coverpoints for the Zcd extension.

[[t-Zcd-coverpoints]]
.Zcd Instruction Coverpoints
include::{testplansdir}/Zcd.adoc[]

include::norm/Zcd_norm_rules.adoc[]

==== Zcb Additional Compressed Instructions

<<t-Zcb-coverpoints>> summarizes the coverpoints for the Zcb extension.

[[t-Zcb-coverpoints]]
.Zcb Instruction Coverpoints
include::{testplansdir}/Zcb.adoc[]

include::norm/Zcb_norm_rules.adoc[]

===== ZcbM

When both Zcb and M are supported, add the instruction in <<t-ZcbM-coverpoints>> to the Zcb coverpoints.

[[t-ZcbM-coverpoints]]
.ZcbM Instruction Coverpoints
include::{testplansdir}/ZcbM.adoc[]

include::norm/ZcbM_norm_rules.adoc[]

===== ZcbZba

When both Zcb and Zba are supported, add the instruction in <<t-ZcbZba-coverpoints>> to the Zcb coverpoints.

[[t-ZcbZba-coverpoints]]
.ZcbZba Instruction Coverpoints
include::{testplansdir}/ZcbZba.adoc[]

include::norm/ZcbZba_norm_rules.adoc[]

===== ZcbZbb

When both Zcb and Zbb are supported, add the instructions in <<t-ZcbZbb-coverpoints>> to the Zcb coverpoints.

[[t-ZcbZbb-coverpoints]]
.ZcbZbb Instruction Coverpoints
include::{testplansdir}/ZcbZbb.adoc[]

include::norm/ZcbZbb_norm_rules.adoc[]
