
=== E Base Embedded Extension

The E Base ISA is a variant of I with 16 general purpose registers.  This test plan also includes tests restricted to these 16 registers for simple extensions most likely to be implemented on an embedded core.

All unprivileged tests for RV32 and RV64 can have E equivalents.  They are distinguished in the tests directory by rv32i, rv64i, rv32e, and rv64e subdirectories.
By default, the test generator only creates rv32e/rv64e tests for the following extensions because embedded cores are most likely to implement these extensions.
However, embedded tests for more extensions can be generated by editing the E_EXTENSION_TESTS variable in the riscv-arch-test generators/testgen/src/testgen/testgen.py script.

* E (base ISA)
* M (multiply/divide)
* Zmmul (multiply)
* Zca (compressed)
* Zcb (more compressed)
* Zcmp (compressed push/pop)
* Zcmt (compressed table jumps)
* Zba (bitmanip address)
* Zbb (bitmanip basic)
* Zbs (bitmanip single-bit)

The normative rule specific to the E base ISA is given in <<t-E-normative-rules>>.  Each instruction also has normative rules inherited from its extension.

include::norm/E_norm_rules.adoc[]

The E base ISA and other extensions based on it use the same coverpoints as the I base ISA.  However, the register coverpoints such as cp_rd, cpr_rs1, cp_rs2, cmp_rd_rs1, etc. only exercise the 16 registers x0 through x15
when E is enabled. (See the get_gpr_reg function in framework/src/act/fcov/coverage/RISCV_instruction_base.svh, which is controlled by the COVER_E symbol).

Privileged tests are written using only x0-x15, so they work for both E and I base ISAs.  One exception is that Ssstrict tests using the upper registers, which should be reserved and trap in E.
