
=== Interrupts

Interrupt tests are organized according to the privilege mode or extension supported.

==== InterruptsSm Machine-Mode Interrupts

These tests are run on any configuration with machine mode that supports interrupts.

[[t-InterruptsSm-coverpoints]]
.InterruptsSm Coverpoints
,===
https://docs.google.com/spreadsheets/d/18S2xJ6lxXhe2X9N9zcahoPMdvrqEnBFKdldi1fc7fOA/edit?gid=399538825#gid=399538825[Google Sheet Testplan]
,===

include::norm/InterruptsSm_norm_rules.adoc[]

TODO: coverpoints will need to ignore bins with mie.msie nonzero:
  # If a system has only one hart, or if a platform standard supports the delivery
  # of machine-level interprocessor interrupts through external interrupts (MEI)
  # instead, then mip.MSIP and mie.MSIE may both be read-only zeros.
  - name: mie_msie_maybe_rdonly0
TODO: mip.MSIP update time
  # When the memory-mapped msip register changes, it is guaranteed to be reflected
  # in mip.MSIP eventually, but not necessarily immediately.
  - name: msip_update_max_time

==== InterruptsS Supervisor-Mode Interrupts

These tests are run on any configuration with supervisor mode that supports interrupts. Note that they include tests in other modes, such as interrupts from user mode delegated to supervisor mode.

[[t-InterruptsS-coverpoints]]
.InterruptsS Coverpoints
,===
https://docs.google.com/spreadsheets/d/18S2xJ6lxXhe2X9N9zcahoPMdvrqEnBFKdldi1fc7fOA/edit?gid=664673151#gid=664673151[Google Sheet Testplan]
,===


include::norm/InterruptsS_norm_rules.adoc[]

==== InterruptsU User-Mode Interrupts

These tests are run on any configuration with user mode that supports interrupts.

[[t-InterruptsU-coverpoints]]
.InterruptsU Coverpoints
,===
https://docs.google.com/spreadsheets/d/18S2xJ6lxXhe2X9N9zcahoPMdvrqEnBFKdldi1fc7fOA/edit?gid=1458360883#gid=1458360883[Google Sheet Testplan]
,===

include::norm/InterruptsU_norm_rules.adoc[]

==== InterruptsSstc Supervisor Timer Compare Interrupts

These tests are run when the Sstc supervisor timer compare extension is supported.

[[t-InterruptsSstc-coverpoints]]
.InterruptsSstc Coverpoints
,===
https://docs.google.com/spreadsheets/d/18S2xJ6lxXhe2X9N9zcahoPMdvrqEnBFKdldi1fc7fOA/edit?gid=347804969#gid=347804969[Google Sheet Testplan]
,===

include::norm/InterruptsSstc_norm_rules.adoc[]
