
=== Ssstrict

The Ssstrict extension indicates that executing unimplemented instructions or accessing unimplemented CSR in the standard or reserved encoding spaces raises an illegal instruction exception.


No non-conforming extensions are present. Attempts to execute unimplemented opcodes
or access unimplemented CSRs in the standard or reserved encoding spaces raises an illegal
instruction exception that results in a contained trap to the supervisor-mode trap handler.

==== SsstrictM

RISC-V does not have a ratified equivalent of Ssstrict for machine mode, but this optional test suite checks the behavior of unimplemented instructions and CSRs from machine mode.

[[t-SsstrictM-coverpoints]]
.SsstrictM Coverpoints
,===
//include::{testplansdir}/SsstrictM.adoc[]
,===
https://docs.google.com/spreadsheets/d/1qJsCYdDPaSxNE1R56jsAUyoAiu4OhMlwwAvGysgx790/edit?gid=1987812700#gid=1987812700[Google Sheet Testplan]

include::norm/SsstrictM_norm_rules.adoc[]

==== SsstrictS

Attempt to issue all flavors of 32-bit instructions in the standard and reserved spaces and all 16-bit compressed instructions.  Also attempt to access all CSRs in the standard and reserved spaces.  Expect illegal instruction trap for unimplemented instructions and CSRs, matching reference model.

According to the RVA23 profile spec, the illegal instruction should be cause a trap to the supervisor trap handler.  However, delegation is the business of the firmware, not the hardware.  These tests only check that a trap occurs and matches the reference model.

[[t-SsstrictS-coverpoints]]
.SsstrictS Coverpoints
,===
//include::{testplansdir}/SsstrictS.adoc[]
,===
https://docs.google.com/spreadsheets/d/1qJsCYdDPaSxNE1R56jsAUyoAiu4OhMlwwAvGysgx790/edit?gid=593261374#gid=593261374[Google Sheet Testplan]

include::norm/SsstrictS_norm_rules.adoc[]


==== SsstrictV

Test that all behaviors called out as "reserved" in the vector specification cause an illegal instruction fault.  Required when Ssstrict and V are both present.

[[t-SsstrictV-coverpoints]]
.SsstrictV Coverpoints
,===
//include::{testplansdir}/SsstrictV.adoc[]
,===

https://docs.google.com/spreadsheets/d/11VGlIA__UYr7H47ZNqXtyYnGH5Fb41E8P9h53rN72ok/edit?gid=743730639#gid=743730639[Google Sheet Testplan]

include::norm/SsstrictV_norm_rules.adoc[]
