
=== Priv

The privileged tests exercise CSRs that are mandatory in each privilege mode.
They also tests mandatory privileged instructions: `ecall`, `ebreak`, `mret`, and `sret`.
The CSR read/write/set/clear instructions themselves are tested in the
unprivileged Zicsr tests of <<Zicsr Control/Status Register Instructions>>.

`wfi` is tested in <<Interrupts>> and `sfence.vma` is tested in <<Sv* Virtual Memory>>.

Privileged tests do not test reserved or custom instructions or CSRs because their behavior is UNSPECIFIED.
Reserved instructions and CSRs are tested in the <<Ssstrict>> Ssstrict tests,
where they should throw an Illegal Instruction exception if not implemented.

==== Sm Machine-Mode CSRs

These test CSRs and privileged instructions in machine mode.

[[t-Sm-coverpoints]]
.Sm Coverpoints
,===
//include::{testplansdir}/Sm.adoc[]
,===
https://docs.google.com/spreadsheets/d/1LEkptHit5Hs1UVtTlHc7nL0zl1ThB9_EPRIZVjQ6WdQ/edit?gid=1563313604#gid=1563313604[Google Sheet Testplan]

*** find all WPRI and WLRL fields.  Don't look at WPRI results.  Only test legal values of WLRL.
  TODO check WARL, WLRL, WPRI behaviors


==== S Supervisor-Mode CSRs

These test additional CSRs that exist in supervisor mode, and privileged instructions in supervisor mode.

[[t-S-coverpoints]]
.S Coverpoints
,===
//include::{testplansdir}/S.adoc[]
,===
https://docs.google.com/spreadsheets/d/1LEkptHit5Hs1UVtTlHc7nL0zl1ThB9_EPRIZVjQ6WdQ/edit?gid=335048477#gid=335048477[Google Sheet Testplan]

==== U User-Mode CSRs

These test additional CSRs that exist in user mode, and privileged instructions in user mode..

[[t-U-coverpoints]]
.U Coverpoints
,===
//include::{testplansdir}/U.adoc[]
,===
https://docs.google.com/spreadsheets/d/1LEkptHit5Hs1UVtTlHc7nL0zl1ThB9_EPRIZVjQ6WdQ/edit?gid=1720466356#gid=1720466356[Google Sheet Testplan]

==== ZicsrF Floating-Point CSRs

These test additional CSRs that exist when floating-point is supported.

[[t-ZicsrF-coverpoints]]
.ZicsrF Coverpoints
,===
//include::{testplansdir}/ZicsrF.adoc[]
,===
https://docs.google.com/spreadsheets/d/1LEkptHit5Hs1UVtTlHc7nL0zl1ThB9_EPRIZVjQ6WdQ/edit?gid=29805079#gid=29805079[Google Sheet Testplan]

*** this should move to F, which requires CSRs fcsr, frm, fflags

==== V Vector CSRs

These test additional CSRs that exist when vector is supported.

[[t-V-coverpoints]]
.V Coverpoints
,===
//include::{testplansdir}/V.adoc[]
,===
https://docs.google.com/spreadsheets/d/11VGlIA__UYr7H47ZNqXtyYnGH5Fb41E8P9h53rN72ok/edit?gid=416753800#gid=416753800[Google Sheet Testplan]

*** reorganize

==== V Vector Floatin-PointCSRs

These test additional CSRs that exist when vector floating-point is supported.

[[t-VF-coverpoints]]
.VF Coverpoints
,===
//include::{testplansdir}/VF.adoc[]
,===
https://docs.google.com/spreadsheets/d/11VGlIA__UYr7H47ZNqXtyYnGH5Fb41E8P9h53rN72ok/edit?gid=1892166886#gid=1892166886[Google Sheet Testplan]

*** reorganize

==== UF User-Mode Floating-Point CSRs

These test additional CSR scenarios that exist when floating-point and user mode are supported.

[[t-UF-coverpoints]]
.UF Coverpoints
,===
//include::{testplansdir}/UF.adoc[]
,===
https://docs.google.com/spreadsheets/d/1LEkptHit5Hs1UVtTlHc7nL0zl1ThB9_EPRIZVjQ6WdQ/edit?gid=242878857#gid=242878857[Google Sheet Testplan]

==== UV User-Mode Vector CSRs

These test additional CSR scenarios that exist when vector and user mode are supported.

[[t-UV-coverpoints]]
.UV Coverpoints
,===
//include::{testplansdir}/UV.adoc[]
,===
https://docs.google.com/spreadsheets/d/1LEkptHit5Hs1UVtTlHc7nL0zl1ThB9_EPRIZVjQ6WdQ/edit?gid=1488477674#gid=1488477674[Google Sheet Testplan]

==== Zkr Entropy CSR

These test CSRs when the Zkr entropy extension is supported.

[[t-ZicsrZkr-coverpoints]]
.ZicsrZkr Coverpoints
,===
//include::{testplansdir}/ZicsrZkr.adoc[]
,===

*** reorganize to Zkr section
