# Copyright (c) 2026, Harvey Mudd College
# SPDX-License-Identifier: Apache-2.0
# CI configuration for the YosysHQ PicoRV32 core

ci_enabled: true

# YosysHQ/picorv32 @ ef203c2:
#   I  I-fence-00: a FENCE with nonzero rd writes the ALU result to rd instead of ignoring the
#      field.
exclude_extensions: "I"

apt_packages: "autoconf flex bison help2man libfl-dev ccache"
install_script: ".github/scripts/install-picorv32.sh"
setup_script: ".github/scripts/setup-picorv32.sh"
