#!/usr/bin/env python3
##################################
# ZicsrM_gen.py
#
# David_Harris@hmc.edu 26 December 2025
# SPDX-License-Identifier: Apache-2.0
#
# Privileged test generator
##################################

import sys
from pathlib import Path
from textwrap import dedent


def makePrivHeader(testname: str, sigupd_count: int, extra_reqext: str, extra_march: str) -> str:
    """Generate the header for privileged tests."""
    cmd = " ".join(sys.argv)
    more_reqext = ""
    if extra_reqext:
        more_reqext = ", " + extra_reqext
    more_march = ""
    if extra_march:
        more_march = "_" + extra_march
    # TODO: it would be nice to use e as the base for priv tests to ensure they run everywhere, but Makefiles would need to be updated to emit mabi=ilp32e/lp64e
    march_base = "rv${XLEN}i_zicsr"
    header_lines = dedent(f"""\
        ///////////////////////////////////////////
        // {testname}
        //
        // Autogenerated by {cmd}
        // Do not modify manually
        //
        // SPDX-License-Identifier: Apache-2.0
        ///////////////////////////////////////////

        ##### START_TEST_CONFIG #####
        # REQUIRED_EXTENSIONS: [I, Zicsr, Sm{more_reqext}]
        # MARCH: {march_base}{more_march}
        # CONFIG_DEPENDENT: true
        ##### END_TEST_CONFIG #####

        #define TEST_FILE "{testname}"
        #define SIGUPD_COUNT {sigupd_count}
        #include "riscv_arch_test.h"

        // Set up test environment and declare main entry point
        RVTEST_BEGIN
        .option norvc          // Do not automatically replace uncompressed instructions with compressed instructions

        """)
    return header_lines


def makePrivFooter(basename: str, testcase_lines: str) -> str:
    """Generate the footer for privileged tests."""
    footer_lines = dedent("""
        /////////////////////////////////
        // Instantiate trap handlers and other epilog code, call RVMODEL_HALT at end of test
        /////////////////////////////////

        RVTEST_CODE_END

        /////////////////////////////////
        // Labels for testcases used in reporting
        /////////////////////////////////

        RVTEST_DATA_BEGIN

        """)
    footer_lines += f"{testcase_lines}"
    footer_lines += dedent("""
        RVTEST_DATA_END

        /////////////////////////////////
        // Signature region for self-checking
        /////////////////////////////////

        RVTEST_SIG_SETUP
        """)
    return footer_lines


def addCSRWriteTest(csr_name: str, reg: str, cpbin: str) -> None:
    """Add a CSR write test.  Update global variables, including the signature update count, body lines, and testcase lines."""
    global sigupd_count, body_lines, testcase_lines
    sigupd_count += 1
    body_lines += f"\tRVTEST_SIGUPD_CSR_WRITE({csr_name}, {reg}, test_{sigupd_count})\n"
    testcase_lines += f'test_{sigupd_count}: .string "\\"test: {sigupd_count}; cp: {cpbin}\\""\n'


def makePrivBody() -> None:
    global body_lines
    """Populates the global body for privileged tests.  Also updates the global signature count and testcase messages"""

    covergroup = "ZicsrM_mcause_cg"

    body_lines = dedent("""
            csrr s0, mcause     # save CSR before testing it

        /////////////////////////////////
        // cp_mcause_write_exception
        //   with interrupt = 0: test writing each exception cause
        /////////////////////////////////
        """)

    causes = (i for i in range(0, 24) if i not in {14, 17})  # skip reserved causes
    coverpoint = "cp_mcause_write_exception"
    for i in causes:
        body_lines += f"\n{covergroup}_{coverpoint}_{i}:\n"
        body_lines += f"\tLI(t0, {i})           # exception cause {i}\n"
        addCSRWriteTest("mcause", "t0", f"{coverpoint}/{coverpoint}/b_{i}")

    body_lines += dedent("""
        /////////////////////////////////
        // cp_mcause_write_interrupt
        //   with interrupt = 1: test writing each interrupt cause
        /////////////////////////////////
        """)

    body_lines += "\tSET_MSB(a0)  # set a0 to have msb = 1 for interrupt tests\n"
    causes = (i for i in range(0, 14) if i not in {0, 4, 8})  # skip reserved causes

    coverpoint = "cp_mcause_write_interrupt"
    for i in causes:
        body_lines += f"\n{covergroup}_{coverpoint}_{i}:\n"
        body_lines += f"\tLI(t0, {i})           # interrupt cause {i}\n"
        body_lines += "\tor t0, t0, a0          # set interrupt bit\n"
        addCSRWriteTest("mcause", "t0", f"{coverpoint}/{coverpoint}/b_{i}")

    body_lines += "\n\tcsrw mcause, s0    # restore CSR"

    # *** this code is totally broken. csrrc isn't right.  There is no coverpoint for this anymore.
    body_lines += dedent("""
        /////////////////////////////////
        // cp_misa_mxl_write
        //   write 0, 1, 2, 3 to misa.MXL.
        //   This field is read-only, so nothing should happen
        /////////////////////////////////

            SET_MSB(a0) # put a 1 in the msb of a0 (XLEN-1)
            srli a1, a0, 1          # put a 1 in the second msb of a1 (XLEN-2)
            or a2, a1, a0           # put a 1 in both msbs of a2 (XLEN-1:XLEN-2)
            not a3, a2              # put 1s in all but the 2 msbs of a3
            csrr s0, misa           # read MISA
            and t0, s0, a3          # clear 2 msbs
            or t1, t0, a1           # set XLEN-2
            or t2, t0, a0           # set XLEN-1
            or t3, t0, a2           # set both msbs
            csrrc t6, misa, t0      # misa.MXL = 0
            csrrc t6, misa, t1      # misa.MXL = 1
            csrrc t6, misa, t2      # misa.MXL = 2
            csrrc t6, misa, t3      # misa.MXL = 3
            csrrw t6, misa, s0      # restore MISA
        """)

    body_lines += dedent("""
        /////////////////////////////////
        // cp_mstatus_sd_write
        //   Write all combinations of mstatus.SD = {0/1}, FS/XS/VS = {00, 01, 10, 11}
        //   mstatus.SD is read-only, so nothing should happen
        /////////////////////////////////

            SET_MSB(a0) # put a 1 in the msb of a0 (XLEN-1)
            csrr s0, mstatus        # read and save mstatus
            # set up a1 with mstatus except SD, FS, XS, VS cleared
            not t0, a0              # t0 has all but msb set
            and a1, s0, t0          # clear SD bit
            LI(t0, 0x1E600)         # t0 has all FS, XS, VS bits set (bits [14:13], [16:15], [10:9], respectively)
            not t0, t0              # t0 has all but FS, XS, VS bits set
            and a1, a1, t0          # clear FS, XS, VS bits
    """)

    covergroup = "ZicsrM_mstatus_cg"
    coverpoint = "cp_mstatus_sd_write"
    for sd in (0, 1):
        for fs in (0, 1, 2, 3):
            for xs in (0, 1, 2, 3):
                for vs in (0, 1, 2, 3):
                    binnameus = f"{covergroup}_{coverpoint}_sd_{sd}_fs_{fs:02b}_xs_{xs:02b}_vs_{vs:02b}"
                    binnameslash = f"{coverpoint}/{coverpoint}/sd_{sd}_fs_{fs:02b}_xs_{xs:02b}_vs_{vs:02b}"
                    body_lines += f"\n{binnameus}:\n"
                    fields = fs << 13 | xs << 15 | vs << 9
                    body_lines += f"\tLI(t0, 0x{fields:08x})  # fs/xs/vs\n"
                    if (sd == 1):
                        body_lines += "\tor t0, t0, a0      # set SD bit\n"
                    body_lines += "\tor t0, t0, a1          # value to write to mstatus with SD/FS/XS/VS bits set/clear\n"
                    addCSRWriteTest("mstatus", "t0", binnameslash)


##################################
# Global variables
##################################
sigupd_count = 0  # keep track of size of signature
body_lines = ""  # body of test
testcase_lines = (
    '# testcase strings for reporting mismatches\ncanary_mismatch: .string "Testcase signature canary mismatch!"\n'
)

##################################
# Main Function
##################################

basename = "ZicsrM"
fname = f"{basename}-01.S"
pathname = Path(fname)
with Path.open(pathname, "w") as outfile:
    sys.stdout = outfile

    makePrivBody()  # populate body_lines and testcase_lines
    header_lines = makePrivHeader(fname, sigupd_count, "", "")
    footer_lines = makePrivFooter(basename, testcase_lines)

    print(header_lines)
    print(body_lines)
    print(footer_lines)
