
== General Requirements

=== Conforming Machine Mode

If a certificate requires privileged modes, then a conforming machine mode implementation is required
so that tests can be written using machine-mode instructions to configure and control the hart.  This is
true even for profiles such as RVA23S64, which defines supervisor but not machine mode behavior.

=== Ssstrict Illegal Instruction Behavior

The Ssstrict extension indicates that

[quote]
attempts to execute unimplemented opcodes or access unimplemented CSRs in the standard or reserved encoding
spaces raises an illegal instruction exception that results in a contained trap to the supervisor-mode trap
handler.

If Ssstrict is tested as a required or optional behavior in a certificate, it will be tested in Machine mode
and all lower privilege modes.  In Machine mode, the trap will take place to the machine-mode handler rather
than the supervisor-mode handler.

=== Required UDB Parameters

For DUTs with privileged support (Sm, ExceptionsSm, etc.), MTVEC_ACCESS must be "rw".  If it is "ro", the privileged tests cannot set a trap vector to record activity.

The MTVEC_BASE_ALIGNMENT_DIRECT and MTVEC_BASE_ALIGNMENT_VECTORED UDB parameters define the minimum alignment for the trap handler. The trap handler by default is aligned to a 64-byte boundary in arch_test.h.  If the DUT requires a coarser alignment, the rvmodel_macros.h in the DUT's config directory must set it (e.g. #define RVMODEL_MTVEC_ALIGN 8 for 256-byte alignment).  Note that the UDB parameters are in units of bytes and RVMODEL_MTVEC_ALIGN is in units of log2(bytes).

MTVEC_MODES must support both Direct and Vectored (0 and 1) to get full coverage.  If one of these modes is unsupported, some interrupt coverage could be waived.

=== Unsupported Parameters


=== UDB Description

Every core being certified must provide a UDB configuration (in JSON format) of the features and parameters that it implements.
This UDB configuration defines what parameter values and optional features are tested during certification.  The configuration may
specify additional optional features that are OUT-OF-SCOPE for certification testing, so long as they are not
INCOMPATIBLE with the certificate.

See an https://github.com/riscv/riscv-arch-test/blob/act4/config/ref/sail-rvi20_32/sail.json[example] UDB configuration.
