# SPDX-License-Identifier: Apache-2.0
# Jordan Carlin jcarlin@hmc.edu April 2026
# CI configuration for CORE-V Wally (CVW)
# Requires Verilator and the CVW repository

# TODO: remove za64rs from excluded_extensions when Sail supports UDB_LRSC_FAIL_ON_NON_EXACT_LRSC to match DUT
ci_enabled: true
exclude_extensions: "Sm,S,Svnapot,InterruptsU,ExceptionsZalrsc,ExceptionsZaamo,ExceptionsSvZalrsc,ExceptionsSvZaamo,Za64rs,PMPS,PMPU,PMPF"
apt_packages: "autoconf flex bison help2man libfl-dev ccache"
install_script: ".github/scripts/install-cvw.sh"
setup_script: ".github/scripts/setup-cvw.sh"
