signature_x26_0:
signature_x26_1:
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xffffffffffffffbe
  .dword 0xffffffffffffffbe
  .dword 0xffffffffffffffbe
  .dword 0xffffffffffffffbe
  .dword 0xffffffffffffffca
  .dword 0xffffffffffffffca
  .dword 0xfffffffffffffffe
  .dword 0xffffffffffffffca
  .dword 0xffffffffffffffca
  .dword 0xffffffffffffffba
  .dword 0xffffffffffffffba
  .dword 0xffffffffffffffba
  .dword 0xffffffffffffffba
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
signature_x3_0:
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0x0000000000000000
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe
  .dword 0xfffffffffffffffe