signature_x1_0:
signature_x1_1:
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0x0000000000000000
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
signature_x2_0:
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe
  .dword 0xbabecafebabecafe