signature_x9_0:
signature_x9_1:
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffbabe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffbabe
  .dword 0xffffffffffffbabe
  .dword 0xffffffffffffbabe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0x0000000000000000
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
signature_x3_0:
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe
  .dword 0xffffffffffffcafe