signature_x9_0:
signature_x9_1:
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0x0000000000000000
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
signature_x1_0:
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe
  .dword 0xffffffffbabecafe