== Abstraction Layer

*** separate this into parts required for all test suites including TT vs. parts required only for ACT4
*** key for TT is to invoke RVMODEL_BOOT and RVMODEL_BOOT_TO_xMODE if they exist, and to implement SBI, also use other RVMODEL macros and link.ld

The abstraction layer provides a set of macros that allow test programs and coverpoints to interact with the DUT in a platform-specific way.  This allows the same test program and coverpoint source code to be used across different DUTs, with only the abstraction layer macros needing to be modified for each DUT.  In particular, the abstraction layer includes

* Boot macros to initialize state.
* Trap handler
* Supervisor Binary Interface (SBI) calls
* RVMODEL DUT-specific macros (semihosting/trick box)
* Memory map (linker script)

Fundamental design considerations are:

* For unprivileged extensions, RISC-V tests cannot assume the existence of any privileged capabilities whatsoever unless a profile explicitly requires them.  For example, RV32I tests should be able to run on a microcontroller that does not implement any CSRs, including `mtvec`, and thus cannot have a trap handler.

* Even if machine-mode exists, the tests cannot assume the existence of a _Conforming Machine Mode_, i.e. a machine mode that implements all of the features in the ISA specification.  In particular, the RVA23S64 profile of particular interest for certification does not require a conforming M-mode, only an execution environment that responds to certain things such as `ecall`.

* Nevertheless, most users will implement a conforming M-mode on their DUT.  Therefore, the abstraction layer should provide default implementations of boot macros, trap handler, and SBI calls that assume a conforming M-mode, and users can override these implementations as needed for their DUT.

* To reduce the risk of bugs from uninitialized state and the burden on test developers, the boot process places known values in all applicable GPRs and CSRs.

The boot sequence boots to the lowest available privilege mode sufficient to run the tests.  Tests may define the BOOT_TO_MMODE or BOOT_TO_SMODE symbols to force booting to M-mode or S-mode, respectively, if the DUT supports those modes.  If neither symbol is defined, the boot sequence boots to U-mode if supported, and M-mode (possibly nonconforming) otherwise. Note that hypervisor tests should define BOOT_TO_SMODE to boot into S (effectively HS)-mode and then are responsible for setting up and switching to VS/VU mode if desired.

In the ACT framework, BOOT_TO_MMODE is defined when REQUIRED_EXTENSIONS contains Sm.  BOOT_TO_SMODE is defined when REQUIRED_EXTENSIONS contains S. Otherwise, neither symbol is defined.  Hence, privileged tests that specify Sm, S, or U will boot into these modes, respectively.  Unprivileged tests run in U-mode if supported, and in M-mode (possibly nonconforming) otherwise.  Another consequence is that if the UDB contains CONFORMING_SM_SUPPORTED, then the trap handler is enabled even for unprivileged tests, helping produce graceful error messages for illegal instructions.  However, a simple core such as an RV32I microcontroller may not enable CONFORMING_SM_SUPPORTED and will not set up a trap handler.

=== Controlling Parameters

Every DUT has `S_SUPPORTED`, `U_SUPPORTED`, and `H_SUPPORTED` parameters from the UDB that indicate which privilege modes are supported.  All DUT UDB configs support `Sm`, but not necessarily a conforming M-mode (and possibly no CSRs at all). Therefore, UDB also provides the `CONFORMING_SM_SUPPORTED` parameter, which is true when the DUT implements mandatory portions of the M-mode spec.

=== Boot Sequence

The user is responsible for loading the test ELF onto the DUT and jumping to `rvtest_entry_point`.  The user may optionally run some other firmware or custom boot loader that performs DUT-specific initialization before loading the test ELF.

The test ELF begins with the `RVTEST_BEGIN` macro, which defines `rvtest_entry_point` (at an address specified in the link.ld file), and jumps to `rvmodel_boot`.

`rvmodel_boot` in turn calls the `RVMODEL_BOOT` macro, which optionally contains DUT-specific boot code such as turning on a PLL or memory controller.  This macro can be empty or undefined in the common case that no DUT-specific boot code is required or that the DUT-specific boot is performed earlier by a separate bootloader.

Next, `rvmodel_boot` calls `RVMODEL_IO_INIT` to perform any necessary I/O initialization, such as configuring baud rate and flow control in a UART.  This macro can also be empty or undefined if no I/O initialization is needed.

Next, `rvmodel_boot` calls `RVTEST_BOOT_TO_MMODE` to set up the trap handlers and initialize M-mode CSRs. This macro first checks if `RVMODEL_BOOT_TO_MMODE` is defined. If undefined, it runs default boot code assuming conforming M-mode. If defined, it runs the DUT-specific `RVMODEL_BOOT_TO_MMODE` that performs the same general steps for nonconforming M-mode (or should be blank for cases such as an RV32I DUT that has no CSRs).

CSR initialization includes

* mie/mip = 0 (disable all interrupts)
* mideleg/medeleg = 0 (don't delegate traps unless turned on during S-mode boot)
* mstatus (SXLEN/UXLEN = MXLEN, SBE/UBE = MBE, other features off)
* menvcfg (enable unpriv features if U supported)
* mstateen0 (enable unpriv features if SMSTATEN_SUPPORTED)
* mcountinhibit = 0 *** if exists
* mhpmenvent3...31/h = 0
* mseccfg (disable features if supported)
* mnstatus (disable resumable NMI fields if SMRNMI_SUPPORTED)
* pmpaddr0/pmpcfg0 if PMP_ENTRIES > 0
* turn off virtual memory and perform sfence.vma to synchronize MMU if SV32_SUPPORTED or SV39_SUPPORTED

Even if conforming M-mode is not supported or RVMODEL_BOOT_TO_MMODE is defined, the boot code still attempts to turn on mstatus.FS/VS if float or vector is supported, because these are needed for unprivileged tests, even on a RV32I DUT that has no other M-mode features.

The boot process ends in M-mode if the BOOT_TO_MMODE symbol is defined in the test (for tests intended to run in machine mode), or if no lower privilege mode is supported.

If the test is continuing to boot to a lower privilege mode, it next checks if `S_SUPPORTED` and, if so, calls `RVTEST_BOOT_TO_SMODE`. This initializes S-mode CSRs, and adjusts M-mode CSRs such as trap delegation and environment configuration. It then enters S-mode. This entire routine can be overridden by a RVMODEL equivalent for non-conforming M-mode implementations that cannot access M-mode CSRs or use the standard `mret` method of entering S-mode.

S-mode CSR initialization includes

* medeleg = 0xFCB5FF (delegate all exceptions except for ecall from M and S mode, and double traps)
* mideleg = 0x366 (delegate all user and supervisor-mode interrupts, including counter overflow)
* sstateen0 (enable unprivileged features if SSSTATEEN)
* scounteren = all 1s (enable counter access from lower priv modes)
* senvcfg (enable unpriv features)

The boot process ends in S-mode if the BOOT_TO_SMODE symbol is defined in the test (for tests intended to run in supervisor mode).

If the test is not intended to run in S-mode, and U-mode is supported, `rvmodel_boot` calls `RVTEST_BOOT_TO_UMODE`, which switches to U-mode by calling `RVTEST_GOTO_LOWER_MODE U`. *** or the correct macro  *** any other .  Again, it can be overridden by `RVMODEL_BOOT_TO_UMODE` for non-conforming M-mode implementations.

Finally, `rvmodel_boot` jumps to `rvtest_init`, which calls `RVTEST_INIT_REGS` to initialize GPRs, then sets up the signature pointer and checks a canary if applicable.***

The test ELF contains the RVMODEL_BOOT macro, which performs any necessary boot operations such as turning on a phase-locked loop or DRAM controller or initializing custom state.  After RVMODEL_BOOT, the system should be in conforming machine mode if supported, with XLEN and endianness for each lower privilege mode set to the same value as in machine mode (MXLEN = SXLEN = UXLEN = HSXLEN = VSXLEN and MBE = SBE = UBE = VSBE). *** replace

[[rvmodel-macros]]
=== RVMODEL DUT-Specific Macros

Each DUT requires implementing a set of macros to perform the following non-ISA functions:

* Run DUT-specific boot code
* Terminate a test with a pass or fail indication
* Send a character to a terminal
* Deliver each supported type of interrupt to the core (Machine/Supervisor External/Timer/Software + guest external interrupts)

The macro names begin with RVMODEL, so they are called _RVMODEL DUT-Specific Macros_.  Their functions are sometimes called _semihosting_ or _trick box_.

The RVMODEL DUT-Specific Macros rely on the capabilities of the SoC and/or testbench.  For example, a SoC with a 16550-compatible UART sends a character by writing a byte to the UART's memory-mapped Transmit Holding Register. A SoC without a UART may have a testbench that monitors writes to a specific memory address and prints the byte written to that address.

Most macros are implemented in config/cores/<core>/<version>/rvmodel_macros.h.  RVMODEL_ACCESS_FAULT_ADDRESS is defined in rvtest_config.h and rvtest_config.svh for the test programs and coverpoints, respectively.

==== Macros

The RVMODEL DUT-Specific Macros are given in <<t-rvmodel>>. The "Can Be Empty?" field indicates circumstances under which the macro can be empty. The Mode column indicates the privilege mode from which the macro is called.

[[t-rvmodel]]
.RVMODEL DUT-Specific Macros
[options=header]
[cols="2, 3, 2, 1", options=header]
[%AUTOWIDTH]
|===
|Macro|Description|Can be Empty?|Mode
|RVMODEL_BOOT|Perform boot operations, such as turning on a phase-locked loop or DRAM controller or initializing custom state. Cannot clobber `x1`/`ra`, but any other registers may be trashed.|Empty or omitted if no boot operations are needed, or a separate DUT-specific executable is used for booting before loading and invoking the test ELF.| Machine
|RVMODEL_HALT_PASS|Terminate test with a pass indication.  When the test is run in simulation, this should end the simulation.|No | Any
|RVMODEL_HALT_FAIL|Terminate test with a fail indication.  When the test is run in simulation, this should end the simulation.|No | Any
|RVMODEL_IO_INIT(_R1, _R2, _R3)|Initialization steps needed prior to writing to the console. _R1, _R2, and _R3 are temporary registers that may be trashed by the macro.|Empty or omitted if no I/O initialization is needed. | Machine
|RVMODEL_IO_WRITE_STR(_R1, _R2, _R3, _STR_PTR)|Write a null-terminated ASCII string to the console, where _R1, _R2, and _R3 are temporary registers that may be trashed by the macro and _STR_PTR is a register containing the address of the first byte of the string.|If the console is unavailable and the user implements an alternate way to signal success (such as test bench reporting or colored LEDs controlled by RVMODEL_HALT). However, a console is required for certification. | Any
|RVMODEL_SET_MEXT_INT(_R1, _R2)|Sets the Machine External Interrupt `mip.MEIP` using platform-specific interrupt controller, if supported. _R1 and _R2 are temporary registers that may be trashed by the macro.|If M-mode external interrupts are not tested.| Machine or Supervisor
|RVMODEL_CLR_MEXT_INT(_R1, _R2)|Clears the Machine External Interrupt `mip.MEIP` using platform-specific interrupt controller. _R1 and _R2 are temporary registers that may be trashed by the macro.|If M-mode external interrupts are not tested. | Machine or Supervisor
|RVMODEL_SET_MSW_INT(_R1, _R2)|Sets the Machine Software Interrupt `mip.MSIP` using a memory-mapped control register, if supported. _R1 and _R2 are temporary registers that may be trashed by the macro.|If M-mode software interrupts are not tested. | Machine or Supervisor
|RVMODEL_CLR_MSW_INT(_R1, _R2)|Clears the Machine Software Interrupt `mip.MSIP` using a memory-mapped control register. _R1 and _R2 are temporary registers that may be trashed by the macro.|If M-mode software interrupts are not tested. | Machine or Supervisor
|RVMODEL_SET_SEXT_INT(_R1, _R2)|Sets the Supervisor External Interrupt `sip.SEIP` using platform-specific interrupt controller, if supported. _R1 and _R2 are temporary registers that may be trashed by the macro.|If S-mode external interrupts are not tested.  | Machine or Supervisor
|RVMODEL_CLR_SEXT_INT(_R1, _R2)|Clears the Supervisor External Interrupt `sip.SEIP` using platform-specific interrupt controller. _R1 and _R2 are temporary registers that may be trashed by the macro.|If S-mode external interrupts are not tested.  | Machine or Supervisor
|RVMODEL_SET_SSW_INT(_R1, _R2)|Sets the Supervisor Software Interrupt `sip.SSIP` using a platform-specific interrupt controller, if supported. _R1 and _R2 are temporary registers that may be trashed by the macro.|If S-mode software interrupts are not tested.  | Machine or Supervisor
|RVMODEL_CLR_SSW_INT(_R1, _R2)|Clears the Supervisor Software Interrupt `sip.SSIP` by using a platform-specific interrupt controller, as applicable. _R1 and _R2 are temporary registers that may be trashed by the macro.|If S-mode software interrupts are not tested.  | Machine or Supervisor
|RVMODEL_ACCESS_FAULT_ADDRESS|The base physical address of a region that causes an access fault when any part of the region is read or written. This is used to test exceptions. The faulting region must be at least 128 bytes; if vector fault-only-first loads are tested, it must be at least ceil(VLEN*LMUL/8) bytes (the vector coverpoints exercise up to 2*VLEN/8 bytes with LMUL=2). For typical implementations where address 0 is unmapped, the entire first page satisfies both requirements.|Omit if DUT does not generate some/all access faults.| n/a
|RVMODEL_MTIME_ADDRESS|The address of the memory-mapped `mtime` register, used for timer accesses and interrupts.|Omit if machine timer interrupts are not tested. | n/a
|RVMODEL_MSIP_ADDRESS|The address of the memory-mapped `msip` register, used to set and clear machine software interrupts (`mip.MSIP`).**Required only for Sm version 1.13 and above.**|Omit if machine software interrupts are not tested. | n/a
|RVMODEL_MTIMECMP_ADDRESS|The address of the memory-mapped `mtimecmp` register, used for timer interrupts.| Omit if machine timer interrupts are not tested. | n/a
|RVMODEL_INTERRUPT_LATENCY|Expected latency (in cycles/NOPs) for interrupt trap processing. Ensures interrupt is received and can be processed before test continues.|Can be 0 if interrupt controller adds no delay. | n/a
|RVMODEL_TIMER_INT_SOON_DELAY|The delay (in cycles) before a timer interrupt fires when using `set_mtimer_int_soon()`. Sets `mtimecmp = mtime + delay`. Should be long enough that the core can run a few instructions before the interrupt fires.| If Machine timer interrupts are not tested. | n/a
|RVMODEL_DATA_SECTION|DUT-specific data that will be placed in a .data section. Used for memory-mapped regions like `tohost`/`fromhost`.  |Yes, if not needed by DUT. | n/a
|===

[NOTE]
RVMODEL interrupt macros are only required for interrupts controlled in a platform-specific fashion. RISC-V has standardized generating timer interrupts using memory-mapped MTIME and MTIMECMP, so no RVMODEL macros are needed for DUT-specific timer interrupt generation.  Similarly, no RVMODEL macros are needed to set or read MTIME, or set or clear interrupts using standard CSR accesses.

[NOTE]
If a macro needs machine mode privileges to perform its function but might be called from any mode, it must change privilege level.  For example, if RVMODEL_IO_WRITE_STR needs machine mode to access a UART, it may call RVTEST_GOTO_M_MODE.  Printing (and halting) is done at the end of a test, so there is no need to return to the previous privilege mode.

==== RVMODEL_BOOT Requirements

The RVMODEL_BOOT macro may be empty for a simple DUT.

For a complex SoC, the macro may need to perform initialization steps such as turning on a phase-locked loop or DRAM controller or initializing custom state.  It must not clobber `x1`/`ra`, but any other registers may be trashed.

At the end of RVMODEL_BOOT, the system should be in conforming machine mode, with XLEN and endianness for each lower privilege mode set to the same value as in machine mode (MXLEN = SXLEN = UXLEN = HSXLEN = VSXLEN and MBE = SBE = UBE = VSBE).

Alternatively, the DUT might run a separate proprietary bootloader executable file that initializes the system, then loads the test ELF and jumps to `rvtest_entry_point`. Or the DUT could modify link.ld to link proprietary bootloader code into the test ELF and jump to `rvtest_entry_point`. In these cases, RVMODEL_BOOT can be empty.

==== RVMODEL Macros for Spike and SAIL

RVMODEL macros for Spike are implemented in https://github.com/riscv/riscv-arch-test/blob/act4/config/spike/spike-rv64-max/rvmodel_macros.h[spike-rv64-max/rvmodel_macros.h].  They use HTIF for termination, and write to a virtual UART at address 0x1000_0000 to print characters.  TODO: Interrupts

RVMODEL macros for the RISC-V Sail model are implemented in https://github.com/riscv/riscv-arch-test/blob/act4/tests/env/sail_test.h[tests/env/sail_test.h].  They are similar to Spike but use HTIF for printing.  TODO: interrupts

==== Host Target Interface

The https://github.com/Timmmm/htif_spec/releases/download/v0.0.1/htif-0.0.1.pdf[host target interface] (HTIF) is an unofficial semihosting method that has become widely used by RISC-V simulators (Spike, QEMU, RISC-V Sail) and test benches.  If your SystemVerilog testbench supports it, you can share the same HTIF code as Spike and RISC-V Sail for the  RVMODEL_HALT_PASS, RVMODEL_HALT_FAIL, and RVMODEL_IO_WRITE_STR DUT-specific macros.  A drawback is that your testbench needs to parse the ELF labels to find the address of the `tohost` symbol, which is used for HTIF communication.  If your testbench does not support HTIF, you can implement the RVMODEL macros using other methods, such as memory-mapped I/O to a SoC peripheral or an address monitored by the testbench.

For example, the testbench might implement the [unofficial HTIF semihosting specification] and print the character `A` by writing the doubleword 0x01010000_00000041 to a label called `tohost` in the .data section of the test program.  The most significant byte is the device (console), the next byte is the command (write), and the least significant 4 bytes are the data (the ASCII code for `A`).  Terminating with a failure code is done by writing the doubleword 0x00000000_00000003 to `tohost`, and terminating with a success code is done by writing the doubleword 0x00000000_00000001 to `tohost`.

Note that writing the upper word of the doubleword to `tohost` with `sd` is only properly defined for RV64.  Therefore, RV32 can use HTIF to terminate with a success or failure code but not necessarily to write to the console.

==== RVMODEL Macros for Other DUTs

If you have a simple DUT designed to match the behavior of RISC-V Sail and Spike, you may be able to implement the RVMODEL macros with the same code used by RISC-V Sail.  Your RVMODEL_BOOT macro can be empty.  The interrupt macros for unsupported privilege modes can be empty.

If you have a complex DUT, you presumably have a team of sophisticated verification engineers who can adapt the example macros to your DUT's requirements.

[[linker-script]]
=== Linker Script

Each DUT needs a linker script tailored to its memory map. The linker script in `config/<core>/<version>/link.ld` defines where to place the code and data regions in the DUT's memory map.  It must contain `.text.init`, `.text.rvtest`, `.data`, and `.text.rvmodel` sections (in that order), and an `ENTRY` point named `rvtest_entry_point`. The first line of the list of `SECTIONS` in the linker script sets the starting address of the ELF (`. = 0x...`) and is the only part of the sample linker script that most users will need to change. Set it to your reset address for simple DUTs. Users with special needs can customize the linker script to start at their own boot code (leaving the `RVMODEL_BOOT` macro blank) and then jump to `rvtest_entry_point`.

The `.text.rvmodel` section contains DUT-specific (`RVMODEL`) code and **must** be placed after the `.data` section.  This ensures that variable-size model-specific macro expansions (which may differ between the DUT build and the reference-model build) do not affect the addresses of test data symbols such as `scratch` and `begin_signature`, preventing signature mismatches.

=== File Organization

Standard macros are defined in `tests/env`.  DUT-specific macros are defined in `rvmodel_macros.h`, which is in a DUT-specific config directory (e.g. `config/<dut>/<version>/rvmodel_macros.h` for predefined simulators, or out-of-tree for custom DUTs).

Standard framework macros begin with `RVTEST`.  They include `rvtest_setup.h` for boot macros and `rvtest_trap_handler.h` for standard trap handlers, and `rvtest_failure_code.h` for error reporting. Other macros are defined in ***util.h, ... describe further

DUT-specific macros begin with `RVMODEL`.  Some `RVTEST` macros check if corresponding `RVMODEL` macros are defined and invoke the `RVMODEL` macro instead for nonconforming DUTs when defined.

=== Test Supervisor Binary Interface (T-SBI)

The test must implement a custom _Test Supervisor Binary Interface_ (T-SBI) providing an abstraction layer to facilitate S and U-mode tests requesting services from a possibly non-conforming M-mode. These services include ***.


TODO: Flush out

TODO:

testgen/src/testgen/io/templates.py format_params needs to accept CONFORMING_SM_SUPPORTED parameter when available.  How to deal with UDB?

remove mention of RVTEST_VECTOR  from vector code

DONE: replace rvtest_mtrap_routine with CONFORMING_SM_SUPPORTED or many places it gets deleted
    replace rvtest_strap_routine with S_SUPPORTED if needed
    replace rvtest_htrap_routine with H_SUPPORTED if needed

Test generator:
    Any test that lists Sm in REQUIRED_EXTENSIONS adds CONFORMING_SM_SUPPORTED as a parameter
    DONE *** edit generators/testgen/src/testgen/io/templates.py/generate_defines_from_extensions to define these boot_TO_*.  DONE Drop RVTEST_FP and tweak where it was used (hopefully removed)
        if any(ext in ext_components for ext in ["H", "S"]):
            extra_defines.append("#define BOOT_TO_SMODE")
        elif any(ext in ext_components for ext in ["Sm"]):
            extra_defines.append("#define BOOT_TO_MMODE")

    TODO: provide a routine to goto UMODE from SMODE
        provide a SBI way to get back to M-mode from U-mode when ecall from U is delegated
        needed  for cleanup after tests.  See UF as an example.
