
=== Exceptions

Exception tests are organized according to the privilege mode or extension supported.  For example, a configuration with Machine, Supervisor, User, and Floating-Point supported should run ExceptionsSm, ExceptionsS, ExceptionsU, and ExceptionsF.

==== ExceptionsSm Machine-Mode Exceptions

These tests are run on any configuration with machine mode that supports exceptions.

[[t-ExceptionsSm-coverpoints]]
.ExceptionsSm Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1987812700#gid=1987812700[Google Sheet Testplan]
,===

include::norm/ExceptionsSm_norm_rules.adoc[]

==== ExceptionsS Supervisor-Mode Exceptions

These additional exception tests are run on configurations with supervisor mode.

[[t-ExceptionsS-coverpoints]]
.ExceptionsS Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=2127390256#gid=2127390256[Google Sheet Testplan]
,===

include::norm/ExceptionsS_norm_rules.adoc[]

==== ExceptionsU User-Mode Exceptions

These additional exception tests are run on configurations with user mode.

[[t-ExceptionsU-coverpoints]]
.ExceptionsU Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=593261374#gid=593261374[Google Sheet Testplan]
,===

include::norm/ExceptionsU_norm_rules.adoc[]

==== ExceptionsF Floating-Point Exceptions

These additional exception tests are run on configurations with floating-point (at least the F extension).

[[t-ExceptionsF-coverpoints]]
.ExceptionsF Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1241522932#gid=1241522932[Google Sheet Testplan]
,===

==== ExceptionsVx Vector Integer Exceptions

These additional exception tests are run on configurations with vector (V extension or subsets thereof that rely on mstatus.VS) related to vector integer instructions.

[[t-ExceptionsVx-coverpoints]]
.ExceptionsVx Coverpoints
,===
https://docs.google.com/spreadsheets/d/11VGlIA__UYr7H47ZNqXtyYnGH5Fb41E8P9h53rN72ok/edit?gid=1139310135#gid=1139310135[Google Sheet Testplan]
,===

==== ExceptionsVf Vector Floating-Point Exceptions

These additional exception tests are run on configurations with vector (V extension or subsets thereof that rely on mstatus.VS) related to vector floating-point instructions.

[[t-ExceptionsVf-coverpoints]]
.ExceptionsVf Coverpoints
,===
https://docs.google.com/spreadsheets/d/11VGlIA__UYr7H47ZNqXtyYnGH5Fb41E8P9h53rN72ok/edit?gid=1839120623#gid=1839120623[Google Sheet Testplan]
,===

==== ExceptionsVls Vector Load/Store Exceptions

These additional exception tests are run on configurations with vector (V extension or subsets thereof that rely on mstatus.VS) related to vector load/store instructions.

[[t-ExceptionsVls-coverpoints]]
.ExceptionsVls Coverpoints

,===
https://docs.google.com/spreadsheets/d/11VGlIA__UYr7H47ZNqXtyYnGH5Fb41E8P9h53rN72ok/edit?gid=1814229778#gid=1814229778[Google Sheet Testplan]

,===

==== ExceptionsZalrsc Atomic LR/SC Exceptions

[[t-ExceptionsZalrsc-coverpoints]]
.ExceptionsZalrsc Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=891200072#gid=891200072[Google Sheet Testplan]
,===

==== ExceptionsZaamo Atomic Memory Operation Exceptions

[[t-ExceptionsZaamo-coverpoints]]
.ExceptionsZaamo Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=2143559149#gid=2143559149[Google Sheet Testplan]
,===

[NOTE]
ExceptionsZaamo also covers Zama16b.

==== ExceptionsZc Compressed Instruction Exceptions

These additional exception tests are run on configurations with compressed instructions (C, Zca, Zcb, etc.).  They attempt to test all compressed loads and stores, but may throw an illegal instruction fault on compressed subword load/store if Zcb is not supported.

[[t-ExceptionsZc-coverpoints]]
.ExceptionsZc Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=538759067#gid=538759067[Google Sheet Testplan]
,===

include::norm/ExceptionsZc_norm_rules.adoc[]


==== ExceptionsZicboS Supervisor-Mode CBO Exceptions

[[t-ExceptionsZicboS-coverpoints]]
.ExceptionsZicboS Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=927893239#gid=927893239[Google Sheet Testplan]
,===

include::norm/ExceptionsZicboS_norm_rules.adoc[]

==== ExceptionsZicboU User-Mode CBO Exceptions

[[t-ExceptionsZicboU-coverpoints]]
.ExceptionsZicboU Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1054505393#gid=1054505393[Google Sheet Testplan]
,===

include::norm/ExceptionsZicboU_norm_rules.adoc[]

==== ExceptionsSv Virtual Memory Exceptions

[[t-ExceptionsSv-coverpoints]]
.ExceptionsSv Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=270777025#gid=270777025[Google Sheet Testplan]
,===

==== ExceptionsSvZalrsc  Virtual Memory LR/SC Exceptions

[[t-ExceptionsSvZalrsc-coverpoints]]
.ExceptionsSvZalrsc Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=287426144#gid=287426144[Google Sheet Testplan]
,===

==== ExceptionsSvZaamo Virtual Memory AMO Exceptions

[[t-ExceptionsSvZaamo-coverpoints]]
.ExceptionsSvZaamo Coverpoints
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1747092954#gid=1747092954[Google Sheet Testplan]
,===
