
=== Interrupts

Interrupt tests are organized according to the privilege mode or extension supported.  InterruptsSm boots to M-mode and exercises interrupts in every supported privilege mode; InterruptsS boots to S-mode and exercises only the interrupts visible to supervisor software.  The Sstc tests check access to the `stimecmp` register; the timer interrupts that `stimecmp` generates are covered by the `cp_trigger_sti_sstc` and `cp_write_stip_sstc` coverpoints of the Interrupts tests.

==== InterruptsSm Machine-Mode Interrupts

These tests are run on any configuration with machine mode that supports interrupts.

include::{privtestplansdir}/InterruptsSm.adoc[]

include::norm/InterruptsSm_norm_rules.adoc[]

TODO: coverpoints will need to ignore bins with mie.msie nonzero:
  # If a system has only one hart, or if a platform standard supports the delivery
  # of machine-level interprocessor interrupts through external interrupts (MEI)
  # instead, then mip.MSIP and mie.MSIE may both be read-only zeros.
  - name: mie_msie_maybe_rdonly0
TODO: mip.MSIP update time
  # When the memory-mapped msip register changes, it is guaranteed to be reflected
  # in mip.MSIP eventually, but not necessarily immediately.
  - name: msip_update_max_time

==== InterruptsS Supervisor-Mode Interrupts

These tests are run on any configuration with supervisor mode that supports interrupts. They boot to S-mode and also run in U-mode (and VS/VU-mode when the H extension is supported); `mideleg` keeps its boot value with all supervisor-level interrupts delegated.

include::{privtestplansdir}/InterruptsS.adoc[]

include::norm/InterruptsS_norm_rules.adoc[]

==== SstcSm Machine-Mode Supervisor Timer Compare

These tests are run on any configuration with machine mode when the Sstc supervisor timer compare extension is supported.

include::{privtestplansdir}/SstcSm.adoc[]

include::norm/SstcSm_norm_rules.adoc[]

==== SstcS Supervisor-Mode Supervisor Timer Compare

These tests are run on any configuration with supervisor mode when the Sstc supervisor timer compare extension is supported.

include::{privtestplansdir}/SstcS.adoc[]

include::norm/SstcS_norm_rules.adoc[]

TODO: beef up testing stimecmp values, behavior near wraparound
