
=== Priv

The privileged tests exercise CSRs that are mandatory in each privilege mode.
They also test mandatory privileged instructions: `ecall`, `ebreak`, `mret`, and `sret`.
The CSR read/write/set/clear instructions themselves are tested in the
unprivileged Zicsr tests of <<Zicsr Control/Status Register Instructions>>.

`wfi` is tested in <<Interrupts>> and `sfence.vma` is tested in <<Sv* Virtual Memory>>.

Privileged tests do not test reserved or custom instructions or CSRs because their behavior is UNSPECIFIED.
Reserved instructions and CSRs are tested in the <<Ssstrict>> Ssstrict tests,
where they should throw an Illegal Instruction exception if not implemented.

==== Sm Machine-Mode CSRs and Instructions

These test CSRs and privileged instructions in machine mode.

include::{testplansdir}/priv/Sm.adoc[]

TODO: Plan how to check WARL, WPRI, WLRL fields.  It seems every CSR needs parameters, either to tell the reference model how they should behave (to generate expected values), or to tell the tests and coverpoints which values are legal to test.

include::norm/Sm_norm_rules.adoc[]

TODO: Many new normative rules have been added since this was written.  Update Sm.yaml.

==== S Supervisor-Mode CSRs and Instructions

These test additional CSRs that exist in supervisor mode, and privileged instructions in supervisor mode.

include::{testplansdir}/priv/S.adoc[]

include::norm/S_norm_rules.adoc[]

[NOTE]
====
sie_sip_strap_time_constraint is not tested yet.  How to handle timing constraints in certification?
How to handle interrupts that don't get evaluated immediately after the macro sets them? The
macro could spin until they fire, but needs to know if they should fire (e.g. not blocked by xstatus.xIE).
====

==== U User-Mode CSRs and Instructions

These test additional CSRs that exist in user mode, and privileged instructions in user mode.

include::{testplansdir}/priv/U.adoc[]

include::norm/U_norm_rules.adoc[]

==== SmF Floating-Point CSRs

These test additional CSRs that exist when floating-point is supported.

include::{testplansdir}/priv/SmF.adoc[]

include::norm/SmF_norm_rules.adoc[]

==== UF User-Mode Floating-Point CSRs

These test additional CSR scenarios that exist when floating-point and user mode are supported.

include::{testplansdir}/priv/UF.adoc[]

include::norm/UF_norm_rules.adoc[]

==== Zkr Entropy CSR

These test CSRs when the Zkr entropy extension is supported.  The seed CSR tests run once per
privilege mode: ZkrSm in M-mode, ZkrS in S-mode, and ZkrU in U-mode.

include::{testplansdir}/priv/Zkr.adoc[]

include::norm/Zkr_norm_rules.adoc[]
