
== Test Suite Requirements

The test suites may be provided by multiple suppliers, but must meet a common set of requirements to interoperate transparently for the user:

* All tests use a common set of DUT configuration files so the user only has to write them once:
** `<dut>.yaml` for the UDB configuration including supported extensions and parameter values
** `rvmodel_macros.h` for the RVMODEL DUT-Specific Macros
** `link.ld` for the linker script

* All tests are self-checking
** Able to run on simulators, RTL, and hardware
** Expected values may be produced by the RISC-V Sail reference model or the test code itself, and must account for relevant parameters
*** Alternate reference model may be used for development until RISC-V Sail is sufficiently mature
** Only test features whose behavior is specified for the given parameters (e.g. only test unimplemented instructions if Ssstrict is supported)
** Calls `RVMODEL_BOOT` for DUT-specific boot code (can be empty) before starting the test
** Test begins in machine mode, if any privileged modes are implemented
** Terminate with `RVMODEL_HALT_PASS` or `RVMODEL_HALT_FAIL` to indicate success
** Print meaningful information to localize a failure with `RVMODEL_IO_WRITE_STR`, including:
*** PC at failure point
*** Expected and actual values of mismatching registers
*** Name of coverpoint and bin that failed, if practical
** Tests should not contain loops over multiple bins.  Each bin of each coverpoint should be tested by a unique instruction so that a failing bin can be uniquely identified from the program counter.  Loops should go in the test generator instead of the test itself.

* Tests are organized in a granular way so that each ISA feature can be tested independently of other features

* All tests are written in assembly or C and work with the latest release of both GCC and Clang
** The latest release is typically needed because new extensions are rapidly being added to these compilers
** Certificates will be tied to specific compiler versions to ensure consistency

* Qualifying each test includes running on the RISC-V Sail reference model, Spike, and Whisper for at least one choice of parameters
** Exceptions can be made for specific tests when there are known bugs or unimplemented extensions

* Tests are for certification, not verification
** Every normative rule is addressed by at least one coverpoint, defined in the CTP
*** Specific normative rules can be omitted from testing if they are not testable. In this case, the rule should still be listed in the CTP and should be explicitly marked as not tested
** Every test is directed to a specific normative rule/coverpoint bin, not fuzzing in the hopes of randomly hitting a rule/coverpoint
*** Exception: Multicore memory ordering is necessarily nondeterministic
** Tests emphasize RISC-V architectural behavior, not microarchitectural behavior such as complex pipeline hazards or timing
** Runtime is important
** Size is important

* All tests have SystemVerilog coverpoints
** Use standard syntax compatible with Questa, VCS and Xcelium (regression on at least Questa)
** All coverpoints must use the RVVI interface

* All testing collateral (tests, test generators, coverpoints, frameworks, documentation, etc.) are owned by RVI and distributed under an open-source license ** TODO: Jeff/Tom/Moiz to update this section
** Hosted in the RISC-V architectural test repository under the stewardship of Architectural Certification Test (ACT) SIG
** Repository contains tests for ratified and in-development features, not just features in certificates
** Generators necessary to recreate the tests for a DUT are included in the repository, but, when tests are not unique to a DUT, the generated tests themselves are also included to reduce requiring users to run generators and to make the tests easier to view and understand

* Don't let the perfect be the enemy of the good
** If necessary to meet schedule, tests can be released addressing most of the normative rules and coverpoints for a feature, and improved over time
** Initial test development prioritizes the common parameter choices (such as XLEN=MXLEN, Endian=Little), and other parameter choices can be added over time
** All limitations must be documented in CTP

=== For discussion:

* Testing of WARL, WLRL, WPRI fields, and the necessary parameters to define what fields should be tested and behaviors should be expected, in collaboration with the Parameters Working Group
* Regression requirements, including multiple parameters
