[appendix]
[[parameter_defs]]
== Parameter Definitions

Parameters are hardware options supported by RISC-V standards.
Many parameters are not named in RISC-V standards but a golden list of parameters
is maintained separately by RISC-V International and this section uses those names.

NOTE: The golden list of parameters is still under development so the parameters in this document
are "preliminary parameters" and subject to change as the golden list is finalized.

Parameters map to one or more normative rules in the RISC-V ISA manual.
Typically these normative rules are the Implementation-Defined Behavior variant of normative rules.
These are normative rules that allow for multiple behaviors and require the implementation to specify its behavior.
By convention, Implementation-Defined Behaviors have uppercase names while other types of normative rules have lowercase names.

.Parameter Definitions
[cols="30%,10%,10%,50%"]
|===
| Parameter and Mapping to Normative Rules | Type | ISA Feature | Definition

a|
[#param:HPM_COUNTER_SZ]#HPM_COUNTER_SZ#

Normative Rule(s):

* https://riscv.github.io/riscv-isa-manual/snapshot/norm-rules/norm-rules.html#HPM_PLATFORM_SPECIFIC_IMPL[HPM_PLATFORM_SPECIFIC_IMPL]
| Array[3:31] of Integer 0 to 64
| Zicntr
| Bit width of each implemented unprivileged hardware performance counter.
A value of 0 indicates the corresponding counter is not implemented.

a|
[#param:LRSC_RESERVATION_STRATEGY]#LRSC_RESERVATION_STRATEGY#

Normative Rule(s):

* https://riscv.github.io/riscv-isa-manual/snapshot/norm-rules/norm-rules.html#LR_RESERVATION_SET_SIZE[LR_RESERVATION_SET_SIZE]
| Enum (Exact, 64B, 128B, Other)
| Atomic (Zalrsc extension)
a| Defines the reservation strategy for load-reserved/store-conditional (LR/SC) atomic instructions:

[%autowidth]
!===
! Value ! Definition

! Exact ! Reservation set is exactly enough to cover the access and no more
! 64B ! Reservation set is naturally-aligned 64-byte region
! 128B ! Reservation set is naturally-aligned 128-byte region
! Other ! Reservation set strategy doesn't fit any of the specified choices
!===

a|
[#param:MISALIGNED_LDST_HW_SUPPORT]#MISALIGNED_LDST_HW_SUPPORT#

Normative Rule(s):

* https://riscv.github.io/riscv-isa-manual/snapshot/norm-rules/norm-rules.html#MISALIGNED_LDST_HW_SUPPORT[MISALIGNED_LDST_HW_SUPPORT]
| Boolean
| RV32I/RV64I Base ISA
a| Hardware support for misaligned integer and floating-point load/store instructions.

[%autowidth]
!===
! Value ! Definition

! False ! No hardware support for misaligned load/store instructions
! True ! Misaligned load/store instructions are supported in hardware (potentially with restrictions expressed by other parameters).
!===

a|
[#param:MISALIGNED_ATOMICITY_GRANULE_SIZE]#MISALIGNED_ATOMICITY_GRANULE_SIZE#

Normative Rule(s):

* https://riscv.github.io/riscv-isa-manual/snapshot/norm-rules/norm-rules.html#MISALIGNED_ATOMICITY_GRANULE_SIZE[MISALIGNED_ATOMICITY_GRANULE_SIZE]
| Integer
| Atomic
| See normative rule

a|
[#param:TIME_CSR_HW_SUPPORT]#TIME_CSR_HW_SUPPORT#

Normative Rule(s):

* https://riscv.github.io/riscv-isa-manual/snapshot/norm-rules/norm-rules.html#execution_environment_implementation_flexibility[execution_environment_implementation_flexibility]
| Boolean
| Zicntr
| Implementation supports reading of all unprivileged time-related CSRs without triggering an exception. For RV32I the `time` and `timeh` CSRs are the unprivileged time-related CSRs. For RV64I the `time` CSR is the only unprivileged time-related CSR.

|===
