= RVA23 Certification Requirements Document (rev 0.2)
:description: RVA23 CRD (Certificate Requirements Document)
include::../../common/adoc_common.adoc[]

_Contributors to all versions of the spec in alphabetical order_

* Jordan Carlin
* Ken Dockser
* David Harris

_This document is released under a Creative Commons Attribution 4.0 International License._

[Preface]
== CRD Revision History

History of documentation changes that eventually lead to releases.

[cols="1,1,5"]
|===
| Date | Revision | Changes

| April 29, 2026
| 0.1
a| * Initial draft
| July 27, 2026
| 0.2
a| * Do not test traps into M-mode except ecall from S-mode

|===

== Introduction

This document describes the requirements for a processor to be eligible for a RVA23 certificate.

The RVA23 processor certificate is based on the https://riscv.github.io/riscv-isa-manual/snapshot/spec/#_rva23s64_profile[RVA23S64] and RVA23U64 profiles. To
qualify for a certificate, the processor must implement the RV64I base instruction set and all of the mandatory
extensions of the profile.  It may implement any of the optional features of
the profile.  It may implement ratified extensions that are not part of the profile. It may implement other unratified extensions, but must not implement
unratified extensions outside the custom encoding spaces if the optional Ssstrict extension is implemented. Extensions outside the profile are not tested during
certification.

NOTE: The profiles already explain what is required and what is optional. Restating the requirements here can lead to confusion.

NOTE: While it is permitted for an implementation to also support RV32I instructions, this is neither a mandated requirement nor explicitly specified option. Therefore, there are no RV32I tests included in RVA23 certification. We encourage those who have implemented RV32I instructions in their processor to test these with the appropriate RISC-V ACTs.

=== Related Specifications

* https://riscv.github.io/riscv-isa-manual/snapshot/unprivileged/index.html[Unprivileged ISA Specification] - Latest version
* https://riscv.github.io/riscv-isa-manual/snapshot/privileged/index.html[Privileged ISA Specification] - Latest version

== Discussion

The primary goal of RVA23 is to provide binary compatibility for S- and U-mode operating system and application code.  It does not impose requirements on M-mode firmware.  Certification deliberately avoids imposing requirements on M-mode behavior except where called out in the profile or where M-mode controls behaviors of lower privilege modes.

=== Custom M-mode

The RVA23S64 profile purposefully excludes Machine mode (M-mode).  It does not require a _Standard M-mode_ consistent with the ratified M-mode specification.

Custom M-mode is a supervisor execution environment that deviates from the M-mode specification.  For example, it might have a bug that affects M-mode behavior but is invisible from S-mode.  The firmware could work around this bug by not running M-mode instructions affected by the bug.  Alternatively, custom M-mode might have some security features or custom CSRs that break compatibility with ratified M-mode.

RVA23 does not place any specific requirements on M-mode implementations as it is not required that M-mode code is portable for compliant designs. Instead, in order to be able to run portable code for modes below M-mode, the processor must interface with a Supervisor Execution Environment (SEE).  The RISC-V SBI specification provides an example of a SEE.  Certification tests do not exercise the RISC-V SBI, but provide a simpler Test Supervisor Binary Interface (T-SBI) to access the execution environment.

=== Execution Environment and Test Supervisor Binary Interface (T-SBI)

Nevertheless, RVA23S64 runs within a supervisor execution environment.  For example, an `ECALL` from supervisor mode causes a requested trap to this execution environment. Similarly, the profile indicates that Sspm requires an execution environment providing a means to select `PMLEN`.

RVA23 requires that the execution environment boot to a deterministic state that allows software to run in S-mode, and to handle traps to the execution environment that implements the T-SBI described below. If a custom M-mode execution environment does not directly implement a feature of standard M-mode in hardware, it must be able to emulate that feature in a way that is transparent to software running in lower privilege modes.  For example, if it does not support delegating interrupts to S-mode in hardware, it must accomplish the same purpose in software by trapping to the execution environment, which may in turn deliver the interrupt to S-mode.

The execution environment must provide a Test Supervisor Binary Interface (T-SBI) that allows S-mode software to make requests of the execution environment.  These requests are made by placing commands in registers and performing an `ECALL`. See the Certification Test Plan (CTP) for details. The certification suite provides a reference T-SBI implementation that runs on standard M-mode, but custom M-mode that differs significantly from standard M-mode might have to provide its own T-SBI implementation.

The T-SBI also encompasses boot code and an M-mode trap handler.  Both might need to be modified by the user to accommodate custom M-mode behavior.

=== M-Mode Trap Handler Requirements

Testing M-mode trap behavior is OUT-OF-SCOPE for RVA23 certification with a few exceptions listed below.  As such, the tests delegate almost all traps to S-mode, and do not test M-mode interrupts (MEI/MTI/MSI).  Exceptions are:

* `ecall` from S-mode must not be delegated because the T-SBI must trap to M-mode to handle these calls.
* Any trap cause that should be handled invisibly by the firmware must not be delegated.
* Hardware may not support delegating certain traps to S-mode.

Invisible traps are traps to emulate a function in firmware that is not implemented in hardware.  An example of an invisible trap is to fix a `fdiv` instruction that malfunctions for certain input values.
If a system required invisible traps to produce correct RVA23 behavior, the user must provide custom firmware to handle these traps, and the certification tests rely on this firmware.  For example, `fdiv` would throw an illegal instruction exception, and this exception would not be delegated to S-mode.  The user would have to provide a M-mode trap handler that inspects illegal instruction exceptions and determines if the instruction is an `fdiv`.  If so, it invisibly fixes any problem and returns.  Otherwise, the M-mode handler places trap information into `sstatus`,`sepc`/`scause`/`stval` and invokes the S-mode trap handler to handle other illegal instructions.

The M-mode trap handler performs the following functions:

. Check if the trap is a T-SBI call and if so, perform the requested T-SBI function and return from the `ecall`.
. Call custom firmware, if any exists, to handle invisible traps.  The custom firmware will save registers relative to `sp`, inspect machine state to see if the trap is an invisible trap, and if so, perform the function, clean up, and return to the appropriate place (perhaps the instruction after the one that trapped, or an S-mode handler if the custom firmware expects S-mode to receive the trap next).  If the trap is not an invisible trap, the custom firmware will return to the next step of the M-mode trap handler.
. For traps that are not delegated in hardware but should still go to S-mode, set up `sstatus`, `sepc`, `scause`, `stval` with values coming from the machine-mode trap CSRs, and return to the S-mode trap handler to effectively delegate to S-mode.

=== T-SBI Control of M-mode CSRs

RVA23 certification requires that the T-SBI provide methods of emulating every writable standard M-mode CSR field that can affect the behavior of lower privilege modes.  With a standard M-mode, the T-SBI may just write bitfields in the M-mode registers.  With custom M-mode, the T-SBI must make it appear to S-mode software that the field holds the value written by the T-SBI, even though the implementation might be different. These CSRs and memory-mapped I/O registers are:

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mstatus` | TSR, TW, TVM
| `mcounteren` | All fields not hardwired to 0 must be controllable to allow testing of counter access from lower privilege modes.
| `mcountinhibit` | All fields not hardwired to 0 must be controllable to allow testing of counter behavior from lower privilege modes.
| `mip` | Interrupts are controlled with RVMODEL macros.  SEIP, STIP, and SSIP may be controlled with T-SBI accesses to `mip`.
| `menvcfg` | STCE, PBMTE, ADUE, PMM, CBZE, CBCFE, CBIE, SSE, LPE may be controllable to allow testing of the behavior of lower privilege modes with these features enabled and disabled. Note that ADUE may be read-only zero because Svadu is optional, and that PMM may only be able to hold PMLEN=0 and 7 per the RVA23 profile. CBIE must be able to hold 00 and at least one of 01 and/or 11. CDE, DTE are OUT-OF-SCOPE because they do not relate to RVA23 features. FIOM is OUT-OF-SCOPE because I/O memory is not required by the RVA23 profile. All writable fields must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled.
| `mseccfg` | SSEED and USEED must be controllable if Zkr is supported; otherwise they are read-only zero.  PMM, MLPE, RLB, MMWP, MML are OUT-OF-SCOPE because they do not relate to RVA23 features.  Note `mseccfg.PMM` affects Smmpm, which is not part of RVA23.
| `mstateen` | SE0, ENVCFG, CONTEXT may be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled. Other fields are OUT-OF-SCOPE because they do not relate to RVA23 features.
| `medeleg` | Each exception cause except `ecall` from S-mode is delegated to S-mode if the corresponding bit can be written to 1.  Otherwise, a user-supplied M-mode trap handler intercepts invisible traps and logs the rest or relays them to S-mode.
| `mideleg` | SEI, STI, SSI, and LCOFI are delegated to S-mode if the corresponding bit can be written to 1.  Otherwise, a user-supplied M-mode trap handler relays these to S-mode. VSEI, VSTI, VSSI and SGEI (if implemented) are read-only 1 per Priv Spec 22.4.2 because hypervisor is a mandatory part of the profile.
|===

The following CSRs and memory-mapped I/O registers are only read during RVA23 certification.

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mhartid` | Must be readable to influence the behavior of multicore tests.
| `mtime` | Must be readable to find the current time to set timer interrupts.
|===

The following M-mode CSRs/fields are OUT-OF-SCOPE and not tested:

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mstatus` | SD, SPELP, MXR, SUM, FS, VS, SPP, SPIE, SIE are accessible from `sstatus` and should not be tested through `mstatus` for RVA23 certification. GVA is accessible from `hstatus` and not tested from `mstatus`.  MPV does not affect the behavior of lower privilege modes. XS, SDT, MBE, SBE, UBE, SXL, UXL OUT-OF-SCOPE for RVA23.
| `mie` | SEIE, STIE, SSIE, LCOFIE, and SGEIE are controlled from `sie` or `hie`.
| `misa` | Not tested because required RVA23 features are not turned off during testing.
| `mvendorid` | Does not affect the behavior of lower privilege modes.
| `marchid` | Does not affect the behavior of lower privilege modes.
| `mimpid` | Does not affect the behavior of lower privilege modes.
| `mconfigptr` | Does not affect the behavior of lower privilege modes.
| `mtvec` | Trap vector must be set up during boot but is not modified through SBI.
| `mepc` | Does not affect the behavior of lower privilege modes.
| `mcause` | Does not affect the behavior of lower privilege modes.
| `mscratch` | Does not affect the behavior of lower privilege modes.
| `mtval` | Does not affect the behavior of lower privilege modes.
| `mtinst` | Does not affect the behavior of lower privilege modes.
| `mtval2` | Does not affect the behavior of lower privilege modes.
| `mtimecmp` | MTI is not tested.
| `msip` | MSI is not tested.
| PMP CSRs | PMP restrictions on access are indistinguishable below M-mode from a PMA that imposes similar restrictions.
|===

=== Interrupts

All supervisor interrupts (SEI, STI, SSI, and LCOFI) are IN-SCOPE for testing. Hypervisor interrupts VSEI, VSTI, VSSI, and SGEI are also IN-SCOPE. Machine interrupts are OUT-OF-SCOPE.

LCOFI is mandatory because it is part of the Sscofpmf extension, which is required by the profile. STI and VSTI are mandatory because Sstc is a required part of the profile. The other supervisor interrupts (SEI, SSI) are optional per the supervisor specification: "Each standard interrupt type (SEI, STI, SSI, or LCOFI) may not be implemented."  SGEI is optional because GEILEN can be 0.  The other hypervisor interrupts (VSEI, VSSI) are vague in the specification but are treated as optional because their supervisor counterparts are optional.

Machine interrupts (MEI, MTI, MSI) are outside the RVA23 profile and are OUT-OF-SCOPE for certification.

=== User Requirements

The user must provide:

* DUT configuration information described in the CTP, including UDB description, linker file describing memory map, sail.json configured to match DUT, RVMODEL macros specific to DUT.
* Custom trap handler, if any, to handle invisible traps.
* Custom boot code, if standard M-mode boot code does not run on the DUT or if additional configuration is necessary.

=== Parameters

Parameters affecting RVA23 are under development and are discussed in the Certification Test Plan.
