= RVA23 Certification Requirements Document (rev 0.1)
:description: RVA23 CRD (Certificate Requirements Document)
include::../../common/adoc_common.adoc[]

_Contributors to all versions of the spec in alphabetical order_

* Ken Dockser
* David Harris

_This document is released under a Creative Commons Attribution 4.0 International License._

[Preface]
== CRD Revision History

History of documentation changes that eventually lead to releases.

[cols="1,1,5"]
|===
| Date | Revision | Changes

| April 29, 2026
| 0.1
a| * Initial draft

|===

// include::glossary.adoc[]

== Introduction

The RVA23 processor certificate is based on compliance with the
https://riscv.github.io/riscv-isa-manual/snapshot/spec/#_rva23_profiles [RVA23
Profiles] which is comprised of the RVA23S64
and RVA23U64 profiles. As described in these profile specifications,
compliance requires that the RV64I base instruction set and all mandatory extensions of the profile must be
implemented. Furthermore, any optional extensions as specified in the profile may be implemented. Any optional portions
of the base ISA and these extensions may be implemented, but if they are
implemented, they must be implemented in their entirety.

There is no prohibition against implementing other RISC-V ratified base ISAs or
extensions, custom extensions, or even non-conforming as
long as they don't interfere with the proper functioning of the RVA23 mandatory
and optional extensions. However, these other base ISAs and extensions will not be tested as
part of RVA23 Certification.

////
NOTE: While it is permitted for an implementation to also support RV32I instructions, this is neither a mandated requirement nor explicitly specified option. Therefore, there are no RV32I tests included in RVA23 certification. We encourage those who have implemented RV32I instructions in their processor to test these with the appropriate RISC-V ACTs.
////

NOTE: We encourage those who have implemented other base ISAs or extensions to
run the appropriate RISC-V ACTs to help ensure compliance.

=== Related Specifications

* https://riscv.github.io/riscv-isa-manual/snapshot/unprivileged/index.html[Unprivileged ISA Specification] - Latest version
* https://riscv.github.io/riscv-isa-manual/snapshot/privileged/index.html[Privileged ISA Specification] - Latest version

////
== Discussion

The RVA23S64 profile implies requirements that might not be immediately
obvious.  This section explains them in detail.
////

=== Abstraction of M-Mode and implementation specific behavior

=== Execution Environment and Test Supervisor Binary Interface (T-SBI)

Application-processor families, including RVA23, purposefully do not include a
machine mode profile as there is no
intention that M-mode code be portable. Therefore, RVA23 Certification does
not test M-mode instructions or CSRs. Any required interaction with M-mode is
abstracted away by a Test Supervisor Binary Interface (T-SBI) and a Test
Supervisor Execution Environment (T-SEE), which are analogous to the RISC-V
Supervisor Binary Interface  and OpenSBI software respectively;
however, they are developed specifically for certification. The T-SEE is also
responsible for invoking the implementation's
boot code as well as setting up the initial M-mode-controlled environment for
the certification tests. All certification tests run under the T-SEE.

As part of the certification test collateral, a reference implementation of
the T-SEE is provided along with a full
specification of the T-SBI. Just like with OpenSBI,
it is up to the designer to modify the T-SEE, as necessary, for their
implementation. The T-SBI specification is especially useful
for those who have created an M-mode that differs substantially from M-mode 1.13
as defined in the RISC-V Privileged Architecture.

When the T-SEE receives a trap from M-mode, it invokes the appropriate handler.
When it is necessary to execute M-mode instructions or access a Machine-mode
ISA CSR in order to properly set up the environment for lower privilege tests, a
T-SBI-defined `ECALL` is made. This `ECALL`'s trap handler executes the
necessary M-mode code need to complete the requested action. One such need for a
T-SBI call is necessary to fufill a requirement of RVA23's defined Sspm
extension which requires an execution environment to provide a means to select
PMLEN. Another need is for the tests to be able to request that specific traps are
delegated away from M- mode.

NOTE: There is no requirement that any traps can be delegated. But if they can be, the SEE must provide a means to request that they are and a means to determine which requested traps have been delegated.

=== M-mode Trap Handler Requirements

All traps default to M-mode. Most traps can be delegated to S-mode, with the following exceptions:

* `ECALL` from S-mode must not be delegated because the T-SBI must trap to
M-mode to handle these calls.
* Any trap cause that should be handled invisibly by the firmware must not be delegated.
* Trap causes that hardware cannot delegate (e.g., bits of `m*deleg` that are
read-only zero.)
* Intentionally testing traps to M-mode.

NOTE: Machine interrupts MEI, MSI, MTI are normally not delegated because they
usually go to M-mode. For purposes of testing, it fine to delegate them to
S-mode when allowed.

Invisible traps are traps to emulate a function in firmware that is not implemented in hardware.  An example of an invisible trap is to fix a `fdiv` instruction that malfunctions for certain input values.
If a system requires invisible traps to produce correct RVA23 behavior, the user must provide custom firmware to handle these traps, and the certification tests rely on this firmware.

The m-mode trap handler performs the following functions:

. Check if the trap is a T-SBI call and if so, perform the requested T-SBI function and return from the `ECALL`.
. Call custom firmware, if any exists, to handle invisible traps.  The custom
firmware will save registers relative to `sp`, inspect machine state to see if
the trap is an invisible trap, and if so, perform the function, clean up, and
return to the appropriate place (perhaps the instruction after the one that
trapped, or an S-mode handler if the custom firmware expects S-mode to receive
the trap next).  If the trap is not an invisible trap, the custom firmware will
return to the next step of the m-mode trap handler.
. Check if the trap is a test of non-delegated traps to M-mode, and if so, 
////
write/compare a trap signature of the standard values expected in `mepc`,
`mcause`, `mtval` and `mstatus.MPV/MPP/MPIE/MPELP`.
////
set up `sstatus`, `sepc`, `scause`, `stval` with values coming from the machine-mode trap CSRs, and return to the S-mode trap handler to effectively delegate to S-mode.


////
NB: The RISC-V SBI specifies the function to be performed (e.g., delegate
misaligned) not the bitfield of a specific register
=== SBI Control of m-mode CSRs

RVA23 certification requires that the SBI provide methods of emulating every
writable standard m-mode CSR field that can affect the behavior of
lower-privilege modes.  With a standard m-mode, the SBI may just write bitfields
in the m-mode registers.  With custom m-mode, the SBI must make it appear to
S-mode software that the field holds the value written by the SBI, even though
the implementation might be different. 
////

These CSRs and memory-mapped I/O registers are:

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mstatus` | TSR, TW, TVM
| `mcounteren` | All fields not hardwired to 0 must be controllable to allow testing of counter access from lower-privilege modes.
| `mcountinhibit` | All fields not hardwired to 0 must be controllable to allow testing of counter behavior from lower privilege modes.
| `mip` | Interrupts are controlled with RVMODEL macros.  SEIP, STIP, and SSIP may be controlled with T-SBI accesses to `mip`.
| `mie` | MEIE, MSIE, MTIE control whether these interrupts are enabled.
| `menvcfg` | STCE, PBMTE, ADUE, PMM, CBZE, CBCFE, CBIE, SSE, LPE, FIOM must be controllable to allow testing of the behavior of lower privilege modes with these features enabled and disabled. Note that some bits may be read-only zero. CDE, DTE are OUT-OF-SCOPE because they do not relate to RVA23 features. All writable fields must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled.
| `mseccfg` | PMM, SSEED, and USEED must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled.  Note that some bits may be read-only zero. MLPE, RLB, MMWP, MML are OUT-OF-SCOPE because they do not relate to RVA23 features.
| `mstateen` | SE0, ENVCFG, CONTEXT must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled. Note that some bits may be read-only zero.  Other fields are OUT-OF-SCOPE because they do not relate to RVA23 features.
| `medeleg` | Each exception cause is tested both with (if possible) and without delegation.
| `mideleg` | Each interrupt cause is tested both with (if possible) and without delegation except that MTI, MEI, MSI are not delegated.
|===

The following CSRs and memory-mapped I/O registers are only read during RVA23 certification.

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mhartid` | Must be readable to influence the behavior of multicore tests.
| `mtime` | Must be readable to find the current time to set timer interrupts.
|===

The following M-mode CSRs/fields are OUT-OF-SCOPE and not tested:

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mstatus` | SD, SPELP, MXR, SUM, FS, VS, SPP, SPIE, SIE are accessible from `sstatus` and should not be tested through `mstatus` for RVA23 certification. GVA is accessible from `hstatus` and not tested from `mstatus`.  MPV does not affect the behavior of lower privilege modes. XS, SDT, MBE, SBE, UBE, SXL, UXL OUT-OF-SCOPE for RVA23.
| `mie` | SEIE, STIE, SSIE, LCOFIE, and SGEIE are controlled from `sie` or `hie`.
| `misa` | Not tested because required RVA23 features are not turned off during testing.
| `mvendorid` | Does not affect the behavior of lower privilege modes.
| `marchid` | Does not affect the behavior of lower privilege modes.
| `mimpid` | Does not affect the behavior of lower privilege modes.
| `mconfigptr` | Does not affect the behavior of lower privilege modes.
| `mtvec` | Trap vector must be set up during boot but is not modified through SBI.
| `mepc` | Does not affect the behavior of lower privilege modes.
| `mcause` | Does not affect the behavior of lower privilege modes.
| `mscratch` | Does not affect the behavior of lower privilege modes.
| `mtval` | Does not affect the behavior of lower privilege modes.
| `mtinst` | Does not affect the behavior of lower privilege modes.
| `mtval2` | Does not affect the behavior of lower privilege modes.
| PMP CSRs | PMP restrictions on access are indistinguishable below M-mode from a PMA that imposes similar restrictions.
|===

=== Interrupts

All interrupts taken from S and U-mode are IN-SCOPE for testing.  MTI, MEI, and MSI are only tested without delegation to S-mode, while the other interrupts are tested with and without delegation, if `mideleg` supports this.


////
NB: Except for the DUT configuration information, this is already defined above
including addition cases
NB: The DUT configuration needs to be described in greater detail. It does not
need to be here.  

=== User Requirements

The user must provide:

* DUT configuration information described in the CTP, including UDB description, linker file describing memory map, sail.json configured to match DUT, RVMODEL macros specific to DUT.
* Implementation-specific firmware, as necessary
* Implementation-specific boot code, as necessary

if standard M-mode boot code does not run on the DUT or if additional
configuration is necessary.

NB: Implementations tend to have their own boot code
////

=== Notes

The following items are still open for discussion:

* Does every certification test need to be run twice with traps delegated and undelegated, or is it sufficient to run each type of trap at least once undelegated to check that the correct information is conveyed to M-mode and run most tests with delegation?
* Generate a list of all applicable RVA23 parameters and their supported range of values.  Depends on input from Parameters Working Group.
