= RVA23 Certification Requirements Document (rev 0.1)
:description: RVA23 CRD (Certificate Requirements Document)
include::../../common/adoc_common.adoc[]

_Contributors to all versions of the spec in alphabetical order_

* Allen Baum
* Jordan Carlin
* Ken Dockser
* David Harris


_This document is released under a Creative Commons Attribution 4.0 International License._

[Preface]
== CRD Revision History

History of documentation changes that eventually lead to releases.

[cols="1,1,5"]
|===
| Date | Revision | Changes

| April 29, 2026
| 0.1
a| * Initial draft

|===

// include::glossary.adoc[]

== Introduction

The RVA23 processor certificate is based on the https://riscv.github.io/riscv-isa-manual/snapshot/spec/#_rva23s64_profile[RVA23S64] profile. To
qualify for a certificate, the processor must implement the RV64I base instruction set and all of the mandatory
extensions of the profile.  It may implement any of the optional features of
the profile.  It may implement ratified extensions that are not part of the profile. It may implement other unratified extensions, but must not implement
unratified extensions outside the custom encoding spaces if the optional Ssstrict extension is implemented. Extensions outside the profile are not tested during
certification.

=== Related Specifications

* https://riscv.github.io/riscv-isa-manual/snapshot/unprivileged/index.html[Unprivileged ISA Specification] - Latest version
* https://riscv.github.io/riscv-isa-manual/snapshot/privileged/index.html[Privileged ISA Specification] - Latest version

== Discussion

The RVA23S64 profile implies requirements that might not be immediately
obvious.  This section explains them in detail.

=== Scope of Testing

RVA23 certification requires testing all of the behaviors defined in the profile at supervisor mode and below.  It also requires testing an `ecall` from supervisor mode to the execution environment as defined in the profile.

RVA23 certification also requires testing all non-machine-mode interrupts (all interrupts except MTI, MEI, MSI). [Ken take an action item of whether these are in scope].

Although it is not explicitly stated in the profile, RVA23 certification requires testing exceptions and interrupts that are received by M-mode rather than delegated to lower modes.  The trap handler must be able to record the machine mode state (such as `mcause`, `mtval`) consistent with the standard M-mode specification. [Try to give cite to spec to justify this.]

Although it is not explicitly stated in the profile, RVA23 certification requires testing certain machine-mode CSR fields that affect the behavior of lower privilege mode. In particular, it requires testing `mstatus.TSR`, `mstatus.TW`, and `mstatus.TVM`.  [Is this everything]?

It does not require testing of M-mode state that disables access to features in lower privilege modes, including `menvcfg`, `mseccfg`, and `mstateen` fields.  These are initialized at the start of the test to support the required and implemented optional features of the profile, and disabling these features from M-mode is OUT-OF-SCOPE.  The tests also assume a reasonable amount of cacheable coherent main memory is available to hold the test code and data, and that PMAs and PMPs permit access to this memory.  Testing PMA or PMP restrictions is OUT-OF-SCOPE. [Is there anything else to go here.  Alternative: test all this disabling, as given in CSR descriptions below.  Update this part or CSRs to match.]

Discuss Allen's problem of unexpected traps. For example, trap on all aes instructions, or trap on fp instruction with subnorm inputs or results.  This break ACT trap logging in a severe way.

Ken: M-mode trap handler has a jump to customer code that optionally does emulation, then returns to our trap handler.

Alternate approach:
Normally just test traps delegated to S-mode in the default trap handler.
If the firmware needs to do something special, it can install a different boot code that traps to M-mode instead, intercepts what needs to happen, and then relays the trap to S-mode if it should have been visible by S-mode.

=== Custom M-mode

The RVA23S64 profile purposefully excludes Machine mode (M-mode).  It does not require a _Standard M-mode_ consistent with the ratified M-mode specification.
Therefore, certification does not run M-mode code directly.

Custom M-mode is an supervisor execution environment that deviates from the M-mode specification.  For example, it might have a bug that affects M-mode behavior but is invisible from S-mode.  The firmware could work around this bug by not running M-mode instructions affected by the bug.  Alternatively, Custom M-mode might have some security features or proprietary CSRs that break compatibility with ratified M-mode.

=== Execution Environment and Supervisor Binary Interface (SBI)

Nevertheless, RVA23S64 runs within a supervisor execution environment.  For example, an `ECALL` from supervisor mode causes a requested trap to this execution environment. Similarly, the profile indicates that Sspm requires an execution environment providing a means to select PMLEN.

RVA23 requires that the execution environment boot to a deterministic state that allows software to run in S-mode, and to handle traps to the execution environment that implements a test SBI (described below). If a custom M-mode execution environment does not directly implement a feature of standard M-mode in hardware, it must be able to emulate that feature in a way that is transparent to software running in lower privilege modes.  For example, if it does not support delegating interrupts to S-mode in hardware, it must accomplish the same purpose in software by trapping to the execution environment, which delivers the interrupt to S-mode.

The execution environment must provide a Supervisor Binary Interface (SBI) that allows S-mode software to make requests of the execution environment.  These requests are made by placing commands in registers and performing an `ECALL`.

=== SBI Control of M-mode CSRs

RVA23 certification requires that the SBI provide methods of emulating every writable standard M-mode CSR field that can affect the behavior of lower privilege modes.  With a standard M-mode, the SBI may just write bitfields in the M-mode registers.  With custom M-mode, the SBI must make it appear to S-mode software that the field holds the value written by the SBI, even though the implementation might be different.

These CSRs and memory-mapped I/O registers are:

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mstatus` | TSR, TW, TVM
| `mcounteren` | All fields not hardwired to 0 must be controllable to allow testing of counter access from lower privilege modes.
| `mcountinhibit` | All fields not hardwired to 0 must be controllable to allow testing of counter behavior from lower privilege modes.
| `menvcfg` | STCE, PBMTE, ADUE, PMM, CBZE, CBCFE, CBIE, SSE, LPE, FIOM must be controllable to allow testing of the behavior of lower privilege modes with these features enabled and disabled. Note that some bits may be read-only zero. CDE, DTE, are OUT-OF-SCOPE because they do not relate to RVA23 features.
All writable fields must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled.
| `mseccfg` | PMM, SSEED, and USEED must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled.  Note that some bits may be read-only zero. MLPE, RLB, MMWP, MML are OUT-OF-SCOPE of RVA23.
| `mstateen` | SE0, ENVCFG, CONTEXT must be controllable to allow testing of the behavior of lower privilege modes when certain features are disabled. Note that some bits may be read-only zero.  Other fields are OUT-OF-SCOPE because they do not relate to RVA23 features.
| `medeleg` | All standard exceptions are tested both with delegation to S and M mode.  When delegated to S mode, `sstatus.SPP/SIE/SPIE`, `sepc`, `scause`, and `stval` must have the values defined by the spec.  If the hardware does not support delegating certain exceptions to S-mode, the M-mode trap handler must be aware of this and emulate delegation to S-mode by invoking the S-mode trap handler through software.  When not delegated to S-mode, the M-mode trap handler must record `mstatus.MPP/MIE/MPIE`, `mepc`, `mcause`, and `mtval`.  If a custom M-mode does not write values to these fields as defined by the M-mode spec, it must emulate the standard behavior by recording what standard M-mode would have written to these CSRs.  TODO: may also need `mtinst`, `mtval2`, `htinst`, check all xstatus bit fields of interest are recorded.
| `mideleg` | Do the same delegation to M and S mode as in `medeleg`for SEI, SSI, STI, LCOFI, SGEI.  MEI, MSI, MTI are OUT-OF-SCOPE and note tested.| `mhartid` | Must be readable to influence the behavior of multicore tests.
| `mtime` | Must be readable to find the current time to set timer interrupts.
| `mtimecmp` | Must be controllable to set timer interrupts.
|===

The following M-mode CSRs are OUT-OF-SCOPE:

[options=header]
[cols="1,5"]
|===
| CSR | Notes
| `mstatus` | SD, SPELP, MXR, SUM, FS, VS, SPP, SPIE, SIE are accessible from `sstatus` and should not be tested through `mstatus` for RVA23 certification. GVA and MPV do not affect the behavior of lower privilege modes. XS, SDT, MBE, SBE, UBE, SXL, UXL OUT-OF-SCOPE for RVA23.
| `misa` | Not tested because the contents do not have a predictable effect on behavior.
| `mvendorid` | Does not affect the behavior of lower privilege modes.
| `marchid` | Does not affect the behavior of lower privilege modes.
| `mimpid` | Does not affect the behavior of lower privilege modes.
| `mconfigptr` | Does not affect the behavior of lower privilege modes.
| PMP CSRs | PMP restrictions on access are indistinguishable below M-mode from a PMA that imposes similar restrictions.
|===

If `mideleg` or `medeleg` fields that should be delegated to S-mode are read-only zero, the supervisor execution environment must respond by invoking the S-mode trap handler through software.

=== Interrupts

Supervisor, virtual supervisor, and counter overflow interrupts are IN-SCOPE and are tested.  Machine interrupts are OUT-OF-SCOPE and are not tested.
