= RVI20 Certification Requirements Document (rev 0.6)
:description: RVI20 CRD (Certificate Requirements Document)
include::../../common/adoc_common.adoc[]

_Contributors to all versions of the spec in alphabetical order_

* James Ball
* David Harris

_This document is released under a Creative Commons Attribution 4.0 International License._

[Preface]
== CRD Revision History

History of documentation changes that eventually lead to releases.

[cols="1,1,5"]
|===
| Date | Revision | Changes

| Mar 5, 2026
| 0.6
a| * Removed MISALIGNED_ATOMICITY_GRANULE_SIZE parameter due to https://github.com/riscv/riscv-isa-manual/issues/2726

| Mar 4, 2026
| 0.5
a| * Added note and link to GitHub issue that MISALIGNED_ATOMICITY_GRANULE_SIZE might be removed from this CRD

| Mar 3, 2026
| 0.4
a| * Incorporated feedback from CSC Requirements WG meeting on Feb 27, 2026
   ** Removed WARL/WLRL handling section since there are no CSRs with WARL/WLRL fields in RVI20
   ** Preliminary parameters now link to normative rules
   * Added Extensions and Parameters appendices
   * Added link to RFC2119 in glossary and use RFC2119 keywords in uppercase throughout the document

| Feb 23, 2026
| 0.3
a| * Incorporated feedback from CSC Requirements WG meeting on Feb 20, 2026
   ** Added column for "Impact on Certificate Scope" in the IN-SCOPE parameters table
   ** Added note that parameters are preliminary

| Feb 23, 2026
| 0.2
a| * Moved from https://github.com/RISC-V-Certification-Steering-Committee/RVCP-docs

| Feb 5, 2026
| 0.1
a| * Copied from UDB-generated adoc
|===

include::glossary.adoc[]

== Introduction

The RVI20-32 processor certificate is based on the RVI20U32 profile.
The RVI20-64 processor certificate is based on the RVI20U64 profile.

The RVI certificate class corresponds to the RVI Profile Family.
This certificate class only includes the RISC-V Unprivileged ISA.
Certificates for the RVI certificate class are intended for internal
use by the RVCP (RISC-V Certification Program).

include::crd_common.adoc[]

=== Related Specifications

* https://riscv.github.io/riscv-isa-manual/snapshot/unprivileged/index.html[Unprivileged ISA Specification] - Latest version
* https://github.com/riscv/riscv-profiles/blob/main/src/profiles.adoc[RISC-V Profiles Document] - Will be moving to ISA Manual repository soon

<<<
== Base ISA

.Base ISA Requirements
[cols="1,4"]
|===
| Requirement ID | Description

| REQ32-BASE | Uses the RV32I base integer ISA
| REQ64-BASE | Uses the RV64I base integer ISA
| REQ-ENDIANNESS | Only little-endian is supported
|===

=== Exclusions

As per the unprivileged architecture specification, the `ecall`
instruction causes a requested trap to the execution environment.
Since the RVI profile family doesn't define any execution environments
the `ecall` instruction is OUT-OF-SCOPE for the RVI20 certificate.

Similarly the `ebreak` and `c.ebreak` instructions are OUT-OF-SCOPE for the RVI20 certificate
since they cause a breakpoint exception and the RVI profile family doesn't define any
execution environments to handle such exceptions.

<<<
== Extensions

:include::extensions_intro.adoc[]

=== Mandatory Extensions

None

=== Optional Extensions

.Optional Extensions
[%autowidth]
|===
| Requirement ID | Extension | Version

| REQ-EXT-A | <<extension:A,A>> | ~> 2.1
| REQ-EXT-C | <<extension:C,C>> | ~> 2.0
| REQ-EXT-D | <<extension:D,D>> | ~> 2.2
| REQ-EXT-F | <<extension:F,F>> | ~> 2.2
| REQ-EXT-M | <<extension:M,M>> | ~> 2.0
| REQ-EXT-Zicntr | <<extension:Zicntr,Zicntr>> | ~> 2.0
| REQ-EXT-Zifencei | <<extension:Zifencei,Zifencei>> | ~> 2.0
| REQ-EXT-Zihpm | <<extension:Zihpm,Zihpm>> | ~> 2.0
|===

<<<
== Parameter Values

This section lists the parameters that are IN-SCOPE and OUT-OF-SCOPE for the RVI20 certificate.

Please refer to the <<parameter_defs,Parameter Definitions>> appendix for more information about the parameters listed in this section or click on the parameter names in the table below to jump to their definitions.

include::in_scope_param_intro.adoc[]

.IN-SCOPE Parameters
[%autowidth]
|===
| Parameter | Allowed Value(s) | Impact on Certificate Scope

| <<param:LRSC_RESERVATION_STRATEGY,LRSC_RESERVATION_STRATEGY>>
| Any
| The load-reserved/store-conditional instructions are only IN-SCOPE if this parameter is not "Other"

| <<param:MISALIGNED_LDST_HW_SUPPORT,MISALIGNED_LDST_HW_SUPPORT>>
| True, False
| Misaligned load/store instructions are only IN-SCOPE if this parameter is true
and if any restrictions on misaligned load/store instructions expressed by other parameters are met.

| <<param:TIME_CSR_HW_SUPPORT,TIME_CSR_HW_SUPPORT>>
| Any
| Reading time-related CSRs is only IN-SCOPE if this parameter is true

|===

include::out_of_scope_param_intro.adoc[]

.OUT-OF-SCOPE Parameters
[%autowidth]
|===
| Parameter

| <<param:HPM_COUNTER_SZ,HPM_COUNTER_SZ>>

|===

== CSR WARL Fields

There are no CSRs in RVI20 with WARL fields.

== CSR WLRL Fields

There are no CSRs in RVI20 with WLRL fields.

<<<
include::extension_defs.adoc[]

<<<
include::param_defs.adoc[]
