// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 RISC-V International
//
// udb_parameters.h: every UDB parameter and the condition under which it applies to the hart.
// Generated by test/gen_udb_parameters.py from riscv-unified-db 1def7f96; do not edit by hand.
//
// UDB_PARAMETERS(P) expands P(name, applies) for each parameter, where applies is a C
// expression over have(), has_s, has_h, has_u, vlen, num_pmp and any_atp.

#define UDB_PARAMETERS(P) \
    P(ARCH_ID_VALUE, (true)) \
    P(ASID_WIDTH, has_s) \
    P(CACHE_BLOCK_SIZE, (have("Zicbom")) || (have("Zicbop")) || (have("Zicboz"))) \
    P(CONFIG_PTR_ADDRESS, true) \
    P(COUNTINHIBIT_EN, (true)) \
    P(DBG_HCONTEXT_WIDTH, have("Sdtrig")) \
    P(DBG_SCONTEXT_WIDTH, have("Sdtrig")) \
    P(DCSR_MPRVEN_TYPE, have("Sdtrig")) \
    P(DCSR_STEPIE_TYPE, have("Sdtrig")) \
    P(DCSR_STOPCOUNT_TYPE, have("Sdtrig")) \
    P(DCSR_STOPTIME_TYPE, have("Sdtrig")) \
    P(ELEN, vlen != 0) \
    P(FOLLOW_VTYPE_RESET_RECOMMENDATION, vlen != 0) \
    P(FORCE_UPGRADE_CBO_INVAL_TO_FLUSH, have("Zicbom")) \
    P(GSTAGE_MODE_BARE, has_h) \
    P(HCONTEXT_AVAILABLE, have("Sdtrig")) \
    P(HCOUNTENABLE_EN, has_h) \
    P(HPM_COUNTER_EN, true) \
    P(HPM_EVENTS, (true)) \
    P(HSTATEEN_AIA_TYPE, (have("Ssaia")) && (has_h) && (have("Ssstateen"))) \
    P(HSTATEEN_CONTEXT_TYPE, (have("Sdtrig")) && (has_h) && (have("Ssstateen"))) \
    P(HSTATEEN_CSRIND_TYPE, (have("Sscsrind")) && (has_h) && (have("Ssstateen"))) \
    P(HSTATEEN_ENVCFG_TYPE, (has_h) && (have("Ssstateen"))) \
    P(HSTATEEN_IMSIC_TYPE, (have("Ssaia")) && (has_h) && (have("Ssstateen"))) \
    P(HSTATEEN_JVT_TYPE, (have("Zcmt")) && (has_h) && (have("Ssstateen"))) \
    P(HW_MSTATUS_FS_DIRTY_UPDATE, (have("F")) && (true)) \
    P(HW_MSTATUS_VS_DIRTY_UPDATE, (vlen != 0) && (true)) \
    P(IGNORE_INVALID_VSATP_MODE_WRITES_WHEN_V_EQ_ZERO, has_h) \
    P(IMPRECISE_VECTOR_TRAP_SETTABLE, vlen != 0) \
    P(IMP_ID_VALUE, (true)) \
    P(JVT_BASE_MASK, (have("Zcmt"))) \
    P(JVT_BASE_TYPE, have("Zcmt")) \
    P(JVT_READ_ONLY, have("Zcmt")) \
    P(LEGAL_VSTART, vlen != 0) \
    P(LRSC_FAIL_ON_NON_EXACT_LRSC, have("Zalrsc")) \
    P(LRSC_FAIL_ON_VA_SYNONYM, have("Zalrsc")) \
    P(LRSC_MISALIGNED_BEHAVIOR, have("Zalrsc")) \
    P(LRSC_RESERVATION_STRATEGY, have("Zalrsc")) \
    P(MARCHID_IMPLEMENTED, true) \
    P(MCID_WIDTH, have("Ssqosid")) \
    P(MCONTEXT_AVAILABLE, have("Sdtrig")) \
    P(MCOUNTENABLE_EN, true) \
    P(MCOUNTINHIBIT_IMPLEMENTED, true) \
    P(MCTRCTL_CORSWAPINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_CUSTOM_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_DIRCALLINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_DIRJMPINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_DIRLJMPINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_EXCINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_INDCALLINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_INDJMPINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_INDLJMPINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_INTRINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_MTE_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_NTBREN_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_RASEMU_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_RETINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_STE_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_TKBRINH_IMPLEMENTED, have("Smctr")) \
    P(MCTRCTL_TRETINH_IMPLEMENTED, have("Smctr")) \
    P(MEI_INTR_IMPL, (true) && (true)) \
    P(MIMPID_IMPLEMENTED, true) \
    P(MISALIGNED_AMO, have("Zaamo")) \
    P(MISALIGNED_LDST, true) \
    P(MISALIGNED_LDST_EXCEPTION_PRIORITY, true) \
    P(MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE, (true)) \
    P(MISALIGNED_SPLIT_STRATEGY, (true)) \
    P(MISA_CSR_IMPLEMENTED, true) \
    P(MSI_INTR_IMPL, (true) && (true)) \
    P(MSTATEEN_AIA_TYPE, (have("Ssaia")) && (have("Smstateen"))) \
    P(MSTATEEN_CONTEXT_TYPE, (have("Sdtrig")) && (have("Smstateen"))) \
    P(MSTATEEN_CSRIND_TYPE, (have("Sscsrind")) && (have("Smstateen"))) \
    P(MSTATEEN_ENVCFG_TYPE, (has_s) && (have("Smstateen"))) \
    P(MSTATEEN_IMSIC_TYPE, (have("Ssaia")) && (have("Smstateen"))) \
    P(MSTATEEN_JVT_TYPE, (have("Zcmt")) && (have("Smstateen"))) \
    P(MSTATUS_FS_LEGAL_VALUES, (true) && ((have("F")) || (has_s))) \
    P(MSTATUS_VS_LEGAL_VALUES, (true) && ((vlen != 0) || (has_s))) \
    P(MTI_INTR_IMPL, (true) && (true)) \
    P(MTVAL_WIDTH, true) \
    P(MTVEC_ACCESS, true) \
    P(MTVEC_BASE_ALIGNMENT_DIRECT, (true)) \
    P(MTVEC_BASE_ALIGNMENT_VECTORED, (true)) \
    P(MTVEC_ILLEGAL_WRITE_BEHAVIOR, true) \
    P(MTVEC_MODES, true) \
    P(MUTABLE_MISA_A, (have("A")) && (true)) \
    P(MUTABLE_MISA_B, (have("B")) && (true)) \
    P(MUTABLE_MISA_C, (have("C")) && (true)) \
    P(MUTABLE_MISA_D, (have("D")) && (true)) \
    P(MUTABLE_MISA_F, (have("F")) && (true)) \
    P(MUTABLE_MISA_H, (true) && (has_h)) \
    P(MUTABLE_MISA_M, (have("M")) && (true)) \
    P(MUTABLE_MISA_Q, (have("Q")) && (true)) \
    P(MUTABLE_MISA_S, (has_s) && (true)) \
    P(MUTABLE_MISA_U, (has_u) && (true)) \
    P(MUTABLE_MISA_V, (have("V")) && (true)) \
    P(MXLEN, true) \
    P(M_MODE_ENDIANNESS, true) \
    P(NUM_EXTERNAL_GUEST_INTERRUPTS, has_h) \
    P(NUM_PMP_ENTRIES, true) \
    P(NUM_USABLE_PMP_ENTRIES, num_pmp > 0) \
    P(PHYS_ADDR_WIDTH, true) \
    P(PMA_GRANULARITY, true) \
    P(PMLEN, (have("Smmpm")) || (have("Smnpm")) || (have("Ssnpm"))) \
    P(PMP_GRANULARITY, num_pmp > 0) \
    P(PMP_NA4_SUPPORTED, num_pmp > 0) \
    P(PMP_NAPOT_SUPPORTED, num_pmp > 0) \
    P(PMP_TOR_SUPPORTED, num_pmp > 0) \
    P(PRECISE_SYNCHRONOUS_EXCEPTIONS, true) \
    P(RCID_WIDTH, have("Ssqosid")) \
    P(REPORT_CAUSE_IN_MTVAL_ON_LANDING_PAD_SOFTWARE_CHECK, have("Zicfilp")) \
    P(REPORT_CAUSE_IN_MTVAL_ON_SHADOW_STACK_SOFTWARE_CHECK, have("Zicfiss")) \
    P(REPORT_CAUSE_IN_STVAL_ON_LANDING_PAD_SOFTWARE_CHECK, have("Zicfilp")) \
    P(REPORT_CAUSE_IN_STVAL_ON_SHADOW_STACK_SOFTWARE_CHECK, have("Zicfiss")) \
    P(REPORT_CAUSE_IN_VSTVAL_ON_LANDING_PAD_SOFTWARE_CHECK, have("Zicfilp")) \
    P(REPORT_CAUSE_IN_VSTVAL_ON_SHADOW_STACK_SOFTWARE_CHECK, have("Zicfiss")) \
    P(REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION, true) \
    P(REPORT_ENCODING_IN_STVAL_ON_ILLEGAL_INSTRUCTION, has_s) \
    P(REPORT_ENCODING_IN_VSTVAL_ON_ILLEGAL_INSTRUCTION, has_h) \
    P(REPORT_ENCODING_IN_VSTVAL_ON_VIRTUAL_INSTRUCTION, has_h) \
    P(REPORT_GPA_IN_HTVAL_ON_GUEST_PAGE_FAULT, has_h) \
    P(REPORT_GPA_IN_TVAL_ON_INSTRUCTION_GUEST_PAGE_FAULT, has_h) \
    P(REPORT_GPA_IN_TVAL_ON_INTERMEDIATE_GUEST_PAGE_FAULT, has_h) \
    P(REPORT_GPA_IN_TVAL_ON_LOAD_GUEST_PAGE_FAULT, has_h) \
    P(REPORT_GPA_IN_TVAL_ON_STORE_AMO_GUEST_PAGE_FAULT, has_h) \
    P(REPORT_VA_IN_MTVAL_ON_BREAKPOINT, true) \
    P(REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT, true) \
    P(REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED, true) \
    P(REPORT_VA_IN_MTVAL_ON_INSTRUCTION_PAGE_FAULT, has_s) \
    P(REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT, true) \
    P(REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED, true) \
    P(REPORT_VA_IN_MTVAL_ON_LOAD_PAGE_FAULT, has_s) \
    P(REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT, true) \
    P(REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED, true) \
    P(REPORT_VA_IN_MTVAL_ON_STORE_AMO_PAGE_FAULT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_BREAKPOINT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_INSTRUCTION_ACCESS_FAULT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_INSTRUCTION_MISALIGNED, has_s) \
    P(REPORT_VA_IN_STVAL_ON_INSTRUCTION_PAGE_FAULT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_LOAD_ACCESS_FAULT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_LOAD_MISALIGNED, has_s) \
    P(REPORT_VA_IN_STVAL_ON_LOAD_PAGE_FAULT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_STORE_AMO_ACCESS_FAULT, has_s) \
    P(REPORT_VA_IN_STVAL_ON_STORE_AMO_MISALIGNED, has_s) \
    P(REPORT_VA_IN_STVAL_ON_STORE_AMO_PAGE_FAULT, has_s) \
    P(REPORT_VA_IN_VSTVAL_ON_BREAKPOINT, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_INSTRUCTION_ACCESS_FAULT, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_INSTRUCTION_MISALIGNED, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_INSTRUCTION_PAGE_FAULT, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_LOAD_ACCESS_FAULT, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_LOAD_MISALIGNED, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_LOAD_PAGE_FAULT, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_STORE_AMO_ACCESS_FAULT, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_STORE_AMO_MISALIGNED, has_h) \
    P(REPORT_VA_IN_VSTVAL_ON_STORE_AMO_PAGE_FAULT, has_h) \
    P(RESERVED_VSET_X0X0_VILL_SET, vlen != 0) \
    P(RESERVED_VSET_X0X0_VLMAX_CHANGE, vlen != 0) \
    P(RVV_VL_WHEN_AVL_LT_DOUBLE_VLMAX, vlen != 0) \
    P(SATP_MODE_BARE, has_s) \
    P(SCOUNTENABLE_EN, has_s) \
    P(SCTRDEPTH_DEPTH_LEGAL_VALUES, have("Smctr")) \
    P(SEI_INTR_IMPL, (true) && (has_s)) \
    P(SEW_MIN, vlen != 0) \
    P(SSI_INTR_IMPL, (true) && (has_s)) \
    P(SSTATEEN_JVT_TYPE, (have("Zcmt")) && (have("Ssstateen"))) \
    P(STI_INTR_IMPL, (true) && (has_s)) \
    P(STVAL_WIDTH, has_s) \
    P(STVEC_BASE_ALIGNMENT_VECTORED, (has_s)) \
    P(STVEC_MODES, has_s) \
    P(SUPPORT_FRACTIONAL_LMUL_BEYOND_REQUIRED, vlen != 0) \
    P(SV32X4_TRANSLATION, (has_h)) \
    P(SV32_VSMODE_TRANSLATION, (has_h)) \
    P(SV39X4_TRANSLATION, (has_h)) \
    P(SV39_VSMODE_TRANSLATION, (has_h)) \
    P(SV48X4_TRANSLATION, (has_h)) \
    P(SV48_VSMODE_TRANSLATION, (has_h)) \
    P(SV57X4_TRANSLATION, (has_h)) \
    P(SV57_VSMODE_TRANSLATION, (has_h)) \
    P(SXLEN, has_s) \
    P(S_MODE_ENDIANNESS, has_s) \
    P(TIME_CSR_IMPLEMENTED, have("Zicntr")) \
    P(TINST_VALUE_ON_BREAKPOINT, has_h) \
    P(TINST_VALUE_ON_FINAL_INSTRUCTION_GUEST_PAGE_FAULT, has_h) \
    P(TINST_VALUE_ON_FINAL_LOAD_GUEST_PAGE_FAULT, has_h) \
    P(TINST_VALUE_ON_FINAL_STORE_AMO_GUEST_PAGE_FAULT, has_h) \
    P(TINST_VALUE_ON_INSTRUCTION_ADDRESS_MISALIGNED, has_h) \
    P(TINST_VALUE_ON_LOAD_ACCESS_FAULT, has_h) \
    P(TINST_VALUE_ON_LOAD_ADDRESS_MISALIGNED, has_h) \
    P(TINST_VALUE_ON_LOAD_PAGE_FAULT, has_h) \
    P(TINST_VALUE_ON_MCALL, has_h) \
    P(TINST_VALUE_ON_SCALL, has_h) \
    P(TINST_VALUE_ON_STORE_AMO_ACCESS_FAULT, has_h) \
    P(TINST_VALUE_ON_STORE_AMO_ADDRESS_MISALIGNED, has_h) \
    P(TINST_VALUE_ON_STORE_AMO_PAGE_FAULT, has_h) \
    P(TINST_VALUE_ON_UCALL, has_h) \
    P(TINST_VALUE_ON_VIRTUAL_INSTRUCTION, has_h) \
    P(TINST_VALUE_ON_VSCALL, has_h) \
    P(TRAP_ON_EBREAK, true) \
    P(TRAP_ON_ECALL_FROM_M, true) \
    P(TRAP_ON_ECALL_FROM_S, has_s) \
    P(TRAP_ON_ECALL_FROM_U, has_u) \
    P(TRAP_ON_ECALL_FROM_VS, has_h) \
    P(TRAP_ON_ILLEGAL_WLRL, true) \
    P(TRAP_ON_RESERVED_INSTRUCTION, true) \
    P(TRAP_ON_SFENCE_VMA_WHEN_SATP_MODE_IS_READ_ONLY, (has_s) && (!(any_atp) && !(any_atp) && !(any_atp) && !(any_atp))) \
    P(TRAP_ON_UNIMPLEMENTED_CSR, true) \
    P(TRAP_ON_UNIMPLEMENTED_INSTRUCTION, true) \
    P(UXLEN, has_u) \
    P(U_MODE_ENDIANNESS, has_u) \
    P(VECTOR_FF_NO_EXCEPTION_TRIM, vlen != 0) \
    P(VECTOR_FF_SEG_EXCEPTION_PARTIAL_LOAD, vlen != 0) \
    P(VECTOR_FF_UPDATE_PAST_TRIM, vlen != 0) \
    P(VECTOR_LOAD_PAST_TRAP, vlen != 0) \
    P(VECTOR_LOAD_SEG_FF_OVERWRITE_ELEMENTS_AFTER_FAULT, vlen != 0) \
    P(VECTOR_LS_INDEX_MAX_EEW, vlen != 0) \
    P(VECTOR_LS_MISALIGNED_LEGAL, vlen != 0) \
    P(VECTOR_LS_SEG_PARTIAL_ACCESS, vlen != 0) \
    P(VECTOR_LS_WHOLEREG_MISALIGNED_LEGAL, vlen != 0) \
    P(VENDOR_ID_BANK, true) \
    P(VENDOR_ID_OFFSET, true) \
    P(VFREDUSUM_FINAL_NODE_ELEMENT_BEHAVIOR, vlen != 0) \
    P(VFREDUSUM_INACTIVE_NODE_ELEMENT_BEHAVIOR, vlen != 0) \
    P(VFREDUSUM_NAN, vlen != 0) \
    P(VFREDUSUM_NODE_ROUNDING_BEHAVIOR, vlen != 0) \
    P(VILL_SET_ON_RESERVED_VTYPE, vlen != 0) \
    P(VLEN, vlen != 0) \
    P(VMID_WIDTH, has_h) \
    P(VSEI_INTR_IMPL, (true) && (has_h)) \
    P(VSSI_INTR_IMPL, (true) && (has_h)) \
    P(VSSTAGE_MODE_BARE, has_h) \
    P(VSSTATUS_VS_EXISTS, vlen != 0) \
    P(VSTI_INTR_IMPL, (true) && (has_h)) \
    P(VSTVEC_MODES, has_h) \
    P(VSXLEN, has_h) \
    P(VS_MODE_ENDIANNESS, has_h) \
    P(VUXLEN, has_h) \
    P(VU_MODE_ENDIANNESS, has_h) \
    P(ZAWRS_NTO_IS_NOP, have("Zawrs")) \
    /* end */
