#define RVMODEL_ACCESS_FAULT_ADDRESS 0x00000000
#define RVMODEL_PMP_GRAIN 0
#define RVMODEL_NUM_PMPS 16
#define D_SUPPORTED
#define F_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZCA_SUPPORTED
#define ZCD_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED

#define TIME_CSR_IMPLEMENTED 1
