///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    MisalignV_vl1re16_v_cg = new(); MisalignV_vl1re16_v_cg.set_inst_name("obj_MisalignV_vl1re16_v");
    MisalignV_vl1re32_v_cg = new(); MisalignV_vl1re32_v_cg.set_inst_name("obj_MisalignV_vl1re32_v");
    MisalignV_vl1re64_v_cg = new(); MisalignV_vl1re64_v_cg.set_inst_name("obj_MisalignV_vl1re64_v");
    MisalignV_vl1re8_v_cg = new(); MisalignV_vl1re8_v_cg.set_inst_name("obj_MisalignV_vl1re8_v");
    MisalignV_vl2re16_v_cg = new(); MisalignV_vl2re16_v_cg.set_inst_name("obj_MisalignV_vl2re16_v");
    MisalignV_vl2re32_v_cg = new(); MisalignV_vl2re32_v_cg.set_inst_name("obj_MisalignV_vl2re32_v");
    MisalignV_vl2re64_v_cg = new(); MisalignV_vl2re64_v_cg.set_inst_name("obj_MisalignV_vl2re64_v");
    MisalignV_vl2re8_v_cg = new(); MisalignV_vl2re8_v_cg.set_inst_name("obj_MisalignV_vl2re8_v");
    MisalignV_vl4re16_v_cg = new(); MisalignV_vl4re16_v_cg.set_inst_name("obj_MisalignV_vl4re16_v");
    MisalignV_vl4re32_v_cg = new(); MisalignV_vl4re32_v_cg.set_inst_name("obj_MisalignV_vl4re32_v");
    MisalignV_vl4re64_v_cg = new(); MisalignV_vl4re64_v_cg.set_inst_name("obj_MisalignV_vl4re64_v");
    MisalignV_vl4re8_v_cg = new(); MisalignV_vl4re8_v_cg.set_inst_name("obj_MisalignV_vl4re8_v");
    MisalignV_vl8re16_v_cg = new(); MisalignV_vl8re16_v_cg.set_inst_name("obj_MisalignV_vl8re16_v");
    MisalignV_vl8re32_v_cg = new(); MisalignV_vl8re32_v_cg.set_inst_name("obj_MisalignV_vl8re32_v");
    MisalignV_vl8re64_v_cg = new(); MisalignV_vl8re64_v_cg.set_inst_name("obj_MisalignV_vl8re64_v");
    MisalignV_vl8re8_v_cg = new(); MisalignV_vl8re8_v_cg.set_inst_name("obj_MisalignV_vl8re8_v");
    MisalignV_vle16_v_cg = new(); MisalignV_vle16_v_cg.set_inst_name("obj_MisalignV_vle16_v");
    MisalignV_vle16ff_v_cg = new(); MisalignV_vle16ff_v_cg.set_inst_name("obj_MisalignV_vle16ff_v");
    MisalignV_vle32_v_cg = new(); MisalignV_vle32_v_cg.set_inst_name("obj_MisalignV_vle32_v");
    MisalignV_vle32ff_v_cg = new(); MisalignV_vle32ff_v_cg.set_inst_name("obj_MisalignV_vle32ff_v");
    MisalignV_vle64_v_cg = new(); MisalignV_vle64_v_cg.set_inst_name("obj_MisalignV_vle64_v");
    MisalignV_vle64ff_v_cg = new(); MisalignV_vle64ff_v_cg.set_inst_name("obj_MisalignV_vle64ff_v");
    MisalignV_vle8_v_cg = new(); MisalignV_vle8_v_cg.set_inst_name("obj_MisalignV_vle8_v");
    MisalignV_vle8ff_v_cg = new(); MisalignV_vle8ff_v_cg.set_inst_name("obj_MisalignV_vle8ff_v");
    MisalignV_vlm_v_cg = new(); MisalignV_vlm_v_cg.set_inst_name("obj_MisalignV_vlm_v");
    MisalignV_vloxei16_v_cg = new(); MisalignV_vloxei16_v_cg.set_inst_name("obj_MisalignV_vloxei16_v");
    MisalignV_vloxei32_v_cg = new(); MisalignV_vloxei32_v_cg.set_inst_name("obj_MisalignV_vloxei32_v");
`ifdef XLEN64
    MisalignV_vloxei64_v_cg = new(); MisalignV_vloxei64_v_cg.set_inst_name("obj_MisalignV_vloxei64_v");
`endif
    MisalignV_vloxei8_v_cg = new(); MisalignV_vloxei8_v_cg.set_inst_name("obj_MisalignV_vloxei8_v");
    MisalignV_vloxseg2ei16_v_cg = new(); MisalignV_vloxseg2ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg2ei16_v");
    MisalignV_vloxseg2ei32_v_cg = new(); MisalignV_vloxseg2ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg2ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg2ei64_v_cg = new(); MisalignV_vloxseg2ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg2ei64_v");
`endif
    MisalignV_vloxseg2ei8_v_cg = new(); MisalignV_vloxseg2ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg2ei8_v");
    MisalignV_vloxseg3ei16_v_cg = new(); MisalignV_vloxseg3ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg3ei16_v");
    MisalignV_vloxseg3ei32_v_cg = new(); MisalignV_vloxseg3ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg3ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg3ei64_v_cg = new(); MisalignV_vloxseg3ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg3ei64_v");
`endif
    MisalignV_vloxseg3ei8_v_cg = new(); MisalignV_vloxseg3ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg3ei8_v");
    MisalignV_vloxseg4ei16_v_cg = new(); MisalignV_vloxseg4ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg4ei16_v");
    MisalignV_vloxseg4ei32_v_cg = new(); MisalignV_vloxseg4ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg4ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg4ei64_v_cg = new(); MisalignV_vloxseg4ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg4ei64_v");
`endif
    MisalignV_vloxseg4ei8_v_cg = new(); MisalignV_vloxseg4ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg4ei8_v");
    MisalignV_vloxseg5ei16_v_cg = new(); MisalignV_vloxseg5ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg5ei16_v");
    MisalignV_vloxseg5ei32_v_cg = new(); MisalignV_vloxseg5ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg5ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg5ei64_v_cg = new(); MisalignV_vloxseg5ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg5ei64_v");
`endif
    MisalignV_vloxseg5ei8_v_cg = new(); MisalignV_vloxseg5ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg5ei8_v");
    MisalignV_vloxseg6ei16_v_cg = new(); MisalignV_vloxseg6ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg6ei16_v");
    MisalignV_vloxseg6ei32_v_cg = new(); MisalignV_vloxseg6ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg6ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg6ei64_v_cg = new(); MisalignV_vloxseg6ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg6ei64_v");
`endif
    MisalignV_vloxseg6ei8_v_cg = new(); MisalignV_vloxseg6ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg6ei8_v");
    MisalignV_vloxseg7ei16_v_cg = new(); MisalignV_vloxseg7ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg7ei16_v");
    MisalignV_vloxseg7ei32_v_cg = new(); MisalignV_vloxseg7ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg7ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg7ei64_v_cg = new(); MisalignV_vloxseg7ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg7ei64_v");
`endif
    MisalignV_vloxseg7ei8_v_cg = new(); MisalignV_vloxseg7ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg7ei8_v");
    MisalignV_vloxseg8ei16_v_cg = new(); MisalignV_vloxseg8ei16_v_cg.set_inst_name("obj_MisalignV_vloxseg8ei16_v");
    MisalignV_vloxseg8ei32_v_cg = new(); MisalignV_vloxseg8ei32_v_cg.set_inst_name("obj_MisalignV_vloxseg8ei32_v");
`ifdef XLEN64
    MisalignV_vloxseg8ei64_v_cg = new(); MisalignV_vloxseg8ei64_v_cg.set_inst_name("obj_MisalignV_vloxseg8ei64_v");
`endif
    MisalignV_vloxseg8ei8_v_cg = new(); MisalignV_vloxseg8ei8_v_cg.set_inst_name("obj_MisalignV_vloxseg8ei8_v");
    MisalignV_vlse16_v_cg = new(); MisalignV_vlse16_v_cg.set_inst_name("obj_MisalignV_vlse16_v");
    MisalignV_vlse32_v_cg = new(); MisalignV_vlse32_v_cg.set_inst_name("obj_MisalignV_vlse32_v");
    MisalignV_vlse64_v_cg = new(); MisalignV_vlse64_v_cg.set_inst_name("obj_MisalignV_vlse64_v");
    MisalignV_vlse8_v_cg = new(); MisalignV_vlse8_v_cg.set_inst_name("obj_MisalignV_vlse8_v");
    MisalignV_vlseg2e16_v_cg = new(); MisalignV_vlseg2e16_v_cg.set_inst_name("obj_MisalignV_vlseg2e16_v");
    MisalignV_vlseg2e16ff_v_cg = new(); MisalignV_vlseg2e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg2e16ff_v");
    MisalignV_vlseg2e32_v_cg = new(); MisalignV_vlseg2e32_v_cg.set_inst_name("obj_MisalignV_vlseg2e32_v");
    MisalignV_vlseg2e32ff_v_cg = new(); MisalignV_vlseg2e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg2e32ff_v");
    MisalignV_vlseg2e64_v_cg = new(); MisalignV_vlseg2e64_v_cg.set_inst_name("obj_MisalignV_vlseg2e64_v");
    MisalignV_vlseg2e64ff_v_cg = new(); MisalignV_vlseg2e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg2e64ff_v");
    MisalignV_vlseg2e8_v_cg = new(); MisalignV_vlseg2e8_v_cg.set_inst_name("obj_MisalignV_vlseg2e8_v");
    MisalignV_vlseg2e8ff_v_cg = new(); MisalignV_vlseg2e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg2e8ff_v");
    MisalignV_vlseg3e16_v_cg = new(); MisalignV_vlseg3e16_v_cg.set_inst_name("obj_MisalignV_vlseg3e16_v");
    MisalignV_vlseg3e16ff_v_cg = new(); MisalignV_vlseg3e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg3e16ff_v");
    MisalignV_vlseg3e32_v_cg = new(); MisalignV_vlseg3e32_v_cg.set_inst_name("obj_MisalignV_vlseg3e32_v");
    MisalignV_vlseg3e32ff_v_cg = new(); MisalignV_vlseg3e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg3e32ff_v");
    MisalignV_vlseg3e64_v_cg = new(); MisalignV_vlseg3e64_v_cg.set_inst_name("obj_MisalignV_vlseg3e64_v");
    MisalignV_vlseg3e64ff_v_cg = new(); MisalignV_vlseg3e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg3e64ff_v");
    MisalignV_vlseg3e8_v_cg = new(); MisalignV_vlseg3e8_v_cg.set_inst_name("obj_MisalignV_vlseg3e8_v");
    MisalignV_vlseg3e8ff_v_cg = new(); MisalignV_vlseg3e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg3e8ff_v");
    MisalignV_vlseg4e16_v_cg = new(); MisalignV_vlseg4e16_v_cg.set_inst_name("obj_MisalignV_vlseg4e16_v");
    MisalignV_vlseg4e16ff_v_cg = new(); MisalignV_vlseg4e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg4e16ff_v");
    MisalignV_vlseg4e32_v_cg = new(); MisalignV_vlseg4e32_v_cg.set_inst_name("obj_MisalignV_vlseg4e32_v");
    MisalignV_vlseg4e32ff_v_cg = new(); MisalignV_vlseg4e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg4e32ff_v");
    MisalignV_vlseg4e64_v_cg = new(); MisalignV_vlseg4e64_v_cg.set_inst_name("obj_MisalignV_vlseg4e64_v");
    MisalignV_vlseg4e64ff_v_cg = new(); MisalignV_vlseg4e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg4e64ff_v");
    MisalignV_vlseg4e8_v_cg = new(); MisalignV_vlseg4e8_v_cg.set_inst_name("obj_MisalignV_vlseg4e8_v");
    MisalignV_vlseg4e8ff_v_cg = new(); MisalignV_vlseg4e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg4e8ff_v");
    MisalignV_vlseg5e16_v_cg = new(); MisalignV_vlseg5e16_v_cg.set_inst_name("obj_MisalignV_vlseg5e16_v");
    MisalignV_vlseg5e16ff_v_cg = new(); MisalignV_vlseg5e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg5e16ff_v");
    MisalignV_vlseg5e32_v_cg = new(); MisalignV_vlseg5e32_v_cg.set_inst_name("obj_MisalignV_vlseg5e32_v");
    MisalignV_vlseg5e32ff_v_cg = new(); MisalignV_vlseg5e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg5e32ff_v");
    MisalignV_vlseg5e64_v_cg = new(); MisalignV_vlseg5e64_v_cg.set_inst_name("obj_MisalignV_vlseg5e64_v");
    MisalignV_vlseg5e64ff_v_cg = new(); MisalignV_vlseg5e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg5e64ff_v");
    MisalignV_vlseg5e8_v_cg = new(); MisalignV_vlseg5e8_v_cg.set_inst_name("obj_MisalignV_vlseg5e8_v");
    MisalignV_vlseg5e8ff_v_cg = new(); MisalignV_vlseg5e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg5e8ff_v");
    MisalignV_vlseg6e16_v_cg = new(); MisalignV_vlseg6e16_v_cg.set_inst_name("obj_MisalignV_vlseg6e16_v");
    MisalignV_vlseg6e16ff_v_cg = new(); MisalignV_vlseg6e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg6e16ff_v");
    MisalignV_vlseg6e32_v_cg = new(); MisalignV_vlseg6e32_v_cg.set_inst_name("obj_MisalignV_vlseg6e32_v");
    MisalignV_vlseg6e32ff_v_cg = new(); MisalignV_vlseg6e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg6e32ff_v");
    MisalignV_vlseg6e64_v_cg = new(); MisalignV_vlseg6e64_v_cg.set_inst_name("obj_MisalignV_vlseg6e64_v");
    MisalignV_vlseg6e64ff_v_cg = new(); MisalignV_vlseg6e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg6e64ff_v");
    MisalignV_vlseg6e8_v_cg = new(); MisalignV_vlseg6e8_v_cg.set_inst_name("obj_MisalignV_vlseg6e8_v");
    MisalignV_vlseg6e8ff_v_cg = new(); MisalignV_vlseg6e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg6e8ff_v");
    MisalignV_vlseg7e16_v_cg = new(); MisalignV_vlseg7e16_v_cg.set_inst_name("obj_MisalignV_vlseg7e16_v");
    MisalignV_vlseg7e16ff_v_cg = new(); MisalignV_vlseg7e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg7e16ff_v");
    MisalignV_vlseg7e32_v_cg = new(); MisalignV_vlseg7e32_v_cg.set_inst_name("obj_MisalignV_vlseg7e32_v");
    MisalignV_vlseg7e32ff_v_cg = new(); MisalignV_vlseg7e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg7e32ff_v");
    MisalignV_vlseg7e64_v_cg = new(); MisalignV_vlseg7e64_v_cg.set_inst_name("obj_MisalignV_vlseg7e64_v");
    MisalignV_vlseg7e64ff_v_cg = new(); MisalignV_vlseg7e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg7e64ff_v");
    MisalignV_vlseg7e8_v_cg = new(); MisalignV_vlseg7e8_v_cg.set_inst_name("obj_MisalignV_vlseg7e8_v");
    MisalignV_vlseg7e8ff_v_cg = new(); MisalignV_vlseg7e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg7e8ff_v");
    MisalignV_vlseg8e16_v_cg = new(); MisalignV_vlseg8e16_v_cg.set_inst_name("obj_MisalignV_vlseg8e16_v");
    MisalignV_vlseg8e16ff_v_cg = new(); MisalignV_vlseg8e16ff_v_cg.set_inst_name("obj_MisalignV_vlseg8e16ff_v");
    MisalignV_vlseg8e32_v_cg = new(); MisalignV_vlseg8e32_v_cg.set_inst_name("obj_MisalignV_vlseg8e32_v");
    MisalignV_vlseg8e32ff_v_cg = new(); MisalignV_vlseg8e32ff_v_cg.set_inst_name("obj_MisalignV_vlseg8e32ff_v");
    MisalignV_vlseg8e64_v_cg = new(); MisalignV_vlseg8e64_v_cg.set_inst_name("obj_MisalignV_vlseg8e64_v");
    MisalignV_vlseg8e64ff_v_cg = new(); MisalignV_vlseg8e64ff_v_cg.set_inst_name("obj_MisalignV_vlseg8e64ff_v");
    MisalignV_vlseg8e8_v_cg = new(); MisalignV_vlseg8e8_v_cg.set_inst_name("obj_MisalignV_vlseg8e8_v");
    MisalignV_vlseg8e8ff_v_cg = new(); MisalignV_vlseg8e8ff_v_cg.set_inst_name("obj_MisalignV_vlseg8e8ff_v");
    MisalignV_vlsseg2e16_v_cg = new(); MisalignV_vlsseg2e16_v_cg.set_inst_name("obj_MisalignV_vlsseg2e16_v");
    MisalignV_vlsseg2e32_v_cg = new(); MisalignV_vlsseg2e32_v_cg.set_inst_name("obj_MisalignV_vlsseg2e32_v");
    MisalignV_vlsseg2e64_v_cg = new(); MisalignV_vlsseg2e64_v_cg.set_inst_name("obj_MisalignV_vlsseg2e64_v");
    MisalignV_vlsseg2e8_v_cg = new(); MisalignV_vlsseg2e8_v_cg.set_inst_name("obj_MisalignV_vlsseg2e8_v");
    MisalignV_vlsseg3e16_v_cg = new(); MisalignV_vlsseg3e16_v_cg.set_inst_name("obj_MisalignV_vlsseg3e16_v");
    MisalignV_vlsseg3e32_v_cg = new(); MisalignV_vlsseg3e32_v_cg.set_inst_name("obj_MisalignV_vlsseg3e32_v");
    MisalignV_vlsseg3e64_v_cg = new(); MisalignV_vlsseg3e64_v_cg.set_inst_name("obj_MisalignV_vlsseg3e64_v");
    MisalignV_vlsseg3e8_v_cg = new(); MisalignV_vlsseg3e8_v_cg.set_inst_name("obj_MisalignV_vlsseg3e8_v");
    MisalignV_vlsseg4e16_v_cg = new(); MisalignV_vlsseg4e16_v_cg.set_inst_name("obj_MisalignV_vlsseg4e16_v");
    MisalignV_vlsseg4e32_v_cg = new(); MisalignV_vlsseg4e32_v_cg.set_inst_name("obj_MisalignV_vlsseg4e32_v");
    MisalignV_vlsseg4e64_v_cg = new(); MisalignV_vlsseg4e64_v_cg.set_inst_name("obj_MisalignV_vlsseg4e64_v");
    MisalignV_vlsseg4e8_v_cg = new(); MisalignV_vlsseg4e8_v_cg.set_inst_name("obj_MisalignV_vlsseg4e8_v");
    MisalignV_vlsseg5e16_v_cg = new(); MisalignV_vlsseg5e16_v_cg.set_inst_name("obj_MisalignV_vlsseg5e16_v");
    MisalignV_vlsseg5e32_v_cg = new(); MisalignV_vlsseg5e32_v_cg.set_inst_name("obj_MisalignV_vlsseg5e32_v");
    MisalignV_vlsseg5e64_v_cg = new(); MisalignV_vlsseg5e64_v_cg.set_inst_name("obj_MisalignV_vlsseg5e64_v");
    MisalignV_vlsseg5e8_v_cg = new(); MisalignV_vlsseg5e8_v_cg.set_inst_name("obj_MisalignV_vlsseg5e8_v");
    MisalignV_vlsseg6e16_v_cg = new(); MisalignV_vlsseg6e16_v_cg.set_inst_name("obj_MisalignV_vlsseg6e16_v");
    MisalignV_vlsseg6e32_v_cg = new(); MisalignV_vlsseg6e32_v_cg.set_inst_name("obj_MisalignV_vlsseg6e32_v");
    MisalignV_vlsseg6e64_v_cg = new(); MisalignV_vlsseg6e64_v_cg.set_inst_name("obj_MisalignV_vlsseg6e64_v");
    MisalignV_vlsseg6e8_v_cg = new(); MisalignV_vlsseg6e8_v_cg.set_inst_name("obj_MisalignV_vlsseg6e8_v");
    MisalignV_vlsseg7e16_v_cg = new(); MisalignV_vlsseg7e16_v_cg.set_inst_name("obj_MisalignV_vlsseg7e16_v");
    MisalignV_vlsseg7e32_v_cg = new(); MisalignV_vlsseg7e32_v_cg.set_inst_name("obj_MisalignV_vlsseg7e32_v");
    MisalignV_vlsseg7e64_v_cg = new(); MisalignV_vlsseg7e64_v_cg.set_inst_name("obj_MisalignV_vlsseg7e64_v");
    MisalignV_vlsseg7e8_v_cg = new(); MisalignV_vlsseg7e8_v_cg.set_inst_name("obj_MisalignV_vlsseg7e8_v");
    MisalignV_vlsseg8e16_v_cg = new(); MisalignV_vlsseg8e16_v_cg.set_inst_name("obj_MisalignV_vlsseg8e16_v");
    MisalignV_vlsseg8e32_v_cg = new(); MisalignV_vlsseg8e32_v_cg.set_inst_name("obj_MisalignV_vlsseg8e32_v");
    MisalignV_vlsseg8e64_v_cg = new(); MisalignV_vlsseg8e64_v_cg.set_inst_name("obj_MisalignV_vlsseg8e64_v");
    MisalignV_vlsseg8e8_v_cg = new(); MisalignV_vlsseg8e8_v_cg.set_inst_name("obj_MisalignV_vlsseg8e8_v");
    MisalignV_vluxei16_v_cg = new(); MisalignV_vluxei16_v_cg.set_inst_name("obj_MisalignV_vluxei16_v");
    MisalignV_vluxei32_v_cg = new(); MisalignV_vluxei32_v_cg.set_inst_name("obj_MisalignV_vluxei32_v");
`ifdef XLEN64
    MisalignV_vluxei64_v_cg = new(); MisalignV_vluxei64_v_cg.set_inst_name("obj_MisalignV_vluxei64_v");
`endif
    MisalignV_vluxei8_v_cg = new(); MisalignV_vluxei8_v_cg.set_inst_name("obj_MisalignV_vluxei8_v");
    MisalignV_vluxseg2ei16_v_cg = new(); MisalignV_vluxseg2ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg2ei16_v");
    MisalignV_vluxseg2ei32_v_cg = new(); MisalignV_vluxseg2ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg2ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg2ei64_v_cg = new(); MisalignV_vluxseg2ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg2ei64_v");
`endif
    MisalignV_vluxseg2ei8_v_cg = new(); MisalignV_vluxseg2ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg2ei8_v");
    MisalignV_vluxseg3ei16_v_cg = new(); MisalignV_vluxseg3ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg3ei16_v");
    MisalignV_vluxseg3ei32_v_cg = new(); MisalignV_vluxseg3ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg3ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg3ei64_v_cg = new(); MisalignV_vluxseg3ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg3ei64_v");
`endif
    MisalignV_vluxseg3ei8_v_cg = new(); MisalignV_vluxseg3ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg3ei8_v");
    MisalignV_vluxseg4ei16_v_cg = new(); MisalignV_vluxseg4ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg4ei16_v");
    MisalignV_vluxseg4ei32_v_cg = new(); MisalignV_vluxseg4ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg4ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg4ei64_v_cg = new(); MisalignV_vluxseg4ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg4ei64_v");
`endif
    MisalignV_vluxseg4ei8_v_cg = new(); MisalignV_vluxseg4ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg4ei8_v");
    MisalignV_vluxseg5ei16_v_cg = new(); MisalignV_vluxseg5ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg5ei16_v");
    MisalignV_vluxseg5ei32_v_cg = new(); MisalignV_vluxseg5ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg5ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg5ei64_v_cg = new(); MisalignV_vluxseg5ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg5ei64_v");
`endif
    MisalignV_vluxseg5ei8_v_cg = new(); MisalignV_vluxseg5ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg5ei8_v");
    MisalignV_vluxseg6ei16_v_cg = new(); MisalignV_vluxseg6ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg6ei16_v");
    MisalignV_vluxseg6ei32_v_cg = new(); MisalignV_vluxseg6ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg6ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg6ei64_v_cg = new(); MisalignV_vluxseg6ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg6ei64_v");
`endif
    MisalignV_vluxseg6ei8_v_cg = new(); MisalignV_vluxseg6ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg6ei8_v");
    MisalignV_vluxseg7ei16_v_cg = new(); MisalignV_vluxseg7ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg7ei16_v");
    MisalignV_vluxseg7ei32_v_cg = new(); MisalignV_vluxseg7ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg7ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg7ei64_v_cg = new(); MisalignV_vluxseg7ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg7ei64_v");
`endif
    MisalignV_vluxseg7ei8_v_cg = new(); MisalignV_vluxseg7ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg7ei8_v");
    MisalignV_vluxseg8ei16_v_cg = new(); MisalignV_vluxseg8ei16_v_cg.set_inst_name("obj_MisalignV_vluxseg8ei16_v");
    MisalignV_vluxseg8ei32_v_cg = new(); MisalignV_vluxseg8ei32_v_cg.set_inst_name("obj_MisalignV_vluxseg8ei32_v");
`ifdef XLEN64
    MisalignV_vluxseg8ei64_v_cg = new(); MisalignV_vluxseg8ei64_v_cg.set_inst_name("obj_MisalignV_vluxseg8ei64_v");
`endif
    MisalignV_vluxseg8ei8_v_cg = new(); MisalignV_vluxseg8ei8_v_cg.set_inst_name("obj_MisalignV_vluxseg8ei8_v");
    MisalignV_vs1r_v_cg = new(); MisalignV_vs1r_v_cg.set_inst_name("obj_MisalignV_vs1r_v");
    MisalignV_vs2r_v_cg = new(); MisalignV_vs2r_v_cg.set_inst_name("obj_MisalignV_vs2r_v");
    MisalignV_vs4r_v_cg = new(); MisalignV_vs4r_v_cg.set_inst_name("obj_MisalignV_vs4r_v");
    MisalignV_vs8r_v_cg = new(); MisalignV_vs8r_v_cg.set_inst_name("obj_MisalignV_vs8r_v");
    MisalignV_vse16_v_cg = new(); MisalignV_vse16_v_cg.set_inst_name("obj_MisalignV_vse16_v");
    MisalignV_vse32_v_cg = new(); MisalignV_vse32_v_cg.set_inst_name("obj_MisalignV_vse32_v");
    MisalignV_vse64_v_cg = new(); MisalignV_vse64_v_cg.set_inst_name("obj_MisalignV_vse64_v");
    MisalignV_vse8_v_cg = new(); MisalignV_vse8_v_cg.set_inst_name("obj_MisalignV_vse8_v");
    MisalignV_vsm_v_cg = new(); MisalignV_vsm_v_cg.set_inst_name("obj_MisalignV_vsm_v");
    MisalignV_vsoxei16_v_cg = new(); MisalignV_vsoxei16_v_cg.set_inst_name("obj_MisalignV_vsoxei16_v");
    MisalignV_vsoxei32_v_cg = new(); MisalignV_vsoxei32_v_cg.set_inst_name("obj_MisalignV_vsoxei32_v");
`ifdef XLEN64
    MisalignV_vsoxei64_v_cg = new(); MisalignV_vsoxei64_v_cg.set_inst_name("obj_MisalignV_vsoxei64_v");
`endif
    MisalignV_vsoxei8_v_cg = new(); MisalignV_vsoxei8_v_cg.set_inst_name("obj_MisalignV_vsoxei8_v");
    MisalignV_vsoxseg2ei16_v_cg = new(); MisalignV_vsoxseg2ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg2ei16_v");
    MisalignV_vsoxseg2ei32_v_cg = new(); MisalignV_vsoxseg2ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg2ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg2ei64_v_cg = new(); MisalignV_vsoxseg2ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg2ei64_v");
`endif
    MisalignV_vsoxseg2ei8_v_cg = new(); MisalignV_vsoxseg2ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg2ei8_v");
    MisalignV_vsoxseg3ei16_v_cg = new(); MisalignV_vsoxseg3ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg3ei16_v");
    MisalignV_vsoxseg3ei32_v_cg = new(); MisalignV_vsoxseg3ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg3ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg3ei64_v_cg = new(); MisalignV_vsoxseg3ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg3ei64_v");
`endif
    MisalignV_vsoxseg3ei8_v_cg = new(); MisalignV_vsoxseg3ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg3ei8_v");
    MisalignV_vsoxseg4ei16_v_cg = new(); MisalignV_vsoxseg4ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg4ei16_v");
    MisalignV_vsoxseg4ei32_v_cg = new(); MisalignV_vsoxseg4ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg4ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg4ei64_v_cg = new(); MisalignV_vsoxseg4ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg4ei64_v");
`endif
    MisalignV_vsoxseg4ei8_v_cg = new(); MisalignV_vsoxseg4ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg4ei8_v");
    MisalignV_vsoxseg5ei16_v_cg = new(); MisalignV_vsoxseg5ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg5ei16_v");
    MisalignV_vsoxseg5ei32_v_cg = new(); MisalignV_vsoxseg5ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg5ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg5ei64_v_cg = new(); MisalignV_vsoxseg5ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg5ei64_v");
`endif
    MisalignV_vsoxseg5ei8_v_cg = new(); MisalignV_vsoxseg5ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg5ei8_v");
    MisalignV_vsoxseg6ei16_v_cg = new(); MisalignV_vsoxseg6ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg6ei16_v");
    MisalignV_vsoxseg6ei32_v_cg = new(); MisalignV_vsoxseg6ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg6ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg6ei64_v_cg = new(); MisalignV_vsoxseg6ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg6ei64_v");
`endif
    MisalignV_vsoxseg6ei8_v_cg = new(); MisalignV_vsoxseg6ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg6ei8_v");
    MisalignV_vsoxseg7ei16_v_cg = new(); MisalignV_vsoxseg7ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg7ei16_v");
    MisalignV_vsoxseg7ei32_v_cg = new(); MisalignV_vsoxseg7ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg7ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg7ei64_v_cg = new(); MisalignV_vsoxseg7ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg7ei64_v");
`endif
    MisalignV_vsoxseg7ei8_v_cg = new(); MisalignV_vsoxseg7ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg7ei8_v");
    MisalignV_vsoxseg8ei16_v_cg = new(); MisalignV_vsoxseg8ei16_v_cg.set_inst_name("obj_MisalignV_vsoxseg8ei16_v");
    MisalignV_vsoxseg8ei32_v_cg = new(); MisalignV_vsoxseg8ei32_v_cg.set_inst_name("obj_MisalignV_vsoxseg8ei32_v");
`ifdef XLEN64
    MisalignV_vsoxseg8ei64_v_cg = new(); MisalignV_vsoxseg8ei64_v_cg.set_inst_name("obj_MisalignV_vsoxseg8ei64_v");
`endif
    MisalignV_vsoxseg8ei8_v_cg = new(); MisalignV_vsoxseg8ei8_v_cg.set_inst_name("obj_MisalignV_vsoxseg8ei8_v");
    MisalignV_vsse16_v_cg = new(); MisalignV_vsse16_v_cg.set_inst_name("obj_MisalignV_vsse16_v");
    MisalignV_vsse32_v_cg = new(); MisalignV_vsse32_v_cg.set_inst_name("obj_MisalignV_vsse32_v");
    MisalignV_vsse64_v_cg = new(); MisalignV_vsse64_v_cg.set_inst_name("obj_MisalignV_vsse64_v");
    MisalignV_vsse8_v_cg = new(); MisalignV_vsse8_v_cg.set_inst_name("obj_MisalignV_vsse8_v");
    MisalignV_vsseg2e16_v_cg = new(); MisalignV_vsseg2e16_v_cg.set_inst_name("obj_MisalignV_vsseg2e16_v");
    MisalignV_vsseg2e32_v_cg = new(); MisalignV_vsseg2e32_v_cg.set_inst_name("obj_MisalignV_vsseg2e32_v");
    MisalignV_vsseg2e64_v_cg = new(); MisalignV_vsseg2e64_v_cg.set_inst_name("obj_MisalignV_vsseg2e64_v");
    MisalignV_vsseg2e8_v_cg = new(); MisalignV_vsseg2e8_v_cg.set_inst_name("obj_MisalignV_vsseg2e8_v");
    MisalignV_vsseg3e16_v_cg = new(); MisalignV_vsseg3e16_v_cg.set_inst_name("obj_MisalignV_vsseg3e16_v");
    MisalignV_vsseg3e32_v_cg = new(); MisalignV_vsseg3e32_v_cg.set_inst_name("obj_MisalignV_vsseg3e32_v");
    MisalignV_vsseg3e64_v_cg = new(); MisalignV_vsseg3e64_v_cg.set_inst_name("obj_MisalignV_vsseg3e64_v");
    MisalignV_vsseg3e8_v_cg = new(); MisalignV_vsseg3e8_v_cg.set_inst_name("obj_MisalignV_vsseg3e8_v");
    MisalignV_vsseg4e16_v_cg = new(); MisalignV_vsseg4e16_v_cg.set_inst_name("obj_MisalignV_vsseg4e16_v");
    MisalignV_vsseg4e32_v_cg = new(); MisalignV_vsseg4e32_v_cg.set_inst_name("obj_MisalignV_vsseg4e32_v");
    MisalignV_vsseg4e64_v_cg = new(); MisalignV_vsseg4e64_v_cg.set_inst_name("obj_MisalignV_vsseg4e64_v");
    MisalignV_vsseg4e8_v_cg = new(); MisalignV_vsseg4e8_v_cg.set_inst_name("obj_MisalignV_vsseg4e8_v");
    MisalignV_vsseg5e16_v_cg = new(); MisalignV_vsseg5e16_v_cg.set_inst_name("obj_MisalignV_vsseg5e16_v");
    MisalignV_vsseg5e32_v_cg = new(); MisalignV_vsseg5e32_v_cg.set_inst_name("obj_MisalignV_vsseg5e32_v");
    MisalignV_vsseg5e64_v_cg = new(); MisalignV_vsseg5e64_v_cg.set_inst_name("obj_MisalignV_vsseg5e64_v");
    MisalignV_vsseg5e8_v_cg = new(); MisalignV_vsseg5e8_v_cg.set_inst_name("obj_MisalignV_vsseg5e8_v");
    MisalignV_vsseg6e16_v_cg = new(); MisalignV_vsseg6e16_v_cg.set_inst_name("obj_MisalignV_vsseg6e16_v");
    MisalignV_vsseg6e32_v_cg = new(); MisalignV_vsseg6e32_v_cg.set_inst_name("obj_MisalignV_vsseg6e32_v");
    MisalignV_vsseg6e64_v_cg = new(); MisalignV_vsseg6e64_v_cg.set_inst_name("obj_MisalignV_vsseg6e64_v");
    MisalignV_vsseg6e8_v_cg = new(); MisalignV_vsseg6e8_v_cg.set_inst_name("obj_MisalignV_vsseg6e8_v");
    MisalignV_vsseg7e16_v_cg = new(); MisalignV_vsseg7e16_v_cg.set_inst_name("obj_MisalignV_vsseg7e16_v");
    MisalignV_vsseg7e32_v_cg = new(); MisalignV_vsseg7e32_v_cg.set_inst_name("obj_MisalignV_vsseg7e32_v");
    MisalignV_vsseg7e64_v_cg = new(); MisalignV_vsseg7e64_v_cg.set_inst_name("obj_MisalignV_vsseg7e64_v");
    MisalignV_vsseg7e8_v_cg = new(); MisalignV_vsseg7e8_v_cg.set_inst_name("obj_MisalignV_vsseg7e8_v");
    MisalignV_vsseg8e16_v_cg = new(); MisalignV_vsseg8e16_v_cg.set_inst_name("obj_MisalignV_vsseg8e16_v");
    MisalignV_vsseg8e32_v_cg = new(); MisalignV_vsseg8e32_v_cg.set_inst_name("obj_MisalignV_vsseg8e32_v");
    MisalignV_vsseg8e64_v_cg = new(); MisalignV_vsseg8e64_v_cg.set_inst_name("obj_MisalignV_vsseg8e64_v");
    MisalignV_vsseg8e8_v_cg = new(); MisalignV_vsseg8e8_v_cg.set_inst_name("obj_MisalignV_vsseg8e8_v");
    MisalignV_vssseg2e16_v_cg = new(); MisalignV_vssseg2e16_v_cg.set_inst_name("obj_MisalignV_vssseg2e16_v");
    MisalignV_vssseg2e32_v_cg = new(); MisalignV_vssseg2e32_v_cg.set_inst_name("obj_MisalignV_vssseg2e32_v");
    MisalignV_vssseg2e64_v_cg = new(); MisalignV_vssseg2e64_v_cg.set_inst_name("obj_MisalignV_vssseg2e64_v");
    MisalignV_vssseg2e8_v_cg = new(); MisalignV_vssseg2e8_v_cg.set_inst_name("obj_MisalignV_vssseg2e8_v");
    MisalignV_vssseg3e16_v_cg = new(); MisalignV_vssseg3e16_v_cg.set_inst_name("obj_MisalignV_vssseg3e16_v");
    MisalignV_vssseg3e32_v_cg = new(); MisalignV_vssseg3e32_v_cg.set_inst_name("obj_MisalignV_vssseg3e32_v");
    MisalignV_vssseg3e64_v_cg = new(); MisalignV_vssseg3e64_v_cg.set_inst_name("obj_MisalignV_vssseg3e64_v");
    MisalignV_vssseg3e8_v_cg = new(); MisalignV_vssseg3e8_v_cg.set_inst_name("obj_MisalignV_vssseg3e8_v");
    MisalignV_vssseg4e16_v_cg = new(); MisalignV_vssseg4e16_v_cg.set_inst_name("obj_MisalignV_vssseg4e16_v");
    MisalignV_vssseg4e32_v_cg = new(); MisalignV_vssseg4e32_v_cg.set_inst_name("obj_MisalignV_vssseg4e32_v");
    MisalignV_vssseg4e64_v_cg = new(); MisalignV_vssseg4e64_v_cg.set_inst_name("obj_MisalignV_vssseg4e64_v");
    MisalignV_vssseg4e8_v_cg = new(); MisalignV_vssseg4e8_v_cg.set_inst_name("obj_MisalignV_vssseg4e8_v");
    MisalignV_vssseg5e16_v_cg = new(); MisalignV_vssseg5e16_v_cg.set_inst_name("obj_MisalignV_vssseg5e16_v");
    MisalignV_vssseg5e32_v_cg = new(); MisalignV_vssseg5e32_v_cg.set_inst_name("obj_MisalignV_vssseg5e32_v");
    MisalignV_vssseg5e64_v_cg = new(); MisalignV_vssseg5e64_v_cg.set_inst_name("obj_MisalignV_vssseg5e64_v");
    MisalignV_vssseg5e8_v_cg = new(); MisalignV_vssseg5e8_v_cg.set_inst_name("obj_MisalignV_vssseg5e8_v");
    MisalignV_vssseg6e16_v_cg = new(); MisalignV_vssseg6e16_v_cg.set_inst_name("obj_MisalignV_vssseg6e16_v");
    MisalignV_vssseg6e32_v_cg = new(); MisalignV_vssseg6e32_v_cg.set_inst_name("obj_MisalignV_vssseg6e32_v");
    MisalignV_vssseg6e64_v_cg = new(); MisalignV_vssseg6e64_v_cg.set_inst_name("obj_MisalignV_vssseg6e64_v");
    MisalignV_vssseg6e8_v_cg = new(); MisalignV_vssseg6e8_v_cg.set_inst_name("obj_MisalignV_vssseg6e8_v");
    MisalignV_vssseg7e16_v_cg = new(); MisalignV_vssseg7e16_v_cg.set_inst_name("obj_MisalignV_vssseg7e16_v");
    MisalignV_vssseg7e32_v_cg = new(); MisalignV_vssseg7e32_v_cg.set_inst_name("obj_MisalignV_vssseg7e32_v");
    MisalignV_vssseg7e64_v_cg = new(); MisalignV_vssseg7e64_v_cg.set_inst_name("obj_MisalignV_vssseg7e64_v");
    MisalignV_vssseg7e8_v_cg = new(); MisalignV_vssseg7e8_v_cg.set_inst_name("obj_MisalignV_vssseg7e8_v");
    MisalignV_vssseg8e16_v_cg = new(); MisalignV_vssseg8e16_v_cg.set_inst_name("obj_MisalignV_vssseg8e16_v");
    MisalignV_vssseg8e32_v_cg = new(); MisalignV_vssseg8e32_v_cg.set_inst_name("obj_MisalignV_vssseg8e32_v");
    MisalignV_vssseg8e64_v_cg = new(); MisalignV_vssseg8e64_v_cg.set_inst_name("obj_MisalignV_vssseg8e64_v");
    MisalignV_vssseg8e8_v_cg = new(); MisalignV_vssseg8e8_v_cg.set_inst_name("obj_MisalignV_vssseg8e8_v");
    MisalignV_vsuxei16_v_cg = new(); MisalignV_vsuxei16_v_cg.set_inst_name("obj_MisalignV_vsuxei16_v");
    MisalignV_vsuxei32_v_cg = new(); MisalignV_vsuxei32_v_cg.set_inst_name("obj_MisalignV_vsuxei32_v");
`ifdef XLEN64
    MisalignV_vsuxei64_v_cg = new(); MisalignV_vsuxei64_v_cg.set_inst_name("obj_MisalignV_vsuxei64_v");
`endif
    MisalignV_vsuxei8_v_cg = new(); MisalignV_vsuxei8_v_cg.set_inst_name("obj_MisalignV_vsuxei8_v");
    MisalignV_vsuxseg2ei16_v_cg = new(); MisalignV_vsuxseg2ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg2ei16_v");
    MisalignV_vsuxseg2ei32_v_cg = new(); MisalignV_vsuxseg2ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg2ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg2ei64_v_cg = new(); MisalignV_vsuxseg2ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg2ei64_v");
`endif
    MisalignV_vsuxseg2ei8_v_cg = new(); MisalignV_vsuxseg2ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg2ei8_v");
    MisalignV_vsuxseg3ei16_v_cg = new(); MisalignV_vsuxseg3ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg3ei16_v");
    MisalignV_vsuxseg3ei32_v_cg = new(); MisalignV_vsuxseg3ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg3ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg3ei64_v_cg = new(); MisalignV_vsuxseg3ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg3ei64_v");
`endif
    MisalignV_vsuxseg3ei8_v_cg = new(); MisalignV_vsuxseg3ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg3ei8_v");
    MisalignV_vsuxseg4ei16_v_cg = new(); MisalignV_vsuxseg4ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg4ei16_v");
    MisalignV_vsuxseg4ei32_v_cg = new(); MisalignV_vsuxseg4ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg4ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg4ei64_v_cg = new(); MisalignV_vsuxseg4ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg4ei64_v");
`endif
    MisalignV_vsuxseg4ei8_v_cg = new(); MisalignV_vsuxseg4ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg4ei8_v");
    MisalignV_vsuxseg5ei16_v_cg = new(); MisalignV_vsuxseg5ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg5ei16_v");
    MisalignV_vsuxseg5ei32_v_cg = new(); MisalignV_vsuxseg5ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg5ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg5ei64_v_cg = new(); MisalignV_vsuxseg5ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg5ei64_v");
`endif
    MisalignV_vsuxseg5ei8_v_cg = new(); MisalignV_vsuxseg5ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg5ei8_v");
    MisalignV_vsuxseg6ei16_v_cg = new(); MisalignV_vsuxseg6ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg6ei16_v");
    MisalignV_vsuxseg6ei32_v_cg = new(); MisalignV_vsuxseg6ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg6ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg6ei64_v_cg = new(); MisalignV_vsuxseg6ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg6ei64_v");
`endif
    MisalignV_vsuxseg6ei8_v_cg = new(); MisalignV_vsuxseg6ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg6ei8_v");
    MisalignV_vsuxseg7ei16_v_cg = new(); MisalignV_vsuxseg7ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg7ei16_v");
    MisalignV_vsuxseg7ei32_v_cg = new(); MisalignV_vsuxseg7ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg7ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg7ei64_v_cg = new(); MisalignV_vsuxseg7ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg7ei64_v");
`endif
    MisalignV_vsuxseg7ei8_v_cg = new(); MisalignV_vsuxseg7ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg7ei8_v");
    MisalignV_vsuxseg8ei16_v_cg = new(); MisalignV_vsuxseg8ei16_v_cg.set_inst_name("obj_MisalignV_vsuxseg8ei16_v");
    MisalignV_vsuxseg8ei32_v_cg = new(); MisalignV_vsuxseg8ei32_v_cg.set_inst_name("obj_MisalignV_vsuxseg8ei32_v");
`ifdef XLEN64
    MisalignV_vsuxseg8ei64_v_cg = new(); MisalignV_vsuxseg8ei64_v_cg.set_inst_name("obj_MisalignV_vsuxseg8ei64_v");
`endif
    MisalignV_vsuxseg8ei8_v_cg = new(); MisalignV_vsuxseg8ei8_v_cg.set_inst_name("obj_MisalignV_vsuxseg8ei8_v");
