##################################
# priv/pmp/__init__.py
#
# Registry and writer for the pure PMP suite generators.
# SPDX-License-Identifier: Apache-2.0
##################################

"""Registry and writer for the declaratively generated ``tests/priv/pmp`` suites.

These are the machine-mode PMP suites (no page tables, no satp), which live in
``tests/priv/pmp/pmp32/<Suite>`` and ``tests/priv/pmp/pmp64/<Suite>``. Each suite
is described as a list of :class:`~testgen.priv.pmp.model.PmpFile` and rendered
directly to .S files by :func:`~testgen.priv.pmp.emit.render_file`.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from testgen.discovery import discover_and_import_modules
from testgen.priv.pmp.emit import render_file
from testgen.priv.pmp.model import PmpFile

SuiteBuilder = Callable[[], "list[PmpFile]"]

_PMP_SUITES: dict[str, SuiteBuilder] = {}


def add_pmp_suite(testsuite: str) -> Callable[[SuiteBuilder], SuiteBuilder]:
    """Decorator registering a builder that returns the PmpFiles for one PMP suite."""

    def decorator(func: SuiteBuilder) -> SuiteBuilder:
        _PMP_SUITES[testsuite] = func
        return func

    return decorator


def get_pmp_suite_names() -> list[str]:
    """Names of all registered pure PMP suites."""
    return list(_PMP_SUITES.keys())


def is_pmp_suite(testsuite: str) -> bool:
    """Whether ``testsuite`` is generated by the pure PMP suite generator."""
    return testsuite in _PMP_SUITES


def write_pmp_suite(testsuite: str, output_test_dir: Path) -> None:
    """Render one PMP suite into ``<output_test_dir>/priv/pmp/pmp{32,64}/<testsuite>/``."""
    specs = _PMP_SUITES[testsuite]()
    written: dict[Path, set[str]] = {}
    for spec in specs:
        output_path = output_test_dir / "priv" / "pmp" / spec.xlen.outdir / testsuite
        output_path.mkdir(parents=True, exist_ok=True)
        (output_path / spec.filename).write_text(render_file(spec))
        written.setdefault(output_path, set()).add(spec.filename)
    for output_path, names in written.items():
        stale = sorted({p.name for p in output_path.glob("*.S")} - names)
        if stale:
            print(
                f"WARNING: {output_path} contains files not produced by the {testsuite} generator "
                f"(stale ghosts — delete by name): {', '.join(stale)}"
            )


# Discover and import suite tables at module load to trigger decorator registration
discover_and_import_modules(Path(__file__).parent / "suites", "testgen.priv.pmp.suites")
