##################################
# priv/pmp/emit.py
#
# File renderer for the pure PMP suite generators.
# SPDX-License-Identifier: Apache-2.0
##################################

"""Render :class:`PmpFile` descriptions into complete .S test files."""

from __future__ import annotations

from testgen.priv.pmp.model import PmpFile

HR = "// --------------------------------------------------------------------------------"

_GENERATED_NOTICE = (
    "// This file was generated by testgen (generators/testgen/src/testgen/priv/pmp); do not edit by hand."
)

_COPYRIGHT = "// Copyright (C) 2025 Harvey Mudd College & Oklahoma State University, UET Lahore, Habib University"


def _render_banner(spec: PmpFile) -> list[str]:
    lines = [HR, _COPYRIGHT, *spec.copyright, "// SPDX-License-Identifier: Apache-2.0", "//"]
    lines.extend(spec.banner.strip("\n").splitlines())
    lines.append(HR)
    return lines


def _render_header(spec: PmpFile) -> list[str]:
    exts = ",".join(f"'{e}'" for e in spec.required_extensions)
    params = (f"MXLEN: {spec.xlen.bits}", *spec.params)
    lines = [
        "",
        "##### START_TEST_CONFIG #####",
        f"# REQUIRED_EXTENSIONS:  [{exts}]",
        "# params:",
        *(f"#   {p}" for p in params),
        f"# MARCH: {spec.march or spec.xlen.march}",
        "##### END_TEST_CONFIG #####",
        "",
        "// Define the size of the signature region",
        f"#define SIGUPD_COUNT {spec.sigupd}",
        "",
        "// Every PMP test configures the PMP from M mode",
        "#define BOOT_TO_MMODE",
    ]
    if spec.extra_defines:
        lines.append("")
        lines.extend(spec.extra_defines)
    lines.extend(["", "// Include framework macros", '#include "riscv_arch_test.h"'])
    lines.extend(["", "// Set up test environment and declare main entry point", "RVTEST_BEGIN", ""])
    return lines


def _render_data(spec: PmpFile) -> list[str]:
    lines = ["RVTEST_CODE_END", "RVTEST_DATA_BEGIN", ""]
    if spec.sig_strs:
        labels = [f"{label}_str:" for label, _ in spec.sig_strs]
        width = max(map(len, labels)) + 1
        lines.append("// Test case strings for reporting")
        lines.extend(
            f'{label:<{width}}.string "\\"{message}\\""'
            for label, (_, message) in zip(labels, spec.sig_strs, strict=True)
        )
        lines.append("")
    if spec.data:
        lines.extend(spec.data)
        lines.append("")
    lines.extend(["RVTEST_DATA_END", "", "// Signature region for self-checking", "RVTEST_SIG_SETUP", ""])
    return lines


def render_file(spec: PmpFile) -> str:
    """Render one complete PMP .S test file from its PmpFile description."""
    parts = [
        _GENERATED_NOTICE,
        *_render_banner(spec),
        *_render_header(spec),
        *((*spec.pre_main, "") if spec.pre_main else ()),
        "main:",
        *spec.body,
        "",
        *_render_data(spec),
    ]
    return "\n".join(parts)
