///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_MISALIGNZCA
covergroup MisalignZca_c_lw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.lw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.lw" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.lw" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignZca_c_lwsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.lwsp"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.lwsp" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.lwsp" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignZca_c_sw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.sw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.sw" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.sw" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignZca_c_swsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.swsp"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.swsp" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.swsp" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
`ifdef UDB_MXLEN_64
covergroup MisalignZca_c_ld_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.ld"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.ld" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.ld" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignZca_c_ldsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.ldsp"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.ldsp" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.ldsp" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignZca_c_sd_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.sd"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.sd" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.sd" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignZca_c_sdsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.sdsp"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("c.sdsp" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("c.sdsp" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
`endif
function void misalignzca_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "c.lw"     : begin
            MisalignZca_c_lw_cg.sample(ins);
        end
        "c.lwsp"     : begin
            MisalignZca_c_lwsp_cg.sample(ins);
        end
        "c.sw"     : begin
            MisalignZca_c_sw_cg.sample(ins);
        end
        "c.swsp"     : begin
            MisalignZca_c_swsp_cg.sample(ins);
        end
`ifdef UDB_MXLEN_64
        "c.ld"     : begin
            MisalignZca_c_ld_cg.sample(ins);
        end
        "c.ldsp"     : begin
            MisalignZca_c_ldsp_cg.sample(ins);
        end
        "c.sd"     : begin
            MisalignZca_c_sd_cg.sample(ins);
        end
        "c.sdsp"     : begin
            MisalignZca_c_sdsp_cg.sample(ins);
        end
`endif
    endcase
endfunction
