///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    MisalignF_flw_cg = new(); MisalignF_flw_cg.set_inst_name("obj_MisalignF_flw");
    MisalignF_fsw_cg = new(); MisalignF_fsw_cg.set_inst_name("obj_MisalignF_fsw");
