///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_MISALIGN
covergroup Misalign_lh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "lh"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_hword : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 2-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:62]};
        bins yes = {[63:63]};
    }

endgroup
// ---------------------
covergroup Misalign_lhu_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "lhu"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_hword : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 2-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:62]};
        bins yes = {[63:63]};
    }

endgroup
// ---------------------
covergroup Misalign_lw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "lw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_word : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 4-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:60]};
        bins yes = {[61:63]};
    }

endgroup
// ---------------------
covergroup Misalign_sh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "sh"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_hword : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 2-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:62]};
        bins yes = {[63:63]};
    }

endgroup
// ---------------------
covergroup Misalign_sw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "sw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_word : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 4-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:60]};
        bins yes = {[61:63]};
    }

endgroup
// ---------------------
`ifdef UDB_MXLEN_64
covergroup Misalign_ld_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "ld"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_double : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 8-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:56]};
        bins yes = {[57:63]};
    }

endgroup
// ---------------------
covergroup Misalign_lwu_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "lwu"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_word : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 4-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:60]};
        bins yes = {[61:63]};
    }

endgroup
// ---------------------
covergroup Misalign_sd_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "sd"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64_double : coverpoint {ins.current.rs1_val + ins.current.imm}[5:0] iff (ins.trap == 0) {
        // Does the 8-byte access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        bins no  = {[0:56]};
        bins yes = {[57:63]};
    }

endgroup
// ---------------------
`endif
function void misalign_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "lh"     : begin
            Misalign_lh_cg.sample(ins);
        end
        "lhu"     : begin
            Misalign_lhu_cg.sample(ins);
        end
        "lw"     : begin
            Misalign_lw_cg.sample(ins);
        end
        "sh"     : begin
            Misalign_sh_cg.sample(ins);
        end
        "sw"     : begin
            Misalign_sw_cg.sample(ins);
        end
`ifdef UDB_MXLEN_64
        "ld"     : begin
            Misalign_ld_cg.sample(ins);
        end
        "lwu"     : begin
            Misalign_lwu_cg.sample(ins);
        end
        "sd"     : begin
            Misalign_sd_cg.sample(ins);
        end
`endif
        default: ; // a case needs at least one item, and some configurations select none
    endcase
endfunction
