///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_MISALIGNF
covergroup MisalignF_flw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "flw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("flw" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("flw" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
covergroup MisalignF_fsw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fsw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_misalign : coverpoint {ins.current.rs1_val + ins.current.imm}[2:0] iff (ins.trap == 0) {
        // all 8 byte offsets within a doubleword
    }

    cp_misalign_cross64 : coverpoint (7'({ins.current.rs1_val + ins.current.imm}[5:0]) +
            (("fsw" inside {"lh", "lhu", "sh"}) ? 7'd2 :
             ("fsw" inside {"ld", "sd", "fld", "fsd", "c.ld", "c.sd", "c.ldsp", "c.sdsp"}) ? 7'd8 : 7'd4)) > 7'd64
            iff (ins.trap == 0) {
        // Does the access cross a 64-byte boundary (and so a 16-, 32- or 64-byte cache line or bus beat)?
        // The access size in bytes comes from the mnemonic: 2 for halfwords, 8 for doublewords, else 4.
        bins no  = {0};
        bins yes = {1};
    }

endgroup
// ---------------------
function void misalignf_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "flw"     : begin
            MisalignF_flw_cg.sample(ins);
        end
        "fsw"     : begin
            MisalignF_fsw_cg.sample(ins);
        end
    endcase
endfunction
