///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    VfCustom16_vfadd_vf_cg = new(); VfCustom16_vfadd_vf_cg.set_inst_name("obj_VfCustom16_vfadd_vf");
    VfCustom16_vfadd_vv_cg = new(); VfCustom16_vfadd_vv_cg.set_inst_name("obj_VfCustom16_vfadd_vv");
    VfCustom16_vfclass_v_cg = new(); VfCustom16_vfclass_v_cg.set_inst_name("obj_VfCustom16_vfclass_v");
    VfCustom16_vfcvt_f_x_v_cg = new(); VfCustom16_vfcvt_f_x_v_cg.set_inst_name("obj_VfCustom16_vfcvt_f_x_v");
    VfCustom16_vfcvt_f_xu_v_cg = new(); VfCustom16_vfcvt_f_xu_v_cg.set_inst_name("obj_VfCustom16_vfcvt_f_xu_v");
    VfCustom16_vfcvt_rtz_x_f_v_cg = new(); VfCustom16_vfcvt_rtz_x_f_v_cg.set_inst_name("obj_VfCustom16_vfcvt_rtz_x_f_v");
    VfCustom16_vfcvt_rtz_xu_f_v_cg = new(); VfCustom16_vfcvt_rtz_xu_f_v_cg.set_inst_name("obj_VfCustom16_vfcvt_rtz_xu_f_v");
    VfCustom16_vfcvt_x_f_v_cg = new(); VfCustom16_vfcvt_x_f_v_cg.set_inst_name("obj_VfCustom16_vfcvt_x_f_v");
    VfCustom16_vfcvt_xu_f_v_cg = new(); VfCustom16_vfcvt_xu_f_v_cg.set_inst_name("obj_VfCustom16_vfcvt_xu_f_v");
    VfCustom16_vfdiv_vf_cg = new(); VfCustom16_vfdiv_vf_cg.set_inst_name("obj_VfCustom16_vfdiv_vf");
    VfCustom16_vfdiv_vv_cg = new(); VfCustom16_vfdiv_vv_cg.set_inst_name("obj_VfCustom16_vfdiv_vv");
    VfCustom16_vfmacc_vf_cg = new(); VfCustom16_vfmacc_vf_cg.set_inst_name("obj_VfCustom16_vfmacc_vf");
    VfCustom16_vfmacc_vv_cg = new(); VfCustom16_vfmacc_vv_cg.set_inst_name("obj_VfCustom16_vfmacc_vv");
    VfCustom16_vfmadd_vf_cg = new(); VfCustom16_vfmadd_vf_cg.set_inst_name("obj_VfCustom16_vfmadd_vf");
    VfCustom16_vfmadd_vv_cg = new(); VfCustom16_vfmadd_vv_cg.set_inst_name("obj_VfCustom16_vfmadd_vv");
    VfCustom16_vfmax_vf_cg = new(); VfCustom16_vfmax_vf_cg.set_inst_name("obj_VfCustom16_vfmax_vf");
    VfCustom16_vfmax_vv_cg = new(); VfCustom16_vfmax_vv_cg.set_inst_name("obj_VfCustom16_vfmax_vv");
    VfCustom16_vfmerge_vfm_cg = new(); VfCustom16_vfmerge_vfm_cg.set_inst_name("obj_VfCustom16_vfmerge_vfm");
    VfCustom16_vfmin_vf_cg = new(); VfCustom16_vfmin_vf_cg.set_inst_name("obj_VfCustom16_vfmin_vf");
    VfCustom16_vfmin_vv_cg = new(); VfCustom16_vfmin_vv_cg.set_inst_name("obj_VfCustom16_vfmin_vv");
    VfCustom16_vfmsac_vf_cg = new(); VfCustom16_vfmsac_vf_cg.set_inst_name("obj_VfCustom16_vfmsac_vf");
    VfCustom16_vfmsac_vv_cg = new(); VfCustom16_vfmsac_vv_cg.set_inst_name("obj_VfCustom16_vfmsac_vv");
    VfCustom16_vfmsub_vf_cg = new(); VfCustom16_vfmsub_vf_cg.set_inst_name("obj_VfCustom16_vfmsub_vf");
    VfCustom16_vfmsub_vv_cg = new(); VfCustom16_vfmsub_vv_cg.set_inst_name("obj_VfCustom16_vfmsub_vv");
    VfCustom16_vfmul_vf_cg = new(); VfCustom16_vfmul_vf_cg.set_inst_name("obj_VfCustom16_vfmul_vf");
    VfCustom16_vfmul_vv_cg = new(); VfCustom16_vfmul_vv_cg.set_inst_name("obj_VfCustom16_vfmul_vv");
    VfCustom16_vfmv_f_s_cg = new(); VfCustom16_vfmv_f_s_cg.set_inst_name("obj_VfCustom16_vfmv_f_s");
    VfCustom16_vfmv_s_f_cg = new(); VfCustom16_vfmv_s_f_cg.set_inst_name("obj_VfCustom16_vfmv_s_f");
    VfCustom16_vfmv_v_f_cg = new(); VfCustom16_vfmv_v_f_cg.set_inst_name("obj_VfCustom16_vfmv_v_f");
`ifndef ELEN16
    VfCustom16_vfncvt_f_f_w_cg = new(); VfCustom16_vfncvt_f_f_w_cg.set_inst_name("obj_VfCustom16_vfncvt_f_f_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_f_x_w_cg = new(); VfCustom16_vfncvt_f_x_w_cg.set_inst_name("obj_VfCustom16_vfncvt_f_x_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_f_xu_w_cg = new(); VfCustom16_vfncvt_f_xu_w_cg.set_inst_name("obj_VfCustom16_vfncvt_f_xu_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_rod_f_f_w_cg = new(); VfCustom16_vfncvt_rod_f_f_w_cg.set_inst_name("obj_VfCustom16_vfncvt_rod_f_f_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_rtz_x_f_w_cg = new(); VfCustom16_vfncvt_rtz_x_f_w_cg.set_inst_name("obj_VfCustom16_vfncvt_rtz_x_f_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_rtz_xu_f_w_cg = new(); VfCustom16_vfncvt_rtz_xu_f_w_cg.set_inst_name("obj_VfCustom16_vfncvt_rtz_xu_f_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_x_f_w_cg = new(); VfCustom16_vfncvt_x_f_w_cg.set_inst_name("obj_VfCustom16_vfncvt_x_f_w");
`endif
`ifndef ELEN16
    VfCustom16_vfncvt_xu_f_w_cg = new(); VfCustom16_vfncvt_xu_f_w_cg.set_inst_name("obj_VfCustom16_vfncvt_xu_f_w");
`endif
    VfCustom16_vfnmacc_vf_cg = new(); VfCustom16_vfnmacc_vf_cg.set_inst_name("obj_VfCustom16_vfnmacc_vf");
    VfCustom16_vfnmacc_vv_cg = new(); VfCustom16_vfnmacc_vv_cg.set_inst_name("obj_VfCustom16_vfnmacc_vv");
    VfCustom16_vfnmadd_vf_cg = new(); VfCustom16_vfnmadd_vf_cg.set_inst_name("obj_VfCustom16_vfnmadd_vf");
    VfCustom16_vfnmadd_vv_cg = new(); VfCustom16_vfnmadd_vv_cg.set_inst_name("obj_VfCustom16_vfnmadd_vv");
    VfCustom16_vfnmsac_vf_cg = new(); VfCustom16_vfnmsac_vf_cg.set_inst_name("obj_VfCustom16_vfnmsac_vf");
    VfCustom16_vfnmsac_vv_cg = new(); VfCustom16_vfnmsac_vv_cg.set_inst_name("obj_VfCustom16_vfnmsac_vv");
    VfCustom16_vfnmsub_vf_cg = new(); VfCustom16_vfnmsub_vf_cg.set_inst_name("obj_VfCustom16_vfnmsub_vf");
    VfCustom16_vfnmsub_vv_cg = new(); VfCustom16_vfnmsub_vv_cg.set_inst_name("obj_VfCustom16_vfnmsub_vv");
    VfCustom16_vfrdiv_vf_cg = new(); VfCustom16_vfrdiv_vf_cg.set_inst_name("obj_VfCustom16_vfrdiv_vf");
    VfCustom16_vfrec7_v_cg = new(); VfCustom16_vfrec7_v_cg.set_inst_name("obj_VfCustom16_vfrec7_v");
    VfCustom16_vfredmax_vs_cg = new(); VfCustom16_vfredmax_vs_cg.set_inst_name("obj_VfCustom16_vfredmax_vs");
    VfCustom16_vfredmin_vs_cg = new(); VfCustom16_vfredmin_vs_cg.set_inst_name("obj_VfCustom16_vfredmin_vs");
    VfCustom16_vfredosum_vs_cg = new(); VfCustom16_vfredosum_vs_cg.set_inst_name("obj_VfCustom16_vfredosum_vs");
    VfCustom16_vfredusum_vs_cg = new(); VfCustom16_vfredusum_vs_cg.set_inst_name("obj_VfCustom16_vfredusum_vs");
    VfCustom16_vfrsqrt7_v_cg = new(); VfCustom16_vfrsqrt7_v_cg.set_inst_name("obj_VfCustom16_vfrsqrt7_v");
    VfCustom16_vfrsub_vf_cg = new(); VfCustom16_vfrsub_vf_cg.set_inst_name("obj_VfCustom16_vfrsub_vf");
    VfCustom16_vfsgnj_vf_cg = new(); VfCustom16_vfsgnj_vf_cg.set_inst_name("obj_VfCustom16_vfsgnj_vf");
    VfCustom16_vfsgnj_vv_cg = new(); VfCustom16_vfsgnj_vv_cg.set_inst_name("obj_VfCustom16_vfsgnj_vv");
    VfCustom16_vfsgnjn_vf_cg = new(); VfCustom16_vfsgnjn_vf_cg.set_inst_name("obj_VfCustom16_vfsgnjn_vf");
    VfCustom16_vfsgnjn_vv_cg = new(); VfCustom16_vfsgnjn_vv_cg.set_inst_name("obj_VfCustom16_vfsgnjn_vv");
    VfCustom16_vfsgnjx_vf_cg = new(); VfCustom16_vfsgnjx_vf_cg.set_inst_name("obj_VfCustom16_vfsgnjx_vf");
    VfCustom16_vfsgnjx_vv_cg = new(); VfCustom16_vfsgnjx_vv_cg.set_inst_name("obj_VfCustom16_vfsgnjx_vv");
    VfCustom16_vfslide1down_vf_cg = new(); VfCustom16_vfslide1down_vf_cg.set_inst_name("obj_VfCustom16_vfslide1down_vf");
    VfCustom16_vfslide1up_vf_cg = new(); VfCustom16_vfslide1up_vf_cg.set_inst_name("obj_VfCustom16_vfslide1up_vf");
    VfCustom16_vfsqrt_v_cg = new(); VfCustom16_vfsqrt_v_cg.set_inst_name("obj_VfCustom16_vfsqrt_v");
    VfCustom16_vfsub_vf_cg = new(); VfCustom16_vfsub_vf_cg.set_inst_name("obj_VfCustom16_vfsub_vf");
    VfCustom16_vfsub_vv_cg = new(); VfCustom16_vfsub_vv_cg.set_inst_name("obj_VfCustom16_vfsub_vv");
`ifndef ELEN16
    VfCustom16_vfwadd_vf_cg = new(); VfCustom16_vfwadd_vf_cg.set_inst_name("obj_VfCustom16_vfwadd_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwadd_vv_cg = new(); VfCustom16_vfwadd_vv_cg.set_inst_name("obj_VfCustom16_vfwadd_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwadd_wf_cg = new(); VfCustom16_vfwadd_wf_cg.set_inst_name("obj_VfCustom16_vfwadd_wf");
`endif
`ifndef ELEN16
    VfCustom16_vfwadd_wv_cg = new(); VfCustom16_vfwadd_wv_cg.set_inst_name("obj_VfCustom16_vfwadd_wv");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_f_f_v_cg = new(); VfCustom16_vfwcvt_f_f_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_f_f_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_f_x_v_cg = new(); VfCustom16_vfwcvt_f_x_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_f_x_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_f_xu_v_cg = new(); VfCustom16_vfwcvt_f_xu_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_f_xu_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_rtz_x_f_v_cg = new(); VfCustom16_vfwcvt_rtz_x_f_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_rtz_x_f_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_rtz_xu_f_v_cg = new(); VfCustom16_vfwcvt_rtz_xu_f_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_rtz_xu_f_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_x_f_v_cg = new(); VfCustom16_vfwcvt_x_f_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_x_f_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwcvt_xu_f_v_cg = new(); VfCustom16_vfwcvt_xu_f_v_cg.set_inst_name("obj_VfCustom16_vfwcvt_xu_f_v");
`endif
`ifndef ELEN16
    VfCustom16_vfwmacc_vf_cg = new(); VfCustom16_vfwmacc_vf_cg.set_inst_name("obj_VfCustom16_vfwmacc_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwmacc_vv_cg = new(); VfCustom16_vfwmacc_vv_cg.set_inst_name("obj_VfCustom16_vfwmacc_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwmsac_vf_cg = new(); VfCustom16_vfwmsac_vf_cg.set_inst_name("obj_VfCustom16_vfwmsac_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwmsac_vv_cg = new(); VfCustom16_vfwmsac_vv_cg.set_inst_name("obj_VfCustom16_vfwmsac_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwmul_vf_cg = new(); VfCustom16_vfwmul_vf_cg.set_inst_name("obj_VfCustom16_vfwmul_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwmul_vv_cg = new(); VfCustom16_vfwmul_vv_cg.set_inst_name("obj_VfCustom16_vfwmul_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwnmacc_vf_cg = new(); VfCustom16_vfwnmacc_vf_cg.set_inst_name("obj_VfCustom16_vfwnmacc_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwnmacc_vv_cg = new(); VfCustom16_vfwnmacc_vv_cg.set_inst_name("obj_VfCustom16_vfwnmacc_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwnmsac_vf_cg = new(); VfCustom16_vfwnmsac_vf_cg.set_inst_name("obj_VfCustom16_vfwnmsac_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwnmsac_vv_cg = new(); VfCustom16_vfwnmsac_vv_cg.set_inst_name("obj_VfCustom16_vfwnmsac_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwredosum_vs_cg = new(); VfCustom16_vfwredosum_vs_cg.set_inst_name("obj_VfCustom16_vfwredosum_vs");
`endif
`ifndef ELEN16
    VfCustom16_vfwredusum_vs_cg = new(); VfCustom16_vfwredusum_vs_cg.set_inst_name("obj_VfCustom16_vfwredusum_vs");
`endif
`ifndef ELEN16
    VfCustom16_vfwsub_vf_cg = new(); VfCustom16_vfwsub_vf_cg.set_inst_name("obj_VfCustom16_vfwsub_vf");
`endif
`ifndef ELEN16
    VfCustom16_vfwsub_vv_cg = new(); VfCustom16_vfwsub_vv_cg.set_inst_name("obj_VfCustom16_vfwsub_vv");
`endif
`ifndef ELEN16
    VfCustom16_vfwsub_wf_cg = new(); VfCustom16_vfwsub_wf_cg.set_inst_name("obj_VfCustom16_vfwsub_wf");
`endif
`ifndef ELEN16
    VfCustom16_vfwsub_wv_cg = new(); VfCustom16_vfwsub_wv_cg.set_inst_name("obj_VfCustom16_vfwsub_wv");
`endif
    VfCustom16_vmfeq_vf_cg = new(); VfCustom16_vmfeq_vf_cg.set_inst_name("obj_VfCustom16_vmfeq_vf");
    VfCustom16_vmfeq_vv_cg = new(); VfCustom16_vmfeq_vv_cg.set_inst_name("obj_VfCustom16_vmfeq_vv");
    VfCustom16_vmfge_vf_cg = new(); VfCustom16_vmfge_vf_cg.set_inst_name("obj_VfCustom16_vmfge_vf");
    VfCustom16_vmfgt_vf_cg = new(); VfCustom16_vmfgt_vf_cg.set_inst_name("obj_VfCustom16_vmfgt_vf");
    VfCustom16_vmfle_vf_cg = new(); VfCustom16_vmfle_vf_cg.set_inst_name("obj_VfCustom16_vmfle_vf");
    VfCustom16_vmfle_vv_cg = new(); VfCustom16_vmfle_vv_cg.set_inst_name("obj_VfCustom16_vmfle_vv");
    VfCustom16_vmflt_vf_cg = new(); VfCustom16_vmflt_vf_cg.set_inst_name("obj_VfCustom16_vmflt_vf");
    VfCustom16_vmflt_vv_cg = new(); VfCustom16_vmflt_vv_cg.set_inst_name("obj_VfCustom16_vmflt_vv");
    VfCustom16_vmfne_vf_cg = new(); VfCustom16_vmfne_vf_cg.set_inst_name("obj_VfCustom16_vmfne_vf");
    VfCustom16_vmfne_vv_cg = new(); VfCustom16_vmfne_vv_cg.set_inst_name("obj_VfCustom16_vmfne_vv");
