///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    VfCustom64_vfadd_vf_cg = new(); VfCustom64_vfadd_vf_cg.set_inst_name("obj_VfCustom64_vfadd_vf");
    VfCustom64_vfadd_vv_cg = new(); VfCustom64_vfadd_vv_cg.set_inst_name("obj_VfCustom64_vfadd_vv");
    VfCustom64_vfclass_v_cg = new(); VfCustom64_vfclass_v_cg.set_inst_name("obj_VfCustom64_vfclass_v");
    VfCustom64_vfcvt_f_x_v_cg = new(); VfCustom64_vfcvt_f_x_v_cg.set_inst_name("obj_VfCustom64_vfcvt_f_x_v");
    VfCustom64_vfcvt_f_xu_v_cg = new(); VfCustom64_vfcvt_f_xu_v_cg.set_inst_name("obj_VfCustom64_vfcvt_f_xu_v");
    VfCustom64_vfcvt_rtz_x_f_v_cg = new(); VfCustom64_vfcvt_rtz_x_f_v_cg.set_inst_name("obj_VfCustom64_vfcvt_rtz_x_f_v");
    VfCustom64_vfcvt_rtz_xu_f_v_cg = new(); VfCustom64_vfcvt_rtz_xu_f_v_cg.set_inst_name("obj_VfCustom64_vfcvt_rtz_xu_f_v");
    VfCustom64_vfcvt_x_f_v_cg = new(); VfCustom64_vfcvt_x_f_v_cg.set_inst_name("obj_VfCustom64_vfcvt_x_f_v");
    VfCustom64_vfcvt_xu_f_v_cg = new(); VfCustom64_vfcvt_xu_f_v_cg.set_inst_name("obj_VfCustom64_vfcvt_xu_f_v");
    VfCustom64_vfdiv_vf_cg = new(); VfCustom64_vfdiv_vf_cg.set_inst_name("obj_VfCustom64_vfdiv_vf");
    VfCustom64_vfdiv_vv_cg = new(); VfCustom64_vfdiv_vv_cg.set_inst_name("obj_VfCustom64_vfdiv_vv");
    VfCustom64_vfmacc_vf_cg = new(); VfCustom64_vfmacc_vf_cg.set_inst_name("obj_VfCustom64_vfmacc_vf");
    VfCustom64_vfmacc_vv_cg = new(); VfCustom64_vfmacc_vv_cg.set_inst_name("obj_VfCustom64_vfmacc_vv");
    VfCustom64_vfmadd_vf_cg = new(); VfCustom64_vfmadd_vf_cg.set_inst_name("obj_VfCustom64_vfmadd_vf");
    VfCustom64_vfmadd_vv_cg = new(); VfCustom64_vfmadd_vv_cg.set_inst_name("obj_VfCustom64_vfmadd_vv");
    VfCustom64_vfmax_vf_cg = new(); VfCustom64_vfmax_vf_cg.set_inst_name("obj_VfCustom64_vfmax_vf");
    VfCustom64_vfmax_vv_cg = new(); VfCustom64_vfmax_vv_cg.set_inst_name("obj_VfCustom64_vfmax_vv");
    VfCustom64_vfmerge_vfm_cg = new(); VfCustom64_vfmerge_vfm_cg.set_inst_name("obj_VfCustom64_vfmerge_vfm");
    VfCustom64_vfmin_vf_cg = new(); VfCustom64_vfmin_vf_cg.set_inst_name("obj_VfCustom64_vfmin_vf");
    VfCustom64_vfmin_vv_cg = new(); VfCustom64_vfmin_vv_cg.set_inst_name("obj_VfCustom64_vfmin_vv");
    VfCustom64_vfmsac_vf_cg = new(); VfCustom64_vfmsac_vf_cg.set_inst_name("obj_VfCustom64_vfmsac_vf");
    VfCustom64_vfmsac_vv_cg = new(); VfCustom64_vfmsac_vv_cg.set_inst_name("obj_VfCustom64_vfmsac_vv");
    VfCustom64_vfmsub_vf_cg = new(); VfCustom64_vfmsub_vf_cg.set_inst_name("obj_VfCustom64_vfmsub_vf");
    VfCustom64_vfmsub_vv_cg = new(); VfCustom64_vfmsub_vv_cg.set_inst_name("obj_VfCustom64_vfmsub_vv");
    VfCustom64_vfmul_vf_cg = new(); VfCustom64_vfmul_vf_cg.set_inst_name("obj_VfCustom64_vfmul_vf");
    VfCustom64_vfmul_vv_cg = new(); VfCustom64_vfmul_vv_cg.set_inst_name("obj_VfCustom64_vfmul_vv");
    VfCustom64_vfmv_f_s_cg = new(); VfCustom64_vfmv_f_s_cg.set_inst_name("obj_VfCustom64_vfmv_f_s");
    VfCustom64_vfmv_s_f_cg = new(); VfCustom64_vfmv_s_f_cg.set_inst_name("obj_VfCustom64_vfmv_s_f");
    VfCustom64_vfmv_v_f_cg = new(); VfCustom64_vfmv_v_f_cg.set_inst_name("obj_VfCustom64_vfmv_v_f");
    VfCustom64_vfnmacc_vf_cg = new(); VfCustom64_vfnmacc_vf_cg.set_inst_name("obj_VfCustom64_vfnmacc_vf");
    VfCustom64_vfnmacc_vv_cg = new(); VfCustom64_vfnmacc_vv_cg.set_inst_name("obj_VfCustom64_vfnmacc_vv");
    VfCustom64_vfnmadd_vf_cg = new(); VfCustom64_vfnmadd_vf_cg.set_inst_name("obj_VfCustom64_vfnmadd_vf");
    VfCustom64_vfnmadd_vv_cg = new(); VfCustom64_vfnmadd_vv_cg.set_inst_name("obj_VfCustom64_vfnmadd_vv");
    VfCustom64_vfnmsac_vf_cg = new(); VfCustom64_vfnmsac_vf_cg.set_inst_name("obj_VfCustom64_vfnmsac_vf");
    VfCustom64_vfnmsac_vv_cg = new(); VfCustom64_vfnmsac_vv_cg.set_inst_name("obj_VfCustom64_vfnmsac_vv");
    VfCustom64_vfnmsub_vf_cg = new(); VfCustom64_vfnmsub_vf_cg.set_inst_name("obj_VfCustom64_vfnmsub_vf");
    VfCustom64_vfnmsub_vv_cg = new(); VfCustom64_vfnmsub_vv_cg.set_inst_name("obj_VfCustom64_vfnmsub_vv");
    VfCustom64_vfrdiv_vf_cg = new(); VfCustom64_vfrdiv_vf_cg.set_inst_name("obj_VfCustom64_vfrdiv_vf");
    VfCustom64_vfrec7_v_cg = new(); VfCustom64_vfrec7_v_cg.set_inst_name("obj_VfCustom64_vfrec7_v");
    VfCustom64_vfredmax_vs_cg = new(); VfCustom64_vfredmax_vs_cg.set_inst_name("obj_VfCustom64_vfredmax_vs");
    VfCustom64_vfredmin_vs_cg = new(); VfCustom64_vfredmin_vs_cg.set_inst_name("obj_VfCustom64_vfredmin_vs");
    VfCustom64_vfredosum_vs_cg = new(); VfCustom64_vfredosum_vs_cg.set_inst_name("obj_VfCustom64_vfredosum_vs");
    VfCustom64_vfredusum_vs_cg = new(); VfCustom64_vfredusum_vs_cg.set_inst_name("obj_VfCustom64_vfredusum_vs");
    VfCustom64_vfrsqrt7_v_cg = new(); VfCustom64_vfrsqrt7_v_cg.set_inst_name("obj_VfCustom64_vfrsqrt7_v");
    VfCustom64_vfrsub_vf_cg = new(); VfCustom64_vfrsub_vf_cg.set_inst_name("obj_VfCustom64_vfrsub_vf");
    VfCustom64_vfsgnj_vf_cg = new(); VfCustom64_vfsgnj_vf_cg.set_inst_name("obj_VfCustom64_vfsgnj_vf");
    VfCustom64_vfsgnj_vv_cg = new(); VfCustom64_vfsgnj_vv_cg.set_inst_name("obj_VfCustom64_vfsgnj_vv");
    VfCustom64_vfsgnjn_vf_cg = new(); VfCustom64_vfsgnjn_vf_cg.set_inst_name("obj_VfCustom64_vfsgnjn_vf");
    VfCustom64_vfsgnjn_vv_cg = new(); VfCustom64_vfsgnjn_vv_cg.set_inst_name("obj_VfCustom64_vfsgnjn_vv");
    VfCustom64_vfsgnjx_vf_cg = new(); VfCustom64_vfsgnjx_vf_cg.set_inst_name("obj_VfCustom64_vfsgnjx_vf");
    VfCustom64_vfsgnjx_vv_cg = new(); VfCustom64_vfsgnjx_vv_cg.set_inst_name("obj_VfCustom64_vfsgnjx_vv");
    VfCustom64_vfslide1down_vf_cg = new(); VfCustom64_vfslide1down_vf_cg.set_inst_name("obj_VfCustom64_vfslide1down_vf");
    VfCustom64_vfslide1up_vf_cg = new(); VfCustom64_vfslide1up_vf_cg.set_inst_name("obj_VfCustom64_vfslide1up_vf");
    VfCustom64_vfsqrt_v_cg = new(); VfCustom64_vfsqrt_v_cg.set_inst_name("obj_VfCustom64_vfsqrt_v");
    VfCustom64_vfsub_vf_cg = new(); VfCustom64_vfsub_vf_cg.set_inst_name("obj_VfCustom64_vfsub_vf");
    VfCustom64_vfsub_vv_cg = new(); VfCustom64_vfsub_vv_cg.set_inst_name("obj_VfCustom64_vfsub_vv");
    VfCustom64_vmfeq_vf_cg = new(); VfCustom64_vmfeq_vf_cg.set_inst_name("obj_VfCustom64_vmfeq_vf");
    VfCustom64_vmfeq_vv_cg = new(); VfCustom64_vmfeq_vv_cg.set_inst_name("obj_VfCustom64_vmfeq_vv");
    VfCustom64_vmfge_vf_cg = new(); VfCustom64_vmfge_vf_cg.set_inst_name("obj_VfCustom64_vmfge_vf");
    VfCustom64_vmfgt_vf_cg = new(); VfCustom64_vmfgt_vf_cg.set_inst_name("obj_VfCustom64_vmfgt_vf");
    VfCustom64_vmfle_vf_cg = new(); VfCustom64_vmfle_vf_cg.set_inst_name("obj_VfCustom64_vmfle_vf");
    VfCustom64_vmfle_vv_cg = new(); VfCustom64_vmfle_vv_cg.set_inst_name("obj_VfCustom64_vmfle_vv");
    VfCustom64_vmflt_vf_cg = new(); VfCustom64_vmflt_vf_cg.set_inst_name("obj_VfCustom64_vmflt_vf");
    VfCustom64_vmflt_vv_cg = new(); VfCustom64_vmflt_vv_cg.set_inst_name("obj_VfCustom64_vmflt_vv");
    VfCustom64_vmfne_vf_cg = new(); VfCustom64_vmfne_vf_cg.set_inst_name("obj_VfCustom64_vmfne_vf");
    VfCustom64_vmfne_vv_cg = new(); VfCustom64_vmfne_vv_cg.set_inst_name("obj_VfCustom64_vmfne_vv");
