///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Vls64_vl1re16_v_cg = new(); Vls64_vl1re16_v_cg.set_inst_name("obj_Vls64_vl1re16_v");
    Vls64_vl1re32_v_cg = new(); Vls64_vl1re32_v_cg.set_inst_name("obj_Vls64_vl1re32_v");
    Vls64_vl1re64_v_cg = new(); Vls64_vl1re64_v_cg.set_inst_name("obj_Vls64_vl1re64_v");
    Vls64_vl1re8_v_cg = new(); Vls64_vl1re8_v_cg.set_inst_name("obj_Vls64_vl1re8_v");
    Vls64_vl2re16_v_cg = new(); Vls64_vl2re16_v_cg.set_inst_name("obj_Vls64_vl2re16_v");
    Vls64_vl2re32_v_cg = new(); Vls64_vl2re32_v_cg.set_inst_name("obj_Vls64_vl2re32_v");
    Vls64_vl2re64_v_cg = new(); Vls64_vl2re64_v_cg.set_inst_name("obj_Vls64_vl2re64_v");
    Vls64_vl2re8_v_cg = new(); Vls64_vl2re8_v_cg.set_inst_name("obj_Vls64_vl2re8_v");
    Vls64_vl4re16_v_cg = new(); Vls64_vl4re16_v_cg.set_inst_name("obj_Vls64_vl4re16_v");
    Vls64_vl4re32_v_cg = new(); Vls64_vl4re32_v_cg.set_inst_name("obj_Vls64_vl4re32_v");
    Vls64_vl4re64_v_cg = new(); Vls64_vl4re64_v_cg.set_inst_name("obj_Vls64_vl4re64_v");
    Vls64_vl4re8_v_cg = new(); Vls64_vl4re8_v_cg.set_inst_name("obj_Vls64_vl4re8_v");
    Vls64_vl8re16_v_cg = new(); Vls64_vl8re16_v_cg.set_inst_name("obj_Vls64_vl8re16_v");
    Vls64_vl8re32_v_cg = new(); Vls64_vl8re32_v_cg.set_inst_name("obj_Vls64_vl8re32_v");
    Vls64_vl8re64_v_cg = new(); Vls64_vl8re64_v_cg.set_inst_name("obj_Vls64_vl8re64_v");
    Vls64_vl8re8_v_cg = new(); Vls64_vl8re8_v_cg.set_inst_name("obj_Vls64_vl8re8_v");
    Vls64_vle16_v_cg = new(); Vls64_vle16_v_cg.set_inst_name("obj_Vls64_vle16_v");
    Vls64_vle16ff_v_cg = new(); Vls64_vle16ff_v_cg.set_inst_name("obj_Vls64_vle16ff_v");
    Vls64_vle32_v_cg = new(); Vls64_vle32_v_cg.set_inst_name("obj_Vls64_vle32_v");
    Vls64_vle32ff_v_cg = new(); Vls64_vle32ff_v_cg.set_inst_name("obj_Vls64_vle32ff_v");
    Vls64_vle64_v_cg = new(); Vls64_vle64_v_cg.set_inst_name("obj_Vls64_vle64_v");
    Vls64_vle64ff_v_cg = new(); Vls64_vle64ff_v_cg.set_inst_name("obj_Vls64_vle64ff_v");
    Vls64_vle8_v_cg = new(); Vls64_vle8_v_cg.set_inst_name("obj_Vls64_vle8_v");
    Vls64_vle8ff_v_cg = new(); Vls64_vle8ff_v_cg.set_inst_name("obj_Vls64_vle8ff_v");
    Vls64_vlm_v_cg = new(); Vls64_vlm_v_cg.set_inst_name("obj_Vls64_vlm_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxei16_v_cg = new(); Vls64_vloxei16_v_cg.set_inst_name("obj_Vls64_vloxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxei32_v_cg = new(); Vls64_vloxei32_v_cg.set_inst_name("obj_Vls64_vloxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxei64_v_cg = new(); Vls64_vloxei64_v_cg.set_inst_name("obj_Vls64_vloxei64_v");
`endif
    Vls64_vloxei8_v_cg = new(); Vls64_vloxei8_v_cg.set_inst_name("obj_Vls64_vloxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg2ei16_v_cg = new(); Vls64_vloxseg2ei16_v_cg.set_inst_name("obj_Vls64_vloxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg2ei32_v_cg = new(); Vls64_vloxseg2ei32_v_cg.set_inst_name("obj_Vls64_vloxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg2ei64_v_cg = new(); Vls64_vloxseg2ei64_v_cg.set_inst_name("obj_Vls64_vloxseg2ei64_v");
`endif
    Vls64_vloxseg2ei8_v_cg = new(); Vls64_vloxseg2ei8_v_cg.set_inst_name("obj_Vls64_vloxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg3ei16_v_cg = new(); Vls64_vloxseg3ei16_v_cg.set_inst_name("obj_Vls64_vloxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg3ei32_v_cg = new(); Vls64_vloxseg3ei32_v_cg.set_inst_name("obj_Vls64_vloxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg3ei64_v_cg = new(); Vls64_vloxseg3ei64_v_cg.set_inst_name("obj_Vls64_vloxseg3ei64_v");
`endif
    Vls64_vloxseg3ei8_v_cg = new(); Vls64_vloxseg3ei8_v_cg.set_inst_name("obj_Vls64_vloxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg4ei16_v_cg = new(); Vls64_vloxseg4ei16_v_cg.set_inst_name("obj_Vls64_vloxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg4ei32_v_cg = new(); Vls64_vloxseg4ei32_v_cg.set_inst_name("obj_Vls64_vloxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg4ei64_v_cg = new(); Vls64_vloxseg4ei64_v_cg.set_inst_name("obj_Vls64_vloxseg4ei64_v");
`endif
    Vls64_vloxseg4ei8_v_cg = new(); Vls64_vloxseg4ei8_v_cg.set_inst_name("obj_Vls64_vloxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg5ei16_v_cg = new(); Vls64_vloxseg5ei16_v_cg.set_inst_name("obj_Vls64_vloxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg5ei32_v_cg = new(); Vls64_vloxseg5ei32_v_cg.set_inst_name("obj_Vls64_vloxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg5ei64_v_cg = new(); Vls64_vloxseg5ei64_v_cg.set_inst_name("obj_Vls64_vloxseg5ei64_v");
`endif
    Vls64_vloxseg5ei8_v_cg = new(); Vls64_vloxseg5ei8_v_cg.set_inst_name("obj_Vls64_vloxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg6ei16_v_cg = new(); Vls64_vloxseg6ei16_v_cg.set_inst_name("obj_Vls64_vloxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg6ei32_v_cg = new(); Vls64_vloxseg6ei32_v_cg.set_inst_name("obj_Vls64_vloxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg6ei64_v_cg = new(); Vls64_vloxseg6ei64_v_cg.set_inst_name("obj_Vls64_vloxseg6ei64_v");
`endif
    Vls64_vloxseg6ei8_v_cg = new(); Vls64_vloxseg6ei8_v_cg.set_inst_name("obj_Vls64_vloxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg7ei16_v_cg = new(); Vls64_vloxseg7ei16_v_cg.set_inst_name("obj_Vls64_vloxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg7ei32_v_cg = new(); Vls64_vloxseg7ei32_v_cg.set_inst_name("obj_Vls64_vloxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg7ei64_v_cg = new(); Vls64_vloxseg7ei64_v_cg.set_inst_name("obj_Vls64_vloxseg7ei64_v");
`endif
    Vls64_vloxseg7ei8_v_cg = new(); Vls64_vloxseg7ei8_v_cg.set_inst_name("obj_Vls64_vloxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vloxseg8ei16_v_cg = new(); Vls64_vloxseg8ei16_v_cg.set_inst_name("obj_Vls64_vloxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vloxseg8ei32_v_cg = new(); Vls64_vloxseg8ei32_v_cg.set_inst_name("obj_Vls64_vloxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vloxseg8ei64_v_cg = new(); Vls64_vloxseg8ei64_v_cg.set_inst_name("obj_Vls64_vloxseg8ei64_v");
`endif
    Vls64_vloxseg8ei8_v_cg = new(); Vls64_vloxseg8ei8_v_cg.set_inst_name("obj_Vls64_vloxseg8ei8_v");
    Vls64_vlse16_v_cg = new(); Vls64_vlse16_v_cg.set_inst_name("obj_Vls64_vlse16_v");
    Vls64_vlse32_v_cg = new(); Vls64_vlse32_v_cg.set_inst_name("obj_Vls64_vlse32_v");
    Vls64_vlse64_v_cg = new(); Vls64_vlse64_v_cg.set_inst_name("obj_Vls64_vlse64_v");
    Vls64_vlse8_v_cg = new(); Vls64_vlse8_v_cg.set_inst_name("obj_Vls64_vlse8_v");
    Vls64_vlseg2e16_v_cg = new(); Vls64_vlseg2e16_v_cg.set_inst_name("obj_Vls64_vlseg2e16_v");
    Vls64_vlseg2e16ff_v_cg = new(); Vls64_vlseg2e16ff_v_cg.set_inst_name("obj_Vls64_vlseg2e16ff_v");
    Vls64_vlseg2e32_v_cg = new(); Vls64_vlseg2e32_v_cg.set_inst_name("obj_Vls64_vlseg2e32_v");
    Vls64_vlseg2e32ff_v_cg = new(); Vls64_vlseg2e32ff_v_cg.set_inst_name("obj_Vls64_vlseg2e32ff_v");
    Vls64_vlseg2e64_v_cg = new(); Vls64_vlseg2e64_v_cg.set_inst_name("obj_Vls64_vlseg2e64_v");
    Vls64_vlseg2e64ff_v_cg = new(); Vls64_vlseg2e64ff_v_cg.set_inst_name("obj_Vls64_vlseg2e64ff_v");
    Vls64_vlseg2e8_v_cg = new(); Vls64_vlseg2e8_v_cg.set_inst_name("obj_Vls64_vlseg2e8_v");
    Vls64_vlseg2e8ff_v_cg = new(); Vls64_vlseg2e8ff_v_cg.set_inst_name("obj_Vls64_vlseg2e8ff_v");
    Vls64_vlseg3e16_v_cg = new(); Vls64_vlseg3e16_v_cg.set_inst_name("obj_Vls64_vlseg3e16_v");
    Vls64_vlseg3e16ff_v_cg = new(); Vls64_vlseg3e16ff_v_cg.set_inst_name("obj_Vls64_vlseg3e16ff_v");
    Vls64_vlseg3e32_v_cg = new(); Vls64_vlseg3e32_v_cg.set_inst_name("obj_Vls64_vlseg3e32_v");
    Vls64_vlseg3e32ff_v_cg = new(); Vls64_vlseg3e32ff_v_cg.set_inst_name("obj_Vls64_vlseg3e32ff_v");
    Vls64_vlseg3e64_v_cg = new(); Vls64_vlseg3e64_v_cg.set_inst_name("obj_Vls64_vlseg3e64_v");
    Vls64_vlseg3e64ff_v_cg = new(); Vls64_vlseg3e64ff_v_cg.set_inst_name("obj_Vls64_vlseg3e64ff_v");
    Vls64_vlseg3e8_v_cg = new(); Vls64_vlseg3e8_v_cg.set_inst_name("obj_Vls64_vlseg3e8_v");
    Vls64_vlseg3e8ff_v_cg = new(); Vls64_vlseg3e8ff_v_cg.set_inst_name("obj_Vls64_vlseg3e8ff_v");
    Vls64_vlseg4e16_v_cg = new(); Vls64_vlseg4e16_v_cg.set_inst_name("obj_Vls64_vlseg4e16_v");
    Vls64_vlseg4e16ff_v_cg = new(); Vls64_vlseg4e16ff_v_cg.set_inst_name("obj_Vls64_vlseg4e16ff_v");
    Vls64_vlseg4e32_v_cg = new(); Vls64_vlseg4e32_v_cg.set_inst_name("obj_Vls64_vlseg4e32_v");
    Vls64_vlseg4e32ff_v_cg = new(); Vls64_vlseg4e32ff_v_cg.set_inst_name("obj_Vls64_vlseg4e32ff_v");
    Vls64_vlseg4e64_v_cg = new(); Vls64_vlseg4e64_v_cg.set_inst_name("obj_Vls64_vlseg4e64_v");
    Vls64_vlseg4e64ff_v_cg = new(); Vls64_vlseg4e64ff_v_cg.set_inst_name("obj_Vls64_vlseg4e64ff_v");
    Vls64_vlseg4e8_v_cg = new(); Vls64_vlseg4e8_v_cg.set_inst_name("obj_Vls64_vlseg4e8_v");
    Vls64_vlseg4e8ff_v_cg = new(); Vls64_vlseg4e8ff_v_cg.set_inst_name("obj_Vls64_vlseg4e8ff_v");
    Vls64_vlseg5e16_v_cg = new(); Vls64_vlseg5e16_v_cg.set_inst_name("obj_Vls64_vlseg5e16_v");
    Vls64_vlseg5e16ff_v_cg = new(); Vls64_vlseg5e16ff_v_cg.set_inst_name("obj_Vls64_vlseg5e16ff_v");
    Vls64_vlseg5e32_v_cg = new(); Vls64_vlseg5e32_v_cg.set_inst_name("obj_Vls64_vlseg5e32_v");
    Vls64_vlseg5e32ff_v_cg = new(); Vls64_vlseg5e32ff_v_cg.set_inst_name("obj_Vls64_vlseg5e32ff_v");
    Vls64_vlseg5e64_v_cg = new(); Vls64_vlseg5e64_v_cg.set_inst_name("obj_Vls64_vlseg5e64_v");
    Vls64_vlseg5e64ff_v_cg = new(); Vls64_vlseg5e64ff_v_cg.set_inst_name("obj_Vls64_vlseg5e64ff_v");
    Vls64_vlseg5e8_v_cg = new(); Vls64_vlseg5e8_v_cg.set_inst_name("obj_Vls64_vlseg5e8_v");
    Vls64_vlseg5e8ff_v_cg = new(); Vls64_vlseg5e8ff_v_cg.set_inst_name("obj_Vls64_vlseg5e8ff_v");
    Vls64_vlseg6e16_v_cg = new(); Vls64_vlseg6e16_v_cg.set_inst_name("obj_Vls64_vlseg6e16_v");
    Vls64_vlseg6e16ff_v_cg = new(); Vls64_vlseg6e16ff_v_cg.set_inst_name("obj_Vls64_vlseg6e16ff_v");
    Vls64_vlseg6e32_v_cg = new(); Vls64_vlseg6e32_v_cg.set_inst_name("obj_Vls64_vlseg6e32_v");
    Vls64_vlseg6e32ff_v_cg = new(); Vls64_vlseg6e32ff_v_cg.set_inst_name("obj_Vls64_vlseg6e32ff_v");
    Vls64_vlseg6e64_v_cg = new(); Vls64_vlseg6e64_v_cg.set_inst_name("obj_Vls64_vlseg6e64_v");
    Vls64_vlseg6e64ff_v_cg = new(); Vls64_vlseg6e64ff_v_cg.set_inst_name("obj_Vls64_vlseg6e64ff_v");
    Vls64_vlseg6e8_v_cg = new(); Vls64_vlseg6e8_v_cg.set_inst_name("obj_Vls64_vlseg6e8_v");
    Vls64_vlseg6e8ff_v_cg = new(); Vls64_vlseg6e8ff_v_cg.set_inst_name("obj_Vls64_vlseg6e8ff_v");
    Vls64_vlseg7e16_v_cg = new(); Vls64_vlseg7e16_v_cg.set_inst_name("obj_Vls64_vlseg7e16_v");
    Vls64_vlseg7e16ff_v_cg = new(); Vls64_vlseg7e16ff_v_cg.set_inst_name("obj_Vls64_vlseg7e16ff_v");
    Vls64_vlseg7e32_v_cg = new(); Vls64_vlseg7e32_v_cg.set_inst_name("obj_Vls64_vlseg7e32_v");
    Vls64_vlseg7e32ff_v_cg = new(); Vls64_vlseg7e32ff_v_cg.set_inst_name("obj_Vls64_vlseg7e32ff_v");
    Vls64_vlseg7e64_v_cg = new(); Vls64_vlseg7e64_v_cg.set_inst_name("obj_Vls64_vlseg7e64_v");
    Vls64_vlseg7e64ff_v_cg = new(); Vls64_vlseg7e64ff_v_cg.set_inst_name("obj_Vls64_vlseg7e64ff_v");
    Vls64_vlseg7e8_v_cg = new(); Vls64_vlseg7e8_v_cg.set_inst_name("obj_Vls64_vlseg7e8_v");
    Vls64_vlseg7e8ff_v_cg = new(); Vls64_vlseg7e8ff_v_cg.set_inst_name("obj_Vls64_vlseg7e8ff_v");
    Vls64_vlseg8e16_v_cg = new(); Vls64_vlseg8e16_v_cg.set_inst_name("obj_Vls64_vlseg8e16_v");
    Vls64_vlseg8e16ff_v_cg = new(); Vls64_vlseg8e16ff_v_cg.set_inst_name("obj_Vls64_vlseg8e16ff_v");
    Vls64_vlseg8e32_v_cg = new(); Vls64_vlseg8e32_v_cg.set_inst_name("obj_Vls64_vlseg8e32_v");
    Vls64_vlseg8e32ff_v_cg = new(); Vls64_vlseg8e32ff_v_cg.set_inst_name("obj_Vls64_vlseg8e32ff_v");
    Vls64_vlseg8e64_v_cg = new(); Vls64_vlseg8e64_v_cg.set_inst_name("obj_Vls64_vlseg8e64_v");
    Vls64_vlseg8e64ff_v_cg = new(); Vls64_vlseg8e64ff_v_cg.set_inst_name("obj_Vls64_vlseg8e64ff_v");
    Vls64_vlseg8e8_v_cg = new(); Vls64_vlseg8e8_v_cg.set_inst_name("obj_Vls64_vlseg8e8_v");
    Vls64_vlseg8e8ff_v_cg = new(); Vls64_vlseg8e8ff_v_cg.set_inst_name("obj_Vls64_vlseg8e8ff_v");
    Vls64_vlsseg2e16_v_cg = new(); Vls64_vlsseg2e16_v_cg.set_inst_name("obj_Vls64_vlsseg2e16_v");
    Vls64_vlsseg2e32_v_cg = new(); Vls64_vlsseg2e32_v_cg.set_inst_name("obj_Vls64_vlsseg2e32_v");
    Vls64_vlsseg2e64_v_cg = new(); Vls64_vlsseg2e64_v_cg.set_inst_name("obj_Vls64_vlsseg2e64_v");
    Vls64_vlsseg2e8_v_cg = new(); Vls64_vlsseg2e8_v_cg.set_inst_name("obj_Vls64_vlsseg2e8_v");
    Vls64_vlsseg3e16_v_cg = new(); Vls64_vlsseg3e16_v_cg.set_inst_name("obj_Vls64_vlsseg3e16_v");
    Vls64_vlsseg3e32_v_cg = new(); Vls64_vlsseg3e32_v_cg.set_inst_name("obj_Vls64_vlsseg3e32_v");
    Vls64_vlsseg3e64_v_cg = new(); Vls64_vlsseg3e64_v_cg.set_inst_name("obj_Vls64_vlsseg3e64_v");
    Vls64_vlsseg3e8_v_cg = new(); Vls64_vlsseg3e8_v_cg.set_inst_name("obj_Vls64_vlsseg3e8_v");
    Vls64_vlsseg4e16_v_cg = new(); Vls64_vlsseg4e16_v_cg.set_inst_name("obj_Vls64_vlsseg4e16_v");
    Vls64_vlsseg4e32_v_cg = new(); Vls64_vlsseg4e32_v_cg.set_inst_name("obj_Vls64_vlsseg4e32_v");
    Vls64_vlsseg4e64_v_cg = new(); Vls64_vlsseg4e64_v_cg.set_inst_name("obj_Vls64_vlsseg4e64_v");
    Vls64_vlsseg4e8_v_cg = new(); Vls64_vlsseg4e8_v_cg.set_inst_name("obj_Vls64_vlsseg4e8_v");
    Vls64_vlsseg5e16_v_cg = new(); Vls64_vlsseg5e16_v_cg.set_inst_name("obj_Vls64_vlsseg5e16_v");
    Vls64_vlsseg5e32_v_cg = new(); Vls64_vlsseg5e32_v_cg.set_inst_name("obj_Vls64_vlsseg5e32_v");
    Vls64_vlsseg5e64_v_cg = new(); Vls64_vlsseg5e64_v_cg.set_inst_name("obj_Vls64_vlsseg5e64_v");
    Vls64_vlsseg5e8_v_cg = new(); Vls64_vlsseg5e8_v_cg.set_inst_name("obj_Vls64_vlsseg5e8_v");
    Vls64_vlsseg6e16_v_cg = new(); Vls64_vlsseg6e16_v_cg.set_inst_name("obj_Vls64_vlsseg6e16_v");
    Vls64_vlsseg6e32_v_cg = new(); Vls64_vlsseg6e32_v_cg.set_inst_name("obj_Vls64_vlsseg6e32_v");
    Vls64_vlsseg6e64_v_cg = new(); Vls64_vlsseg6e64_v_cg.set_inst_name("obj_Vls64_vlsseg6e64_v");
    Vls64_vlsseg6e8_v_cg = new(); Vls64_vlsseg6e8_v_cg.set_inst_name("obj_Vls64_vlsseg6e8_v");
    Vls64_vlsseg7e16_v_cg = new(); Vls64_vlsseg7e16_v_cg.set_inst_name("obj_Vls64_vlsseg7e16_v");
    Vls64_vlsseg7e32_v_cg = new(); Vls64_vlsseg7e32_v_cg.set_inst_name("obj_Vls64_vlsseg7e32_v");
    Vls64_vlsseg7e64_v_cg = new(); Vls64_vlsseg7e64_v_cg.set_inst_name("obj_Vls64_vlsseg7e64_v");
    Vls64_vlsseg7e8_v_cg = new(); Vls64_vlsseg7e8_v_cg.set_inst_name("obj_Vls64_vlsseg7e8_v");
    Vls64_vlsseg8e16_v_cg = new(); Vls64_vlsseg8e16_v_cg.set_inst_name("obj_Vls64_vlsseg8e16_v");
    Vls64_vlsseg8e32_v_cg = new(); Vls64_vlsseg8e32_v_cg.set_inst_name("obj_Vls64_vlsseg8e32_v");
    Vls64_vlsseg8e64_v_cg = new(); Vls64_vlsseg8e64_v_cg.set_inst_name("obj_Vls64_vlsseg8e64_v");
    Vls64_vlsseg8e8_v_cg = new(); Vls64_vlsseg8e8_v_cg.set_inst_name("obj_Vls64_vlsseg8e8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxei16_v_cg = new(); Vls64_vluxei16_v_cg.set_inst_name("obj_Vls64_vluxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxei32_v_cg = new(); Vls64_vluxei32_v_cg.set_inst_name("obj_Vls64_vluxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxei64_v_cg = new(); Vls64_vluxei64_v_cg.set_inst_name("obj_Vls64_vluxei64_v");
`endif
    Vls64_vluxei8_v_cg = new(); Vls64_vluxei8_v_cg.set_inst_name("obj_Vls64_vluxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg2ei16_v_cg = new(); Vls64_vluxseg2ei16_v_cg.set_inst_name("obj_Vls64_vluxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg2ei32_v_cg = new(); Vls64_vluxseg2ei32_v_cg.set_inst_name("obj_Vls64_vluxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg2ei64_v_cg = new(); Vls64_vluxseg2ei64_v_cg.set_inst_name("obj_Vls64_vluxseg2ei64_v");
`endif
    Vls64_vluxseg2ei8_v_cg = new(); Vls64_vluxseg2ei8_v_cg.set_inst_name("obj_Vls64_vluxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg3ei16_v_cg = new(); Vls64_vluxseg3ei16_v_cg.set_inst_name("obj_Vls64_vluxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg3ei32_v_cg = new(); Vls64_vluxseg3ei32_v_cg.set_inst_name("obj_Vls64_vluxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg3ei64_v_cg = new(); Vls64_vluxseg3ei64_v_cg.set_inst_name("obj_Vls64_vluxseg3ei64_v");
`endif
    Vls64_vluxseg3ei8_v_cg = new(); Vls64_vluxseg3ei8_v_cg.set_inst_name("obj_Vls64_vluxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg4ei16_v_cg = new(); Vls64_vluxseg4ei16_v_cg.set_inst_name("obj_Vls64_vluxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg4ei32_v_cg = new(); Vls64_vluxseg4ei32_v_cg.set_inst_name("obj_Vls64_vluxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg4ei64_v_cg = new(); Vls64_vluxseg4ei64_v_cg.set_inst_name("obj_Vls64_vluxseg4ei64_v");
`endif
    Vls64_vluxseg4ei8_v_cg = new(); Vls64_vluxseg4ei8_v_cg.set_inst_name("obj_Vls64_vluxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg5ei16_v_cg = new(); Vls64_vluxseg5ei16_v_cg.set_inst_name("obj_Vls64_vluxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg5ei32_v_cg = new(); Vls64_vluxseg5ei32_v_cg.set_inst_name("obj_Vls64_vluxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg5ei64_v_cg = new(); Vls64_vluxseg5ei64_v_cg.set_inst_name("obj_Vls64_vluxseg5ei64_v");
`endif
    Vls64_vluxseg5ei8_v_cg = new(); Vls64_vluxseg5ei8_v_cg.set_inst_name("obj_Vls64_vluxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg6ei16_v_cg = new(); Vls64_vluxseg6ei16_v_cg.set_inst_name("obj_Vls64_vluxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg6ei32_v_cg = new(); Vls64_vluxseg6ei32_v_cg.set_inst_name("obj_Vls64_vluxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg6ei64_v_cg = new(); Vls64_vluxseg6ei64_v_cg.set_inst_name("obj_Vls64_vluxseg6ei64_v");
`endif
    Vls64_vluxseg6ei8_v_cg = new(); Vls64_vluxseg6ei8_v_cg.set_inst_name("obj_Vls64_vluxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg7ei16_v_cg = new(); Vls64_vluxseg7ei16_v_cg.set_inst_name("obj_Vls64_vluxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg7ei32_v_cg = new(); Vls64_vluxseg7ei32_v_cg.set_inst_name("obj_Vls64_vluxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg7ei64_v_cg = new(); Vls64_vluxseg7ei64_v_cg.set_inst_name("obj_Vls64_vluxseg7ei64_v");
`endif
    Vls64_vluxseg7ei8_v_cg = new(); Vls64_vluxseg7ei8_v_cg.set_inst_name("obj_Vls64_vluxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vluxseg8ei16_v_cg = new(); Vls64_vluxseg8ei16_v_cg.set_inst_name("obj_Vls64_vluxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vluxseg8ei32_v_cg = new(); Vls64_vluxseg8ei32_v_cg.set_inst_name("obj_Vls64_vluxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vluxseg8ei64_v_cg = new(); Vls64_vluxseg8ei64_v_cg.set_inst_name("obj_Vls64_vluxseg8ei64_v");
`endif
    Vls64_vluxseg8ei8_v_cg = new(); Vls64_vluxseg8ei8_v_cg.set_inst_name("obj_Vls64_vluxseg8ei8_v");
    Vls64_vs1r_v_cg = new(); Vls64_vs1r_v_cg.set_inst_name("obj_Vls64_vs1r_v");
    Vls64_vs2r_v_cg = new(); Vls64_vs2r_v_cg.set_inst_name("obj_Vls64_vs2r_v");
    Vls64_vs4r_v_cg = new(); Vls64_vs4r_v_cg.set_inst_name("obj_Vls64_vs4r_v");
    Vls64_vs8r_v_cg = new(); Vls64_vs8r_v_cg.set_inst_name("obj_Vls64_vs8r_v");
    Vls64_vse16_v_cg = new(); Vls64_vse16_v_cg.set_inst_name("obj_Vls64_vse16_v");
    Vls64_vse32_v_cg = new(); Vls64_vse32_v_cg.set_inst_name("obj_Vls64_vse32_v");
    Vls64_vse64_v_cg = new(); Vls64_vse64_v_cg.set_inst_name("obj_Vls64_vse64_v");
    Vls64_vse8_v_cg = new(); Vls64_vse8_v_cg.set_inst_name("obj_Vls64_vse8_v");
    Vls64_vsm_v_cg = new(); Vls64_vsm_v_cg.set_inst_name("obj_Vls64_vsm_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxei16_v_cg = new(); Vls64_vsoxei16_v_cg.set_inst_name("obj_Vls64_vsoxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxei32_v_cg = new(); Vls64_vsoxei32_v_cg.set_inst_name("obj_Vls64_vsoxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxei64_v_cg = new(); Vls64_vsoxei64_v_cg.set_inst_name("obj_Vls64_vsoxei64_v");
`endif
    Vls64_vsoxei8_v_cg = new(); Vls64_vsoxei8_v_cg.set_inst_name("obj_Vls64_vsoxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg2ei16_v_cg = new(); Vls64_vsoxseg2ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg2ei32_v_cg = new(); Vls64_vsoxseg2ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg2ei64_v_cg = new(); Vls64_vsoxseg2ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg2ei64_v");
`endif
    Vls64_vsoxseg2ei8_v_cg = new(); Vls64_vsoxseg2ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg3ei16_v_cg = new(); Vls64_vsoxseg3ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg3ei32_v_cg = new(); Vls64_vsoxseg3ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg3ei64_v_cg = new(); Vls64_vsoxseg3ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg3ei64_v");
`endif
    Vls64_vsoxseg3ei8_v_cg = new(); Vls64_vsoxseg3ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg4ei16_v_cg = new(); Vls64_vsoxseg4ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg4ei32_v_cg = new(); Vls64_vsoxseg4ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg4ei64_v_cg = new(); Vls64_vsoxseg4ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg4ei64_v");
`endif
    Vls64_vsoxseg4ei8_v_cg = new(); Vls64_vsoxseg4ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg5ei16_v_cg = new(); Vls64_vsoxseg5ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg5ei32_v_cg = new(); Vls64_vsoxseg5ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg5ei64_v_cg = new(); Vls64_vsoxseg5ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg5ei64_v");
`endif
    Vls64_vsoxseg5ei8_v_cg = new(); Vls64_vsoxseg5ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg6ei16_v_cg = new(); Vls64_vsoxseg6ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg6ei32_v_cg = new(); Vls64_vsoxseg6ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg6ei64_v_cg = new(); Vls64_vsoxseg6ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg6ei64_v");
`endif
    Vls64_vsoxseg6ei8_v_cg = new(); Vls64_vsoxseg6ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg7ei16_v_cg = new(); Vls64_vsoxseg7ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg7ei32_v_cg = new(); Vls64_vsoxseg7ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg7ei64_v_cg = new(); Vls64_vsoxseg7ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg7ei64_v");
`endif
    Vls64_vsoxseg7ei8_v_cg = new(); Vls64_vsoxseg7ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsoxseg8ei16_v_cg = new(); Vls64_vsoxseg8ei16_v_cg.set_inst_name("obj_Vls64_vsoxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsoxseg8ei32_v_cg = new(); Vls64_vsoxseg8ei32_v_cg.set_inst_name("obj_Vls64_vsoxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsoxseg8ei64_v_cg = new(); Vls64_vsoxseg8ei64_v_cg.set_inst_name("obj_Vls64_vsoxseg8ei64_v");
`endif
    Vls64_vsoxseg8ei8_v_cg = new(); Vls64_vsoxseg8ei8_v_cg.set_inst_name("obj_Vls64_vsoxseg8ei8_v");
    Vls64_vsse16_v_cg = new(); Vls64_vsse16_v_cg.set_inst_name("obj_Vls64_vsse16_v");
    Vls64_vsse32_v_cg = new(); Vls64_vsse32_v_cg.set_inst_name("obj_Vls64_vsse32_v");
    Vls64_vsse64_v_cg = new(); Vls64_vsse64_v_cg.set_inst_name("obj_Vls64_vsse64_v");
    Vls64_vsse8_v_cg = new(); Vls64_vsse8_v_cg.set_inst_name("obj_Vls64_vsse8_v");
    Vls64_vsseg2e16_v_cg = new(); Vls64_vsseg2e16_v_cg.set_inst_name("obj_Vls64_vsseg2e16_v");
    Vls64_vsseg2e32_v_cg = new(); Vls64_vsseg2e32_v_cg.set_inst_name("obj_Vls64_vsseg2e32_v");
    Vls64_vsseg2e64_v_cg = new(); Vls64_vsseg2e64_v_cg.set_inst_name("obj_Vls64_vsseg2e64_v");
    Vls64_vsseg2e8_v_cg = new(); Vls64_vsseg2e8_v_cg.set_inst_name("obj_Vls64_vsseg2e8_v");
    Vls64_vsseg3e16_v_cg = new(); Vls64_vsseg3e16_v_cg.set_inst_name("obj_Vls64_vsseg3e16_v");
    Vls64_vsseg3e32_v_cg = new(); Vls64_vsseg3e32_v_cg.set_inst_name("obj_Vls64_vsseg3e32_v");
    Vls64_vsseg3e64_v_cg = new(); Vls64_vsseg3e64_v_cg.set_inst_name("obj_Vls64_vsseg3e64_v");
    Vls64_vsseg3e8_v_cg = new(); Vls64_vsseg3e8_v_cg.set_inst_name("obj_Vls64_vsseg3e8_v");
    Vls64_vsseg4e16_v_cg = new(); Vls64_vsseg4e16_v_cg.set_inst_name("obj_Vls64_vsseg4e16_v");
    Vls64_vsseg4e32_v_cg = new(); Vls64_vsseg4e32_v_cg.set_inst_name("obj_Vls64_vsseg4e32_v");
    Vls64_vsseg4e64_v_cg = new(); Vls64_vsseg4e64_v_cg.set_inst_name("obj_Vls64_vsseg4e64_v");
    Vls64_vsseg4e8_v_cg = new(); Vls64_vsseg4e8_v_cg.set_inst_name("obj_Vls64_vsseg4e8_v");
    Vls64_vsseg5e16_v_cg = new(); Vls64_vsseg5e16_v_cg.set_inst_name("obj_Vls64_vsseg5e16_v");
    Vls64_vsseg5e32_v_cg = new(); Vls64_vsseg5e32_v_cg.set_inst_name("obj_Vls64_vsseg5e32_v");
    Vls64_vsseg5e64_v_cg = new(); Vls64_vsseg5e64_v_cg.set_inst_name("obj_Vls64_vsseg5e64_v");
    Vls64_vsseg5e8_v_cg = new(); Vls64_vsseg5e8_v_cg.set_inst_name("obj_Vls64_vsseg5e8_v");
    Vls64_vsseg6e16_v_cg = new(); Vls64_vsseg6e16_v_cg.set_inst_name("obj_Vls64_vsseg6e16_v");
    Vls64_vsseg6e32_v_cg = new(); Vls64_vsseg6e32_v_cg.set_inst_name("obj_Vls64_vsseg6e32_v");
    Vls64_vsseg6e64_v_cg = new(); Vls64_vsseg6e64_v_cg.set_inst_name("obj_Vls64_vsseg6e64_v");
    Vls64_vsseg6e8_v_cg = new(); Vls64_vsseg6e8_v_cg.set_inst_name("obj_Vls64_vsseg6e8_v");
    Vls64_vsseg7e16_v_cg = new(); Vls64_vsseg7e16_v_cg.set_inst_name("obj_Vls64_vsseg7e16_v");
    Vls64_vsseg7e32_v_cg = new(); Vls64_vsseg7e32_v_cg.set_inst_name("obj_Vls64_vsseg7e32_v");
    Vls64_vsseg7e64_v_cg = new(); Vls64_vsseg7e64_v_cg.set_inst_name("obj_Vls64_vsseg7e64_v");
    Vls64_vsseg7e8_v_cg = new(); Vls64_vsseg7e8_v_cg.set_inst_name("obj_Vls64_vsseg7e8_v");
    Vls64_vsseg8e16_v_cg = new(); Vls64_vsseg8e16_v_cg.set_inst_name("obj_Vls64_vsseg8e16_v");
    Vls64_vsseg8e32_v_cg = new(); Vls64_vsseg8e32_v_cg.set_inst_name("obj_Vls64_vsseg8e32_v");
    Vls64_vsseg8e64_v_cg = new(); Vls64_vsseg8e64_v_cg.set_inst_name("obj_Vls64_vsseg8e64_v");
    Vls64_vsseg8e8_v_cg = new(); Vls64_vsseg8e8_v_cg.set_inst_name("obj_Vls64_vsseg8e8_v");
    Vls64_vssseg2e16_v_cg = new(); Vls64_vssseg2e16_v_cg.set_inst_name("obj_Vls64_vssseg2e16_v");
    Vls64_vssseg2e32_v_cg = new(); Vls64_vssseg2e32_v_cg.set_inst_name("obj_Vls64_vssseg2e32_v");
    Vls64_vssseg2e64_v_cg = new(); Vls64_vssseg2e64_v_cg.set_inst_name("obj_Vls64_vssseg2e64_v");
    Vls64_vssseg2e8_v_cg = new(); Vls64_vssseg2e8_v_cg.set_inst_name("obj_Vls64_vssseg2e8_v");
    Vls64_vssseg3e16_v_cg = new(); Vls64_vssseg3e16_v_cg.set_inst_name("obj_Vls64_vssseg3e16_v");
    Vls64_vssseg3e32_v_cg = new(); Vls64_vssseg3e32_v_cg.set_inst_name("obj_Vls64_vssseg3e32_v");
    Vls64_vssseg3e64_v_cg = new(); Vls64_vssseg3e64_v_cg.set_inst_name("obj_Vls64_vssseg3e64_v");
    Vls64_vssseg3e8_v_cg = new(); Vls64_vssseg3e8_v_cg.set_inst_name("obj_Vls64_vssseg3e8_v");
    Vls64_vssseg4e16_v_cg = new(); Vls64_vssseg4e16_v_cg.set_inst_name("obj_Vls64_vssseg4e16_v");
    Vls64_vssseg4e32_v_cg = new(); Vls64_vssseg4e32_v_cg.set_inst_name("obj_Vls64_vssseg4e32_v");
    Vls64_vssseg4e64_v_cg = new(); Vls64_vssseg4e64_v_cg.set_inst_name("obj_Vls64_vssseg4e64_v");
    Vls64_vssseg4e8_v_cg = new(); Vls64_vssseg4e8_v_cg.set_inst_name("obj_Vls64_vssseg4e8_v");
    Vls64_vssseg5e16_v_cg = new(); Vls64_vssseg5e16_v_cg.set_inst_name("obj_Vls64_vssseg5e16_v");
    Vls64_vssseg5e32_v_cg = new(); Vls64_vssseg5e32_v_cg.set_inst_name("obj_Vls64_vssseg5e32_v");
    Vls64_vssseg5e64_v_cg = new(); Vls64_vssseg5e64_v_cg.set_inst_name("obj_Vls64_vssseg5e64_v");
    Vls64_vssseg5e8_v_cg = new(); Vls64_vssseg5e8_v_cg.set_inst_name("obj_Vls64_vssseg5e8_v");
    Vls64_vssseg6e16_v_cg = new(); Vls64_vssseg6e16_v_cg.set_inst_name("obj_Vls64_vssseg6e16_v");
    Vls64_vssseg6e32_v_cg = new(); Vls64_vssseg6e32_v_cg.set_inst_name("obj_Vls64_vssseg6e32_v");
    Vls64_vssseg6e64_v_cg = new(); Vls64_vssseg6e64_v_cg.set_inst_name("obj_Vls64_vssseg6e64_v");
    Vls64_vssseg6e8_v_cg = new(); Vls64_vssseg6e8_v_cg.set_inst_name("obj_Vls64_vssseg6e8_v");
    Vls64_vssseg7e16_v_cg = new(); Vls64_vssseg7e16_v_cg.set_inst_name("obj_Vls64_vssseg7e16_v");
    Vls64_vssseg7e32_v_cg = new(); Vls64_vssseg7e32_v_cg.set_inst_name("obj_Vls64_vssseg7e32_v");
    Vls64_vssseg7e64_v_cg = new(); Vls64_vssseg7e64_v_cg.set_inst_name("obj_Vls64_vssseg7e64_v");
    Vls64_vssseg7e8_v_cg = new(); Vls64_vssseg7e8_v_cg.set_inst_name("obj_Vls64_vssseg7e8_v");
    Vls64_vssseg8e16_v_cg = new(); Vls64_vssseg8e16_v_cg.set_inst_name("obj_Vls64_vssseg8e16_v");
    Vls64_vssseg8e32_v_cg = new(); Vls64_vssseg8e32_v_cg.set_inst_name("obj_Vls64_vssseg8e32_v");
    Vls64_vssseg8e64_v_cg = new(); Vls64_vssseg8e64_v_cg.set_inst_name("obj_Vls64_vssseg8e64_v");
    Vls64_vssseg8e8_v_cg = new(); Vls64_vssseg8e8_v_cg.set_inst_name("obj_Vls64_vssseg8e8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxei16_v_cg = new(); Vls64_vsuxei16_v_cg.set_inst_name("obj_Vls64_vsuxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxei32_v_cg = new(); Vls64_vsuxei32_v_cg.set_inst_name("obj_Vls64_vsuxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxei64_v_cg = new(); Vls64_vsuxei64_v_cg.set_inst_name("obj_Vls64_vsuxei64_v");
`endif
    Vls64_vsuxei8_v_cg = new(); Vls64_vsuxei8_v_cg.set_inst_name("obj_Vls64_vsuxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg2ei16_v_cg = new(); Vls64_vsuxseg2ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg2ei32_v_cg = new(); Vls64_vsuxseg2ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg2ei64_v_cg = new(); Vls64_vsuxseg2ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg2ei64_v");
`endif
    Vls64_vsuxseg2ei8_v_cg = new(); Vls64_vsuxseg2ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg3ei16_v_cg = new(); Vls64_vsuxseg3ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg3ei32_v_cg = new(); Vls64_vsuxseg3ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg3ei64_v_cg = new(); Vls64_vsuxseg3ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg3ei64_v");
`endif
    Vls64_vsuxseg3ei8_v_cg = new(); Vls64_vsuxseg3ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg4ei16_v_cg = new(); Vls64_vsuxseg4ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg4ei32_v_cg = new(); Vls64_vsuxseg4ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg4ei64_v_cg = new(); Vls64_vsuxseg4ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg4ei64_v");
`endif
    Vls64_vsuxseg4ei8_v_cg = new(); Vls64_vsuxseg4ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg5ei16_v_cg = new(); Vls64_vsuxseg5ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg5ei32_v_cg = new(); Vls64_vsuxseg5ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg5ei64_v_cg = new(); Vls64_vsuxseg5ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg5ei64_v");
`endif
    Vls64_vsuxseg5ei8_v_cg = new(); Vls64_vsuxseg5ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg6ei16_v_cg = new(); Vls64_vsuxseg6ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg6ei32_v_cg = new(); Vls64_vsuxseg6ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg6ei64_v_cg = new(); Vls64_vsuxseg6ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg6ei64_v");
`endif
    Vls64_vsuxseg6ei8_v_cg = new(); Vls64_vsuxseg6ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg7ei16_v_cg = new(); Vls64_vsuxseg7ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg7ei32_v_cg = new(); Vls64_vsuxseg7ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg7ei64_v_cg = new(); Vls64_vsuxseg7ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg7ei64_v");
`endif
    Vls64_vsuxseg7ei8_v_cg = new(); Vls64_vsuxseg7ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls64_vsuxseg8ei16_v_cg = new(); Vls64_vsuxseg8ei16_v_cg.set_inst_name("obj_Vls64_vsuxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls64_vsuxseg8ei32_v_cg = new(); Vls64_vsuxseg8ei32_v_cg.set_inst_name("obj_Vls64_vsuxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls64_vsuxseg8ei64_v_cg = new(); Vls64_vsuxseg8ei64_v_cg.set_inst_name("obj_Vls64_vsuxseg8ei64_v");
`endif
    Vls64_vsuxseg8ei8_v_cg = new(); Vls64_vsuxseg8ei8_v_cg.set_inst_name("obj_Vls64_vsuxseg8ei8_v");
