///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Vls8_vl1re16_v_cg = new(); Vls8_vl1re16_v_cg.set_inst_name("obj_Vls8_vl1re16_v");
    Vls8_vl1re32_v_cg = new(); Vls8_vl1re32_v_cg.set_inst_name("obj_Vls8_vl1re32_v");
    Vls8_vl1re64_v_cg = new(); Vls8_vl1re64_v_cg.set_inst_name("obj_Vls8_vl1re64_v");
    Vls8_vl1re8_v_cg = new(); Vls8_vl1re8_v_cg.set_inst_name("obj_Vls8_vl1re8_v");
    Vls8_vl2re16_v_cg = new(); Vls8_vl2re16_v_cg.set_inst_name("obj_Vls8_vl2re16_v");
    Vls8_vl2re32_v_cg = new(); Vls8_vl2re32_v_cg.set_inst_name("obj_Vls8_vl2re32_v");
    Vls8_vl2re64_v_cg = new(); Vls8_vl2re64_v_cg.set_inst_name("obj_Vls8_vl2re64_v");
    Vls8_vl2re8_v_cg = new(); Vls8_vl2re8_v_cg.set_inst_name("obj_Vls8_vl2re8_v");
    Vls8_vl4re16_v_cg = new(); Vls8_vl4re16_v_cg.set_inst_name("obj_Vls8_vl4re16_v");
    Vls8_vl4re32_v_cg = new(); Vls8_vl4re32_v_cg.set_inst_name("obj_Vls8_vl4re32_v");
    Vls8_vl4re64_v_cg = new(); Vls8_vl4re64_v_cg.set_inst_name("obj_Vls8_vl4re64_v");
    Vls8_vl4re8_v_cg = new(); Vls8_vl4re8_v_cg.set_inst_name("obj_Vls8_vl4re8_v");
    Vls8_vl8re16_v_cg = new(); Vls8_vl8re16_v_cg.set_inst_name("obj_Vls8_vl8re16_v");
    Vls8_vl8re32_v_cg = new(); Vls8_vl8re32_v_cg.set_inst_name("obj_Vls8_vl8re32_v");
    Vls8_vl8re64_v_cg = new(); Vls8_vl8re64_v_cg.set_inst_name("obj_Vls8_vl8re64_v");
    Vls8_vl8re8_v_cg = new(); Vls8_vl8re8_v_cg.set_inst_name("obj_Vls8_vl8re8_v");
    Vls8_vle16_v_cg = new(); Vls8_vle16_v_cg.set_inst_name("obj_Vls8_vle16_v");
    Vls8_vle16ff_v_cg = new(); Vls8_vle16ff_v_cg.set_inst_name("obj_Vls8_vle16ff_v");
    Vls8_vle32_v_cg = new(); Vls8_vle32_v_cg.set_inst_name("obj_Vls8_vle32_v");
    Vls8_vle32ff_v_cg = new(); Vls8_vle32ff_v_cg.set_inst_name("obj_Vls8_vle32ff_v");
    Vls8_vle64_v_cg = new(); Vls8_vle64_v_cg.set_inst_name("obj_Vls8_vle64_v");
    Vls8_vle64ff_v_cg = new(); Vls8_vle64ff_v_cg.set_inst_name("obj_Vls8_vle64ff_v");
    Vls8_vle8_v_cg = new(); Vls8_vle8_v_cg.set_inst_name("obj_Vls8_vle8_v");
    Vls8_vle8ff_v_cg = new(); Vls8_vle8ff_v_cg.set_inst_name("obj_Vls8_vle8ff_v");
    Vls8_vlm_v_cg = new(); Vls8_vlm_v_cg.set_inst_name("obj_Vls8_vlm_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxei16_v_cg = new(); Vls8_vloxei16_v_cg.set_inst_name("obj_Vls8_vloxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxei32_v_cg = new(); Vls8_vloxei32_v_cg.set_inst_name("obj_Vls8_vloxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxei64_v_cg = new(); Vls8_vloxei64_v_cg.set_inst_name("obj_Vls8_vloxei64_v");
`endif
    Vls8_vloxei8_v_cg = new(); Vls8_vloxei8_v_cg.set_inst_name("obj_Vls8_vloxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg2ei16_v_cg = new(); Vls8_vloxseg2ei16_v_cg.set_inst_name("obj_Vls8_vloxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg2ei32_v_cg = new(); Vls8_vloxseg2ei32_v_cg.set_inst_name("obj_Vls8_vloxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg2ei64_v_cg = new(); Vls8_vloxseg2ei64_v_cg.set_inst_name("obj_Vls8_vloxseg2ei64_v");
`endif
    Vls8_vloxseg2ei8_v_cg = new(); Vls8_vloxseg2ei8_v_cg.set_inst_name("obj_Vls8_vloxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg3ei16_v_cg = new(); Vls8_vloxseg3ei16_v_cg.set_inst_name("obj_Vls8_vloxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg3ei32_v_cg = new(); Vls8_vloxseg3ei32_v_cg.set_inst_name("obj_Vls8_vloxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg3ei64_v_cg = new(); Vls8_vloxseg3ei64_v_cg.set_inst_name("obj_Vls8_vloxseg3ei64_v");
`endif
    Vls8_vloxseg3ei8_v_cg = new(); Vls8_vloxseg3ei8_v_cg.set_inst_name("obj_Vls8_vloxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg4ei16_v_cg = new(); Vls8_vloxseg4ei16_v_cg.set_inst_name("obj_Vls8_vloxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg4ei32_v_cg = new(); Vls8_vloxseg4ei32_v_cg.set_inst_name("obj_Vls8_vloxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg4ei64_v_cg = new(); Vls8_vloxseg4ei64_v_cg.set_inst_name("obj_Vls8_vloxseg4ei64_v");
`endif
    Vls8_vloxseg4ei8_v_cg = new(); Vls8_vloxseg4ei8_v_cg.set_inst_name("obj_Vls8_vloxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg5ei16_v_cg = new(); Vls8_vloxseg5ei16_v_cg.set_inst_name("obj_Vls8_vloxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg5ei32_v_cg = new(); Vls8_vloxseg5ei32_v_cg.set_inst_name("obj_Vls8_vloxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg5ei64_v_cg = new(); Vls8_vloxseg5ei64_v_cg.set_inst_name("obj_Vls8_vloxseg5ei64_v");
`endif
    Vls8_vloxseg5ei8_v_cg = new(); Vls8_vloxseg5ei8_v_cg.set_inst_name("obj_Vls8_vloxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg6ei16_v_cg = new(); Vls8_vloxseg6ei16_v_cg.set_inst_name("obj_Vls8_vloxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg6ei32_v_cg = new(); Vls8_vloxseg6ei32_v_cg.set_inst_name("obj_Vls8_vloxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg6ei64_v_cg = new(); Vls8_vloxseg6ei64_v_cg.set_inst_name("obj_Vls8_vloxseg6ei64_v");
`endif
    Vls8_vloxseg6ei8_v_cg = new(); Vls8_vloxseg6ei8_v_cg.set_inst_name("obj_Vls8_vloxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg7ei16_v_cg = new(); Vls8_vloxseg7ei16_v_cg.set_inst_name("obj_Vls8_vloxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg7ei32_v_cg = new(); Vls8_vloxseg7ei32_v_cg.set_inst_name("obj_Vls8_vloxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg7ei64_v_cg = new(); Vls8_vloxseg7ei64_v_cg.set_inst_name("obj_Vls8_vloxseg7ei64_v");
`endif
    Vls8_vloxseg7ei8_v_cg = new(); Vls8_vloxseg7ei8_v_cg.set_inst_name("obj_Vls8_vloxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vloxseg8ei16_v_cg = new(); Vls8_vloxseg8ei16_v_cg.set_inst_name("obj_Vls8_vloxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vloxseg8ei32_v_cg = new(); Vls8_vloxseg8ei32_v_cg.set_inst_name("obj_Vls8_vloxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vloxseg8ei64_v_cg = new(); Vls8_vloxseg8ei64_v_cg.set_inst_name("obj_Vls8_vloxseg8ei64_v");
`endif
    Vls8_vloxseg8ei8_v_cg = new(); Vls8_vloxseg8ei8_v_cg.set_inst_name("obj_Vls8_vloxseg8ei8_v");
    Vls8_vlse16_v_cg = new(); Vls8_vlse16_v_cg.set_inst_name("obj_Vls8_vlse16_v");
    Vls8_vlse32_v_cg = new(); Vls8_vlse32_v_cg.set_inst_name("obj_Vls8_vlse32_v");
    Vls8_vlse64_v_cg = new(); Vls8_vlse64_v_cg.set_inst_name("obj_Vls8_vlse64_v");
    Vls8_vlse8_v_cg = new(); Vls8_vlse8_v_cg.set_inst_name("obj_Vls8_vlse8_v");
    Vls8_vlseg2e16_v_cg = new(); Vls8_vlseg2e16_v_cg.set_inst_name("obj_Vls8_vlseg2e16_v");
    Vls8_vlseg2e16ff_v_cg = new(); Vls8_vlseg2e16ff_v_cg.set_inst_name("obj_Vls8_vlseg2e16ff_v");
    Vls8_vlseg2e32_v_cg = new(); Vls8_vlseg2e32_v_cg.set_inst_name("obj_Vls8_vlseg2e32_v");
    Vls8_vlseg2e32ff_v_cg = new(); Vls8_vlseg2e32ff_v_cg.set_inst_name("obj_Vls8_vlseg2e32ff_v");
    Vls8_vlseg2e8_v_cg = new(); Vls8_vlseg2e8_v_cg.set_inst_name("obj_Vls8_vlseg2e8_v");
    Vls8_vlseg2e8ff_v_cg = new(); Vls8_vlseg2e8ff_v_cg.set_inst_name("obj_Vls8_vlseg2e8ff_v");
    Vls8_vlseg3e16_v_cg = new(); Vls8_vlseg3e16_v_cg.set_inst_name("obj_Vls8_vlseg3e16_v");
    Vls8_vlseg3e16ff_v_cg = new(); Vls8_vlseg3e16ff_v_cg.set_inst_name("obj_Vls8_vlseg3e16ff_v");
    Vls8_vlseg3e8_v_cg = new(); Vls8_vlseg3e8_v_cg.set_inst_name("obj_Vls8_vlseg3e8_v");
    Vls8_vlseg3e8ff_v_cg = new(); Vls8_vlseg3e8ff_v_cg.set_inst_name("obj_Vls8_vlseg3e8ff_v");
    Vls8_vlseg4e16_v_cg = new(); Vls8_vlseg4e16_v_cg.set_inst_name("obj_Vls8_vlseg4e16_v");
    Vls8_vlseg4e16ff_v_cg = new(); Vls8_vlseg4e16ff_v_cg.set_inst_name("obj_Vls8_vlseg4e16ff_v");
    Vls8_vlseg4e8_v_cg = new(); Vls8_vlseg4e8_v_cg.set_inst_name("obj_Vls8_vlseg4e8_v");
    Vls8_vlseg4e8ff_v_cg = new(); Vls8_vlseg4e8ff_v_cg.set_inst_name("obj_Vls8_vlseg4e8ff_v");
    Vls8_vlseg5e8_v_cg = new(); Vls8_vlseg5e8_v_cg.set_inst_name("obj_Vls8_vlseg5e8_v");
    Vls8_vlseg5e8ff_v_cg = new(); Vls8_vlseg5e8ff_v_cg.set_inst_name("obj_Vls8_vlseg5e8ff_v");
    Vls8_vlseg6e8_v_cg = new(); Vls8_vlseg6e8_v_cg.set_inst_name("obj_Vls8_vlseg6e8_v");
    Vls8_vlseg6e8ff_v_cg = new(); Vls8_vlseg6e8ff_v_cg.set_inst_name("obj_Vls8_vlseg6e8ff_v");
    Vls8_vlseg7e8_v_cg = new(); Vls8_vlseg7e8_v_cg.set_inst_name("obj_Vls8_vlseg7e8_v");
    Vls8_vlseg7e8ff_v_cg = new(); Vls8_vlseg7e8ff_v_cg.set_inst_name("obj_Vls8_vlseg7e8ff_v");
    Vls8_vlseg8e8_v_cg = new(); Vls8_vlseg8e8_v_cg.set_inst_name("obj_Vls8_vlseg8e8_v");
    Vls8_vlseg8e8ff_v_cg = new(); Vls8_vlseg8e8ff_v_cg.set_inst_name("obj_Vls8_vlseg8e8ff_v");
    Vls8_vlsseg2e16_v_cg = new(); Vls8_vlsseg2e16_v_cg.set_inst_name("obj_Vls8_vlsseg2e16_v");
    Vls8_vlsseg2e32_v_cg = new(); Vls8_vlsseg2e32_v_cg.set_inst_name("obj_Vls8_vlsseg2e32_v");
    Vls8_vlsseg2e8_v_cg = new(); Vls8_vlsseg2e8_v_cg.set_inst_name("obj_Vls8_vlsseg2e8_v");
    Vls8_vlsseg3e16_v_cg = new(); Vls8_vlsseg3e16_v_cg.set_inst_name("obj_Vls8_vlsseg3e16_v");
    Vls8_vlsseg3e8_v_cg = new(); Vls8_vlsseg3e8_v_cg.set_inst_name("obj_Vls8_vlsseg3e8_v");
    Vls8_vlsseg4e16_v_cg = new(); Vls8_vlsseg4e16_v_cg.set_inst_name("obj_Vls8_vlsseg4e16_v");
    Vls8_vlsseg4e8_v_cg = new(); Vls8_vlsseg4e8_v_cg.set_inst_name("obj_Vls8_vlsseg4e8_v");
    Vls8_vlsseg5e8_v_cg = new(); Vls8_vlsseg5e8_v_cg.set_inst_name("obj_Vls8_vlsseg5e8_v");
    Vls8_vlsseg6e8_v_cg = new(); Vls8_vlsseg6e8_v_cg.set_inst_name("obj_Vls8_vlsseg6e8_v");
    Vls8_vlsseg7e8_v_cg = new(); Vls8_vlsseg7e8_v_cg.set_inst_name("obj_Vls8_vlsseg7e8_v");
    Vls8_vlsseg8e8_v_cg = new(); Vls8_vlsseg8e8_v_cg.set_inst_name("obj_Vls8_vlsseg8e8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxei16_v_cg = new(); Vls8_vluxei16_v_cg.set_inst_name("obj_Vls8_vluxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxei32_v_cg = new(); Vls8_vluxei32_v_cg.set_inst_name("obj_Vls8_vluxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxei64_v_cg = new(); Vls8_vluxei64_v_cg.set_inst_name("obj_Vls8_vluxei64_v");
`endif
    Vls8_vluxei8_v_cg = new(); Vls8_vluxei8_v_cg.set_inst_name("obj_Vls8_vluxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg2ei16_v_cg = new(); Vls8_vluxseg2ei16_v_cg.set_inst_name("obj_Vls8_vluxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg2ei32_v_cg = new(); Vls8_vluxseg2ei32_v_cg.set_inst_name("obj_Vls8_vluxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg2ei64_v_cg = new(); Vls8_vluxseg2ei64_v_cg.set_inst_name("obj_Vls8_vluxseg2ei64_v");
`endif
    Vls8_vluxseg2ei8_v_cg = new(); Vls8_vluxseg2ei8_v_cg.set_inst_name("obj_Vls8_vluxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg3ei16_v_cg = new(); Vls8_vluxseg3ei16_v_cg.set_inst_name("obj_Vls8_vluxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg3ei32_v_cg = new(); Vls8_vluxseg3ei32_v_cg.set_inst_name("obj_Vls8_vluxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg3ei64_v_cg = new(); Vls8_vluxseg3ei64_v_cg.set_inst_name("obj_Vls8_vluxseg3ei64_v");
`endif
    Vls8_vluxseg3ei8_v_cg = new(); Vls8_vluxseg3ei8_v_cg.set_inst_name("obj_Vls8_vluxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg4ei16_v_cg = new(); Vls8_vluxseg4ei16_v_cg.set_inst_name("obj_Vls8_vluxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg4ei32_v_cg = new(); Vls8_vluxseg4ei32_v_cg.set_inst_name("obj_Vls8_vluxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg4ei64_v_cg = new(); Vls8_vluxseg4ei64_v_cg.set_inst_name("obj_Vls8_vluxseg4ei64_v");
`endif
    Vls8_vluxseg4ei8_v_cg = new(); Vls8_vluxseg4ei8_v_cg.set_inst_name("obj_Vls8_vluxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg5ei16_v_cg = new(); Vls8_vluxseg5ei16_v_cg.set_inst_name("obj_Vls8_vluxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg5ei32_v_cg = new(); Vls8_vluxseg5ei32_v_cg.set_inst_name("obj_Vls8_vluxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg5ei64_v_cg = new(); Vls8_vluxseg5ei64_v_cg.set_inst_name("obj_Vls8_vluxseg5ei64_v");
`endif
    Vls8_vluxseg5ei8_v_cg = new(); Vls8_vluxseg5ei8_v_cg.set_inst_name("obj_Vls8_vluxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg6ei16_v_cg = new(); Vls8_vluxseg6ei16_v_cg.set_inst_name("obj_Vls8_vluxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg6ei32_v_cg = new(); Vls8_vluxseg6ei32_v_cg.set_inst_name("obj_Vls8_vluxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg6ei64_v_cg = new(); Vls8_vluxseg6ei64_v_cg.set_inst_name("obj_Vls8_vluxseg6ei64_v");
`endif
    Vls8_vluxseg6ei8_v_cg = new(); Vls8_vluxseg6ei8_v_cg.set_inst_name("obj_Vls8_vluxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg7ei16_v_cg = new(); Vls8_vluxseg7ei16_v_cg.set_inst_name("obj_Vls8_vluxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg7ei32_v_cg = new(); Vls8_vluxseg7ei32_v_cg.set_inst_name("obj_Vls8_vluxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg7ei64_v_cg = new(); Vls8_vluxseg7ei64_v_cg.set_inst_name("obj_Vls8_vluxseg7ei64_v");
`endif
    Vls8_vluxseg7ei8_v_cg = new(); Vls8_vluxseg7ei8_v_cg.set_inst_name("obj_Vls8_vluxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vluxseg8ei16_v_cg = new(); Vls8_vluxseg8ei16_v_cg.set_inst_name("obj_Vls8_vluxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vluxseg8ei32_v_cg = new(); Vls8_vluxseg8ei32_v_cg.set_inst_name("obj_Vls8_vluxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vluxseg8ei64_v_cg = new(); Vls8_vluxseg8ei64_v_cg.set_inst_name("obj_Vls8_vluxseg8ei64_v");
`endif
    Vls8_vluxseg8ei8_v_cg = new(); Vls8_vluxseg8ei8_v_cg.set_inst_name("obj_Vls8_vluxseg8ei8_v");
    Vls8_vs1r_v_cg = new(); Vls8_vs1r_v_cg.set_inst_name("obj_Vls8_vs1r_v");
    Vls8_vs2r_v_cg = new(); Vls8_vs2r_v_cg.set_inst_name("obj_Vls8_vs2r_v");
    Vls8_vs4r_v_cg = new(); Vls8_vs4r_v_cg.set_inst_name("obj_Vls8_vs4r_v");
    Vls8_vs8r_v_cg = new(); Vls8_vs8r_v_cg.set_inst_name("obj_Vls8_vs8r_v");
    Vls8_vse16_v_cg = new(); Vls8_vse16_v_cg.set_inst_name("obj_Vls8_vse16_v");
    Vls8_vse32_v_cg = new(); Vls8_vse32_v_cg.set_inst_name("obj_Vls8_vse32_v");
    Vls8_vse64_v_cg = new(); Vls8_vse64_v_cg.set_inst_name("obj_Vls8_vse64_v");
    Vls8_vse8_v_cg = new(); Vls8_vse8_v_cg.set_inst_name("obj_Vls8_vse8_v");
    Vls8_vsm_v_cg = new(); Vls8_vsm_v_cg.set_inst_name("obj_Vls8_vsm_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxei16_v_cg = new(); Vls8_vsoxei16_v_cg.set_inst_name("obj_Vls8_vsoxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxei32_v_cg = new(); Vls8_vsoxei32_v_cg.set_inst_name("obj_Vls8_vsoxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxei64_v_cg = new(); Vls8_vsoxei64_v_cg.set_inst_name("obj_Vls8_vsoxei64_v");
`endif
    Vls8_vsoxei8_v_cg = new(); Vls8_vsoxei8_v_cg.set_inst_name("obj_Vls8_vsoxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg2ei16_v_cg = new(); Vls8_vsoxseg2ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg2ei32_v_cg = new(); Vls8_vsoxseg2ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg2ei64_v_cg = new(); Vls8_vsoxseg2ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg2ei64_v");
`endif
    Vls8_vsoxseg2ei8_v_cg = new(); Vls8_vsoxseg2ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg3ei16_v_cg = new(); Vls8_vsoxseg3ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg3ei32_v_cg = new(); Vls8_vsoxseg3ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg3ei64_v_cg = new(); Vls8_vsoxseg3ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg3ei64_v");
`endif
    Vls8_vsoxseg3ei8_v_cg = new(); Vls8_vsoxseg3ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg4ei16_v_cg = new(); Vls8_vsoxseg4ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg4ei32_v_cg = new(); Vls8_vsoxseg4ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg4ei64_v_cg = new(); Vls8_vsoxseg4ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg4ei64_v");
`endif
    Vls8_vsoxseg4ei8_v_cg = new(); Vls8_vsoxseg4ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg5ei16_v_cg = new(); Vls8_vsoxseg5ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg5ei32_v_cg = new(); Vls8_vsoxseg5ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg5ei64_v_cg = new(); Vls8_vsoxseg5ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg5ei64_v");
`endif
    Vls8_vsoxseg5ei8_v_cg = new(); Vls8_vsoxseg5ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg6ei16_v_cg = new(); Vls8_vsoxseg6ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg6ei32_v_cg = new(); Vls8_vsoxseg6ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg6ei64_v_cg = new(); Vls8_vsoxseg6ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg6ei64_v");
`endif
    Vls8_vsoxseg6ei8_v_cg = new(); Vls8_vsoxseg6ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg7ei16_v_cg = new(); Vls8_vsoxseg7ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg7ei32_v_cg = new(); Vls8_vsoxseg7ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg7ei64_v_cg = new(); Vls8_vsoxseg7ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg7ei64_v");
`endif
    Vls8_vsoxseg7ei8_v_cg = new(); Vls8_vsoxseg7ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsoxseg8ei16_v_cg = new(); Vls8_vsoxseg8ei16_v_cg.set_inst_name("obj_Vls8_vsoxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsoxseg8ei32_v_cg = new(); Vls8_vsoxseg8ei32_v_cg.set_inst_name("obj_Vls8_vsoxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsoxseg8ei64_v_cg = new(); Vls8_vsoxseg8ei64_v_cg.set_inst_name("obj_Vls8_vsoxseg8ei64_v");
`endif
    Vls8_vsoxseg8ei8_v_cg = new(); Vls8_vsoxseg8ei8_v_cg.set_inst_name("obj_Vls8_vsoxseg8ei8_v");
    Vls8_vsse16_v_cg = new(); Vls8_vsse16_v_cg.set_inst_name("obj_Vls8_vsse16_v");
    Vls8_vsse32_v_cg = new(); Vls8_vsse32_v_cg.set_inst_name("obj_Vls8_vsse32_v");
    Vls8_vsse64_v_cg = new(); Vls8_vsse64_v_cg.set_inst_name("obj_Vls8_vsse64_v");
    Vls8_vsse8_v_cg = new(); Vls8_vsse8_v_cg.set_inst_name("obj_Vls8_vsse8_v");
    Vls8_vsseg2e16_v_cg = new(); Vls8_vsseg2e16_v_cg.set_inst_name("obj_Vls8_vsseg2e16_v");
    Vls8_vsseg2e32_v_cg = new(); Vls8_vsseg2e32_v_cg.set_inst_name("obj_Vls8_vsseg2e32_v");
    Vls8_vsseg2e8_v_cg = new(); Vls8_vsseg2e8_v_cg.set_inst_name("obj_Vls8_vsseg2e8_v");
    Vls8_vsseg3e16_v_cg = new(); Vls8_vsseg3e16_v_cg.set_inst_name("obj_Vls8_vsseg3e16_v");
    Vls8_vsseg3e8_v_cg = new(); Vls8_vsseg3e8_v_cg.set_inst_name("obj_Vls8_vsseg3e8_v");
    Vls8_vsseg4e16_v_cg = new(); Vls8_vsseg4e16_v_cg.set_inst_name("obj_Vls8_vsseg4e16_v");
    Vls8_vsseg4e8_v_cg = new(); Vls8_vsseg4e8_v_cg.set_inst_name("obj_Vls8_vsseg4e8_v");
    Vls8_vsseg5e8_v_cg = new(); Vls8_vsseg5e8_v_cg.set_inst_name("obj_Vls8_vsseg5e8_v");
    Vls8_vsseg6e8_v_cg = new(); Vls8_vsseg6e8_v_cg.set_inst_name("obj_Vls8_vsseg6e8_v");
    Vls8_vsseg7e8_v_cg = new(); Vls8_vsseg7e8_v_cg.set_inst_name("obj_Vls8_vsseg7e8_v");
    Vls8_vsseg8e8_v_cg = new(); Vls8_vsseg8e8_v_cg.set_inst_name("obj_Vls8_vsseg8e8_v");
    Vls8_vssseg2e16_v_cg = new(); Vls8_vssseg2e16_v_cg.set_inst_name("obj_Vls8_vssseg2e16_v");
    Vls8_vssseg2e32_v_cg = new(); Vls8_vssseg2e32_v_cg.set_inst_name("obj_Vls8_vssseg2e32_v");
    Vls8_vssseg2e8_v_cg = new(); Vls8_vssseg2e8_v_cg.set_inst_name("obj_Vls8_vssseg2e8_v");
    Vls8_vssseg3e16_v_cg = new(); Vls8_vssseg3e16_v_cg.set_inst_name("obj_Vls8_vssseg3e16_v");
    Vls8_vssseg3e8_v_cg = new(); Vls8_vssseg3e8_v_cg.set_inst_name("obj_Vls8_vssseg3e8_v");
    Vls8_vssseg4e16_v_cg = new(); Vls8_vssseg4e16_v_cg.set_inst_name("obj_Vls8_vssseg4e16_v");
    Vls8_vssseg4e8_v_cg = new(); Vls8_vssseg4e8_v_cg.set_inst_name("obj_Vls8_vssseg4e8_v");
    Vls8_vssseg5e8_v_cg = new(); Vls8_vssseg5e8_v_cg.set_inst_name("obj_Vls8_vssseg5e8_v");
    Vls8_vssseg6e8_v_cg = new(); Vls8_vssseg6e8_v_cg.set_inst_name("obj_Vls8_vssseg6e8_v");
    Vls8_vssseg7e8_v_cg = new(); Vls8_vssseg7e8_v_cg.set_inst_name("obj_Vls8_vssseg7e8_v");
    Vls8_vssseg8e8_v_cg = new(); Vls8_vssseg8e8_v_cg.set_inst_name("obj_Vls8_vssseg8e8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxei16_v_cg = new(); Vls8_vsuxei16_v_cg.set_inst_name("obj_Vls8_vsuxei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxei32_v_cg = new(); Vls8_vsuxei32_v_cg.set_inst_name("obj_Vls8_vsuxei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxei64_v_cg = new(); Vls8_vsuxei64_v_cg.set_inst_name("obj_Vls8_vsuxei64_v");
`endif
    Vls8_vsuxei8_v_cg = new(); Vls8_vsuxei8_v_cg.set_inst_name("obj_Vls8_vsuxei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg2ei16_v_cg = new(); Vls8_vsuxseg2ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg2ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg2ei32_v_cg = new(); Vls8_vsuxseg2ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg2ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg2ei64_v_cg = new(); Vls8_vsuxseg2ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg2ei64_v");
`endif
    Vls8_vsuxseg2ei8_v_cg = new(); Vls8_vsuxseg2ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg2ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg3ei16_v_cg = new(); Vls8_vsuxseg3ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg3ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg3ei32_v_cg = new(); Vls8_vsuxseg3ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg3ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg3ei64_v_cg = new(); Vls8_vsuxseg3ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg3ei64_v");
`endif
    Vls8_vsuxseg3ei8_v_cg = new(); Vls8_vsuxseg3ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg3ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg4ei16_v_cg = new(); Vls8_vsuxseg4ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg4ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg4ei32_v_cg = new(); Vls8_vsuxseg4ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg4ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg4ei64_v_cg = new(); Vls8_vsuxseg4ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg4ei64_v");
`endif
    Vls8_vsuxseg4ei8_v_cg = new(); Vls8_vsuxseg4ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg4ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg5ei16_v_cg = new(); Vls8_vsuxseg5ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg5ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg5ei32_v_cg = new(); Vls8_vsuxseg5ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg5ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg5ei64_v_cg = new(); Vls8_vsuxseg5ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg5ei64_v");
`endif
    Vls8_vsuxseg5ei8_v_cg = new(); Vls8_vsuxseg5ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg5ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg6ei16_v_cg = new(); Vls8_vsuxseg6ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg6ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg6ei32_v_cg = new(); Vls8_vsuxseg6ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg6ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg6ei64_v_cg = new(); Vls8_vsuxseg6ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg6ei64_v");
`endif
    Vls8_vsuxseg6ei8_v_cg = new(); Vls8_vsuxseg6ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg6ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg7ei16_v_cg = new(); Vls8_vsuxseg7ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg7ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg7ei32_v_cg = new(); Vls8_vsuxseg7ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg7ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg7ei64_v_cg = new(); Vls8_vsuxseg7ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg7ei64_v");
`endif
    Vls8_vsuxseg7ei8_v_cg = new(); Vls8_vsuxseg7ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg7ei8_v");
`ifdef MAXINDEXEEW_GE16
    Vls8_vsuxseg8ei16_v_cg = new(); Vls8_vsuxseg8ei16_v_cg.set_inst_name("obj_Vls8_vsuxseg8ei16_v");
`endif
`ifdef MAXINDEXEEW_GE32
    Vls8_vsuxseg8ei32_v_cg = new(); Vls8_vsuxseg8ei32_v_cg.set_inst_name("obj_Vls8_vsuxseg8ei32_v");
`endif
`ifdef MAXINDEXEEW_GE64
    Vls8_vsuxseg8ei64_v_cg = new(); Vls8_vsuxseg8ei64_v_cg.set_inst_name("obj_Vls8_vsuxseg8ei64_v");
`endif
    Vls8_vsuxseg8ei8_v_cg = new(); Vls8_vsuxseg8ei8_v_cg.set_inst_name("obj_Vls8_vsuxseg8ei8_v");
