///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zabha_amoadd_b_cg = new(); Zabha_amoadd_b_cg.set_inst_name("obj_Zabha_amoadd_b");
    Zabha_amoadd_h_cg = new(); Zabha_amoadd_h_cg.set_inst_name("obj_Zabha_amoadd_h");
    Zabha_amoand_b_cg = new(); Zabha_amoand_b_cg.set_inst_name("obj_Zabha_amoand_b");
    Zabha_amoand_h_cg = new(); Zabha_amoand_h_cg.set_inst_name("obj_Zabha_amoand_h");
    Zabha_amomax_b_cg = new(); Zabha_amomax_b_cg.set_inst_name("obj_Zabha_amomax_b");
    Zabha_amomax_h_cg = new(); Zabha_amomax_h_cg.set_inst_name("obj_Zabha_amomax_h");
    Zabha_amomaxu_b_cg = new(); Zabha_amomaxu_b_cg.set_inst_name("obj_Zabha_amomaxu_b");
    Zabha_amomaxu_h_cg = new(); Zabha_amomaxu_h_cg.set_inst_name("obj_Zabha_amomaxu_h");
    Zabha_amomin_b_cg = new(); Zabha_amomin_b_cg.set_inst_name("obj_Zabha_amomin_b");
    Zabha_amomin_h_cg = new(); Zabha_amomin_h_cg.set_inst_name("obj_Zabha_amomin_h");
    Zabha_amominu_b_cg = new(); Zabha_amominu_b_cg.set_inst_name("obj_Zabha_amominu_b");
    Zabha_amominu_h_cg = new(); Zabha_amominu_h_cg.set_inst_name("obj_Zabha_amominu_h");
    Zabha_amoor_b_cg = new(); Zabha_amoor_b_cg.set_inst_name("obj_Zabha_amoor_b");
    Zabha_amoor_h_cg = new(); Zabha_amoor_h_cg.set_inst_name("obj_Zabha_amoor_h");
    Zabha_amoswap_b_cg = new(); Zabha_amoswap_b_cg.set_inst_name("obj_Zabha_amoswap_b");
    Zabha_amoswap_h_cg = new(); Zabha_amoswap_h_cg.set_inst_name("obj_Zabha_amoswap_h");
    Zabha_amoxor_b_cg = new(); Zabha_amoxor_b_cg.set_inst_name("obj_Zabha_amoxor_b");
    Zabha_amoxor_h_cg = new(); Zabha_amoxor_h_cg.set_inst_name("obj_Zabha_amoxor_h");
