///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zbc_clmul_cg = new(); Zbc_clmul_cg.set_inst_name("obj_Zbc_clmul");
    Zbc_clmulh_cg = new(); Zbc_clmulh_cg.set_inst_name("obj_Zbc_clmulh");
    Zbc_clmulr_cg = new(); Zbc_clmulr_cg.set_inst_name("obj_Zbc_clmulr");
