///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zbs_bclr_cg = new(); Zbs_bclr_cg.set_inst_name("obj_Zbs_bclr");
    Zbs_bclri_cg = new(); Zbs_bclri_cg.set_inst_name("obj_Zbs_bclri");
    Zbs_bext_cg = new(); Zbs_bext_cg.set_inst_name("obj_Zbs_bext");
    Zbs_bexti_cg = new(); Zbs_bexti_cg.set_inst_name("obj_Zbs_bexti");
    Zbs_binv_cg = new(); Zbs_binv_cg.set_inst_name("obj_Zbs_binv");
    Zbs_binvi_cg = new(); Zbs_binvi_cg.set_inst_name("obj_Zbs_binvi");
    Zbs_bset_cg = new(); Zbs_bset_cg.set_inst_name("obj_Zbs_bset");
    Zbs_bseti_cg = new(); Zbs_bseti_cg.set_inst_name("obj_Zbs_bseti");
