///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    ZcbM_c_mul_cg = new(); ZcbM_c_mul_cg.set_inst_name("obj_ZcbM_c_mul");
