///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zfa_fleq_s_cg = new(); Zfa_fleq_s_cg.set_inst_name("obj_Zfa_fleq_s");
    Zfa_fli_s_cg = new(); Zfa_fli_s_cg.set_inst_name("obj_Zfa_fli_s");
    Zfa_fltq_s_cg = new(); Zfa_fltq_s_cg.set_inst_name("obj_Zfa_fltq_s");
    Zfa_fmaxm_s_cg = new(); Zfa_fmaxm_s_cg.set_inst_name("obj_Zfa_fmaxm_s");
    Zfa_fminm_s_cg = new(); Zfa_fminm_s_cg.set_inst_name("obj_Zfa_fminm_s");
    Zfa_fround_s_cg = new(); Zfa_fround_s_cg.set_inst_name("obj_Zfa_fround_s");
    Zfa_froundnx_s_cg = new(); Zfa_froundnx_s_cg.set_inst_name("obj_Zfa_froundnx_s");
