///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    ZfaZfhD_fleq_h_cg = new(); ZfaZfhD_fleq_h_cg.set_inst_name("obj_ZfaZfhD_fleq_h");
    ZfaZfhD_fli_h_cg = new(); ZfaZfhD_fli_h_cg.set_inst_name("obj_ZfaZfhD_fli_h");
    ZfaZfhD_fltq_h_cg = new(); ZfaZfhD_fltq_h_cg.set_inst_name("obj_ZfaZfhD_fltq_h");
    ZfaZfhD_fmaxm_h_cg = new(); ZfaZfhD_fmaxm_h_cg.set_inst_name("obj_ZfaZfhD_fmaxm_h");
    ZfaZfhD_fminm_h_cg = new(); ZfaZfhD_fminm_h_cg.set_inst_name("obj_ZfaZfhD_fminm_h");
    ZfaZfhD_fround_h_cg = new(); ZfaZfhD_fround_h_cg.set_inst_name("obj_ZfaZfhD_fround_h");
    ZfaZfhD_froundnx_h_cg = new(); ZfaZfhD_froundnx_h_cg.set_inst_name("obj_ZfaZfhD_froundnx_h");
