///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFAZVFH
covergroup ZfaZvfh_fli_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }
    cp_asm_count : coverpoint ins.ins_str == "fli.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }
    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }
    cp_rs1_fli : coverpoint ins.current.insn[19:15]  iff (ins.trap == 0 )  {
        // FLI immediate encoding
    }
endgroup
// ---------------------
function void zfazvfh_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fli.h"     : begin
            ZfaZvfh_fli_h_cg.sample(ins);
        end
    endcase
endfunction
