///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zfh_fadd_h_cg = new(); Zfh_fadd_h_cg.set_inst_name("obj_Zfh_fadd_h");
    Zfh_fclass_h_cg = new(); Zfh_fclass_h_cg.set_inst_name("obj_Zfh_fclass_h");
    Zfh_fcvt_h_s_cg = new(); Zfh_fcvt_h_s_cg.set_inst_name("obj_Zfh_fcvt_h_s");
    Zfh_fcvt_h_w_cg = new(); Zfh_fcvt_h_w_cg.set_inst_name("obj_Zfh_fcvt_h_w");
    Zfh_fcvt_h_wu_cg = new(); Zfh_fcvt_h_wu_cg.set_inst_name("obj_Zfh_fcvt_h_wu");
    Zfh_fcvt_s_h_cg = new(); Zfh_fcvt_s_h_cg.set_inst_name("obj_Zfh_fcvt_s_h");
    Zfh_fcvt_w_h_cg = new(); Zfh_fcvt_w_h_cg.set_inst_name("obj_Zfh_fcvt_w_h");
    Zfh_fcvt_wu_h_cg = new(); Zfh_fcvt_wu_h_cg.set_inst_name("obj_Zfh_fcvt_wu_h");
    Zfh_fdiv_h_cg = new(); Zfh_fdiv_h_cg.set_inst_name("obj_Zfh_fdiv_h");
    Zfh_feq_h_cg = new(); Zfh_feq_h_cg.set_inst_name("obj_Zfh_feq_h");
    Zfh_fle_h_cg = new(); Zfh_fle_h_cg.set_inst_name("obj_Zfh_fle_h");
    Zfh_flh_cg = new(); Zfh_flh_cg.set_inst_name("obj_Zfh_flh");
    Zfh_flt_h_cg = new(); Zfh_flt_h_cg.set_inst_name("obj_Zfh_flt_h");
    Zfh_fmadd_h_cg = new(); Zfh_fmadd_h_cg.set_inst_name("obj_Zfh_fmadd_h");
    Zfh_fmax_h_cg = new(); Zfh_fmax_h_cg.set_inst_name("obj_Zfh_fmax_h");
    Zfh_fmin_h_cg = new(); Zfh_fmin_h_cg.set_inst_name("obj_Zfh_fmin_h");
    Zfh_fmsub_h_cg = new(); Zfh_fmsub_h_cg.set_inst_name("obj_Zfh_fmsub_h");
    Zfh_fmul_h_cg = new(); Zfh_fmul_h_cg.set_inst_name("obj_Zfh_fmul_h");
    Zfh_fmv_h_x_cg = new(); Zfh_fmv_h_x_cg.set_inst_name("obj_Zfh_fmv_h_x");
    Zfh_fmv_x_h_cg = new(); Zfh_fmv_x_h_cg.set_inst_name("obj_Zfh_fmv_x_h");
    Zfh_fnmadd_h_cg = new(); Zfh_fnmadd_h_cg.set_inst_name("obj_Zfh_fnmadd_h");
    Zfh_fnmsub_h_cg = new(); Zfh_fnmsub_h_cg.set_inst_name("obj_Zfh_fnmsub_h");
    Zfh_fsgnj_h_cg = new(); Zfh_fsgnj_h_cg.set_inst_name("obj_Zfh_fsgnj_h");
    Zfh_fsgnjn_h_cg = new(); Zfh_fsgnjn_h_cg.set_inst_name("obj_Zfh_fsgnjn_h");
    Zfh_fsgnjx_h_cg = new(); Zfh_fsgnjx_h_cg.set_inst_name("obj_Zfh_fsgnjx_h");
    Zfh_fsh_cg = new(); Zfh_fsh_cg.set_inst_name("obj_Zfh_fsh");
    Zfh_fsqrt_h_cg = new(); Zfh_fsqrt_h_cg.set_inst_name("obj_Zfh_fsqrt_h");
    Zfh_fsub_h_cg = new(); Zfh_fsub_h_cg.set_inst_name("obj_Zfh_fsub_h");
`ifdef UDB_MXLEN_64
    Zfh_fcvt_h_l_cg = new(); Zfh_fcvt_h_l_cg.set_inst_name("obj_Zfh_fcvt_h_l");
    Zfh_fcvt_h_lu_cg = new(); Zfh_fcvt_h_lu_cg.set_inst_name("obj_Zfh_fcvt_h_lu");
    Zfh_fcvt_l_h_cg = new(); Zfh_fcvt_l_h_cg.set_inst_name("obj_Zfh_fcvt_l_h");
    Zfh_fcvt_lu_h_cg = new(); Zfh_fcvt_lu_h_cg.set_inst_name("obj_Zfh_fcvt_lu_h");
`endif
`ifdef D_SUPPORTED
    ZfhD_fadd_h_cg = new(); ZfhD_fadd_h_cg.set_inst_name("obj_ZfhD_fadd_h");
    ZfhD_fclass_h_cg = new(); ZfhD_fclass_h_cg.set_inst_name("obj_ZfhD_fclass_h");
    ZfhD_fcvt_d_h_cg = new(); ZfhD_fcvt_d_h_cg.set_inst_name("obj_ZfhD_fcvt_d_h");
    ZfhD_fcvt_h_d_cg = new(); ZfhD_fcvt_h_d_cg.set_inst_name("obj_ZfhD_fcvt_h_d");
    ZfhD_fcvt_h_s_cg = new(); ZfhD_fcvt_h_s_cg.set_inst_name("obj_ZfhD_fcvt_h_s");
    ZfhD_fcvt_h_w_cg = new(); ZfhD_fcvt_h_w_cg.set_inst_name("obj_ZfhD_fcvt_h_w");
    ZfhD_fcvt_h_wu_cg = new(); ZfhD_fcvt_h_wu_cg.set_inst_name("obj_ZfhD_fcvt_h_wu");
    ZfhD_fcvt_s_h_cg = new(); ZfhD_fcvt_s_h_cg.set_inst_name("obj_ZfhD_fcvt_s_h");
    ZfhD_fcvt_w_h_cg = new(); ZfhD_fcvt_w_h_cg.set_inst_name("obj_ZfhD_fcvt_w_h");
    ZfhD_fcvt_wu_h_cg = new(); ZfhD_fcvt_wu_h_cg.set_inst_name("obj_ZfhD_fcvt_wu_h");
    ZfhD_fdiv_h_cg = new(); ZfhD_fdiv_h_cg.set_inst_name("obj_ZfhD_fdiv_h");
    ZfhD_feq_h_cg = new(); ZfhD_feq_h_cg.set_inst_name("obj_ZfhD_feq_h");
    ZfhD_fle_h_cg = new(); ZfhD_fle_h_cg.set_inst_name("obj_ZfhD_fle_h");
    ZfhD_flh_cg = new(); ZfhD_flh_cg.set_inst_name("obj_ZfhD_flh");
    ZfhD_flt_h_cg = new(); ZfhD_flt_h_cg.set_inst_name("obj_ZfhD_flt_h");
    ZfhD_fmadd_h_cg = new(); ZfhD_fmadd_h_cg.set_inst_name("obj_ZfhD_fmadd_h");
    ZfhD_fmax_h_cg = new(); ZfhD_fmax_h_cg.set_inst_name("obj_ZfhD_fmax_h");
    ZfhD_fmin_h_cg = new(); ZfhD_fmin_h_cg.set_inst_name("obj_ZfhD_fmin_h");
    ZfhD_fmsub_h_cg = new(); ZfhD_fmsub_h_cg.set_inst_name("obj_ZfhD_fmsub_h");
    ZfhD_fmul_h_cg = new(); ZfhD_fmul_h_cg.set_inst_name("obj_ZfhD_fmul_h");
    ZfhD_fmv_h_x_cg = new(); ZfhD_fmv_h_x_cg.set_inst_name("obj_ZfhD_fmv_h_x");
    ZfhD_fmv_x_h_cg = new(); ZfhD_fmv_x_h_cg.set_inst_name("obj_ZfhD_fmv_x_h");
    ZfhD_fnmadd_h_cg = new(); ZfhD_fnmadd_h_cg.set_inst_name("obj_ZfhD_fnmadd_h");
    ZfhD_fnmsub_h_cg = new(); ZfhD_fnmsub_h_cg.set_inst_name("obj_ZfhD_fnmsub_h");
    ZfhD_fsgnj_h_cg = new(); ZfhD_fsgnj_h_cg.set_inst_name("obj_ZfhD_fsgnj_h");
    ZfhD_fsgnjn_h_cg = new(); ZfhD_fsgnjn_h_cg.set_inst_name("obj_ZfhD_fsgnjn_h");
    ZfhD_fsgnjx_h_cg = new(); ZfhD_fsgnjx_h_cg.set_inst_name("obj_ZfhD_fsgnjx_h");
    ZfhD_fsh_cg = new(); ZfhD_fsh_cg.set_inst_name("obj_ZfhD_fsh");
    ZfhD_fsqrt_h_cg = new(); ZfhD_fsqrt_h_cg.set_inst_name("obj_ZfhD_fsqrt_h");
    ZfhD_fsub_h_cg = new(); ZfhD_fsub_h_cg.set_inst_name("obj_ZfhD_fsub_h");
`ifdef UDB_MXLEN_64
    ZfhD_fcvt_h_l_cg = new(); ZfhD_fcvt_h_l_cg.set_inst_name("obj_ZfhD_fcvt_h_l");
    ZfhD_fcvt_h_lu_cg = new(); ZfhD_fcvt_h_lu_cg.set_inst_name("obj_ZfhD_fcvt_h_lu");
    ZfhD_fcvt_l_h_cg = new(); ZfhD_fcvt_l_h_cg.set_inst_name("obj_ZfhD_fcvt_l_h");
    ZfhD_fcvt_lu_h_cg = new(); ZfhD_fcvt_lu_h_cg.set_inst_name("obj_ZfhD_fcvt_lu_h");
`endif
`endif
