///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFHMIN
covergroup Zfhmin_fcvt_h_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.h.s"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_voun : coverpoint {
        get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "fcsr", "fflags")[4:0],
        get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags")[4:0]
    } iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = {10'b0????_1????};
        wildcard bins NV1  = {10'b1????_1????};
        wildcard bins OF   = {10'b??0??_??1??};
        wildcard bins OF1  = {10'b??1??_??1??};
        wildcard bins UF   = {10'b???0?_???1?};
        wildcard bins UF1  = {10'b???1?_???1?};
        wildcard bins NX   = {10'b????0_????1};
        wildcard bins NX1  = {10'b????1_????1};
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // FS1 edges
        bins pos0             = {32'h00000000};
        bins neg0             = {32'h80000000};
        bins pos1             = {32'h3f800000};
        bins neg1             = {32'hbf800000};
        bins pos2p5           = {32'h40200000};
        bins neg2p5           = {32'hc0200000};
        bins pos2prec         = {32'h4b800000};
        bins neg2prec         = {32'hcb800000};
        bins posminnorm       = {32'h00800000};
        bins negminnorm       = {32'h80800000};
        bins posmaxnorm       = {32'h7f7fffff};
        bins negmaxnorm       = {32'hff7fffff};
        bins posmax_subnorm   = {32'h007fffff};
        bins negmax_subnorm   = {32'h807fffff};
        bins posmid_subnorm   = {32'h00400000};
        bins negmid_subnorm   = {32'h80400000};
        bins posmin_subnorm   = {32'h00000001};
        bins negmin_subnorm   = {32'h80000001};
        bins posinfinity      = {32'h7f800000};
        bins neginfinity      = {32'hff800000};
        bins posQNaN          = {[32'h7fc00000:32'h7fffffff]};
        bins posSNaN          = {[32'h7f800001:32'h7fbfffff]};
        bins negQNaN          = {[32'hffc00000:32'hffffffff]};
        bins negSNaN          = {[32'hff800001:32'hffbfffff]};
        bins posrandom        = {32'h7ef8654f};
        bins negrandom        = {32'h813d9ab0};
    }

endgroup
// ---------------------
covergroup Zfhmin_fcvt_s_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.s.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint {
        get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "fcsr", "fflags")[4:0],
        get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags")[4:0]
    } iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = {10'b0????_1????};
        wildcard bins NV1  = {10'b1????_1????};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {32'b????????????????_0111111?????????};
        wildcard bins posSNaN = {
            32'b????????????????_01111101????????,
            32'b????????????????_011111001???????,
            32'b????????????????_0111110001??????,
            32'b????????????????_01111100001?????,
            32'b????????????????_011111000001????,
            32'b????????????????_0111110000001???,
            32'b????????????????_01111100000001??,
            32'b????????????????_011111000000001?,
            32'b????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[32'hFFFF_0000:32'hFFFF_FFFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos2p5           = {16'h4100};
        bins neg2p5           = {16'hC100};
        bins pos2prec         = {16'h6800};
        bins neg2prec         = {16'hE800};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

endgroup
// ---------------------
covergroup Zfhmin_flh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "flh"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_imm_edges : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins zero  = {0};
        bins p0    = {1};
        bins p1    = {2};
        bins three = {3};
        bins p2    = {4};
        bins p3    = {8};
        bins p4    = {16};
        bins p5    = {32};
        bins p6    = {64};
        bins p7    = {128};
        bins p8    = {256};
        bins p9    = {512};
        bins hm1   = {1023};
        bins p10   = {1024};
        bins max   = {2047};
        bins min   = {-2048};
        bins minp1 = {-2047};
        bins onesm1 = {-2};
        bins ones   = {-1};
        bins randomp = {1795};
    }

    cp_memval_fp_half : coverpoint unsigned'(ins.current.fd_val[15:0])  iff (ins.trap == 0 )  {
        // Half-precision value loaded from memory
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos2p5           = {16'h4100};
        bins neg2p5           = {16'hC100};
        bins pos2prec         = {16'h6800};
        bins neg2prec         = {16'hE800};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zfhmin_fmv_h_x_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fmv.h.x"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_rs1 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins W80      = {64'b0000000000000000000000000000000010000000000000000000000000000000};
            bins W7F      = {64'b0000000000000000000000000000000001111111111111111111111111111111};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

endgroup
// ---------------------
covergroup Zfhmin_fmv_x_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fmv.x.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {32'b????????????????_0111111?????????};
        wildcard bins posSNaN = {
            32'b????????????????_01111101????????,
            32'b????????????????_011111001???????,
            32'b????????????????_0111110001??????,
            32'b????????????????_01111100001?????,
            32'b????????????????_011111000001????,
            32'b????????????????_0111110000001???,
            32'b????????????????_01111100000001??,
            32'b????????????????_011111000000001?,
            32'b????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[32'hFFFF_0000:32'hFFFF_FFFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos2p5           = {16'h4100};
        bins neg2p5           = {16'hC100};
        bins pos2prec         = {16'h6800};
        bins neg2prec         = {16'hE800};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

endgroup
// ---------------------
covergroup Zfhmin_fsh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fsh"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_badNB_S_H : coverpoint unsigned'(ins.current.fs2_val[31:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {32'b????????????????_0111111?????????};
        wildcard bins posSNaN = {
            32'b????????????????_01111101????????,
            32'b????????????????_011111001???????,
            32'b????????????????_0111110001??????,
            32'b????????????????_01111100001?????,
            32'b????????????????_011111000001????,
            32'b????????????????_0111110000001???,
            32'b????????????????_01111100000001??,
            32'b????????????????_011111000000001?,
            32'b????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[32'hFFFF_0000:32'hFFFF_FFFF]};
    }

    cp_fs2_edges_H : coverpoint unsigned'(ins.current.fs2_val[15:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos2p5           = {16'h4100};
        bins neg2p5           = {16'hC100};
        bins pos2prec         = {16'h6800};
        bins neg2prec         = {16'hE800};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_imm_edges : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins zero  = {0};
        bins p0    = {1};
        bins p1    = {2};
        bins three = {3};
        bins p2    = {4};
        bins p3    = {8};
        bins p4    = {16};
        bins p5    = {32};
        bins p6    = {64};
        bins p7    = {128};
        bins p8    = {256};
        bins p9    = {512};
        bins hm1   = {1023};
        bins p10   = {1024};
        bins max   = {2047};
        bins min   = {-2048};
        bins minp1 = {-2047};
        bins onesm1 = {-2};
        bins ones   = {-1};
        bins randomp = {1795};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
`ifdef D_SUPPORTED
covergroup ZfhminD_fcvt_d_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.d.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint {
        get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "fcsr", "fflags")[4:0],
        get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags")[4:0]
    } iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = {10'b0????_1????};
        wildcard bins NV1  = {10'b1????_1????};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {64'b????????????????????????????????????????????????_0111111?????????};
        wildcard bins posSNaN = {
            64'b????????????????????????????????????????????????_01111101????????,
            64'b????????????????????????????????????????????????_011111001???????,
            64'b????????????????????????????????????????????????_0111110001??????,
            64'b????????????????????????????????????????????????_01111100001?????,
            64'b????????????????????????????????????????????????_011111000001????,
            64'b????????????????????????????????????????????????_0111110000001???,
            64'b????????????????????????????????????????????????_01111100000001??,
            64'b????????????????????????????????????????????????_011111000000001?,
            64'b????????????????????????????????????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[64'hFFFFFFFFFFFF_0000:64'hFFFFFFFFFFFF_FFFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos2p5           = {16'h4100};
        bins neg2p5           = {16'hC100};
        bins pos2prec         = {16'h6800};
        bins neg2prec         = {16'hE800};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

endgroup
// ---------------------
covergroup ZfhminD_fcvt_h_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.h.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_voun : coverpoint {
        get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "fcsr", "fflags")[4:0],
        get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags")[4:0]
    } iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = {10'b0????_1????};
        wildcard bins NV1  = {10'b1????_1????};
        wildcard bins OF   = {10'b??0??_??1??};
        wildcard bins OF1  = {10'b??1??_??1??};
        wildcard bins UF   = {10'b???0?_???1?};
        wildcard bins UF1  = {10'b???1?_???1?};
        wildcard bins NX   = {10'b????0_????1};
        wildcard bins NX1  = {10'b????1_????1};
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos2p5           = {64'h4004000000000000};
        bins neg2p5           = {64'hc004000000000000};
        bins pos2prec         = {64'h4340000000000000};
        bins neg2prec         = {64'hc340000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cr_fs1_edges_frm_D : cross cp_fs1_edges_D,cp_frm_2  iff (ins.trap == 0 )  {
        // Cross coverage FS1 (double precision), FRM
    }

endgroup
// ---------------------
covergroup ZfhminD_fcvt_h_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhminD_fcvt_s_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {64'b????????????????????????????????????????????????_0111111?????????};
        wildcard bins posSNaN = {
            64'b????????????????????????????????????????????????_01111101????????,
            64'b????????????????????????????????????????????????_011111001???????,
            64'b????????????????????????????????????????????????_0111110001??????,
            64'b????????????????????????????????????????????????_01111100001?????,
            64'b????????????????????????????????????????????????_011111000001????,
            64'b????????????????????????????????????????????????_0111110000001???,
            64'b????????????????????????????????????????????????_01111100000001??,
            64'b????????????????????????????????????????????????_011111000000001?,
            64'b????????????????????????????????????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[64'hFFFFFFFFFFFF_0000:64'hFFFFFFFFFFFF_FFFF]};
    }

endgroup
// ---------------------
covergroup ZfhminD_flh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhminD_fmv_h_x_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhminD_fmv_x_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {64'b????????????????????????????????????????????????_0111111?????????};
        wildcard bins posSNaN = {
            64'b????????????????????????????????????????????????_01111101????????,
            64'b????????????????????????????????????????????????_011111001???????,
            64'b????????????????????????????????????????????????_0111110001??????,
            64'b????????????????????????????????????????????????_01111100001?????,
            64'b????????????????????????????????????????????????_011111000001????,
            64'b????????????????????????????????????????????????_0111110000001???,
            64'b????????????????????????????????????????????????_01111100000001??,
            64'b????????????????????????????????????????????????_011111000000001?,
            64'b????????????????????????????????????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[64'hFFFFFFFFFFFF_0000:64'hFFFFFFFFFFFF_FFFF]};
    }

endgroup
// ---------------------
covergroup ZfhminD_fsh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        // Any positive quiet/signaling NaN in the low 16 bits with improper boxing
        wildcard bins posQNaN = {64'b????????????????????????????????????????????????_0111111?????????};
        wildcard bins posSNaN = {
            64'b????????????????????????????????????????????????_01111101????????,
            64'b????????????????????????????????????????????????_011111001???????,
            64'b????????????????????????????????????????????????_0111110001??????,
            64'b????????????????????????????????????????????????_01111100001?????,
            64'b????????????????????????????????????????????????_011111000001????,
            64'b????????????????????????????????????????????????_0111110000001???,
            64'b????????????????????????????????????????????????_01111100000001??,
            64'b????????????????????????????????????????????????_011111000000001?,
            64'b????????????????????????????????????????????????_0111110000000001
        };
        // A properly NaN-boxed value is not a badNB case, so it must not hit the NaN bins above.
        ignore_bins nanboxed = {[64'hFFFFFFFFFFFF_0000:64'hFFFFFFFFFFFF_FFFF]};
    }

endgroup
// ---------------------
`endif
function void zfhmin_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
`ifdef D_SUPPORTED
        "fcvt.d.h"     : begin
            ZfhminD_fcvt_d_h_cg.sample(ins);
        end
`endif
`ifdef D_SUPPORTED
        "fcvt.h.d"     : begin
            ZfhminD_fcvt_h_d_cg.sample(ins);
        end
`endif
        "fcvt.h.s"     : begin
            Zfhmin_fcvt_h_s_cg.sample(ins);
`ifdef D_SUPPORTED
            ZfhminD_fcvt_h_s_cg.sample(ins);
`endif
        end
        "fcvt.s.h"     : begin
            Zfhmin_fcvt_s_h_cg.sample(ins);
`ifdef D_SUPPORTED
            ZfhminD_fcvt_s_h_cg.sample(ins);
`endif
        end
        "flh"     : begin
            Zfhmin_flh_cg.sample(ins);
`ifdef D_SUPPORTED
            ZfhminD_flh_cg.sample(ins);
`endif
        end
        "fmv.h.x"     : begin
            Zfhmin_fmv_h_x_cg.sample(ins);
`ifdef D_SUPPORTED
            ZfhminD_fmv_h_x_cg.sample(ins);
`endif
        end
        "fmv.x.h"     : begin
            Zfhmin_fmv_x_h_cg.sample(ins);
`ifdef D_SUPPORTED
            ZfhminD_fmv_x_h_cg.sample(ins);
`endif
        end
        "fsh"     : begin
            Zfhmin_fsh_cg.sample(ins);
`ifdef D_SUPPORTED
            ZfhminD_fsh_cg.sample(ins);
`endif
        end
        default: ; // a case needs at least one item, and some configurations select none
    endcase
endfunction
