///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zicbom_cbo_clean_cg = new(); Zicbom_cbo_clean_cg.set_inst_name("obj_Zicbom_cbo_clean");
    Zicbom_cbo_flush_cg = new(); Zicbom_cbo_flush_cg.set_inst_name("obj_Zicbom_cbo_flush");
    Zicbom_cbo_inval_cg = new(); Zicbom_cbo_inval_cg.set_inst_name("obj_Zicbom_cbo_inval");
