///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZICBOP
covergroup Zicbop_prefetch_i_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "prefetch.i"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }
    // Custom coverpoints for cbo.  Coverpoint just checks that instruction was executed
    // but test is more comprehensive, writing and reading back consecutive words

    cp_custom_prefetch : coverpoint ins.current.insn  {
        wildcard bins prefetch = {32'b???????000???????110000000010011};
    }
    cp_rs1 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }
endgroup
// ---------------------
covergroup Zicbop_prefetch_r_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "prefetch.r"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }
    // Custom coverpoints for cbo.  Coverpoint just checks that instruction was executed
    // but test is more comprehensive, writing and reading back consecutive words

    cp_custom_prefetch : coverpoint ins.current.insn  {
        wildcard bins prefetch = {32'b???????000???????110000000010011};
    }
    cp_rs1 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }
endgroup
// ---------------------
covergroup Zicbop_prefetch_w_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "prefetch.w"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }
    // Custom coverpoints for cbo.  Coverpoint just checks that instruction was executed
    // but test is more comprehensive, writing and reading back consecutive words

    cp_custom_prefetch : coverpoint ins.current.insn  {
        wildcard bins prefetch = {32'b???????000???????110000000010011};
    }
    cp_rs1 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }
endgroup
// ---------------------
function void zicbop_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "prefetch.i"     : begin
            Zicbop_prefetch_i_cg.sample(ins);
        end
        "prefetch.r"     : begin
            Zicbop_prefetch_r_cg.sample(ins);
        end
        "prefetch.w"     : begin
            Zicbop_prefetch_w_cg.sample(ins);
        end
    endcase
endfunction
