///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZICBOM
covergroup Zicbom_cbo_clean_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "cbo.clean"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // Custom coverpoints for cbo.  Coverpoint just checks that instruction was executed
    // but test is more comprehensive, writing and reading back consecutive words

    cp_custom_cbo : coverpoint ins.current.insn  {
        wildcard bins cbo_op  = {32'b000000000????????010000000001111};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zicbom_cbo_flush_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "cbo.flush"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // Custom coverpoints for cbo.  Coverpoint just checks that instruction was executed
    // but test is more comprehensive, writing and reading back consecutive words

    cp_custom_cbo : coverpoint ins.current.insn  {
        wildcard bins cbo_op  = {32'b000000000????????010000000001111};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zicbom_cbo_inval_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "cbo.inval"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // Custom coverpoints for cbo.  Coverpoint just checks that instruction was executed
    // but test is more comprehensive, writing and reading back consecutive words

    cp_custom_cbo : coverpoint ins.current.insn  {
        wildcard bins cbo_op  = {32'b000000000????????010000000001111};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
function void zicbom_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "cbo.clean"     : begin
            Zicbom_cbo_clean_cg.sample(ins);
        end
        "cbo.flush"     : begin
            Zicbom_cbo_flush_cg.sample(ins);
        end
        "cbo.inval"     : begin
            Zicbom_cbo_inval_cg.sample(ins);
        end
    endcase
endfunction
