///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zicntr_csrrc_cg = new(); Zicntr_csrrc_cg.set_inst_name("obj_Zicntr_csrrc");
    Zicntr_csrrs_cg = new(); Zicntr_csrrs_cg.set_inst_name("obj_Zicntr_csrrs");
