///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zicsr_csrrc_cg = new(); Zicsr_csrrc_cg.set_inst_name("obj_Zicsr_csrrc");
    Zicsr_csrrci_cg = new(); Zicsr_csrrci_cg.set_inst_name("obj_Zicsr_csrrci");
    Zicsr_csrrs_cg = new(); Zicsr_csrrs_cg.set_inst_name("obj_Zicsr_csrrs");
    Zicsr_csrrsi_cg = new(); Zicsr_csrrsi_cg.set_inst_name("obj_Zicsr_csrrsi");
    Zicsr_csrrw_cg = new(); Zicsr_csrrw_cg.set_inst_name("obj_Zicsr_csrrw");
    Zicsr_csrrwi_cg = new(); Zicsr_csrrwi_cg.set_inst_name("obj_Zicsr_csrrwi");
