///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZIFENCEI
covergroup Zifencei_fence_i_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fence.i"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // Custom coverpoints for fence.i

    // the test should do some self-modifying code and then a fence.i and then run the code
    // this is too complicated to express with a coverpoint, so just check that the fence.i
    // is executed, and leave it to the test code to do the right thing

    cp_custom_fencei : coverpoint ins.current.insn  {
        bins fencei            = {32'h0000100f}; // normal fence.i
        bins fencei_nonzerors1 = {32'h0001100f}; // fence.i with nonzero rs1 ignores this field
        bins fencei_nonzerord  = {32'h0000108f}; // fence.i with nonzero rd ignores this field
        bins fencei_nonzerof12 = {32'h0010100f}; // fence.i with nonzero funct12 ignores this field
    }

endgroup
// ---------------------
function void zifencei_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fence.i"     : begin
            Zifencei_fence_i_cg.sample(ins);
        end
    endcase
endfunction
