///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zimop_mop_r_0_cg = new(); Zimop_mop_r_0_cg.set_inst_name("obj_Zimop_mop_r_0");
    Zimop_mop_r_1_cg = new(); Zimop_mop_r_1_cg.set_inst_name("obj_Zimop_mop_r_1");
    Zimop_mop_r_10_cg = new(); Zimop_mop_r_10_cg.set_inst_name("obj_Zimop_mop_r_10");
    Zimop_mop_r_11_cg = new(); Zimop_mop_r_11_cg.set_inst_name("obj_Zimop_mop_r_11");
    Zimop_mop_r_12_cg = new(); Zimop_mop_r_12_cg.set_inst_name("obj_Zimop_mop_r_12");
    Zimop_mop_r_13_cg = new(); Zimop_mop_r_13_cg.set_inst_name("obj_Zimop_mop_r_13");
    Zimop_mop_r_14_cg = new(); Zimop_mop_r_14_cg.set_inst_name("obj_Zimop_mop_r_14");
    Zimop_mop_r_15_cg = new(); Zimop_mop_r_15_cg.set_inst_name("obj_Zimop_mop_r_15");
    Zimop_mop_r_16_cg = new(); Zimop_mop_r_16_cg.set_inst_name("obj_Zimop_mop_r_16");
    Zimop_mop_r_17_cg = new(); Zimop_mop_r_17_cg.set_inst_name("obj_Zimop_mop_r_17");
    Zimop_mop_r_18_cg = new(); Zimop_mop_r_18_cg.set_inst_name("obj_Zimop_mop_r_18");
    Zimop_mop_r_19_cg = new(); Zimop_mop_r_19_cg.set_inst_name("obj_Zimop_mop_r_19");
    Zimop_mop_r_2_cg = new(); Zimop_mop_r_2_cg.set_inst_name("obj_Zimop_mop_r_2");
    Zimop_mop_r_20_cg = new(); Zimop_mop_r_20_cg.set_inst_name("obj_Zimop_mop_r_20");
    Zimop_mop_r_21_cg = new(); Zimop_mop_r_21_cg.set_inst_name("obj_Zimop_mop_r_21");
    Zimop_mop_r_22_cg = new(); Zimop_mop_r_22_cg.set_inst_name("obj_Zimop_mop_r_22");
    Zimop_mop_r_23_cg = new(); Zimop_mop_r_23_cg.set_inst_name("obj_Zimop_mop_r_23");
    Zimop_mop_r_24_cg = new(); Zimop_mop_r_24_cg.set_inst_name("obj_Zimop_mop_r_24");
    Zimop_mop_r_25_cg = new(); Zimop_mop_r_25_cg.set_inst_name("obj_Zimop_mop_r_25");
    Zimop_mop_r_26_cg = new(); Zimop_mop_r_26_cg.set_inst_name("obj_Zimop_mop_r_26");
    Zimop_mop_r_27_cg = new(); Zimop_mop_r_27_cg.set_inst_name("obj_Zimop_mop_r_27");
    Zimop_mop_r_28_cg = new(); Zimop_mop_r_28_cg.set_inst_name("obj_Zimop_mop_r_28");
    Zimop_mop_r_29_cg = new(); Zimop_mop_r_29_cg.set_inst_name("obj_Zimop_mop_r_29");
    Zimop_mop_r_3_cg = new(); Zimop_mop_r_3_cg.set_inst_name("obj_Zimop_mop_r_3");
    Zimop_mop_r_30_cg = new(); Zimop_mop_r_30_cg.set_inst_name("obj_Zimop_mop_r_30");
    Zimop_mop_r_31_cg = new(); Zimop_mop_r_31_cg.set_inst_name("obj_Zimop_mop_r_31");
    Zimop_mop_r_4_cg = new(); Zimop_mop_r_4_cg.set_inst_name("obj_Zimop_mop_r_4");
    Zimop_mop_r_5_cg = new(); Zimop_mop_r_5_cg.set_inst_name("obj_Zimop_mop_r_5");
    Zimop_mop_r_6_cg = new(); Zimop_mop_r_6_cg.set_inst_name("obj_Zimop_mop_r_6");
    Zimop_mop_r_7_cg = new(); Zimop_mop_r_7_cg.set_inst_name("obj_Zimop_mop_r_7");
    Zimop_mop_r_8_cg = new(); Zimop_mop_r_8_cg.set_inst_name("obj_Zimop_mop_r_8");
    Zimop_mop_r_9_cg = new(); Zimop_mop_r_9_cg.set_inst_name("obj_Zimop_mop_r_9");
    Zimop_mop_rr_0_cg = new(); Zimop_mop_rr_0_cg.set_inst_name("obj_Zimop_mop_rr_0");
    Zimop_mop_rr_1_cg = new(); Zimop_mop_rr_1_cg.set_inst_name("obj_Zimop_mop_rr_1");
    Zimop_mop_rr_2_cg = new(); Zimop_mop_rr_2_cg.set_inst_name("obj_Zimop_mop_rr_2");
    Zimop_mop_rr_3_cg = new(); Zimop_mop_rr_3_cg.set_inst_name("obj_Zimop_mop_rr_3");
    Zimop_mop_rr_4_cg = new(); Zimop_mop_rr_4_cg.set_inst_name("obj_Zimop_mop_rr_4");
    Zimop_mop_rr_5_cg = new(); Zimop_mop_rr_5_cg.set_inst_name("obj_Zimop_mop_rr_5");
    Zimop_mop_rr_6_cg = new(); Zimop_mop_rr_6_cg.set_inst_name("obj_Zimop_mop_rr_6");
    Zimop_mop_rr_7_cg = new(); Zimop_mop_rr_7_cg.set_inst_name("obj_Zimop_mop_rr_7");
