///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZVABD64
`define COVER_ZVABDCUSTOM64
`ifdef UDB_ELEN_64
    `define SEW_64_EQ_ELEN
`endif
`ifdef UDB_ELEN_128
    `define SEW_64_EQ_ELEN_DIV_2
`endif
covergroup Zvabd64_vabs_v_cg with function sample(ins_t ins);
    option.per_instance = 0;
    //////////////////////////////////////////////////////////////////////////////////
    // cmp_vd_vs2
    //////////////////////////////////////////////////////////////////////////////////

    cmp_vd_vs2 : coverpoint ins.get_vr_reg(ins.current.vd)  iff (ins.current.vd == ins.current.vs2 & ins.trap == 0 )  {
        // Compare assignments of all 32 registers
    }

    //// end cmp_vd_vs2////////////////////////////////////////////////

    cp_asm_count : coverpoint ins.ins_str == "vabs.v"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_masking_edges : coverpoint mask_edges_check(ins.hart, ins.issue, ins.prev.v_wdata[0])  iff (ins.trap == 0 & ins.current.vm == 0)  {
        // Edges values of v0 (vector mask register)
        bins zero           = {mask_zero            };
        bins ones           = {mask_ones            };
        bins vlmaxm1ones    = {mask_vlmaxm1ones     };
        bins vlmaxd2p1ones  = {mask_vlmaxd2p1ones   };
        bins random         = {mask_random          };
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vd
    //////////////////////////////////////////////////////////////////////////////////

    cp_vd : coverpoint ins.get_vr_reg(ins.current.vd)  iff (ins.trap == 0 )  {
        // VD register assignment
    }

    //// end cp_vd////////////////////////////////////////////////

    cp_vl_0 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") {
    bins zero = {0};
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2 : coverpoint ins.get_vr_reg(ins.current.vs2)  iff (ins.trap == 0 )  {
        // VS2 register assignment
    }

    //// end cp_vs2////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_edges
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_edges : coverpoint vs_edges_check(ins.hart, ins.issue, ins.current.vs2_val, "1")  iff (ins.trap == 0 )  {
        // Edges values of vs2, assuming vl = 1
        bins zero       = {vs_zero      };   //  = {(`SEW){1'b0}},
        bins one        = {vs_one       };   //  = {(`SEW-1){1'b0}, {1'b1}},
        bins two        = {vs_two       };   //  = {(`SEW-2){1'b0}, {2'b10}},
        bins min        = {vs_min       };   //  = {{1'b1}, (`SEW-1){1'b0}},
        bins minp1      = {vs_minp1     };   //  = {{1'b1}, (`SEW-2){1'b0}, {1'b1}},
        bins max        = {vs_max       };   //  = {{1'b0}, (`SEW-1){1'b1}},
        bins maxm1      = {vs_maxm1     };   //  = {{1'b0}, (`SEW-2){1'b1}, {1'b0}},
        bins ones       = {vs_ones      };   //  = {(`SEW){1'b1}},
        bins onesm1     = {vs_onesm1    };   //  = {(`SEW-1){1'b1}, {1'b0}},
        bins walkodd    = {vs_walkodd   };   //  = {(`SEW/2){2'b10}},
        bins walkeven   = {vs_walkeven  };   //  = {(`SEW/2){2'b01}},
        bins random     = {vs_random    };   //  = {(SEW){random}}
    }

    //// end cp_vs2_edges////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vl_lmul_sew64
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_lmul_all_sew64_lmul_le_8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul")  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 3) {
        // Value of VTYPE.vlmul (vector register grouping), SEW = 64
        bins one    = {0};
        bins two    = {1};
        bins four   = {2};
        bins eight  = {3};
    }

    cp_csr_vl_edges : coverpoint vl_check(ins.hart, ins.issue)  iff (ins.trap == 0 )  {
        // Edges values of VL (vector length)
        bins one        = {vl_one       };
        bins vlmax      = {vl_vlmax     };
        bins legal      = {vl_legal     };
    }

    cr_vl_lmul_sew64 : cross cp_csr_vtype_lmul_all_sew64_lmul_le_8, cp_csr_vl_edges  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 3)  {
        // Cross coverage all legal LMULs for SEW = 64 and vl edges (1, random, vlmax)
    }

    //////////////////////////////////////////////////////////////////////////////////

    //// end cr_vl_lmul_sew64////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vtype_agnostic
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_vta : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vta")  iff (ins.trap == 0)  {
        // Value of VTYPE.vta (vector tail agnostic)
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    cp_csr_vtype_vma : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vma")  iff (ins.trap == 0)  {
        // Value of VTYPE.vma (vector mask agnostic)
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    mask_enabled_agnostic: coverpoint ins.current.insn[25] {
        bins enabled = {1'b0};
    }

    cr_vtype_agnostic : cross cp_csr_vtype_vta,cp_csr_vtype_vma,mask_enabled_agnostic iff (ins.trap == 0 )  {
        // Cross coverage of vector tail and mask agnostic behaviors
    }

    //// end cr_vtype_agnostic////////////////////////////////////////////////

endgroup
// ---------------------
function void zvabd64_sample(int hart, int issue, ins_t ins);
    // Want to sample only if the SEW matches the target SEW of the file, some tests require
    // testing when vill is set, if vill=1 all other vtype bits are set to 0 so there is no
    // associated sew with these tests
    if (get_csr_val(hart, issue, `SAMPLE_BEFORE, "vtype", "vsew") == 3 ||
        get_csr_val(hart, issue, `SAMPLE_BEFORE, "vtype", "vill") == 1) begin
        case (traceDataQ[hart][issue][0].inst_name)
            "vabs.v"     : begin
                Zvabd64_vabs_v_cg.sample(ins);
            end
        endcase
    end
endfunction
