///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvbb64_vandn_vv_cg = new(); Zvbb64_vandn_vv_cg.set_inst_name("obj_Zvbb64_vandn_vv");
    Zvbb64_vandn_vx_cg = new(); Zvbb64_vandn_vx_cg.set_inst_name("obj_Zvbb64_vandn_vx");
    Zvbb64_vbrev_v_cg = new(); Zvbb64_vbrev_v_cg.set_inst_name("obj_Zvbb64_vbrev_v");
    Zvbb64_vbrev8_v_cg = new(); Zvbb64_vbrev8_v_cg.set_inst_name("obj_Zvbb64_vbrev8_v");
    Zvbb64_vclz_v_cg = new(); Zvbb64_vclz_v_cg.set_inst_name("obj_Zvbb64_vclz_v");
    Zvbb64_vcpop_v_cg = new(); Zvbb64_vcpop_v_cg.set_inst_name("obj_Zvbb64_vcpop_v");
    Zvbb64_vctz_v_cg = new(); Zvbb64_vctz_v_cg.set_inst_name("obj_Zvbb64_vctz_v");
    Zvbb64_vrev8_v_cg = new(); Zvbb64_vrev8_v_cg.set_inst_name("obj_Zvbb64_vrev8_v");
    Zvbb64_vrol_vv_cg = new(); Zvbb64_vrol_vv_cg.set_inst_name("obj_Zvbb64_vrol_vv");
    Zvbb64_vrol_vx_cg = new(); Zvbb64_vrol_vx_cg.set_inst_name("obj_Zvbb64_vrol_vx");
    Zvbb64_vror_vi_cg = new(); Zvbb64_vror_vi_cg.set_inst_name("obj_Zvbb64_vror_vi");
    Zvbb64_vror_vv_cg = new(); Zvbb64_vror_vv_cg.set_inst_name("obj_Zvbb64_vror_vv");
    Zvbb64_vror_vx_cg = new(); Zvbb64_vror_vx_cg.set_inst_name("obj_Zvbb64_vror_vx");
