///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvbb8_vandn_vv_cg = new(); Zvbb8_vandn_vv_cg.set_inst_name("obj_Zvbb8_vandn_vv");
    Zvbb8_vandn_vx_cg = new(); Zvbb8_vandn_vx_cg.set_inst_name("obj_Zvbb8_vandn_vx");
    Zvbb8_vbrev_v_cg = new(); Zvbb8_vbrev_v_cg.set_inst_name("obj_Zvbb8_vbrev_v");
    Zvbb8_vbrev8_v_cg = new(); Zvbb8_vbrev8_v_cg.set_inst_name("obj_Zvbb8_vbrev8_v");
    Zvbb8_vclz_v_cg = new(); Zvbb8_vclz_v_cg.set_inst_name("obj_Zvbb8_vclz_v");
    Zvbb8_vcpop_v_cg = new(); Zvbb8_vcpop_v_cg.set_inst_name("obj_Zvbb8_vcpop_v");
    Zvbb8_vctz_v_cg = new(); Zvbb8_vctz_v_cg.set_inst_name("obj_Zvbb8_vctz_v");
    Zvbb8_vrev8_v_cg = new(); Zvbb8_vrev8_v_cg.set_inst_name("obj_Zvbb8_vrev8_v");
    Zvbb8_vrol_vv_cg = new(); Zvbb8_vrol_vv_cg.set_inst_name("obj_Zvbb8_vrol_vv");
    Zvbb8_vrol_vx_cg = new(); Zvbb8_vrol_vx_cg.set_inst_name("obj_Zvbb8_vrol_vx");
    Zvbb8_vror_vi_cg = new(); Zvbb8_vror_vi_cg.set_inst_name("obj_Zvbb8_vror_vi");
    Zvbb8_vror_vv_cg = new(); Zvbb8_vror_vv_cg.set_inst_name("obj_Zvbb8_vror_vv");
    Zvbb8_vror_vx_cg = new(); Zvbb8_vror_vx_cg.set_inst_name("obj_Zvbb8_vror_vx");
    Zvbb8_vwsll_vi_cg = new(); Zvbb8_vwsll_vi_cg.set_inst_name("obj_Zvbb8_vwsll_vi");
    Zvbb8_vwsll_vv_cg = new(); Zvbb8_vwsll_vv_cg.set_inst_name("obj_Zvbb8_vwsll_vv");
    Zvbb8_vwsll_vx_cg = new(); Zvbb8_vwsll_vx_cg.set_inst_name("obj_Zvbb8_vwsll_vx");
