///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvbb16_vandn_vv_cg = new(); Zvbb16_vandn_vv_cg.set_inst_name("obj_Zvbb16_vandn_vv");
    Zvbb16_vandn_vx_cg = new(); Zvbb16_vandn_vx_cg.set_inst_name("obj_Zvbb16_vandn_vx");
    Zvbb16_vbrev_v_cg = new(); Zvbb16_vbrev_v_cg.set_inst_name("obj_Zvbb16_vbrev_v");
    Zvbb16_vbrev8_v_cg = new(); Zvbb16_vbrev8_v_cg.set_inst_name("obj_Zvbb16_vbrev8_v");
    Zvbb16_vclz_v_cg = new(); Zvbb16_vclz_v_cg.set_inst_name("obj_Zvbb16_vclz_v");
    Zvbb16_vcpop_v_cg = new(); Zvbb16_vcpop_v_cg.set_inst_name("obj_Zvbb16_vcpop_v");
    Zvbb16_vctz_v_cg = new(); Zvbb16_vctz_v_cg.set_inst_name("obj_Zvbb16_vctz_v");
    Zvbb16_vrev8_v_cg = new(); Zvbb16_vrev8_v_cg.set_inst_name("obj_Zvbb16_vrev8_v");
    Zvbb16_vrol_vv_cg = new(); Zvbb16_vrol_vv_cg.set_inst_name("obj_Zvbb16_vrol_vv");
    Zvbb16_vrol_vx_cg = new(); Zvbb16_vrol_vx_cg.set_inst_name("obj_Zvbb16_vrol_vx");
    Zvbb16_vror_vi_cg = new(); Zvbb16_vror_vi_cg.set_inst_name("obj_Zvbb16_vror_vi");
    Zvbb16_vror_vv_cg = new(); Zvbb16_vror_vv_cg.set_inst_name("obj_Zvbb16_vror_vv");
    Zvbb16_vror_vx_cg = new(); Zvbb16_vror_vx_cg.set_inst_name("obj_Zvbb16_vror_vx");
    Zvbb16_vwsll_vi_cg = new(); Zvbb16_vwsll_vi_cg.set_inst_name("obj_Zvbb16_vwsll_vi");
    Zvbb16_vwsll_vv_cg = new(); Zvbb16_vwsll_vv_cg.set_inst_name("obj_Zvbb16_vwsll_vv");
    Zvbb16_vwsll_vx_cg = new(); Zvbb16_vwsll_vx_cg.set_inst_name("obj_Zvbb16_vwsll_vx");
