///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvfbfwma_vfwmaccbf16_vf_cg = new(); Zvfbfwma_vfwmaccbf16_vf_cg.set_inst_name("obj_Zvfbfwma_vfwmaccbf16_vf");
    Zvfbfwma_vfwmaccbf16_vv_cg = new(); Zvfbfwma_vfwmaccbf16_vv_cg.set_inst_name("obj_Zvfbfwma_vfwmaccbf16_vv");
