///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvkb64_vandn_vv_cg = new(); Zvkb64_vandn_vv_cg.set_inst_name("obj_Zvkb64_vandn_vv");
    Zvkb64_vandn_vx_cg = new(); Zvkb64_vandn_vx_cg.set_inst_name("obj_Zvkb64_vandn_vx");
    Zvkb64_vbrev8_v_cg = new(); Zvkb64_vbrev8_v_cg.set_inst_name("obj_Zvkb64_vbrev8_v");
    Zvkb64_vrev8_v_cg = new(); Zvkb64_vrev8_v_cg.set_inst_name("obj_Zvkb64_vrev8_v");
    Zvkb64_vrol_vv_cg = new(); Zvkb64_vrol_vv_cg.set_inst_name("obj_Zvkb64_vrol_vv");
    Zvkb64_vrol_vx_cg = new(); Zvkb64_vrol_vx_cg.set_inst_name("obj_Zvkb64_vrol_vx");
    Zvkb64_vror_vi_cg = new(); Zvkb64_vror_vi_cg.set_inst_name("obj_Zvkb64_vror_vi");
    Zvkb64_vror_vv_cg = new(); Zvkb64_vror_vv_cg.set_inst_name("obj_Zvkb64_vror_vv");
    Zvkb64_vror_vx_cg = new(); Zvkb64_vror_vx_cg.set_inst_name("obj_Zvkb64_vror_vx");
