==== Vector Coverpoints

Running long vectors is computationally expensive, so only a subset of vectors tests run on multi-element vectors.  Coverpoints for source and destination registers, edge values, etc. run on a vector length of vl = 1.

<<t-vector-coverpoints>> defines the coverpoints used in vector instructions.  Unless otherwise specified, each coverpoint uses vector length vl=1 and length multiplier LMUL=1, no mask (vm=1), and vstart=0. Hence, they act on exactly one vector element. For such coverpoints, instructions that require a mask use v0=0.

[[t-vector-coverpoints]]
.Vector Coverpoint Definitions
[cols="2,1,5" options=header]
[%AUTOWIDTH]
|===
|Coverpoint|# Bins|Definition
3+^|Coverpoints acting on single element vl=1
|cp_vd|32|All vector destination registers vd=0-31
|cp_vs2|32|All vector source registers vs2=0-31
|cp_vs1|32|All vector source registers vs1=0-31
|cp_vs3|32|All vector source registers vs3=0-31
|cp_rs1|32|All scalar registers rs1=0-31
|cp_rs2|32|All scalar registers rs2=0-31
|cp_imm_5bit|32|Signed immediate values -16 to +15
|cmp_rs1_rs2|32|rs1 and rs2 are same register ID
|cmp_vd_vs2|32|vd and vs2 are same register ID
|cmp_vd_vs1|32|vd and vs1 are same register ID
|cmp_vs2_vs1|32|vs2 and vs1 are same register ID
|cmp_vs3_vs2|32|vs3 and vs2 are the same register ID
|cmp_vd_vs1_vs2|32|vd and vs1 and vs2 are same register ID
|cp_rs1_edges|9|0, 1, 2, -1, -2, most negative, most negative+1, most positive, most positive-1
|cp_rs2_edges|5|0, 1, 2, -1, -2 (for strided vector load/store)
|cp_fs1_edges|20|0, -1, -smallest subnorm, -inf, 1, 1+ulp, 0.5, 1.5, 2, 4, pi, 2^emax, largest normal, smallest normal, largest subnormal, subnormal with leading 1 in fraction, infinity, canonical quite NaN, noncanonical quiet NaN, signaling NaN with payload of 1
|cp_vs2_edges|9 or 20|see cp_rs1_edges or cp_fs1_edges
|cp_vs1_edges|9 or 20|see cp_rs1_edges
|cr_vs2_vs1_edges|9^2 or 20^2|Cross-product of edges of vs2 and vs1
|cr_vs2_rs1_edges|9*9|Cross-product of edges of vs2 and rs1
|cr_vs2_fs1_edges|20*20|Cross-product of edges of vs2 and fs1
|cr_vs2_imm_edges|9*9|Cross-product of edges of vs2 and imm={0, 1, 2, 14, 15, -1, -2, -15,-16}
|cr_vxrm_vs2_vs1_edges|9*9*4|Cross-product of edges of vs2 and vs1 with vector rounding mode={rod, rdn, rne, rnu}
|cr_vxrm_vs2_rs1_edges|9*9*4|See cr_vxrm_vs2_vs1_edges
|cr_vxrm_vs2_imm_edges|9*9*4|See cr_vxrm_vs2_vs1_edges
|cp_csr_frm|5*10|Floating-point rounding mode={rdn, rmm, rne, rtz, rup} with 10 random inputs per mode
|cp_csr_fflags|5*2|Floating-point sets and clears all applicable flags
3+^|Coverpoints acting on multiple elements vl ≠ 1
|cp_masking_edges|5|Mask edge cases v0=all 1s, all 0s, random, first VLMAX-1 ones, first VLMAX/2+1 ones; vl=VLMAX, vm=1 to mask, vma = random, vta = 0
|cr_vl_lmul|7*3|Cross legal combinations of LMUL={1/2/4/8/f2/f4/f8} and vl={1, random, VLMAX}, while randomizing v0 mask value, vm, vta, vma.
|cr_vtype_agnostic|4|Cross vta={0/1} and vma={0/1}. Random legal LMUL, random legal vl, vm=1, v0=random mask
|cp_vxsat|2|vxsat={0, 1}.  Hit by cr_vs2_vs1_edges so no tests needed.
|cp_vl_0|1|vl=0.  LMUL=1, no mask, vma=0, vta=1
|===

As with other unprivileged testplans, an x in the spreadsheet indicates to use the coverpoint.  Other values in the spreadsheet indicate a variant of the coverpoint:

* nv0: Do not include v0 in the coverpoint.  For example, cp_vd_nv0 means that the destination register vd does not include v0.
* emul2: Only exercise even-numbered registers.  For example cp_vs2_emul2 uses vs2={v0, v2, v4, ...v30}.  For edge values, emul2 means the edge value is twice the width of SEW.
* emul4/8: Similar to emul2
* emulf2, emulf4, emulf8: edge values are 1/2, 1/4, or 1/8 the width of SEW.  Used in extension instructions such as vsext.vf2.
* u: Treat immediate as unsigned 0 to 31 rather than signed -16 to +15. For edge values, {0, 1, 2, 15, 16, 30, 31}.
* eew1/mm: Mask instructions with 1-bit elements such as vmand.mm use at least vl=8 to operate on multi-bit masks.
* wv: vs2 is double-width and uses emul2 for its edge values.  vs1 is normal width.
* wred: vs1 is double-width and uses emul2 for its edge values.  vs2 is normal width.
* wx: vs2 is double-width and uses emul2 for its edge values.  rs1 is normal width.
* wi/wiu: vs2 is double-width and uses emul2 for its edge values.  immediate is 5 bit signed or unsigned.
* lmul4max/emul4max: maximum LMUL/EMUL is 4 instead of 8.  vwadd.vv uses lmul4max because it cannot accept LMUL=8 widened to 16.  vlseg2e8.v uses emul4max because the number of segments * EMUL cannot exceed 8.
* lmul2max/lmul1max/emul2max/emul1max: see lmul4max
* lte30/.../lte24: Register number is less than or equal to 30, ..., 24.  Used for segmented load/store so segments won't overflow the register file.
* ls_e{8/16/32/64}: load/store edges with EEW=8,...,64.  Used to convert strided loads from elements to bytes.
* ls: load/store edges instead of integer edges: vs2={0, random < 2*VLMAX}.  rs2= {1, 2, -1, -2, 0}
* f: floating-point edges instead of integer edges: ***
