#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 RISC-V International
#
# Generate udb_parameters.h, the list of every UDB parameter with the condition under which it
# applies to a hart, from a riscv-unified-db checkout:
#
#   test/gen_udb_parameters.py /path/to/riscv-unified-db > udb_parameters.h
#
# The extractor prints, commented out, every parameter that applies to the hart but that it could
# not determine, so the reader of the output knows what is left to fill in by hand.

import subprocess
import sys
from pathlib import Path

import yaml

# Extensions the extractor knows by a name other than have("X")
SPECIAL = {
    "Sm": "true",
    "Zicsr": "true",
    "S": "has_s",
    "H": "has_h",
    "U": "has_u",
    "Zvl32b": "vlen != 0",
    # the translation modes are not in the extension tables; any_atp says whether satp accepts one
    "Sv32": "any_atp",
    "Sv39": "any_atp",
    "Sv48": "any_atp",
    "Sv57": "any_atp",
}


def gate(node: object) -> str:
    """The C condition for a definedBy node: extensions become have() tests, allOf/anyOf combine them."""
    if isinstance(node, dict):
        if "extension" in node:
            return gate(node["extension"])
        if "allOf" in node:
            parts = [gate(n) for n in node["allOf"]]
            parts = [p for p in parts if p]
            return " && ".join(f"({p})" for p in parts) if parts else ""
        if "anyOf" in node:
            parts = [gate(n) for n in node["anyOf"]]
            parts = [p for p in parts if p]
            return " || ".join(f"({p})" for p in parts) if parts else ""
        if "noneOf" in node:
            parts = [gate(n) for n in node["noneOf"]]
            parts = [p for p in parts if p]
            return " && ".join(f"!({p})" for p in parts) if parts else ""
        if "param" in node:
            p = node["param"]
            if p.get("name") == "NUM_PMP_ENTRIES":
                return "num_pmp > 0"
            return ""  # a condition on another parameter: not modelled
        if "name" in node:
            return SPECIAL.get(node["name"], f'have("{node["name"]}")')
    if isinstance(node, list):
        parts = [gate(n) for n in node]
        parts = [p for p in parts if p]
        return " && ".join(f"({p})" for p in parts) if parts else ""
    return ""


def main() -> None:
    udb = Path(sys.argv[1])
    rev = subprocess.run(
        ["git", "-C", str(udb), "rev-parse", "--short", "HEAD"], capture_output=True, text=True, check=False
    ).stdout.strip()
    rows = []
    for f in sorted((udb / "spec/std/isa/param").glob("*.yaml")):
        doc = yaml.safe_load(f.read_text())
        if not isinstance(doc, dict) or doc.get("kind") != "parameter":
            continue
        g = gate(doc.get("definedBy", {})) or "true"
        rows.append((doc["name"], g))
    print("// SPDX-License-Identifier: Apache-2.0")
    print("// Copyright (c) 2026 RISC-V International")
    print("//")
    print("// udb_parameters.h: every UDB parameter and the condition under which it applies to the hart.")
    print(f"// Generated by test/gen_udb_parameters.py from riscv-unified-db {rev}; do not edit by hand.")
    print("//")
    print("// UDB_PARAMETERS(P) expands P(name, applies) for each parameter, where applies is a C")
    print("// expression over have(), has_s, has_h, has_u, vlen, num_pmp and any_atp.")
    print()
    print("#define UDB_PARAMETERS(P) \\")
    for name, g in rows:
        print(f"    P({name}, {g}) \\")
    print("    /* end */")


if __name__ == "__main__":
    main()
