##################################
# SdtrigCommon.py
#
# Sdtrig (debug triggers) shared test-case generators.
# pclark@hmc.edu Jul 2026
# SPDX-License-Identifier: Apache-2.0
##################################

"""Shared Sdtrig debug-trigger test-case generators."""

from __future__ import annotations

from testgen.asm.helpers import comment_banner, write_sigupd
from testgen.asm.tsbi import add_tsbi
from testgen.data.state import TestData
from testgen.data.test_chunk import TestChunk

# data
PERM_XSL = ("exec", "store", "load")
SIZE_ALL = ("any", "b8", "b16", "b32", "b48", "b64", "b128")
SIZE_SEW = ("any", "s8", "s16", "s32", "s64", "s128")
UDB_NUM_TRIGGERS = 1  # TODO: Relate to UDB
HINT = 0x00208033
NOP = 0x00000013
NOTANOP = 0x00130033  # add x0,x6,x1: upper parcel 0x0013 == NOP tdata2, full opcode != NOP
C_NOP = 0x0001
TDATA2_NOFIRE = 0x2
MODE_PRIVBIT = {"Sm": 0b10000, "S": 0b01000, "U": 0b00100}

# TODO: replace this with UDB-autogenerated parameters.
UDB_DEFINES = [
    f"#define UDB_NUM_TRIGGERS {UDB_NUM_TRIGGERS}",
    "#define UDB_TDATA1_AVAILABLE",
    "#define UDB_TDATA2_AVAILABLE",
    "#define UDB_TDATA3_AVAILABLE",
    "#define UDB_TINFO_AVAILABLE",
    "#define UDB_SCONTEXT_AVAILABLE",
    "#define UDB_MCONTEXT_AVAILABLE",
    "//#define UDB_TCONTROL_AVAILABLE",
    "//#define UDB_HCONTEXT_AVAILABLE",
    "//#define UDB_MSCONTEXT_AVAILABLE",
    "#define UDB_MCONTROL6_TRIG0_AVAILABLE",
    "#define UDB_ICOUNT_TRIG0_AVAILABLE",
    "#define UDB_ITRIGGER_TRIG0_AVAILABLE",
    "#define UDB_ETRIGGER_TRIG0_AVAILABLE",
    "#define UDB_MCONTROL6_TRIG1_AVAILABLE",
    "#define UDB_ICOUNT_TRIG1_AVAILABLE",
    "#define UDB_ITRIGGER_TRIG1_AVAILABLE",
    "#define UDB_ETRIGGER_TRIG1_AVAILABLE",
    "//#define UDB_ICOUNT_HARDWIRED_1",
    # extension availability for load/store access widths (see loadstore coverpoints)
    "//#define RV32",  # c.flw/flwsp/fsw/fswsp (Zcf)
    "#define RV64",  # lwu/ld/sd
]

INSTR_IFDEFS = {
    "sb": [],
    "sh": [],
    "sw": [],
    "lb": [],
    "lbu": [],
    "lh": [],
    "lhu": [],
    "lw": [],
    "sd": ["#ifdef RV64"],
    "lwu": ["#ifdef RV64"],
    "ld": ["#ifdef RV64"],
    "fsw": ["#ifdef F_SUPPORTED"],
    "flw": ["#ifdef F_SUPPORTED"],
    "fsd": ["#ifdef D_SUPPORTED"],
    "fld": ["#ifdef D_SUPPORTED"],
    "fsh": ["#ifdef ZFH_SUPPORTED"],
    "flh": ["#ifdef ZFH_SUPPORTED"],
    "c.sw": ["#ifdef ZCA_SUPPORTED"],
    "c.lw": ["#ifdef ZCA_SUPPORTED"],
    "c.swsp": ["#ifdef ZCA_SUPPORTED"],
    "c.lwsp": ["#ifdef ZCA_SUPPORTED"],
    "c.sd": ["#ifdef ZCA_SUPPORTED", "#ifdef RV64"],
    "c.ld": ["#ifdef ZCA_SUPPORTED", "#ifdef RV64"],
    "c.sdsp": ["#ifdef ZCA_SUPPORTED", "#ifdef RV64"],
    "c.ldsp": ["#ifdef ZCA_SUPPORTED", "#ifdef RV64"],
    "c.sb": ["#ifdef ZCB_SUPPORTED"],
    "c.sh": ["#ifdef ZCB_SUPPORTED"],
    "c.lbu": ["#ifdef ZCB_SUPPORTED"],
    "c.lh": ["#ifdef ZCB_SUPPORTED"],
    "c.lhu": ["#ifdef ZCB_SUPPORTED"],
    "c.fsw": ["#ifdef ZCF_SUPPORTED", "#ifdef RV32"],
    "c.flw": ["#ifdef ZCF_SUPPORTED", "#ifdef RV32"],
    "c.fswsp": ["#ifdef ZCF_SUPPORTED", "#ifdef RV32"],
    "c.flwsp": ["#ifdef ZCF_SUPPORTED", "#ifdef RV32"],
    "c.fsd": ["#ifdef ZCD_SUPPORTED"],
    "c.fld": ["#ifdef ZCD_SUPPORTED"],
    "c.fsdsp": ["#ifdef ZCD_SUPPORTED"],
    "c.fldsp": ["#ifdef ZCD_SUPPORTED"],
}


def add_tc(test_data: TestData, mode: str, binname: str, coverpoint: str, covergroup: str) -> str:
    """Register a testcase with its mode ("Sm"/"S"/"U") prefixed onto the bin name."""
    # Leading newline gives every testcase a blank separator line in the emitted asm.
    return "\n" + test_data.add_testcase(f"{mode}_{binname}", coverpoint, covergroup)


def _csr_access(instr: str, mode: str) -> str:
    """Accesses a CSR using an T-SBI or CSR operation based on mode"""
    if mode == "Sm":
        return instr
    else:
        return add_tsbi(instr)


def _load_tdata1(reg: int, trig_type: int, mode: str, lowfields: int = 0) -> list[str]:
    """Load tdata1 = (type << top) | lowfields into x{reg} and write it to tdata1."""
    lines = [
        "#if __riscv_xlen == 64",
        f"LI(x{reg}, 0x{(trig_type << 60) | lowfields:x})",
        "#else",
        f"LI(x{reg}, 0x{(trig_type << 28) | lowfields:x})",
        "#endif",
    ]
    if mode == "Sm":
        lines.append(f"csrw tdata1, x{reg} # write trigger type")
    else:
        lines.append(add_tsbi(f"csrw tdata1, x{reg} # write trigger type"))
    return lines


def _load_reg(reg: int, val: int | str) -> str:
    """Emit a load of ``val`` into x{reg}: ints via LI (constant), symbols via LA (address)."""
    return f"LA(x{reg}, {val})" if isinstance(val, str) else f"LI(x{reg}, 0x{val:x})"


def _arch_guard(instr: str, exts: list[str]) -> list[str]:
    """Bracket a single instruction with `.option arch, +ext...` (no-op if exts empty)."""
    if not exts:
        return [instr]
    adds = ", ".join(f"+{e.strip().lower()}" for e in exts)
    return [".option push", f".option arch, {adds}", instr, ".option pop"]


def ifdef_guard(instr: str, closing: bool = False) -> list[str]:
    """Emit the opening #ifdef guards for instr (or matching #endif when closing)."""
    ifdefs = INSTR_IFDEFS[instr]
    if closing:
        return ["#endif"] * len(ifdefs)
    return list(ifdefs)


def _disable_all_triggers(reg: int, mode: str) -> list[str]:
    """Disable every trigger by zeroing tdata1/2/3."""
    lines: list[str] = ["# disable all triggers"]
    if mode == "Sm":
        lines.append("csrci mstatus, 0x8 # MIE=0 while reconfiguring")
    elif mode == "S":
        lines.append("csrci sstatus, 0x2 # SIE=0 while reconfiguring")
    for t in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                _load_reg(reg, t),
                _csr_access(f"csrw tselect, x{reg}", mode),
                _csr_access("csrw tdata1, x0", mode),
                _csr_access("csrw tdata2, x0", mode),
                _csr_access("csrw tdata3, x0", mode),
            ]
        )
    return lines


def _arm_triggers(mode: str, arm: bool) -> list[str]:
    """Set (``arm``) or clear the interrupt-enable bit that gates action=0 triggers."""
    op = "csrsi" if arm else "csrci"
    verb = "arm" if arm else "disarm"
    if mode == "Sm":
        return [f"{op} mstatus, 0x8 # MIE={int(arm)} to {verb} M-mode trigger"]
    if mode == "S":
        return [f"{op} sstatus, 0x2 # SIE={int(arm)} to {verb} S-mode trigger"]
    return []


def _config_mcontrol6(
    reg: int,
    tselect: int,
    tdata2: int | str,
    mode: str,
    *,
    privbits: int | None = None,
    xsl: int = 0b000,
    select: int = 0,
    size: int = 0,
    match: int = 0,
    chain: int = 0,
    action: int = 0,
    tdata3: int | str = 0,
) -> list[str]:
    """Emit assembly configuring trigger ``tselect`` as an mcontrol6 trigger."""
    if privbits is None:
        privbits = MODE_PRIVBIT[mode]

    m = (privbits >> 4) & 1
    s = (privbits >> 3) & 1
    u = (privbits >> 2) & 1
    vs = (privbits >> 1) & 1
    vu = privbits & 1
    lowfields = (
        (vs << 24)
        | (vu << 23)
        | (select << 21)
        | ((size & 0b111) << 16)
        | (action << 12)
        | (chain << 11)
        | ((match & 0xF) << 7)
        | (m << 6)
        | (s << 4)
        | (u << 3)
        | (xsl & 0b111)
    )
    mcontrol6 = 6  # tdata1.type
    return [
        f"# configure trigger {tselect} as mcontrol6",
        _load_reg(reg, tselect),
        _csr_access(f"csrw tselect, x{reg}", mode),
        _csr_access("csrw tdata1, x0 # disable before configuring", mode),
        _load_reg(reg, tdata2),
        _csr_access(f"csrw tdata2, x{reg} # match value", mode),
        _load_reg(reg, tdata3),
        _csr_access(f"csrw tdata3, x{reg} # textra context matching ", mode),
        f"# tdata1: type={mcontrol6} priv={privbits:05b} xsl={xsl:03b} select={select} size={size} match={match} chain={chain}",
        *_load_tdata1(reg, mcontrol6, mode, lowfields),  # load data in tdata1
    ]


def _config_icount(
    reg: int,
    tselect: int,
    count: int,
    mode: str,
    *,
    privbits: int | None = None,
    pending: int = 0,
    action: int = 0,
    tdata3: int | str = 0,
) -> list[str]:
    """Emit assembly configuring trigger ``tselect`` as an icount trigger."""
    if privbits is None:
        privbits = MODE_PRIVBIT[mode]

    m = (privbits >> 4) & 1
    s = (privbits >> 3) & 1
    u = (privbits >> 2) & 1
    vs = (privbits >> 1) & 1
    vu = privbits & 1
    lowfields = (
        (vs << 26)
        | (vu << 25)
        | ((count & 0x3FFF) << 10)
        | (m << 9)
        | (pending << 8)
        | (s << 7)
        | (u << 6)
        | (action & 0x3F)
    )
    icount = 3  # tdata1.type
    return [
        f"# configure trigger {tselect} as icount",
        *_arm_triggers(mode, False),
        _load_reg(reg, tselect),
        _csr_access(f"csrw tselect, x{reg}", mode),
        _csr_access("csrw tdata1, x0 # disable before configuring", mode),
        _load_reg(reg, tdata3),
        _csr_access(f"csrw tdata3, x{reg} # textra", mode),
        f"# tdata1: type={icount} priv={privbits:05b} count={count} pending={pending} action={action}",
        *_load_tdata1(reg, icount, mode, lowfields),  # load data in tdata1
        *_arm_triggers(mode, True),  # arm trigger
    ]


def _generate_access_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate common trigger-CSR access tests."""
    covergroup = f"Sdtrig{mode}_access_cg"
    tc = test_data.begin_test_chunk("Access")
    lines = tc.code

    ######################################
    coverpoint = "cp_sdtrig_csr_access_common"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "Access every trigger CSR across all triggers and trigger types\n"
            "Should not cause any illegal instruction exceptions on implemented triggers",
        )
    )
    csrs = ("tdata1", "tdata2", "tdata3", "tinfo", "tcontrol", "scontext", "mcontext", "hcontext")

    type_reg, save_reg, temp_reg = test_data.int_regs.get_registers(
        3, exclude_regs=[10, 11]
    )  # exclude a0, a1 because they are used in SBI

    for trig_num in range(UDB_NUM_TRIGGERS):
        for trig_type in range(16):
            for csr in csrs:
                lines.append(f"#ifdef UDB_{csr}_AVAILABLE")
                binname = f"tselect_{trig_num}_type_{trig_type}_csr_{csr}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                        f"LI x{temp_reg}, {trig_num} # load trig_num value",
                        _csr_access(f"csrw tselect, x{temp_reg} # set tselect = trig_num", mode),
                        *_load_tdata1(type_reg, trig_type, mode),  # load tdata1 with the type
                        f"LI x{temp_reg}, -1 # load all 1's value",
                        _csr_access(f"csrr x{save_reg}, {csr} # save original value", mode),
                        _csr_access(f"csrw {csr}, x{temp_reg} # write all-1s", mode),
                        _csr_access(f"csrw {csr}, x0 # write all-0s", mode),
                        _csr_access(f"csrs {csr}, x{temp_reg} # set all-1s", mode),
                        _csr_access(f"csrc {csr}, x{temp_reg} # clear all-1s", mode),
                        _csr_access(f"csrw {csr}, x{save_reg} # write back original value", mode),
                    ]
                )
                lines.append("#endif")

    test_data.int_regs.return_registers([type_reg, save_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_native_triggers_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate native trigger breakpoint-delegation tests."""
    # covergroup = "SdtrigSm_native_triggers_cg"
    tc = test_data.begin_test_chunk("NativeTriggers")
    lines: list[str] = tc.code

    lines.append("#ifdef S_SUPPORTED")
    ######################################
    coverpoint = "cp_sdtrig_breakpoint_delegate"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "Breakpoint from a fired trigger, taken in M-mode and delegated to\nS-mode via medeleg[3]",
        )
    )

    r1, r2, addr_reg, medeleg_reg, scr_reg = test_data.int_regs.get_registers(5)

    # TODO: sweep all triggers via CSRW(tselect, trig); using trigger 0 for now
    for delegate in (0, 1):  # medeleg[3]
        medelegop = "csrs" if delegate else "csrc"
        lines.extend(
            [
                "",
                f"# --- medeleg[3] = {delegate} ---",
                "RVTEST_GOTO_MMODE",
                f"LI(x{medeleg_reg}, 8)",  # medeleg bit 3 = breakpoint
                f"{medelegop} medeleg, x{medeleg_reg}",
            ]
        )
    lines.extend(
        [
            "",
            "# restore medeleg[3]",
            f"csrc medeleg, x{medeleg_reg}",
        ]
    )
    test_data.int_regs.return_registers([r1, r2, addr_reg, medeleg_reg, scr_reg])

    lines.append("#endif")
    return [test_data.end_test_chunk()]


def _generate_a_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate A-extension load/store/AMO matching tests."""
    covergroup = "SdtrigSm_a_cg"
    tc = test_data.begin_test_chunk("AExt")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_lrsc_addr"
    ######################################
    lines.append("#ifdef ZALRSC_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 address match on lr/sc access address",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for insn in ("lr_w", "sc_w", "lr_d", "sc_d"):
                for perm in PERM_XSL:
                    binname = f"trig_num_{trig_num}_addr_{addrval}_{insn}_perm_{perm:03b}"
                    lines.extend(
                        [
                            add_tc(test_data, mode, binname, coverpoint, covergroup),
                        ]
                    )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_lrsc_data"
    ######################################
    lines.append("#ifdef ZALRSC_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 data match on lr/sc value",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for insn in ("lr_w", "sc_w", "lr_d", "sc_d"):
                for perm in PERM_XSL:
                    binname = f"trig_num_{trig_num}_data_{addrval}_{insn}_perm_{perm:03b}"
                    lines.extend(
                        [
                            add_tc(test_data, mode, binname, coverpoint, covergroup),
                        ]
                    )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_amo"
    ######################################
    lines.append("#ifdef ZAAMO_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 address match on AMO read and write portions",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for insn in ("amoswap_w", "amoswap_d"):
                for perm in PERM_XSL:
                    binname = f"trig_num_{trig_num}_addr_{addrval}_{insn}_perm_{perm:03b}"
                    lines.extend(
                        [
                            add_tc(test_data, mode, binname, coverpoint, covergroup),
                        ]
                    )
    lines.append("#endif")

    return [test_data.end_test_chunk()]


def _generate_combined_accesses_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate multi-access (vector / cm.push-pop) instruction tests."""
    covergroup = "SdtrigSm_combined_accesses_cg"
    tc = test_data.begin_test_chunk("CombinedAccesses")
    lines: list[str] = tc.code

    vsews = ("sew8", "sew16", "sew32", "sew64")

    ######################################
    coverpoint = "cp_sdtrig_vector_load_store"
    ######################################
    lines.append("#ifdef V_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 matches each element of a vector load/store as an\nindividual SEW-sized access",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for vsew in vsews:
                for size in SIZE_SEW:
                    for vperm in ("store", "load"):
                        binname = f"trig_num_{trig_num}_addr_{addrval}_{vsew}_size_{size}_{vperm}"
                        lines.extend(
                            [
                                add_tc(test_data, mode, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_vector_accesses"
    ######################################
    lines.append("#ifdef V_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "vector accesses across scratch / scratch+8 / 0 tdata2 values",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "marker8", "zero"):
            for vsew in vsews:
                for size in SIZE_SEW:
                    for vperm in ("store", "load"):
                        binname = f"trig_num_{trig_num}_addr_{addrval}_{vsew}_size_{size}_{vperm}"
                        lines.extend(
                            [
                                add_tc(test_data, mode, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_cm_pop_push"
    ######################################
    lines.append("#ifdef ZCMP_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 matches each XLEN store of cm.push / cm.pop",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "marker8", "zero"):
            for insn in ("cm_push", "cm_pop"):
                for size in SIZE_ALL:
                    for perm in ("store", "load"):
                        binname = f"trig_num_{trig_num}_addr_{addrval}_{insn}_size_{size}_{perm:03b}"
                        lines.extend(
                            [
                                add_tc(test_data, mode, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    return [test_data.end_test_chunk()]


def _generate_cache_operations_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate Zicbo* cache-operation matching tests."""
    covergroup = "SdtrigSm_cache_operations_cg"
    tc = test_data.begin_test_chunk("CacheOps")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_cache_zicbom"
    ######################################
    lines.append("#ifdef ZICBOM_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "cbo.clean/flush/inval match as stores",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for insn in ("cbo_clean", "cbo_flush", "cbo_inval"):
            for addrval in ("marker", "zero"):
                for size in SIZE_ALL:
                    for perm in PERM_XSL:
                        binname = f"trig_num_{trig_num}_{insn}_addr_{addrval}_size_{size}_perm_{perm:03b}"
                        lines.extend(
                            [
                                add_tc(test_data, mode, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_cache_zicboz"
    ######################################
    lines.append("#ifdef ZICBOZ_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "cbo.zero matches as a store",
        )
    )
    for addrval in ("marker", "zero"):
        for size in SIZE_ALL:
            for perm in PERM_XSL:
                binname = f"cbo_zero_addr_{addrval}_size_{size}_perm_{perm:03b}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                    ]
                )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_cache_zicbop"
    ######################################
    lines.append("#ifdef ZICBOP_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "prefetch.i/r/w (HINTs) do not match",
        )
    )
    for insn in ("prefetch_i", "prefetch_r", "prefetch_w"):
        binname = f"{insn}"
        lines.extend(
            [
                add_tc(test_data, mode, binname, coverpoint, covergroup),
            ]
        )
    lines.append("#endif")

    return [test_data.end_test_chunk()]


def _generate_address_matches_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate tdata2 address-storage / translation tests."""
    covergroup = "SdtrigSm_address_matches_cg"
    tc = test_data.begin_test_chunk("AddressMatches")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_tdata2_translate"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tdata2 holds full-width virtual/physical addresses across satp modes;\nhigh bit reads back",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        # RV64 satp modes; RV32 uses (bare, sv32)
        for satp in ("bare", "sv39", "sv48", "sv57"):
            for msb in (0, 1):  # tdata2 high bit
                binname = f"trig_num_{trig_num}_satp_{satp}_msb_{msb}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                    ]
                )

    return [test_data.end_test_chunk()]


def _generate_csr_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate trigger-module register semantics tests."""
    covergroup = "SdtrigSm_csr_cg"
    tc = test_data.begin_test_chunk("Csr")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_tselect_trigs"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tselect selects contiguous triggers starting at 0; read tinfo",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                add_tc(test_data, mode, f"trig_num_{trig_num}_tinfo", coverpoint, covergroup),
            ]
        )

    ######################################
    coverpoint = "cp_sdtrig_tdata_write"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "writing one tdata register does not disturb the others",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for csr in ("tdata1", "tdata2", "tdata3"):
            binname = f"trig_num_{trig_num}_write_{csr}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_csr_smode_access"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "S-mode access to M-only trigger CSRs raises illegal instruction",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for csr in ("tdata1", "tdata2", "tdata3", "tinfo", "tcontrol", "mcontext", "hcontext"):
            binname = f"trig_num_{trig_num}_smode_{csr}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_tdata1_mode_hardwired"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "type-0 dmode/data fields hard-wired to 0",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for priv in range(32):  # priv_all: all 32 m/s/u/vs/vu enable combinations
            binname = f"trig_num_{trig_num}_priv_{priv:05b}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_tinfo_read_only"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tinfo is read-only",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                add_tc(test_data, mode, f"trig_num_{trig_num}_tinfo", coverpoint, covergroup),
            ]
        )

    ######################################
    coverpoint = "cp_sdtrig_tcontrol_enable"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tcontrol.mte gates M-mode trigger firing",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for mte in (0, 1):  # tcontrol[3]
            binname = f"trig_num_{trig_num}_mte_{mte}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_tcontrol_mtrap"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mte/mpte updated on trap into M-mode",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for mte in (0, 1):  # tcontrol[3]
            for mpte in (0, 1):  # tcontrol[7]
                binname = f"trig_num_{trig_num}_mte_{mte}_mpte_{mpte}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_tcontrol_mret"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mte restored from mpte on mret",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for mte in (0, 1):  # tcontrol[3]
            for mpte in (0, 1):  # tcontrol[7]
                binname = f"trig_num_{trig_num}_mte_{mte}_mpte_{mpte}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_mscontext_alias"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mscontext aliases scontext",
        )
    )
    lines.extend(
        [
            add_tc(test_data, mode, "alias", coverpoint, covergroup),
        ]
    )

    ######################################
    coverpoint = "cp_sdtrig_mcontext_smode"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "S-mode access to mcontext raises illegal instruction",
        )
    )
    lines.extend(
        [
            add_tc(test_data, mode, "mcontext", coverpoint, covergroup),
        ]
    )

    return [test_data.end_test_chunk()]


def _generate_mcontrol6_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate mcontrol6 address/data match trigger tests."""
    covergroup = "SdtrigSm_mcontrol6_cg"
    tc = test_data.begin_test_chunk("Mcontrol6")
    lines: list[str] = tc.code
    lines.extend([*_arm_triggers(mode, True)])

    # setup registers
    sp_reg, addr_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        4, exclude_regs=[2], reg_range=list(range(8, 16))
    )

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_priv_mode"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires on a sw when the privilege bit corresponding to mode is enabled",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for priv in range(32):
            binname = f"trig_num_{trig_num}_priv_{priv:05b}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(temp_reg, trig_num, "scratch", mode, privbits=priv, xsl=0b010, select=0),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, 0x12345678)",
                    f"sw x{data_reg}, 0(x{addr_reg}) # fire trigger if applicable",
                ]
            )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_execute_adr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when PC == tdata2 ",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for perm in range(8):  # perm_xsl
            label = f"exec_adr_trig_num_{trig_num}_xls_{perm:03b}"
            binname = f"trig_num_{trig_num}_exec_adr_fire_perm_{perm:03b}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(temp_reg, trig_num, label, mode, privbits=0b10000, xsl=perm, select=0),
                    f"{label}:",
                    "add x0, x1, x2 # execute here; PC == tdata2",
                ]
            )
            binname = f"trig_num_{trig_num}_exec_adr_nofire_perm_{perm:03b}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(temp_reg, trig_num, 0, mode, privbits=0b10000, xsl=perm, select=0),
                    "add x0, x1, x2 # execute here; PC == tdata2",
                ]
            )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_load_store_adr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when access address == tdata2 (select=address)",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for tdata2 in ("scratch", 0):
            for perm in range(8):  # perm_xsl
                binname = f"trig_num_{trig_num}_td2_{tdata2}_perm_{perm:03b}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=perm, select=0),
                        f"LA(x{addr_reg}, scratch) # x{addr_reg} = &scratch",
                        f"LI(x{data_reg}, 0x12345678)",
                        f"sw x{data_reg}, 0(x{addr_reg}) # store: breakpoint iff addr==tdata2 and xsl has store bit",
                        "nop # spacer",
                        f"lw x{data_reg}, 0(x{addr_reg}) # fire iff addr==tdata2 and xsl has load bit",
                        "nop # spacer",
                    ]
                )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_execute_data"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when instruction encoding == tdata2 (select=data)",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for tdata2 in (
            NOP,
            TDATA2_NOFIRE,
        ):  # tdata2=NOP; executed word is NOTANOP to prove spike matches 16-bit parcels
            for perm in range(8):  # perm_xsl
                binname = f"trig_num_{trig_num}_exec_data_td2_{tdata2}_perm_{perm:03b}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=perm, select=1),
                        "nop # fire trigger when opcode==tdata2",
                        "add   x0, x1, x2 # spacer (nop here would match tdata2)",
                        "add   x0, x1, x2 # spacer (nop here would match tdata2)",
                    ]
                )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_load_store_data"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when load/store data == tdata2 (select=data)",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for tdata2 in (0x12345678, TDATA2_NOFIRE):
            for perm in range(8):  # perm_xsl
                binname = f"trig_num_{trig_num}_td2_{tdata2}_perm_{perm:03b}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=perm, select=1),
                        f"LA(x{addr_reg}, scratch) # x{addr_reg} = &scratch",
                        f"LI(x{data_reg}, 0x12345678)",
                        f"sw x{data_reg}, 0(x{addr_reg}) # store: breakpoint iff data==tdata2 and xsl has store bit",
                        "nop # spacer (data match fires after)",
                        f"lw x{data_reg}, 0(x{addr_reg}) # fire iff data==tdata2 and xsl has load bit",
                        "nop # spacer (data match fires after)",
                    ]
                )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_execute_size"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 execute match across access sizes",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for tdata2 in (NOP, C_NOP):  # tdata2_nop_sizes
            for size in range(7):
                bin1 = f"trig_num_{trig_num}_td2_{tdata2}_insn_nop_size_{size}"
                bin2 = f"trig_num_{trig_num}_td2_{tdata2}_insn_c.nop_size_{size}"
                lines.extend(
                    [
                        add_tc(test_data, mode, bin1, coverpoint, covergroup),
                        *_config_mcontrol6(
                            temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b100, select=1, size=size
                        ),
                        "nop",
                        "add   x0, x1, x2 # spacer (nop here would match tdata2)",
                        "add   x0, x1, x2 # spacer (nop here would match tdata2)",
                    ]
                )
                lines.extend(
                    [
                        "#ifdef ZCA_SUPPORTED",
                        add_tc(test_data, mode, bin2, coverpoint, covergroup),
                        *_config_mcontrol6(
                            temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b100, select=1, size=size
                        ),
                        *_arch_guard("c.nop", ["zca"]),
                        "add   x0, x1, x2 # spacer (nop here would match tdata2)",
                        "add   x0, x1, x2 # spacer (nop here would match tdata2)",
                        "#endif",
                    ]
                )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_load_store_size"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 load/store match across access sizes",
        )
    )

    # enable mstatus.FS (bits 14:13) so the fp loads/stores below don't trap as illegal,
    lines.extend(
        [
            f"LI(x{temp_reg}, 0x6000)",
            _csr_access(f"csrs mstatus, x{temp_reg}", mode),
            f"LA(x{addr_reg}, scratch)",
            f"LI(x{data_reg}, 0x12345678)",
        ]
    )

    instr_asm = {
        "sb": [f"sb x{data_reg}, 0(x{addr_reg})", []],
        "sh": [f"sh x{data_reg}, 0(x{addr_reg})", []],
        "sw": [f"sw x{data_reg}, 0(x{addr_reg})", []],
        "lb": [f"lb x{data_reg}, 0(x{addr_reg})", []],
        "lbu": [f"lbu x{data_reg}, 0(x{addr_reg})", []],
        "lh": [f"lh x{data_reg}, 0(x{addr_reg})", []],
        "lhu": [f"lhu x{data_reg}, 0(x{addr_reg})", []],
        "lw": [f"lw x{data_reg}, 0(x{addr_reg})", []],
        "sd": [f"sd x{data_reg}, 0(x{addr_reg})", []],
        "lwu": [f"lwu x{data_reg}, 0(x{addr_reg})", []],
        "ld": [f"ld x{data_reg}, 0(x{addr_reg})", []],
        "fsw": [f"fsw f{data_reg}, 0(x{addr_reg})", ["f"]],
        "flw": [f"flw f{data_reg}, 0(x{addr_reg})", ["f"]],
        "fsd": [f"fsd f{data_reg}, 0(x{addr_reg})", ["d"]],
        "fld": [f"fld f{data_reg}, 0(x{addr_reg})", ["d"]],
        "fsh": [f"fsh f{data_reg}, 0(x{addr_reg})", ["zfh"]],
        "flh": [f"flh f{data_reg}, 0(x{addr_reg})", ["zfh"]],
        "c.sw": [f"c.sw x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.lw": [f"c.lw x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.swsp": [f"c.swsp x{data_reg}, 0(sp)", ["zca"]],
        "c.lwsp": [f"c.lwsp x{data_reg}, 0(sp)", ["zca"]],
        "c.sd": [f"c.sd x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.ld": [f"c.ld x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.sdsp": [f"c.sdsp x{data_reg}, 0(sp)", ["zca"]],
        "c.ldsp": [f"c.ldsp x{data_reg}, 0(sp)", ["zca"]],
        "c.sb": [f"c.sb x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.sh": [f"c.sh x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.lbu": [f"c.lbu x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.lh": [f"c.lh x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.lhu": [f"c.lhu x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.fsw": [f"c.fsw f{data_reg}, 0(x{addr_reg})", ["zcf"]],
        "c.flw": [f"c.flw f{data_reg}, 0(x{addr_reg})", ["zcf"]],
        "c.fswsp": [f"c.fswsp f{data_reg}, 0(sp)", ["zcf"]],
        "c.flwsp": [f"c.flwsp f{data_reg}, 0(sp)", ["zcf"]],
        "c.fsd": [f"c.fsd f{data_reg}, 0(x{addr_reg})", ["zcd"]],
        "c.fld": [f"c.fld f{data_reg}, 0(x{addr_reg})", ["zcd"]],
        "c.fsdsp": [f"c.fsdsp f{data_reg}, 0(sp)", ["zcd"]],
        "c.fldsp": [f"c.fldsp f{data_reg}, 0(sp)", ["zcd"]],
    }

    # get the 64-bit token into f{data_reg}: fmv.d.x on RV64; via memory on RV32
    fp_d_data_setup = [
        "#ifdef RV64",
        *_arch_guard(f"fmv.d.x f{data_reg}, x{data_reg}", ["d"]),
        "#endif",
        "#ifdef RV32",
        f"sw x{data_reg}, 0(x{addr_reg})",
        f"sw x0, 4(x{addr_reg})",
        *_arch_guard(f"fld f{data_reg}, 0(x{addr_reg})", ["d"]),
        "#endif",
    ]

    instr_setup_asm = {
        "fsw": [
            *_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"]),
        ],
        "flw": [
            *_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"]),
        ],
        "fsd": [
            *fp_d_data_setup,
        ],
        "fld": [
            *fp_d_data_setup,
        ],
        "fsh": [
            *_arch_guard(f"fmv.h.x f{data_reg}, x{data_reg}", ["zfh"]),
        ],
        "flh": [
            *_arch_guard(f"fmv.h.x f{data_reg}, x{data_reg}", ["zfh"]),
        ],
        "c.fsw": [*_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"])],
        "c.flw": [*_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"])],
        "c.fswsp": [
            *_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"]),
            f"mv x{sp_reg}, sp",
            "LA(sp, scratch)",
        ],
        "c.flwsp": [
            *_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"]),
            f"mv x{sp_reg}, sp",
            "LA(sp, scratch)",
        ],
        "c.fsd": fp_d_data_setup,
        "c.fld": fp_d_data_setup,
        "c.fsdsp": [
            *fp_d_data_setup,
            f"mv x{sp_reg}, sp",
            "LA(sp, scratch)",
        ],
        "c.fldsp": [
            *fp_d_data_setup,
            f"mv x{sp_reg}, sp",
            "LA(sp, scratch)",
        ],
        # sp-relative accesses must NOT use the framework sp (x2 = signature
        # pointer; a c.swsp there clobbers the preloaded self-check reference).
        # Park sp at scratch for the access, restore it in instr_teardown_asm.
        "c.swsp": [f"mv x{sp_reg}, sp", "LA(sp, scratch)"],
        "c.lwsp": [f"mv x{sp_reg}, sp", "LA(sp, scratch)"],
        "c.sdsp": [f"mv x{sp_reg}, sp", "LA(sp, scratch)"],
        "c.ldsp": [f"mv x{sp_reg}, sp", "LA(sp, scratch)"],
    }

    instr_teardown_asm = {
        "c.swsp": [f"mv sp, x{sp_reg}"],
        "c.lwsp": [f"mv sp, x{sp_reg}"],
        "c.sdsp": [f"mv sp, x{sp_reg}"],
        "c.ldsp": [f"mv sp, x{sp_reg}"],
        "c.fswsp": [f"mv sp, x{sp_reg}"],
        "c.flwsp": [f"mv sp, x{sp_reg}"],
        "c.fsdsp": [f"mv sp, x{sp_reg}"],
        "c.fldsp": [f"mv sp, x{sp_reg}"],
    }

    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        for tdata2 in ("scratch", 0):
            # for size in (0):  TODO change to (0, 1, 2, 3, 5), spike only supports size = 0
            size = 0
            lines.extend(
                [
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, select=0, size=size
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, 0x12345678)",
                ]
            )
            for instr in instr_asm:
                binname = f"trig_num_{trig_num}_td2_{tdata2}_size_{size}_instr_{instr}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                        *ifdef_guard(instr),
                        *instr_setup_asm.get(instr, []),
                        *_arch_guard(instr_asm[instr][0], instr_asm[instr][1]),
                        "nop # spacer",
                        *instr_teardown_asm.get(instr, []),
                        *ifdef_guard(instr, closing=True),
                    ]
                )
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_match"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 match types equal / ge / lt / not-equal",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        # for match in (0, 2, 3, 8): TODO Add once sail supported
        match = 0
        lines.append("#ifdef RV32")
        for data in (0x00000000, 0x12345677, 0x12345678, 0x12345679, 0xFFFFFFFF):
            binname = f"RV32_trig_num_{trig_num}_match_{match}_data_{data}"
            tdata2 = 0x12345678
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, match=match, select=1
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {data})",
                    f"sw x{data_reg}, 0(x{addr_reg})",
                    "nop # spacer (data match fires after)",
                ]
            )
        lines.append("#endif")
        lines.append("#ifdef RV64")
        for data in (
            0x0000000000000000,
            0x123456789ABCDEEF,
            0x123456789ABCDEF0,
            0x123456789ABCDEF1,
            0xFFFFFFFFFFFFFFFF,
        ):
            binname = f"RV64_trig_num_{trig_num}_match_{match}_data_{data}"
            tdata2 = 0x123456789ABCDEF0
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, match=match, select=1
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {data})",
                    f"sd x{data_reg}, 0(x{addr_reg})",
                    "nop # spacer (data match fires after)",
                ]
            )
        lines.append("#endif")
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_match_napot"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 NAPOT and not-NAPOT match types",
        )
    )

    def walking_zeros(xlen: int) -> list[str]:
        values = []
        all_ones = (1 << xlen) - 1  # e.g. 0xFFFF...F for xlen bits
        for i in range(xlen):
            values.append(hex(all_ones & ~(1 << i)))  # clear bit i
        return values

    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        # for match in (1, 9): TODO Add once sail supported
        match = 0
        lines.append("#ifdef RV32")
        for data in (0x00000000, 0x12345678, 0xFFFFFFFF, *walking_zeros(32)):
            binname = f"RV32_trig_num_{trig_num}_match_{match}_data_{data}"
            tdata2 = 0xFFFFFFFF
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, match=match, select=1
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {data})",
                    f"sw x{data_reg}, 0(x{addr_reg})",
                    "nop # spacer (data match fires after)",
                ]
            )
        lines.append("#endif")
        lines.append("#ifdef RV64")
        for data in (0x0000000000000000, 0x123456789ABCDEF0, 0xFFFFFFFFFFFFFFFF, *walking_zeros(64)):
            binname = f"RV64_trig_num_{trig_num}_match_{match}_data_{data}"
            tdata2 = 0xFFFFFFFFFFFFFFFF
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, match=match, select=1
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {data})",
                    f"sd x{data_reg}, 0(x{addr_reg})",
                    "nop # spacer (data match fires after)",
                ]
            )
        lines.append("#endif")
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_match_mask"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 mask-low / mask-high match types",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")
        # for match in (4, 5, 12, 13): TODO Add once sail supported
        match = 0
        lines.append("#ifdef RV32")
        for data in (0x00000000, 0x12345678, 0xFFFF5678, 0x1234FFFF, 0xFFFFFFFF):
            binname = f"RV32_trig_num_{trig_num}_match_{match}_data_{data}"
            tdata2 = 0x12345678
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, match=match, select=1
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {data})",
                    f"sw x{data_reg}, 0(x{addr_reg})",
                    "nop # spacer (data match fires after)",
                ]
            )
        lines.append("#endif")
        lines.append("#ifdef RV64")
        for data in (
            0x0000000000000000,
            0x123456789ABCDEF0,
            0xFFFFFFFF9ABCDEF0,
            0x12345678FFFFFFFF,
            0xFFFFFFFFFFFFFFFF,
        ):
            binname = f"RV64_trig_num_{trig_num}_match_{match}_data_{data}"
            tdata2 = 0x123456789ABCDEF0
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    *_config_mcontrol6(
                        temp_reg, trig_num, tdata2, mode, privbits=0b10000, xsl=0b011, match=match, select=1
                    ),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {data})",
                    f"sd x{data_reg}, 0(x{addr_reg})",
                    "nop # spacer (data match fires after)",
                ]
            )
        lines.append("#endif")
        lines.append(f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_chain_adr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "chained mcontrol6 triggers fire only when both match the same\n"
            "instruction (trig0 chain=1 address, trig1 chain=0 data)",
        )
    )
    # chain uses fixed triggers 0 and 1 (chain_pair/select_pair are single-bin)
    lines.append("#if UDB_NUM_TRIGGERS > 1")
    lines.append("#ifdef UDB_MCONTROL6_TRIG0_AVAILABLE")
    lines.append("#ifdef UDB_MCONTROL6_TRIG1_AVAILABLE")
    lines.extend(
        [
            *_config_mcontrol6(temp_reg, 0, "scratch", mode, privbits=0b10000, xsl=0b010, select=0, chain=1),
            *_config_mcontrol6(temp_reg, 1, 0x12345678, mode, privbits=0b10000, xsl=0b010, select=1, chain=0),
            f"LA(x{addr_reg}, scratch)",
        ]
    )
    # sweep data-match x addr-match; only both-match fires the chained pair
    for data in (0x12345678, 0):
        for offset in (0, 8):
            binname = f"data_{data}_adr_offset_{offset}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                    f"LI(x{data_reg}, {data})",
                    f"sw x{data_reg}, {offset}(x{addr_reg}) # fire trigger when both triggers match",
                    "nop # spacer (data match fires after)",
                ]
            )
    lines.append("#endif")
    lines.append("#endif")
    lines.append("#endif")

    lines.extend(
        [
            *_disable_all_triggers(temp_reg, mode),
        ]
    )
    test_data.int_regs.return_registers([sp_reg, addr_reg, data_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_icount_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate icount instruction-count trigger tests."""
    covergroup = "SdtrigSm_icount_cg"
    tc = test_data.begin_test_chunk("Icount")
    lines: list[str] = tc.code
    lines.append("#ifdef UDB_ICOUNT_SUPPORTED")

    # setup registers
    sp_reg, addr_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        4, exclude_regs=[2, 10, 11], reg_range=list(range(8, 16))
    )  # exclude a0, a1 because they are used in SBI

    ######################################
    coverpoint = "cp_sdtrig_icount_hardwired"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount priv/action hard-wired field behavior",
        )
    )
    lines.append("#ifdef UDB_ICOUNT_HARDWIRED_1")
    for trig_num in range(UDB_NUM_TRIGGERS):
        binname = f"trig_num_{trig_num}"
        lines.extend(
            [
                add_tc(test_data, mode, binname, coverpoint, covergroup),
                *_config_icount(temp_reg, trig_num, 1, mode),
                "nop # decrement count",
                _csr_access(f"csrr x{data_reg}, tdata1 # read back hardwired fields", mode),
                f"LI(x{temp_reg}, 0x1000000) # icount hit bit (bit 24)",
                f"not x{temp_reg}, x{temp_reg}",
                f"and x{data_reg}, x{data_reg}, x{temp_reg} # mask out optional hit bit",
                write_sigupd(data_reg, test_data),
            ]
        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_icount_instr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount fires after count instructions",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        binname = f"trig_num_{trig_num}"
        lines.extend(
            [
                add_tc(test_data, mode, binname, coverpoint, covergroup),
                *_config_icount(temp_reg, trig_num, 9, mode),
                *["nop # decrement count"] * 9,
                "nop # spacer",
                _csr_access(f"csrr x{data_reg}, tdata1 # read back hardwired fields", mode),
                f"LI(x{temp_reg}, 0x1000000) # icount hit bit (bit 24)",
                f"not x{temp_reg}, x{temp_reg}",
                f"and x{data_reg}, x{data_reg}, x{temp_reg} # mask out optional hit bit",
                write_sigupd(data_reg, test_data),
            ]
        )

    ######################################
    coverpoint = "cp_sdtrig_icount_trap"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount count decrement across a trap",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        binname = f"trig_num_{trig_num}"
        lines.extend(
            [
                add_tc(test_data, mode, binname, coverpoint, covergroup),
                *_config_icount(temp_reg, trig_num, 9, mode),
            ]
        )

    ######################################
    coverpoint = "cp_sdtrig_icount_eq0"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount pending bit when count reaches 0",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for pending in (0, 1):  # tdata1[8]
            binname = f"trig_num_{trig_num}_pending_{pending}"
            lines.extend(
                [
                    add_tc(test_data, mode, binname, coverpoint, covergroup),
                ]
            )

    lines.append("#endif")  # endif ICOUNT_SUPPORTED

    test_data.int_regs.return_registers([sp_reg, addr_reg, data_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_itrigger_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate itrigger interrupt trigger tests."""
    covergroup = "SdtrigSm_itrigger_cg"
    tc = test_data.begin_test_chunk("Itrigger")
    lines: list[str] = tc.code
    lines.append("#ifdef UDB_ITRIGGER_SUPPORTED")

    # one-hot tdata2 interrupt-code bins (RV64 / no-H spelling)
    intcode = ("ssi", "msi", "sti", "mti", "sei", "mei", "lcofi")

    ######################################
    coverpoint = "cp_sdtrig_itrigger"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "itrigger fires on each interrupt cause in the tdata2 mask",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for code in intcode:
            for priv in range(32):  # itrigger_priv_all
                for hit in ("nofire", "fire"):
                    for tval in ("zero", "nonzero"):  # tval_zero
                        binname = f"trig_num_{trig_num}_code_{code}_priv_{priv:05b}_hit_{hit}_tval_{tval}"
                        lines.extend(
                            [
                                add_tc(test_data, mode, binname, coverpoint, covergroup),
                            ]
                        )

    ######################################
    coverpoint = "cp_sdtrig_itrigger_nmi"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "itrigger nmi bit",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for code in intcode:
            for priv in range(32):  # itrigger_priv_all
                for nmi in ("off", "on"):  # tdata1[10]
                    binname = f"trig_num_{trig_num}_code_{code}_priv_{priv:05b}_nmi_{nmi}"
                    lines.extend(
                        [
                            add_tc(test_data, mode, binname, coverpoint, covergroup),
                        ]
                    )

    lines.append("#endif")  # endif ITRIGGER_SUPPORTED
    return [test_data.end_test_chunk()]


def _generate_etrigger_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate etrigger exception trigger tests."""
    covergroup = "SdtrigSm_etrigger_cg"
    tc = test_data.begin_test_chunk("Etrigger")
    lines: list[str] = tc.code
    lines.append("#ifdef UDB_ETRIGGER_SUPPORTED")

    ######################################
    coverpoint = "cp_sdtrig_etrigger"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "etrigger fires on each exception cause in the tdata2 mask",
        )
    )
    # one-hot tdata2 exception-code bins (base set; U/S/H/etc. gated in svh)
    excode = ("iam", "iacc", "ill", "bp", "lam", "lacc", "sam", "sacc", "ecu", "ecs", "ecm", "ipf", "lpf", "spf")
    for trig_num in range(UDB_NUM_TRIGGERS):
        for code in excode:
            for priv in range(32):  # etrigger_priv_all
                for tval in ("zero", "nonzero"):  # tval_zero
                    binname = f"trig_num_{trig_num}_code_{code}_priv_{priv:05b}_tval_{tval}"
                    lines.extend(
                        [
                            add_tc(test_data, mode, binname, coverpoint, covergroup),
                        ]
                    )

    lines.append("#endif")  # endif ETRIGGER_SUPPORTED
    return [test_data.end_test_chunk()]


def _generate_textra_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate textra32/64 (tdata3) context-matching tests."""
    covergroup = "SdtrigSm_textra_cg"
    tc = test_data.begin_test_chunk("Textra")
    lines: list[str] = tc.code

    trig_type4 = ("icount", "itrigger", "etrigger", "mcontrol6")
    # RV64 spelling; RV32 bins differ (see svh)
    mhvalue = ("match", "zero", "half")
    svalue = ("aaaaaaaa", "bbbbbbaa", "bbbbaabb", "bbaabbbb", "aabbbbbb", "bbbbbbbb")
    svalue_asid = ("below", "equal", "above")

    ######################################
    coverpoint = "cp_sdtrig_textra_mcontext"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "textra mhselect/mhvalue match against mcontext",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for tt in trig_type4:
            for mhv in mhvalue:
                binname = f"trig_num_{trig_num}_type_{tt}_mhvalue_{mhv}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_textra_scontext"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "textra sselect=scontext svalue/sbytemask match against scontext",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for tt in trig_type4:
            for sv in svalue:
                for mask in range(4):  # sbytemask (RV64: 4 bits; RV32: 2 bits -> range(4))
                    binname = f"trig_num_{trig_num}_type_{tt}_svalue_{sv}_mask_{mask:02b}"
                    lines.extend(
                        [
                            add_tc(test_data, mode, binname, coverpoint, covergroup),
                        ]
                    )

    ######################################
    coverpoint = "cp_sdtrig_textra_asid"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "textra sselect=asid match against satp.ASID",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for tt in trig_type4:
            for sv in svalue_asid:
                binname = f"trig_num_{trig_num}_type_{tt}_asid_{sv}"
                lines.extend(
                    [
                        add_tc(test_data, mode, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_smode_fields_hardwired"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "svalue/sselect read 0 when S-mode is not supported",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                add_tc(test_data, mode, f"trig_num_{trig_num}_hardwired", coverpoint, covergroup),
            ]
        )

    return [test_data.end_test_chunk()]


# ── Suite assembly ─────────────────────────────────────────────────────────


def generate_sdtrig_suite(test_data: TestData, mode: str) -> list[TestChunk]:
    """Assemble the full Sdtrig suite for ``mode`` ("Sm"/"S"/"U") as test chunks."""
    test_chunks: list[TestChunk] = []
    test_chunks.extend(_generate_access_tests(test_data, mode))
    # test_chunks.extend(_generate_native_triggers_tests(test_data, mode))
    # test_chunks.extend(_generate_a_tests(test_data, mode))
    # test_chunks.extend(_generate_combined_accesses_tests(test_data, mode))
    # test_chunks.extend(_generate_cache_operations_tests(test_data, mode))
    # test_chunks.extend(_generate_address_matches_tests(test_data, mode))
    # test_chunks.extend(_generate_csr_tests(test_data, mode))
    test_chunks.extend(_generate_mcontrol6_tests(test_data, mode))
    test_chunks.extend(_generate_icount_tests(test_data, mode))
    # test_chunks.extend(_generate_itrigger_tests(test_data, mode))
    # test_chunks.extend(_generate_etrigger_tests(test_data, mode))
    # test_chunks.extend(_generate_textra_tests(test_data, mode))
    return test_chunks
