##################################
# SdtrigCommon.py
#
# Sdtrig (debug triggers) shared test-case generators.
# pclark@hmc.edu Jul 2026
# SPDX-License-Identifier: Apache-2.0
##################################

"""Shared Sdtrig debug-trigger test-case generators."""

from random import seed

from testgen.asm.helpers import comment_banner, reproducible_hash, write_sigupd
from testgen.asm.tsbi import tsbi_call
from testgen.data.random import random_int
from testgen.data.state import TestData
from testgen.data.test_chunk import TestChunk
from testgen.priv.extensions.Sstvala import (
    _VA_PF_PAGE_RV32,
    _VA_PF_PAGE_RV64,
    _generate_page_table_data_section,
    _pf_pte_setup_sv32,
    _pf_pte_setup_sv39,
)

# data
PERM_XSL = ("exec", "store", "load")
SIZE_ALL = ("any", "b8", "b16", "b32", "b48", "b64", "b128")
SIZE_SEW = ("any", "s8", "s16", "s32", "s64", "s128")
UDB_NUM_TRIGGERS = 2  # TODO: Relate to UDB
NOP = 0x00000013
C_NOP = 0x0001
ADDI_HINT = 0x00008013  # TODO Uses because U mode calls trigger on nops emitted by tsbi callss
TDATA2_NOFIRE = 0x2
MODE_PRIVBIT = {"Sm": 0b10000, "S": 0b01000, "U": 0b00100, "Vs": 0b00010, "Vu": 0b00001}
MODE_UDB_LETTER = {"Sm": "M", "S": "S", "U": "U", "Vs": "VS", "Vu": "VU"}

_PAGE_FAULT_CODES = (12, 13, 15)

# MPRV=1, MPP=U: next M-mode load/store is translated as U-mode (needed for codes 13/15 when mode="Sm").
_MSTATUS_MPP_MASK = 0x1800
_MSTATUS_MPRV = 0x20000

# Fetch-type codes: a trigger bp here leaves xEPC unfetchable.
_FETCH_EXCODES = (0, 1, 12)

# maps mcause exception code -> short mnemonic used in binnames / ifdef names
ETRIGGER_EXCODE_NAMES = {
    0: "iaf",
    1: "iacc",
    2: "ill",
    3: "bp",
    4: "lam",
    5: "lacc",
    6: "sam",
    7: "sacc",
    8: "ecu",
    9: "ecs",
    11: "ecm",
    12: "ipf",
    13: "lpf",
    15: "spf",
}

# TODO: replace this with UDB-autogenerated parameters.
UDB_DEFINES = [
    f"#define UDB_NUM_TRIGGERS {UDB_NUM_TRIGGERS}",
    # CSR Params
    "#define UDB_TDATA1_AVAILABLE",
    "#define UDB_TDATA2_AVAILABLE",
    "#define UDB_TDATA3_AVAILABLE",
    "#define UDB_TINFO_AVAILABLE",
    "#define UDB_SCONTEXT_AVAILABLE",
    "#define UDB_MCONTEXT_AVAILABLE",
    "//#define UDB_TCONTROL_AVAILABLE",
    "//#define UDB_HCONTEXT_AVAILABLE",
    "//#define UDB_MSCONTEXT_AVAILABLE",
    # MCONTROl6 params
    "#define UDB_SDTRIG_MCONTROL6_SUPPORTED0",
    "#define UDB_SDTRIG_MCONTROL6_SUPPORTED1",
    "#define UDB_SDTRIG_MCONTROL6_SUPPORTED2",
    "#define UDB_SDTRIG_MCONTROL6_SUPPORTED3",
    f"#define UDB_SDTRIG_NUM_TRIGGERS {UDB_NUM_TRIGGERS}",
    "#define UDB_SDTRIG_MASKMAX6 63",
    "#define UDB_SDTRIG_MCONTROL6_CHAIN_AVAILABLE",
    "#define UDB_SDTRIG_MCONTROL6_EXECUTE_AVAILABLE",
    "#define UDB_SDTRIG_MCONTROL6_LOAD_AVAILABLE",
    "//#define UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE",
    "#define UDB_SDTRIG_MCONTROL6_SELECT_AVAILABLE",
    "//#define UDB_SDTRIG_MCONTROL6_SIZE_AVAILABLE",
    "#define UDB_SDTRIG_MCONTROL6_STORE_AVAILABLE",
    "#define UDB_SDTRIG_M_AVAILABLE",
    "#define UDB_SDTRIG_S_AVAILABLE",
    "#define UDB_SDTRIG_U_AVAILABLE",
    "#define UDB_SDTRIG_VS_AVAILABLE",
    "#define UDB_SDTRIG_VU_AVAILABLE",
    # Etrigger params
    *[f"#define UDB_SDTRIG_ETRIGGER_SUPPORTED{i}" for i in range(UDB_NUM_TRIGGERS)],
    *[f"#define UDB_EXCEPTION_{name.upper()}_SUPPORTED" for name in ETRIGGER_EXCODE_NAMES.values()],
    "#define UDB_SDTRIG_HIT_IMPLEMENTED",
    # Sims that do not follow Suggested Trigger Timing in spec or fires several cycles after will mismatch MEPC in trap handler
    # "#define SDTRIG_IMPRECISE_XEPC", # Remove if traphandler changes are correct
    "#define SDTRIG_TRIGGER_BP_HANDLING",  # replaces SDTRIG_IMPRECISE_XEPC
]

XSL_UDB_NAMES = ("LOAD", "STORE", "EXECUTE")  # mcontrol6 xsl bits 0, 1, 2


def _xsl_ifdefs(xsl: int) -> list[str]:
    """One ``#ifdef`` per mcontrol6 x/s/l capability ``xsl`` uses; empty list when xsl == 0."""
    ifdefs: list[str] = []
    if xsl > 0:
        for i, name in enumerate(XSL_UDB_NAMES):
            if xsl >> i & 1:
                prefix = "\n" if not ifdefs else ""
                ifdefs.append(f"{prefix}#ifdef UDB_SDTRIG_MCONTROL6_{name}_AVAILABLE")
    return ifdefs


INSTR_IFDEFS = {
    "sb": [],
    "sh": [],
    "sw": [],
    "lb": [],
    "lbu": [],
    "lh": [],
    "lhu": [],
    "lw": [],
    "sd": ["#if __riscv_xlen == 64"],
    "lwu": ["#if __riscv_xlen == 64"],
    "ld": ["#if __riscv_xlen == 64"],
    "fsw": ["#ifdef F_SUPPORTED"],
    "flw": ["#ifdef F_SUPPORTED"],
    "fsd": ["#ifdef D_SUPPORTED"],
    "fld": ["#ifdef D_SUPPORTED"],
    "fsh": ["#ifdef ZFH_SUPPORTED"],
    "flh": ["#ifdef ZFH_SUPPORTED"],
    "c.sw": ["#ifdef ZCA_SUPPORTED"],
    "c.lw": ["#ifdef ZCA_SUPPORTED"],
    "c.swsp": ["#ifdef ZCA_SUPPORTED"],
    "c.lwsp": ["#ifdef ZCA_SUPPORTED"],
    "c.sd": ["#ifdef ZCA_SUPPORTED", "#if __riscv_xlen == 64"],
    "c.ld": ["#ifdef ZCA_SUPPORTED", "#if __riscv_xlen == 64"],
    "c.sdsp": ["#ifdef ZCA_SUPPORTED", "#if __riscv_xlen == 64"],
    "c.ldsp": ["#ifdef ZCA_SUPPORTED", "#if __riscv_xlen == 64"],
    "c.sb": ["#ifdef ZCB_SUPPORTED"],
    "c.sh": ["#ifdef ZCB_SUPPORTED"],
    "c.lbu": ["#ifdef ZCB_SUPPORTED"],
    "c.lh": ["#ifdef ZCB_SUPPORTED"],
    "c.lhu": ["#ifdef ZCB_SUPPORTED"],
    "c.fsw": ["#ifdef ZCF_SUPPORTED"],
    "c.flw": ["#ifdef ZCF_SUPPORTED"],
    "c.fswsp": ["#ifdef ZCF_SUPPORTED"],
    "c.flwsp": ["#ifdef ZCF_SUPPORTED"],
    "c.fsd": ["#ifdef ZCD_SUPPORTED"],
    "c.fld": ["#ifdef ZCD_SUPPORTED"],
    "c.fsdsp": ["#ifdef ZCD_SUPPORTED"],
    "c.fldsp": ["#ifdef ZCD_SUPPORTED"],
}


def _add_tc(test_data: TestData, binname: str, coverpoint: str, covergroup: str) -> str:
    """Register a testcase with a new line in front of it."""
    # Leading newline gives every testcase a blank separator line in the emitted asm.
    return "\n" + test_data.add_testcase(binname, coverpoint, covergroup)


def _csr_access(instr: str, mode: str) -> str:
    """Accesses a CSR using an T-SBI or CSR operation based on mode"""
    if mode == "Sm":
        return instr
    else:
        return tsbi_call(instr)


def _load_tdata1(reg: int, trig_type: int, mode: str, lowfields: int = 0) -> list[str]:
    """Load tdata1 = (type << top) | lowfields into x{reg} and write it to tdata1."""
    lines = [
        "#if __riscv_xlen == 64",
        f"LI(x{reg}, 0x{(trig_type << 60) | lowfields:x})",
        "#else",
        f"LI(x{reg}, 0x{(trig_type << 28) | lowfields:x})",
        "#endif",
    ]
    lines.append(_csr_access(f"csrw tdata1, x{reg} # write trigger type", mode))
    return lines


def _global_ie(mode: str, enable: bool) -> list[str]:
    """TODO REMOVE ONCE SAIL IMPLEMENTED: globally enable/disable interrupts to arm triggers."""
    op, why = ("csrsi", "arm") if enable else ("csrci", "disarm")
    if mode == "Sm":
        return [f"{op} mstatus, 0x8 # MIE={int(enable)} to {why} M-mode triggers"]
    if mode == "S":
        return [f"{op} sstatus, 0x2 # SIE={int(enable)} to {why} S-mode triggers"]
    return []


def _load_reg(reg: int, val: int | str) -> str:
    """Emit a load of ``val`` into x{reg}: ints via LI (constant), symbols via LA (address)."""
    return f"LA(x{reg}, {val})" if isinstance(val, str) else f"LI(x{reg}, 0x{val:x})"


def _sigupd_masked(data_reg: int, temp_reg: int, mask: int, test_data: TestData, comment: str = "") -> list[str]:
    """Clear ``mask`` bits in x{data_reg} (optional/non-portable fields), then sigupd it."""
    note = f" # {comment}" if comment else ""
    return [
        f"LI(x{temp_reg}, 0x{mask:x}){note}",
        f"not x{temp_reg}, x{temp_reg}",
        f"and x{data_reg}, x{data_reg}, x{temp_reg} # mask out",
        write_sigupd(data_reg, test_data),
    ]


def _arch_guard(instr: str, exts: list[str]) -> list[str]:
    """Bracket a single instruction with `.option arch, +ext...` (no-op if exts empty)."""
    if not exts:
        return [instr]
    adds = ", ".join(f"+{e.strip().lower()}" for e in exts)
    return [".option push", f".option arch, {adds}", instr, ".option pop"]


def _ifdef_guard(instr: str, closing: bool = False) -> list[str]:
    """Emit the opening #ifdef guards for instr (or matching #endif when closing)."""
    ifdefs = INSTR_IFDEFS[instr]
    if closing:
        return ["#endif"] * len(ifdefs)
    return list(ifdefs)


def _disable_trigger(reg: int, trig_num: int, mode: str) -> list[str]:
    """Disable a trigger by zeroing tdata1/2/3."""
    lines: list[str] = [f"\n# disable trigger {trig_num}"]
    lines.extend(
        [
            _load_reg(reg, trig_num),
            _csr_access(f"csrw tselect, x{reg}", mode),
            _csr_access("csrw tdata1, x0", mode),
        ]
    )
    return lines


def _page_fault_perms(code: int) -> str:
    """PTE permission bits that leave the access ``code`` raises unpermitted."""
    if code == 12:  # instruction page fault: valid, readable/writable, not executable
        return "PTE_D | PTE_A | PTE_U | PTE_R | PTE_W | PTE_V"
    if code in (13, 15):  # load/store page fault: execute-only page
        return "PTE_D | PTE_A | PTE_U | PTE_X | PTE_V"
    raise ValueError(f"_page_fault_perms: exception code {code} is not a page fault code")


def _page_fault_setup(code: int) -> list[str]:
    perms = _page_fault_perms(code)
    return [
        "#if __riscv_xlen == 64",
        "#ifdef SV39_SUPPORTED",
        "SATP_SETUP_RV64(sv39)",
        "sfence.vma",
        *_pf_pte_setup_sv39(_VA_PF_PAGE_RV64, perms),
        "#endif",
        "#else",
        "#ifdef SV32_SUPPORTED",
        "SATP_SETUP_SV32",
        "sfence.vma",
        *_pf_pte_setup_sv32(_VA_PF_PAGE_RV32, perms),
        "#endif",
        "#endif",
    ]


def _page_fault_teardown() -> list[str]:
    return ["csrwi satp, 0", "sfence.vma"]


def _mprv_as_umode_setup(scratch_reg: int) -> list[str]:
    """MPRV=1, MPP=U: next load/store is translated as if from U-mode."""
    return [
        f"LI(x{scratch_reg}, {hex(_MSTATUS_MPP_MASK)})",
        f"csrc mstatus, x{scratch_reg} # MPP=U",
        f"LI(x{scratch_reg}, {hex(_MSTATUS_MPRV)})",
        f"csrs mstatus, x{scratch_reg} # MPRV=1",
    ]


def _mprv_as_umode_teardown(scratch_reg: int) -> list[str]:
    """Clear MPRV, restoring normal M-mode (untranslated) access."""
    return [
        f"LI(x{scratch_reg}, {hex(_MSTATUS_MPRV)})",
        f"csrc mstatus, x{scratch_reg} # MPRV=0",
    ]


def _set_medeleg(reg: int, code: int, enable: bool) -> list[str]:
    """Set or clear medeleg[code]."""
    op = "csrs" if enable else "csrc"
    return [
        f"LI(x{reg}, 0x{1 << code:x})",
        f"{op} medeleg, x{reg} # medeleg[{code}]={int(enable)}",
    ]


def _sdtrig_bp_arm(raised_code: int) -> str | None:
    """a1 token for the handler; None for code 3 (a real ebreak needs no note)."""
    if raised_code == 3:
        return None
    return "SDTRIG_BP_FETCH" if raised_code in _FETCH_EXCODES else "SDTRIG_BP_SKIP"


def _etrigger_codes_to_test(mode: str, cross_priv: bool = False) -> tuple[int, ...]:
    """Return exception codes that can be raised from ``mode``."""

    if cross_priv:
        if mode == "S":
            return (1, 2, 5, 7, 9, 12, 13, 15)

        if mode == "U":
            return (1, 2, 5, 7, 8, 13, 15)  # Exception 12 is failing on spike excluded for now

        raise ValueError(f"Unsupported target mode: {mode}")

    # Normal SdtrigSm/S/U tests use the same exception codes.
    if mode in ("Sm", "S", "U"):
        ecall_code = {"Sm": 11, "S": 9, "U": 8}[mode]
        return (1, 2, 3, 4, 5, 6, 7, ecall_code, 13, 15)

    raise ValueError(f"Unsupported mode: {mode}")


def _check_etrigger_hit(
    cfg_reg: int,
    data_reg: int,
    trig_num: int,
    mode: str,
    test_data: TestData,
) -> list[str]:
    """Record tdata1.hit for an e-trigger when the field is implemented."""
    return [
        "#ifdef UDB_SDTRIG_HIT_IMPLEMENTED",
        _load_reg(cfg_reg, trig_num),
        _csr_access(f"csrw tselect, x{cfg_reg}", mode),
        _csr_access(f"csrr x{data_reg}, tdata1", mode),
        "#if __riscv_xlen == 64",
        f"srli x{data_reg}, x{data_reg}, 58 # isolate hit",
        "#else",
        f"srli x{data_reg}, x{data_reg}, 26 # isolate hit",
        "#endif",
        f"andi x{data_reg}, x{data_reg}, 1",
        write_sigupd(data_reg, test_data),
        "#endif",
    ]


def _cause_exception(
    code: int,
    mode: str,
    addr_reg: int | None = None,
    data_reg: int | None = None,
    *,
    mprv_scratch_reg: int | None = None,
) -> list[str]:
    """Emit assembly that synchronously raises mcause exception ``code``."""

    if code == 0:  # instruction address misaligned
        if addr_reg is None:
            raise ValueError("addr_reg is required for instruction address misaligned")

        return [
            ".p2align 2",
            f"auipc x{addr_reg}, 0 # x{addr_reg} = PC (word-aligned by the .p2align above)",
            f"addi x{addr_reg}, x{addr_reg}, 6",
            f"jalr ra, 0(x{addr_reg}) # instruction address misaligned",
            "nop # spacer; trap handler returns here",
        ]

    if code == 1:  # instruction access fault
        if addr_reg is None:
            raise ValueError("addr_reg is required for instruction access fault")

        return [
            f"la x{addr_reg}, RVMODEL_ACCESS_FAULT_ADDRESS",
            f"jalr ra, 0(x{addr_reg})",
            "nop # spacer; trap handler returns here",
        ]

    if code == 2:  # illegal instruction
        return [".word 0xffffffff # illegal instruction"]

    if code == 3:  # breakpoint
        return ["ebreak # breakpoint"]

    if code == 4:  # load address misaligned
        if addr_reg is None:
            raise ValueError("addr_reg is required for load address misaligned")

        return [
            f"LA(x{addr_reg}, scratch)",
            f"addi x{addr_reg}, x{addr_reg}, 1",
            f"lw x{data_reg}, 0(x{addr_reg}) # load address misaligned",
        ]

    if code == 5:  # load access fault
        if addr_reg is None:
            raise ValueError("addr_reg is required for load access fault")

        return [
            f"LA(x{addr_reg}, RVMODEL_ACCESS_FAULT_ADDRESS)",
            f"lw x{data_reg}, 0(x{addr_reg}) # load access fault",
        ]

    if code == 6:  # store/AMO address misaligned
        if addr_reg is None:
            raise ValueError("addr_reg is required for store/AMO address misaligned")

        return [
            f"LI(x{data_reg}, 0xDEADBEEF)",
            f"LA(x{addr_reg}, scratch)",
            f"addi x{addr_reg}, x{addr_reg}, 1",
            f"sw x{data_reg}, 0(x{addr_reg}) # store/AMO address misaligned",
        ]

    if code == 7:
        if addr_reg is None or data_reg is None:
            raise ValueError("addr_reg and data_reg are required for store access fault")
        return [
            f"LA(x{addr_reg}, RVMODEL_ACCESS_FAULT_ADDRESS)",
            f"sw x0, 0(x{addr_reg}) # store access fault",
            "nop # spacer; trap handler returns here",
        ]

    if code in (8, 9, 11):  # Ecall from U-mode, S-mode, M-mode
        return [f"RVTEST_TSBI_ECALL_TEST # ecall from {mode}-mode"]

    if code == 12:
        if addr_reg is None:
            raise ValueError("addr_reg is required for instruction page fault")

        if mode == "Sm":
            raise ValueError(
                "_cause_exception: code 12 cannot be raised with mode='Sm' M-mode fetches are never translated"
            )

        return [
            "#if __riscv_xlen == 64",
            f"LI(x{addr_reg}, 0x140300000)",
            "#else",
            f"LI(x{addr_reg}, 0xC0300000)",
            "#endif",
            f"jalr ra, 0(x{addr_reg}) # instruction page fault",
            "nop # spacer; trap handler returns here",
        ]

    if code == 13:  # load page fault
        if addr_reg is None or data_reg is None:
            raise ValueError("addr_reg and data_reg are required for load page fault")

        lines = [
            "#if __riscv_xlen == 64",
            f"LI(x{addr_reg}, 0x140300000)",
            "#else",
            f"LI(x{addr_reg}, 0xC0300000)",
            "#endif",
        ]
        if mode == "Sm":
            assert mprv_scratch_reg is not None
            lines.extend(_mprv_as_umode_setup(mprv_scratch_reg))
        lines.append(f"lw x{data_reg}, 0(x{addr_reg}) # load page fault")
        lines.append("nop # spacer; trap handler returns here")
        if mode == "Sm":
            assert mprv_scratch_reg is not None
            lines.extend(_mprv_as_umode_teardown(mprv_scratch_reg))
        return lines

    if code == 15:  # store/AMO page fault
        if addr_reg is None or data_reg is None:
            raise ValueError("addr_reg and data_reg are required for store page fault")

        lines = [
            "#if __riscv_xlen == 64",
            f"LI(x{addr_reg}, 0x140300000)",
            "#else",
            f"LI(x{addr_reg}, 0xC0300000)",
            "#endif",
            f"LI(x{data_reg}, 0xDEADBEEF)",
        ]
        if mode == "Sm":
            assert mprv_scratch_reg is not None
            lines.extend(_mprv_as_umode_setup(mprv_scratch_reg))
        lines.append(f"sw x{data_reg}, 0(x{addr_reg}) # store page fault")
        lines.append("nop # spacer; trap handler returns here")
        if mode == "Sm":
            assert mprv_scratch_reg is not None
            lines.extend(_mprv_as_umode_teardown(mprv_scratch_reg))
        return lines

    raise ValueError(
        f"_cause_exception: exception code {code} ({ETRIGGER_EXCODE_NAMES.get(code, '?')}) not implemented yet"
    )


def _cause_interrupt(code: int, mode: str, r1: int) -> list[str]:
    """Emit assembly that makes interrupt ``code`` (mcause interrupt code) pending."""
    flavor = "M" if mode == "Sm" else mode
    if code == 1:  # supervisor software interrupt (SSIP)
        return [f"LI(x{r1}, 0x2) # SSIP", _csr_access(f"csrs mip, x{r1}", mode)]
    if code == 5:  # supervisor timer interrupt (STIP)
        return [f"LI(x{r1}, 0x20) # STIP", _csr_access(f"csrs mip, x{r1}", mode)]
    if code == 9:  # supervisor external interrupt (SEIP)
        return [f"LI(x{r1}, 0x200) # SEIP", _csr_access(f"csrs mip, x{r1}", mode)]
    if code == 13:  # local counter overflow interrupt (LCOFIP)
        return [f"LI(x{r1}, 0x2000) # LCOFIP", _csr_access(f"csrs mip, x{r1}", mode)]
    if code == 3:  # machine software interrupt (CLINT MSIP; M-mode only)
        return [f"RVTEST_SET_MSW_INT_{flavor}"]
    if code == 7:  # machine timer interrupt (mtimecmp = mtime; M-mode only)
        return [f"RVTEST_SET_MTIME_INT_{flavor}"]
    if code == 11:  # machine external interrupt (PLIC MEIP; M-mode only)
        return [f"RVTEST_SET_MEXT_INT_{flavor}"]
    raise ValueError(f"unsupported interrupt code {code}")


def _config_mcontrol6(
    reg: int,
    tselect: int,
    tdata2: int | str,
    mode: str,
    *,
    privbits: int | None = None,
    xsl: int = 0b000,
    select: int = 0,
    size: int = 0,
    match: int = 0,
    chain: int = 0,
    action: int = 0,
    tdata3: int | str = 0,
) -> list[str]:
    """Emit assembly configuring trigger ``tselect`` as an mcontrol6 trigger."""
    if privbits is None:
        privbits = MODE_PRIVBIT[mode]

    m = (privbits >> 4) & 1
    s = (privbits >> 3) & 1
    u = (privbits >> 2) & 1
    vs = (privbits >> 1) & 1
    vu = privbits & 1
    lowfields = (
        (vs << 24)
        | (vu << 23)
        | (select << 21)
        | ((size & 0b111) << 16)
        | (action << 12)
        | (chain << 11)
        | ((match & 0xF) << 7)
        | (m << 6)
        | (s << 4)
        | (u << 3)
        | (xsl & 0b111)
    )
    mcontrol6 = 6  # tdata1.type
    lines: list[str] = []
    lines.extend(
        [
            f"# configure trigger {tselect} as mcontrol6",
            _load_reg(reg, tselect),
            _csr_access(f"csrw tselect, x{reg}", mode),
            _csr_access("csrw tdata1, x0 # disable before configuring", mode),
            _load_reg(reg, tdata2),
            _csr_access(f"csrw tdata2, x{reg} # match value", mode),
            _load_reg(reg, tdata3),
            _csr_access(f"csrw tdata3, x{reg} # textra context matching ", mode),
            f"# tdata1: type={mcontrol6} priv={privbits:05b} xsl={xsl:03b} select={select} size={size} match={match} chain={chain}",
            *_load_tdata1(reg, mcontrol6, mode, lowfields),  # load data in tdata1
        ]
    )
    return lines


def _config_icount(
    reg: int,
    tselect: int,
    count: int,
    mode: str,
    *,
    privbits: int | None = None,
    pending: int = 0,
    action: int = 0,
    tdata3: int | str = 0,
) -> list[str]:
    """Emit assembly configuring trigger ``tselect`` as an icount trigger."""
    if privbits is None:
        privbits = MODE_PRIVBIT[mode]

    m = (privbits >> 4) & 1
    s = (privbits >> 3) & 1
    u = (privbits >> 2) & 1
    vs = (privbits >> 1) & 1
    vu = privbits & 1
    lowfields = (
        (vs << 26)
        | (vu << 25)
        | ((count & 0x3FFF) << 10)
        | (m << 9)
        | (pending << 8)
        | (s << 7)
        | (u << 6)
        | (action & 0x3F)
    )
    icount = 3  # tdata1.type
    lines: list[str] = []
    lines.extend(
        [
            f"# configure trigger {tselect} as icount",
            _load_reg(reg, tselect),
            _csr_access(f"csrw tselect, x{reg}", mode),
            _csr_access("csrw tdata1, x0 # disable before configuring", mode),
            _load_reg(reg, tdata3),
            _csr_access(f"csrw tdata3, x{reg} # textra", mode),
            f"# tdata1: type={icount} priv={privbits:05b} count={count} pending={pending} action={action}",
            *_load_tdata1(reg, icount, mode, lowfields),  # load data in tdata1
        ]
    )
    return lines


def _config_itrigger(
    reg: int,
    tselect: int,
    tdata2: int | str,
    mode: str,
    *,
    privbits: int | None = None,
    nmi: int = 0,
    action: int = 0,
    tdata3: int | str = 0,
) -> list[str]:
    """Emit assembly configuring trigger ``tselect`` as an itrigger."""
    if privbits is None:
        privbits = MODE_PRIVBIT[mode]

    m = (privbits >> 4) & 1
    s = (privbits >> 3) & 1
    u = (privbits >> 2) & 1
    vs = (privbits >> 1) & 1
    vu = privbits & 1
    lowfields = (vs << 12) | (vu << 11) | (nmi << 10) | (m << 9) | (s << 7) | (u << 6) | (action & 0x3F)
    itrigger = 4  # tdata1.type
    lines: list[str] = []
    lines.extend(
        [
            f"# configure trigger {tselect} as itrigger",
            _load_reg(reg, tselect),
            _csr_access(f"csrw tselect, x{reg}", mode),
            _csr_access("csrw tdata1, x0 # disable before configuring", mode),
            _load_reg(reg, tdata2),
            _csr_access(f"csrw tdata2, x{reg} # interrupt-cause mask", mode),
            _csr_access(f"csrs mie, x{reg} # enable masked interrupt(s)", mode),
            _load_reg(reg, tdata3),
            _csr_access(f"csrw tdata3, x{reg} # textra context matching ", mode),
            f"# tdata1: type={itrigger} priv={privbits:05b} nmi={nmi} action={action}",
            *_load_tdata1(reg, itrigger, mode, lowfields),  # load data in tdata1
        ]
    )
    return lines


def _config_etrigger(
    reg: int,
    tselect: int,
    tdata2: int | str,
    mode: str,
    *,
    privbits: int | None = None,
    action: int = 0,
    tdata3: int | str = 0,
) -> list[str]:
    """Emit assembly configuring trigger ``tselect`` as an etrigger."""
    if privbits is None:
        privbits = MODE_PRIVBIT[mode]

    m = (privbits >> 4) & 1
    s = (privbits >> 3) & 1
    u = (privbits >> 2) & 1
    vs = (privbits >> 1) & 1
    vu = privbits & 1
    lowfields = (vs << 12) | (vu << 11) | (m << 9) | (s << 7) | (u << 6) | (action & 0x3F)
    etrigger = 5  # tdata1.type
    lines: list[str] = []
    lines.extend(
        [
            f"# configure trigger {tselect} as etrigger",
            _load_reg(reg, tselect),
            _csr_access(f"csrw tselect, x{reg}", mode),
            _csr_access("csrw tdata1, x0 # disable before configuring", mode),
            _load_reg(reg, tdata2),
            _csr_access(f"csrw tdata2, x{reg} # exception-cause mask", mode),
            _load_reg(reg, tdata3),
            _csr_access(f"csrw tdata3, x{reg} # textra context matching ", mode),
            f"# tdata1: type={etrigger} priv={privbits:05b} action={action}",
            *_load_tdata1(reg, etrigger, mode, lowfields),  # load data in tdata1
        ]
    )
    return lines


def _fire_supported_triggers(trig_num: int, mode: str, cfg_reg: int, addr_reg: int, data_reg: int) -> list[str]:
    """Emit firing code for every trigger type supported on ``trig_num``."""
    lines: list[str] = []

    # mcontrol6: watch &scratch, fire with a store to it
    lines.extend(
        [
            f"#ifdef UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE",
            *_config_mcontrol6(cfg_reg, trig_num, "scratch", mode, xsl=0b010, select=0),
            f"LA(x{addr_reg}, scratch)",
            f"LI(x{data_reg}, {random_int(32, signed=False)})",
            f"sw x{data_reg}, 0(x{addr_reg}) # fire mcontrol6",
            *_disable_trigger(cfg_reg, trig_num, mode),
            f"#endif // UDB_MCONTROL6_TRIG{trig_num}_AVAILABLE",
        ]
    )

    # icount: count=1, fires on the next retired instruction
    lines.extend(
        [
            f"#ifdef UDB_ICOUNT_TRIG{trig_num}_AVAILABLE",
            *_config_icount(cfg_reg, trig_num, 1, mode),
            "nop # fire icount",
            *_disable_trigger(cfg_reg, trig_num, mode),
            f"#endif // UDB_ICOUNT_TRIG{trig_num}_AVAILABLE",
        ]
    )

    # # itrigger: mask SSIP, fire by making it pending
    # lines.extend(
    #     [
    #         f"#ifdef UDB_ITRIGGER_TRIG{trig_num}_AVAILABLE",
    #         *_config_itrigger(cfg_reg, trig_num, 1 << 1, mode),
    #         *_cause_interrupt(1, mode, cfg_reg),
    #         "nop # spacer",
    #         *_disable_trigger(cfg_reg, trig_num, mode),
    #         f"#endif // UDB_ITRIGGER_TRIG{trig_num}_AVAILABLE",
    #     ]
    # )

    # etrigger: watch ecall-from-<mode>, fire with an ecall
    # ecall_cause = {"M": 11, "S": 9, "U": 8}.get(mode[0], 11)
    # lines.extend(
    #     [
    #         f"#ifdef UDB_ETRIGGER_TRIG{trig_num}_AVAILABLE",
    #         *_config_etrigger(cfg_reg, trig_num, 1 << ecall_cause, mode),
    #         "ecall # fire etrigger",
    #         "nop # spacer",
    #         *_disable_trigger(cfg_reg, trig_num, mode),
    #         f"#endif // UDB_ETRIGGER_TRIG{trig_num}_AVAILABLE",
    #     ]
    # )

    return lines


### COVERPOINTS


def _generate_access_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate common trigger-CSR access tests."""
    covergroup = f"Sdtrig{mode}_access_cg"
    tc = test_data.begin_test_chunk("Access")
    lines = tc.code

    ######################################
    coverpoint = "cp_sdtrig_csr_access_common"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "Access every trigger CSR across all triggers and trigger types\n"
            "Should not cause any illegal instruction exceptions on implemented triggers",
        )
    )
    csrs = ("tdata1", "tdata2", "tdata3", "tinfo", "tcontrol", "scontext", "mcontext", "hcontext")

    type_reg, save_reg, temp_reg = test_data.int_regs.get_registers(
        3, exclude_regs=[10, 11]
    )  # exclude a0, a1 because they are used in SBI

    for trig_num in range(UDB_NUM_TRIGGERS):
        for trig_type in range(16):
            for csr in csrs:
                lines.append(f"#ifdef UDB_{csr}_AVAILABLE")
                binname = f"tselect_{trig_num}_type_{trig_type}_csr_{csr}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        f"LI x{temp_reg}, {trig_num} # load trig_num value",
                        _csr_access(f"csrw tselect, x{temp_reg} # set tselect = trig_num", mode),
                        *_load_tdata1(type_reg, trig_type, mode),  # load tdata1 with the type
                        f"LI x{temp_reg}, -1 # load all 1's value",
                        _csr_access(f"csrr x{save_reg}, {csr} # save original value", mode),
                        _csr_access(f"csrw {csr}, x{temp_reg} # write all-1s", mode),
                        _csr_access(f"csrw {csr}, x0 # write all-0s", mode),
                        _csr_access(f"csrs {csr}, x{temp_reg} # set all-1s", mode),
                        _csr_access(f"csrc {csr}, x{temp_reg} # clear all-1s", mode),
                        _csr_access(f"csrw {csr}, x{save_reg} # write back original value", mode),
                    ]
                )
                lines.append("#endif")

    test_data.int_regs.return_registers([type_reg, save_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_native_triggers_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate native trigger breakpoint-delegation tests."""
    # covergroup = f"Sdtrig{mode}_native_triggers_cg"
    tc = test_data.begin_test_chunk("NativeTriggers")
    lines: list[str] = tc.code

    lines.append("#ifdef S_SUPPORTED")
    ######################################
    coverpoint = "cp_sdtrig_breakpoint_delegate"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "Breakpoint from a fired trigger, taken in M-mode and delegated to\nS-mode via medeleg[3]",
        )
    )

    r1, r2, addr_reg, medeleg_reg, scr_reg = test_data.int_regs.get_registers(5)

    # for delegate in (0, 1):  # medeleg[3]
    #     medelegop = "csrs" if delegate else "csrc"
    #     for trig_num in range(UDB_NUM_TRIGGERS):
    #         binname = f"trig_num_{trig_num}_delegate_{delegate}"
    #         lines.extend(
    #             [
    #                 _add_tc(test_data, binname, coverpoint, covergroup),
    #                 f"LI(x{medeleg_reg}, 8)",  # medeleg bit 3 = breakpoint
    #                 f"{medelegop} medeleg, x{medeleg_reg}",
    #                 *_fire_supported_triggers(trig_num, mode, r1, addr_reg, r2),
    #                 "# restore medeleg[3]",
    #                 f"csrc medeleg, x{medeleg_reg}",
    #             ]
    #         )

    test_data.int_regs.return_registers([r1, r2, addr_reg, medeleg_reg, scr_reg])

    lines.append("#endif")
    return [test_data.end_test_chunk()]


def _generate_a_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate A-extension load/store/AMO matching tests."""
    covergroup = f"Sdtrig{mode}_a_cg"
    tc = test_data.begin_test_chunk("AExt")
    lines: list[str] = tc.code

    # setup registers
    sp_reg, addr_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        4, exclude_regs=[2], reg_range=list(range(8, 16))
    )

    ######################################
    coverpoint = "cp_sdtrig_lrsc_addr"
    ######################################
    lines.append("#ifdef ZALRSC_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 address match on lr/sc access address",
        )
    )
    # for trig_num in range(UDB_NUM_TRIGGERS):
    #     for tdata2 in ("scratch", 0):
    #         for perm in range(4):
    #             binname = f"trig_num_{trig_num}_tdata2_{tdata2}_perm_{perm:03b}"
    #             lines.extend(
    #                 [
    #                     _add_tc(test_data, binname, coverpoint, covergroup),
    #                     f"LA(x{addr_reg}, scratch) # x{addr_reg} = &scratch",
    #                     f"LI(x{data_reg}, {random_int(32, signed=False)})",
    #                     f"sw x{data_reg}, 0(x{addr_reg})",
    #                     *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=perm, select=0),

    #                     *_arch_guard(f"lr.w x{data_reg}, (x{addr_reg}) # fire if addr==tdata2 and xsl has load bit", ["zalrsc"]),
    #                     "nop # spacer",
    #                     *_arch_guard(f"sc.w x{temp_reg}, x{data_reg}, (x{addr_reg}) # fire if addr==tdata2 and xsl has store bit", ["zalrsc"]),
    #                     "nop # spacer",

    #                     "#if __riscv_xlen == 64",
    #                     *_arch_guard(f"lr.d x{data_reg}, (x{addr_reg}) # fire if addr==tdata2 and xsl has load bit", ["zalrsc"]),
    #                     "nop # spacer",
    #                     *_arch_guard(f"sc.d x{temp_reg}, x{data_reg}, (x{addr_reg}) # fire if addr==tdata2 and xsl has store bit", ["zalrsc"]),
    #                     "nop # spacer",
    #                     "#endif",

    #                     *_disable_trigger(temp_reg, trig_num, mode)
    #                 ]
    #             )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_lrsc_data"
    ######################################
    lines.append("#ifdef ZALRSC_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 data match on lr/sc value",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for insn in ("lr_w", "sc_w", "lr_d", "sc_d"):
                for perm in range(4):
                    binname = f"trig_num_{trig_num}_data_{addrval}_{insn}_perm_{perm:03b}"
                    lines.extend(
                        [
                            _add_tc(test_data, binname, coverpoint, covergroup),
                        ]
                    )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_amo"
    ######################################
    lines.append("#ifdef ZAAMO_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 address match on AMO read and write portions",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for insn in ("amoswap_w", "amoswap_d"):
                for perm in range(4):
                    binname = f"trig_num_{trig_num}_addr_{addrval}_{insn}_perm_{perm:03b}"
                    lines.extend(
                        [
                            _add_tc(test_data, binname, coverpoint, covergroup),
                        ]
                    )
    lines.append("#endif")

    test_data.int_regs.return_registers([sp_reg, addr_reg, data_reg, temp_reg])

    return [test_data.end_test_chunk()]


def _generate_combined_accesses_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate multi-access (vector / cm.push-pop) instruction tests."""
    covergroup = f"Sdtrig{mode}_combined_accesses_cg"
    tc = test_data.begin_test_chunk("CombinedAccesses")
    lines: list[str] = tc.code

    vsews = ("sew8", "sew16", "sew32", "sew64")

    ######################################
    coverpoint = "cp_sdtrig_vector_load_store"
    ######################################
    lines.append("#ifdef V_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 matches each element of a vector load/store as an\nindividual SEW-sized access",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "zero"):
            for vsew in vsews:
                for size in SIZE_SEW:
                    for vperm in ("store", "load"):
                        binname = f"trig_num_{trig_num}_addr_{addrval}_{vsew}_size_{size}_{vperm}"
                        lines.extend(
                            [
                                _add_tc(test_data, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_vector_accesses"
    ######################################
    lines.append("#ifdef V_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "vector accesses across scratch / scratch+8 / 0 tdata2 values",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "marker8", "zero"):
            for vsew in vsews:
                for size in SIZE_SEW:
                    for vperm in ("store", "load"):
                        binname = f"trig_num_{trig_num}_addr_{addrval}_{vsew}_size_{size}_{vperm}"
                        lines.extend(
                            [
                                _add_tc(test_data, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_cm_pop_push"
    ######################################
    lines.append("#ifdef ZCMP_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 matches each XLEN store of cm.push / cm.pop",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for addrval in ("marker", "marker8", "zero"):
            for insn in ("cm_push", "cm_pop"):
                for size in SIZE_ALL:
                    for perm in ("store", "load"):
                        binname = f"trig_num_{trig_num}_addr_{addrval}_{insn}_size_{size}_{perm:03b}"
                        lines.extend(
                            [
                                _add_tc(test_data, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    return [test_data.end_test_chunk()]


def _generate_cache_operations_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate Zicbo* cache-operation matching tests."""
    covergroup = f"Sdtrig{mode}_cache_operations_cg"
    tc = test_data.begin_test_chunk("CacheOps")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_cache_zicbom"
    ######################################
    lines.append("#ifdef ZICBOM_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "cbo.clean/flush/inval match as stores",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for insn in ("cbo_clean", "cbo_flush", "cbo_inval"):
            for addrval in ("marker", "zero"):
                for size in SIZE_ALL:
                    for perm in PERM_XSL:
                        binname = f"trig_num_{trig_num}_{insn}_addr_{addrval}_size_{size}_perm_{perm:03b}"
                        lines.extend(
                            [
                                _add_tc(test_data, binname, coverpoint, covergroup),
                            ]
                        )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_cache_zicboz"
    ######################################
    lines.append("#ifdef ZICBOZ_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "cbo.zero matches as a store",
        )
    )
    for addrval in ("marker", "zero"):
        for size in SIZE_ALL:
            for perm in PERM_XSL:
                binname = f"cbo_zero_addr_{addrval}_size_{size}_perm_{perm:03b}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                    ]
                )
    lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_cache_zicbop"
    ######################################
    lines.append("#ifdef ZICBOP_SUPPORTED")
    lines.append(
        comment_banner(
            coverpoint,
            "prefetch.i/r/w (HINTs) do not match",
        )
    )
    for insn in ("prefetch_i", "prefetch_r", "prefetch_w"):
        binname = f"{insn}"
        lines.extend(
            [
                _add_tc(test_data, binname, coverpoint, covergroup),
            ]
        )
    lines.append("#endif")

    return [test_data.end_test_chunk()]


def _generate_address_matches_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate tdata2 address-storage / translation tests."""
    covergroup = f"Sdtrig{mode}_address_matches_cg"
    tc = test_data.begin_test_chunk("AddressMatches")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_tdata2_translate"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tdata2 holds full-width virtual/physical addresses across satp modes;\nhigh bit reads back",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        # RV64 satp modes; RV32 uses (bare, sv32)
        for satp in ("bare", "sv39", "sv48", "sv57"):
            for msb in (0, 1):  # tdata2 high bit
                binname = f"trig_num_{trig_num}_satp_{satp}_msb_{msb}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                    ]
                )

    return [test_data.end_test_chunk()]


def _generate_csr_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate trigger-module register semantics tests."""
    covergroup = f"Sdtrig{mode}_csr_cg"
    tc = test_data.begin_test_chunk("Csr")
    lines: list[str] = tc.code

    ######################################
    coverpoint = "cp_sdtrig_tselect_trigs"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tselect selects contiguous triggers starting at 0; read tinfo",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                _add_tc(test_data, f"trig_num_{trig_num}_tinfo", coverpoint, covergroup),
            ]
        )

    ######################################
    coverpoint = "cp_sdtrig_tdata_write"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "writing one tdata register does not disturb the others",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for csr in ("tdata1", "tdata2", "tdata3"):
            binname = f"trig_num_{trig_num}_write_{csr}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_csr_smode_access"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "S-mode access to M-only trigger CSRs raises illegal instruction",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for csr in ("tdata1", "tdata2", "tdata3", "tinfo", "tcontrol", "mcontext", "hcontext"):
            binname = f"trig_num_{trig_num}_smode_{csr}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_tdata1_mode_hardwired"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "type-0 dmode/data fields hard-wired to 0",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for priv in range(32):  # priv_all: all 32 m/s/u/vs/vu enable combinations
            binname = f"trig_num_{trig_num}_priv_{priv:05b}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_tinfo_read_only"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tinfo is read-only",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                _add_tc(test_data, f"trig_num_{trig_num}_tinfo", coverpoint, covergroup),
            ]
        )

    ######################################
    coverpoint = "cp_sdtrig_tcontrol_enable"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "tcontrol.mte gates M-mode trigger firing",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for mte in (0, 1):  # tcontrol[3]
            binname = f"trig_num_{trig_num}_mte_{mte}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                ]
            )

    ######################################
    coverpoint = "cp_sdtrig_tcontrol_mtrap"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mte/mpte updated on trap into M-mode",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for mte in (0, 1):  # tcontrol[3]
            for mpte in (0, 1):  # tcontrol[7]
                binname = f"trig_num_{trig_num}_mte_{mte}_mpte_{mpte}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_tcontrol_mret"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mte restored from mpte on mret",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for mte in (0, 1):  # tcontrol[3]
            for mpte in (0, 1):  # tcontrol[7]
                binname = f"trig_num_{trig_num}_mte_{mte}_mpte_{mpte}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_mscontext_alias"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mscontext aliases scontext",
        )
    )
    lines.extend(
        [
            _add_tc(test_data, "alias", coverpoint, covergroup),
        ]
    )

    ######################################
    coverpoint = "cp_sdtrig_mcontext_smode"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "S-mode access to mcontext raises illegal instruction",
        )
    )
    lines.extend(
        [
            _add_tc(test_data, "mcontext", coverpoint, covergroup),
        ]
    )

    return [test_data.end_test_chunk()]


def _generate_mcontrol6_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate mcontrol6 address/data match trigger tests."""
    covergroup = f"Sdtrig{mode}_mcontrol6_cg"
    seed(reproducible_hash(covergroup))
    tc = test_data.begin_test_chunk("Mcontrol6")
    lines: list[str] = tc.code

    # setup registers
    sp_reg, addr_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        4, exclude_regs=[2], reg_range=list(range(8, 16))
    )
    lines.extend(_global_ie(mode, True))

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_priv_mode"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires on a sw when the privilege bit corresponding to mode is enabled",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        for priv in (0, MODE_PRIVBIT[mode]):
            if priv != 0:
                lines.append(f"\n#ifdef UDB_SDTRIG_{MODE_UDB_LETTER[mode]}_AVAILABLE")

            binname = f"trig_num_{trig_num}_priv_{priv:05b}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                    *_config_mcontrol6(temp_reg, trig_num, "scratch", mode, privbits=priv, xsl=0b010, select=0),
                    f"LA(x{addr_reg}, scratch)",
                    f"LI(x{data_reg}, {random_int(32, signed=False)})",
                    f"sw x{data_reg}, 0(x{addr_reg}) # fire trigger if applicable",
                ]
            )

            if priv != 0:
                lines.append(f"#endif // UDB_SDTRIG_{MODE_UDB_LETTER[mode]}_AVAILABLE")
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_execute_adr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when PC == tdata2",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        for perm in range(8):  # perm_xsl
            lines.extend(_xsl_ifdefs(perm))
            label = f"exec_adr_trig_num_{trig_num}_xls_{perm:03b}"
            binname = f"trig_num_{trig_num}_exec_adr_perm_{perm:03b}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                    *_config_mcontrol6(temp_reg, trig_num, label, mode, xsl=perm, select=0),
                    f"{label}:",
                    "add x0, x1, x2 # execute here; PC == tdata2",
                ]
            )
            binname = f"trig_num_{trig_num}_exec_adr_nofire_perm_{perm:03b}"
            lines.extend(
                [
                    _add_tc(test_data, binname, coverpoint, covergroup),
                    *_config_mcontrol6(temp_reg, trig_num, 0, mode, xsl=perm, select=0),
                    "add x0, x1, x2 # execute here; PC == tdata2",
                ]
            )
            lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(perm)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_load_store_adr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when access address == tdata2 (select=address)",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        for tdata2 in ("scratch", 0):
            for perm in range(8):  # perm_xsl
                lines.extend(_xsl_ifdefs(perm))
                binname = f"trig_num_{trig_num}_td2_{tdata2}_perm_{perm:03b}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=perm, select=0),
                        f"LA(x{addr_reg}, scratch) # x{addr_reg} = &scratch",
                        f"LI(x{data_reg}, {random_int(32, signed=False)})",
                        f"sw x{data_reg}, 0(x{addr_reg}) # store: breakpoint iff addr==tdata2 and xsl has store bit",
                        "nop # spacer",
                        f"lw x{data_reg}, 0(x{addr_reg}) # fire iff addr==tdata2 and xsl has load bit",
                        "nop # spacer",
                    ]
                )
                lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(perm)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_execute_data"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when instruction encoding == tdata2 (select=data)",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        for tdata2 in (ADDI_HINT, TDATA2_NOFIRE):
            for perm in range(8):  # perm_xsl
                lines.extend(_xsl_ifdefs(perm))
                binname = f"trig_num_{trig_num}_exec_data_td2_{tdata2}_perm_{perm:03b}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=perm, select=1),
                        "addi x0, x1, 0 # fire trigger when opcode==tdata2",
                        "nop # spacer (does not match tdata2)",
                        "nop # spacer (does not match tdata2)",
                    ]
                )
                lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(perm)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_load_store_data"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 fires when load/store data == tdata2 (select=data)",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        match_val = random_int(32, signed=False)
        nofire_val = (match_val ^ 1) & 0xFFFFFFFF
        for case, tdata2 in [("Fire", match_val), ("NoFire", nofire_val)]:
            for perm in range(8):  # perm_xsl
                lines.extend(_xsl_ifdefs(perm))
                binname = f"trig_num_{trig_num}_td2_{tdata2}_{case}_perm_{perm:03b}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=perm, select=1),
                        f"LA(x{addr_reg}, scratch) # x{addr_reg} = &scratch",
                        f"LI(x{data_reg}, {match_val})",
                        f"sw x{data_reg}, 0(x{addr_reg}) # store: breakpoint iff data==tdata2 and xsl has store bit",
                        "nop # spacer (data match fires after)",
                        f"lw x{data_reg}, 0(x{addr_reg}) # fire iff data==tdata2 and xsl has load bit",
                        "nop # spacer (data match fires after)",
                    ]
                )
                lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(perm)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_execute_size"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 execute match across access sizes",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        lines.append("\n#ifdef UDB_SDTRIG_MCONTROL6_EXECUTE_AVAILABLE")
        for tdata2 in (ADDI_HINT, C_NOP):  # tdata2 sizes: 32-bit and 16-bit targets
            for size in range(7):
                lines.append(f"\n# Size = {size}")
                if size > 0:
                    lines.append("#ifdef UDB_SDTRIG_MCONTROL6_SIZE_AVAILABLE")
                bin1 = f"trig_num_{trig_num}_td2_{tdata2}_insn_addi_size_{size}"
                bin2 = f"trig_num_{trig_num}_td2_{tdata2}_insn_c.nop_size_{size}"
                lines.extend(
                    [
                        _add_tc(test_data, bin1, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b100, select=1, size=size),
                        "addi x0, x1, 0 # 32-bit target; fires iff tdata2 matches",
                        # "nop # spacer (does not match tdata2)",
                    ]
                )
                lines.extend(
                    [
                        "#ifdef ZCA_SUPPORTED",
                        _add_tc(test_data, bin2, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b100, select=1, size=size),
                        *_arch_guard("c.nop", ["zca"]),
                        "nop # spacer (does not match tdata2)",
                        "#endif",
                    ]
                )
                if size > 0:
                    lines.append("#endif // UDB_SDTRIG_MCONTROL6_SIZE_AVAILABLE")
        lines.append("#endif // UDB_SDTRIG_MCONTROL6_EXECUTE_AVAILABLE")
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_load_store_size"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 load/store match across access sizes",
        )
    )

    lines.extend(
        [
            f"LI(x{temp_reg}, 0x6000)",
            _csr_access(
                f"csrs mstatus, x{temp_reg} # enable mstatus.FS (bits 14:13) so the fp loads/stores below don't trap as illegal instructions",
                mode,
            ),
        ]
    )

    instr_asm = {
        "sb": [f"sb x{data_reg}, 0(x{addr_reg})", []],
        "sh": [f"sh x{data_reg}, 0(x{addr_reg})", []],
        "sw": [f"sw x{data_reg}, 0(x{addr_reg})", []],
        "lb": [f"lb x{data_reg}, 0(x{addr_reg})", []],
        "lbu": [f"lbu x{data_reg}, 0(x{addr_reg})", []],
        "lh": [f"lh x{data_reg}, 0(x{addr_reg})", []],
        "lhu": [f"lhu x{data_reg}, 0(x{addr_reg})", []],
        "lw": [f"lw x{data_reg}, 0(x{addr_reg})", []],
        "sd": [f"sd x{data_reg}, 0(x{addr_reg})", []],
        "lwu": [f"lwu x{data_reg}, 0(x{addr_reg})", []],
        "ld": [f"ld x{data_reg}, 0(x{addr_reg})", []],
        "fsw": [f"fsw f{data_reg}, 0(x{addr_reg})", ["f"]],
        "flw": [f"flw f{data_reg}, 0(x{addr_reg})", ["f"]],
        "fsd": [f"fsd f{data_reg}, 0(x{addr_reg})", ["d"]],
        "fld": [f"fld f{data_reg}, 0(x{addr_reg})", ["d"]],
        "fsh": [f"fsh f{data_reg}, 0(x{addr_reg})", ["zfh"]],
        "flh": [f"flh f{data_reg}, 0(x{addr_reg})", ["zfh"]],
        "c.sw": [f"c.sw x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.lw": [f"c.lw x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.swsp": [f"c.swsp x{data_reg}, 0(sp)", ["zca"]],
        "c.lwsp": [f"c.lwsp x{data_reg}, 0(sp)", ["zca"]],
        "c.sd": [f"c.sd x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.ld": [f"c.ld x{data_reg}, 0(x{addr_reg})", ["zca"]],
        "c.sdsp": [f"c.sdsp x{data_reg}, 0(sp)", ["zca"]],
        "c.ldsp": [f"c.ldsp x{data_reg}, 0(sp)", ["zca"]],
        "c.sb": [f"c.sb x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.sh": [f"c.sh x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.lbu": [f"c.lbu x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.lh": [f"c.lh x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.lhu": [f"c.lhu x{data_reg}, 0(x{addr_reg})", ["zcb"]],
        "c.fsw": [f"c.fsw f{data_reg}, 0(x{addr_reg})", ["zcf"]],
        "c.flw": [f"c.flw f{data_reg}, 0(x{addr_reg})", ["zcf"]],
        "c.fswsp": [f"c.fswsp f{data_reg}, 0(sp)", ["zcf"]],
        "c.flwsp": [f"c.flwsp f{data_reg}, 0(sp)", ["zcf"]],
        "c.fsd": [f"c.fsd f{data_reg}, 0(x{addr_reg})", ["zcd"]],
        "c.fld": [f"c.fld f{data_reg}, 0(x{addr_reg})", ["zcd"]],
        "c.fsdsp": [f"c.fsdsp f{data_reg}, 0(sp)", ["zcd"]],
        "c.fldsp": [f"c.fldsp f{data_reg}, 0(sp)", ["zcd"]],
    }
    sp_setup_asm = [f"mv x{sp_reg}, sp", "LA(sp, scratch)"]
    sp_teardown_asm = [f"mv sp, x{sp_reg}"]

    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        lines.extend(_xsl_ifdefs(0b011))
        for tdata2 in ("scratch", 0):
            for size in (0, 1, 2, 3, 5):
                lines.append(f"\n# Size = {size}")
                if size > 0:
                    lines.append("#ifdef UDB_SDTRIG_MCONTROL6_SIZE_AVAILABLE")
                lines.extend(
                    [
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, select=0, size=size),
                        f"LA(x{addr_reg}, scratch) # load/store address",
                        f"LI(x{data_reg}, {random_int(32, signed=False)}) # random load/store value",
                        "#ifdef F_SUPPORTED",
                        *_arch_guard(f"fmv.w.x f{data_reg}, x{data_reg}", ["f"]),
                        "#endif",
                    ]
                )
                for instr in instr_asm:
                    binname = f"trig_num_{trig_num}_td2_{tdata2}_size_{size}_instr_{instr}"
                    lines.extend(
                        [
                            _add_tc(test_data, binname, coverpoint, covergroup),
                            *_ifdef_guard(instr),
                            *(sp_setup_asm if instr.endswith("sp") else []),
                            *_arch_guard(instr_asm[instr][0], instr_asm[instr][1]),
                            "nop # spacer",
                            *(sp_teardown_asm if instr.endswith("sp") else []),
                            *_ifdef_guard(instr, closing=True),
                        ]
                    )
                if size > 0:
                    lines.append("#endif // UDB_SDTRIG_MCONTROL6_SIZE_AVAILABLE")
        lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(0b011)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_match"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 match types equal / ge / lt / not-equal",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        lines.extend(_xsl_ifdefs(0b011))
        for match in (0, 2, 3, 8):
            lines.append(f"\n# Match = {match}")
            if match > 0:
                lines.append("#ifdef UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE")
            lines.append("#if __riscv_xlen == 32")
            for data in (0x00000000, 0x12345677, 0x12345678, 0x12345679, 0xFFFFFFFF):
                tdata2 = 0x12345678
                binname = f"RV32_trig_num_{trig_num}_match_{match}_tdata2_{tdata2:x}_data_{data:x}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, match=match, select=1),
                        f"LA(x{addr_reg}, scratch) # store address",
                        f"LI(x{data_reg}, {data}) # store data value",
                        f"sw x{data_reg}, 0(x{addr_reg})",
                        "nop # spacer (data match fires after)",
                    ]
                )
            lines.append("#else // XLEN == 64")
            for data in (
                0x0000000000000000,
                0x123456789ABCDEEF,
                0x123456789ABCDEF0,
                0x123456789ABCDEF1,
                0xFFFFFFFFFFFFFFFF,
            ):
                tdata2 = 0x123456789ABCDEF0
                binname = f"RV64_trig_num_{trig_num}_match_{match}_tdata2_{tdata2:x}_data_{data:x}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, match=match, select=1),
                        f"LA(x{addr_reg}, scratch)",
                        f"LI(x{data_reg}, {data})",
                        f"sd x{data_reg}, 0(x{addr_reg})",
                        "nop # spacer (data match fires after)",
                    ]
                )
            lines.append("#endif // __riscv_xlen")
            if match > 0:
                lines.append("#endif // UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE")
        lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(0b011)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_match_napot"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 NAPOT and not-NAPOT match types",
        )
    )

    def walking_zeros(xlen: int) -> list[str]:
        values = []
        all_ones = (1 << xlen) - 1  # e.g. 0xFFFF...F for xlen bits
        for i in range(xlen):
            values.append(hex(all_ones & ~(1 << i)))  # clear bit i
        return values

    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        lines.extend(_xsl_ifdefs(0b011))
        lines.append("\n#ifdef UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE")
        for match in (1, 9):
            lines.append(f"\n# Match = {match}")
            lines.append("#if __riscv_xlen == 32")
            for data in (0x00000000, 0x12345678, 0xFFFFFFFF, *walking_zeros(32)):
                binname = f"RV32_trig_num_{trig_num}_match_{match}_data_{data}"
                tdata2 = 0xFFFFFFFF
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, match=match, select=1),
                        f"LA(x{addr_reg}, scratch)",
                        f"LI(x{data_reg}, {data})",
                        f"sw x{data_reg}, 0(x{addr_reg})",
                        "nop # spacer (data match fires after)",
                    ]
                )
            lines.append("#endif")
            lines.append("#if __riscv_xlen == 64")
            for data in (
                0x0000000000000000,
                0x123456789ABCDEF0,
                0xFFFFFFFFFFFFFFFF,
                *walking_zeros(64),
            ):  # TODO match top M bits but not lower bits, not match top M bits in one place but does match lower bits
                binname = f"RV64_trig_num_{trig_num}_match_{match}_data_{data}"
                tdata2 = 0xFFFFFFFFFFFFFFFF  # TODO Walk zeros
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, match=match, select=1),
                        f"LA(x{addr_reg}, scratch)",
                        f"LI(x{data_reg}, {data})",
                        f"sd x{data_reg}, 0(x{addr_reg})",
                        "nop # spacer (data match fires after)",
                    ]
                )
            lines.append("#endif")
        lines.append("#endif // UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE")
        lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(0b011)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_match_mask"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "mcontrol6 mask-low / mask-high match types",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        lines.extend(_xsl_ifdefs(0b011))
        lines.append("\n#ifdef UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE")
        for match in (4, 5, 12, 13):  # 4: mask low, 5: mask high, 12: not mask low, 13: not mask high
            lines.append(f"\n# Match = {match}")
            lines.append("#if __riscv_xlen == 32")
            for data in (0x00000000, 0x12345678, 0xFFFF5678, 0x1234FFFF, 0xFFFFFFFF):
                binname = f"RV32_trig_num_{trig_num}_match_{match}_data_{data}"
                tdata2 = 0x12345678
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, match=match, select=1),
                        f"LA(x{addr_reg}, scratch)",
                        f"LI(x{data_reg}, {data})",
                        f"sw x{data_reg}, 0(x{addr_reg})",
                        "nop # spacer (data match fires after)",
                    ]
                )
            lines.append("#else // XLEN == 64")
            for data in (
                0x0000000000000000,
                0x123456789ABCDEF0,
                0xFFFFFFFF9ABCDEF0,
                0x12345678FFFFFFFF,
                0xFFFFFFFFFFFFFFFF,
            ):
                binname = f"RV64_trig_num_{trig_num}_match_{match}_data_{data}"
                tdata2 = 0x123456789ABCDEF0
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        *_config_mcontrol6(temp_reg, trig_num, tdata2, mode, xsl=0b011, match=match, select=1),
                        f"LA(x{addr_reg}, scratch)",
                        f"LI(x{data_reg}, {data})",
                        f"sd x{data_reg}, 0(x{addr_reg})",
                        "nop # spacer (data match fires after)",
                    ]
                )
            lines.append("#endif")
        lines.append("#endif // UDB_SDTRIG_MCONTROL6_MATCH_AVAILABLE")
        lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(0b011)))
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    ######################################
    coverpoint = "cp_sdtrig_mcontrol6_chain_adr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "chained mcontrol6 triggers fire only when both match the same\n"
            "instruction (trigN chain=1 address, trigN+1 chain=0 data)",
        )
    )
    match_val = random_int(32, signed=False)

    for trig_num in range(UDB_NUM_TRIGGERS - 1):
        lines.append(f"\n#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")
        lines.append(f"#ifdef UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num + 1}")
        lines.append("#ifdef UDB_SDTRIG_MCONTROL6_CHAIN_AVAILABLE")
        lines.extend(_xsl_ifdefs(0b010))
        lines.extend(
            [
                *_config_mcontrol6(temp_reg, trig_num, "scratch", mode, xsl=0b010, select=0, chain=1),
                *_config_mcontrol6(temp_reg, trig_num + 1, match_val, mode, xsl=0b010, select=1, chain=0),
                f"LA(x{addr_reg}, scratch)",
            ]
        )
        # sweep data-match x addr-match; only both-match fires the chained pair
        for data_case, data in [("Fire", match_val), ("NoFire", 0)]:
            for adr_case, offset in [("Fire", 0), ("NoFire", 8)]:
                binname = f"trig_nums_{trig_num}_{trig_num + 1}_data_{data_case}_adr_{adr_case}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        f"LI(x{data_reg}, {data})",
                        f"sw x{data_reg}, {offset}(x{addr_reg}) # fire trigger when both triggers match",
                        "nop # spacer (data match fires after)",
                    ]
                )
        lines.extend(["#endif // UDB_SDTRIG_MCONTROL6_XSL_AVAILABLE"] * len(_xsl_ifdefs(0b010)))
        lines.append("#endif // UDB_SDTRIG_MCONTROL6_CHAIN_AVAILABLE")
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.extend(_disable_trigger(temp_reg, trig_num + 1, mode))
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num + 1}")
        lines.append(f"#endif // UDB_SDTRIG_MCONTROL6_SUPPORTED{trig_num}")

    lines.extend(_global_ie(mode, False))
    test_data.int_regs.return_registers([sp_reg, addr_reg, data_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_icount_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate icount instruction-count trigger tests."""
    # covergroup = f"Sdtrig{mode}_icount_cg"
    tc = test_data.begin_test_chunk("Icount")
    lines: list[str] = tc.code

    # setup registers
    sp_reg, addr_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        4, exclude_regs=[2], reg_range=list(range(8, 16))
    )  # exclude a0, a1 because they are used in SBI

    ######################################
    coverpoint = "cp_sdtrig_icount_hardwired"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount priv/action hard-wired field behavior",
        )
    )
    # lines.append("#ifdef UDB_ICOUNT_HARDWIRED_1")
    # for trig_num in range(UDB_NUM_TRIGGERS):
    #     lines.append(f"#ifdef UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")
    #     binname = f"trig_num_{trig_num}"
    #     lines.extend(
    #         [
    #             _add_tc(test_data, binname, coverpoint, covergroup),
    #             *_config_icount(temp_reg, trig_num, 1, mode, privbits=0b11111),
    #             "nop # decrement count",
    #             _csr_access(f"csrr x{data_reg}, tdata1 # read back hardwired fields", mode),
    #             *_sigupd_masked(data_reg, temp_reg, 0x1000000, test_data, "icount hit bit (bit 24)"),
    #             *_disable_trigger(temp_reg, trig_num, mode)
    #         ]
    #     )
    #     lines.append(f"#endif // UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")
    # lines.append("#endif")

    ######################################
    coverpoint = "cp_sdtrig_icount_instr"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount fires after count instructions",
        )
    )
    # for trig_num in range(UDB_NUM_TRIGGERS):
    #     lines.append(f"#ifdef UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")
    #     for priv_en in (0, 1):  # trigger disabled/enabled in the current mode
    #         privbits = MODE_PRIVBIT[mode] if priv_en else 0
    #         binname = f"trig_num_{trig_num}_priv_{priv_en}"
    #         lines.extend(
    #             [
    #                 _add_tc(test_data, binname, coverpoint, covergroup),
    #                 *_config_icount(temp_reg, trig_num, 9, mode, privbits=privbits),
    #                 *["nop # decrement count"] * 9,
    #                 "nop # spacer",
    #                 _csr_access(f"csrr x{data_reg}, tdata1 # read back hardwired fields", mode),
    #                 *_sigupd_masked(data_reg, temp_reg, 0x1000000, test_data, "icount hit bit (bit 24)"),
    #                 *_disable_trigger(temp_reg, trig_num, mode),
    #             ]
    #         )
    #     lines.append(f"#endif // UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_icount_trap"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount count decrement across a trap",
        )
    )
    # for trig_num in range(UDB_NUM_TRIGGERS):
    #     lines.append(f"#ifdef UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")
    #     for priv_en in (0, 1):  # trigger disabled/enabled in the current mode
    #         privbits = MODE_PRIVBIT[mode] if priv_en else 0
    #         binname = f"trig_num_{trig_num}_priv_{priv_en}"
    #         lines.extend(
    #             [
    #                 _add_tc(test_data, binname, coverpoint, covergroup),
    #                 *_config_icount(temp_reg, trig_num, 1, mode, privbits=privbits),
    #                 ".word 0x00000000",
    #                 "nop # spacer",
    #                 _csr_access(f"csrr x{data_reg}, tdata1 # read back hardwired fields", mode),
    #                 *_sigupd_masked(data_reg, temp_reg, 0x1000000, test_data, "icount hit bit (bit 24)"),
    #                 *_disable_trigger(temp_reg, trig_num, mode),
    #             ]
    #         )
    #     lines.append(f"#endif // UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")

    ######################################
    coverpoint = "cp_sdtrig_icount_eq0"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "icount pending bit when count reaches 0",
        )
    )
    # for trig_num in range(UDB_NUM_TRIGGERS):
    #     lines.append(f"#ifdef UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")
    #     for pending in (0, 1):  # tdata1[8]
    #         binname = f"trig_num_{trig_num}_pending_{pending}"
    #         lines.extend(
    #             [
    #                 _add_tc(test_data, binname, coverpoint, covergroup),
    #                 *_config_icount(temp_reg, trig_num, 0, mode, pending=pending),
    #                 "nop # Fires trigger when pending = 1",
    #                 *["nop # count must stay zero"] * 9,
    #                 _csr_access(f"csrr x{data_reg}, tdata1 # read back hardwired fields", mode),
    #                 *_sigupd_masked(data_reg, temp_reg, 0x1000000, test_data, "icount hit bit (bit 24)"),
    #                 *_disable_trigger(temp_reg, trig_num, mode),
    #             ]
    #         )
    #     lines.append(f"#endif // UDB_ICOUNT_TRIG{trig_num}_AVAILABLE")

    test_data.int_regs.return_registers([sp_reg, addr_reg, data_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_itrigger_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate itrigger interrupt trigger tests."""
    covergroup = f"Sdtrig{mode}_itrigger_cg"
    tc = test_data.begin_test_chunk("Itrigger")
    lines: list[str] = tc.code

    # setup registers
    t1, t2, t3, t4 = test_data.int_regs.get_registers(4, exclude_regs=[2], reg_range=list(range(8, 16)))

    ######################################
    coverpoint = "cp_sdtrig_itrigger"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "itrigger fires on each interrupt cause in the tdata2 mask",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"#ifdef UDB_ITRIGGER_TRIG{trig_num}_AVAILABLE")
        for code in (1,):  # one interrupt type at a time while debugging (1=SSIP)
            for priv in (0, MODE_PRIVBIT[mode]):
                binname = f"trig_num_{trig_num}_code_{code}_priv_{priv:05b}"

                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                        # *_config_itrigger(t1, trig_num, 1 << code, mode, privbits=priv),
                        # *_cause_interrupt(code, mode, t1),
                        # "nop # spacer",
                    ]
                )
        lines.append("#endif")  # endif ITRIGGER_SUPPORTED

    test_data.int_regs.return_registers([t1, t2, t3, t4])

    return [test_data.end_test_chunk()]


def _generate_etrigger_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate etrigger exception trigger tests."""
    covergroup = f"Sdtrig{mode}_etrigger_cg"
    tc = test_data.begin_test_chunk("Etrigger")
    lines: list[str] = tc.code

    cfg_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        3, exclude_regs=[2, 10, 11], reg_range=list(range(8, 16))
    )

    ######################################
    coverpoint = "cp_sdtrig_etrigger"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "etrigger fires (breakpoint) iff the raised exception code is set\n"
            "in tdata2 AND tdata1.priv is set; tval is forced to 0 on match",
        )
    )

    # Exception codes under test
    codes_to_test = _etrigger_codes_to_test(mode)

    if any(code in _PAGE_FAULT_CODES for code in codes_to_test):
        lines.extend(_generate_page_table_data_section())

    # Exception value CSR for the current privilege mode.
    tval_csr = "mtval" if mode == "Sm" else "stval"

    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_ETRIGGER_SUPPORTED{trig_num}")
        for code in codes_to_test:
            name = ETRIGGER_EXCODE_NAMES[code]
            lines.append(f"\n#ifdef UDB_EXCEPTION_{name.upper()}_SUPPORTED")
            raised_codes = (code,) if code == 2 else (code, 2)
            for priv_en in (0, 1):
                privbits = MODE_PRIVBIT[mode] if priv_en else 0
                for raised_code in raised_codes:
                    outcome = "match" if raised_code == code else "mismatch"
                    binname = f"trig_num_{trig_num}_code_{name}_priv{priv_en}_{outcome}"
                    is_pf = raised_code in _PAGE_FAULT_CODES

                    lines.extend(
                        [
                            _add_tc(test_data, binname, coverpoint, covergroup),
                            *_config_etrigger(cfg_reg, trig_num, 1 << code, mode, privbits=privbits),
                        ]
                    )
                    bp_token = _sdtrig_bp_arm(raised_code)
                    if is_pf:
                        lines.extend(_page_fault_setup(raised_code))
                    if bp_token:
                        lines.append(f"LI(a1, {bp_token}) # sdtrig: note for the handler if this becomes a bp")
                    lines.extend(
                        [
                            *_cause_exception(
                                raised_code,
                                mode,
                                data_reg,
                                temp_reg,
                                mprv_scratch_reg=cfg_reg if (is_pf and mode == "Sm") else None,
                            ),
                        ]
                    )
                    if bp_token:
                        lines.append("LI(a1, SDTRIG_BP_NONE) # sdtrig: clear the note")
                    if is_pf:
                        lines.extend(_page_fault_teardown())
                    lines.extend(
                        [
                            f"csrr x{data_reg}, {tval_csr} # 0 iff matched",
                            write_sigupd(data_reg, test_data),
                        ]
                    )
                    lines.extend(_check_etrigger_hit(cfg_reg, data_reg, trig_num, mode, test_data))
            lines.append(f"#endif // UDB_EXCEPTION_{name.upper()}_SUPPORTED")
        lines.extend(_disable_trigger(temp_reg, trig_num, mode))
        lines.append(f"#endif // UDB_SDTRIG_ETRIGGER_SUPPORTED{trig_num}")

    test_data.int_regs.return_registers([cfg_reg, data_reg, temp_reg])
    return [test_data.end_test_chunk()]


def etrigger_cross_priv_delegate_test(test_data: TestData, target_mode: str) -> list[TestChunk]:
    """Etrigger cross-privilege delegation tests."""
    if target_mode not in ("S", "U"):
        raise ValueError(f"etrigger_cross_priv_delegate_test: target_mode must be 'S' or 'U', got {target_mode!r}")

    covergroup = f"SdtrigSm_etrigger_cross_priv_{target_mode}_cg"
    tc = test_data.begin_test_chunk(f"EtriggerCrossPriv{target_mode}")
    lines: list[str] = tc.code

    cfg_reg, data_reg, temp_reg = test_data.int_regs.get_registers(
        3, exclude_regs=[2, 10, 11], reg_range=list(range(8, 16))
    )

    ######################################
    coverpoint = "cp_sdtrig_etrigger_cross_priv"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            f"etrigger configured in M fires on a matching exception raised while\n"
            f"executing in {target_mode}-mode, independent of medeleg[cause]; tdata1.priv\n"
            f"gates the match and tval is forced to 0 on match",
        )
    )

    codes_to_test = _etrigger_codes_to_test(target_mode, cross_priv=True)
    goto_target = "RVTEST_TSBI_GOTO_SMODE" if target_mode == "S" else "RVTEST_TSBI_GOTO_UMODE"

    if any(code in _PAGE_FAULT_CODES for code in codes_to_test):
        lines.extend(_generate_page_table_data_section())

    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.append(f"\n#ifdef UDB_SDTRIG_ETRIGGER_SUPPORTED{trig_num}")
        for code in codes_to_test:
            name = ETRIGGER_EXCODE_NAMES[code]
            lines.append(f"\n#ifdef UDB_EXCEPTION_{name.upper()}_SUPPORTED")
            raised_codes = (code,) if code == 2 else (code, 2)

            for priv_en in (0, 1):
                privbits = MODE_PRIVBIT[target_mode] if priv_en else 0
                for medeleg_en in (0, 1):
                    for raised_code in raised_codes:
                        outcome = "match" if raised_code == code else "mismatch"
                        is_pf = raised_code in _PAGE_FAULT_CODES
                        binname = (
                            f"trig_num_{trig_num}_{target_mode.lower()}_code_{name}"
                            f"_priv{priv_en}_medeleg{medeleg_en}_{outcome}"
                        )

                        lines.extend(
                            [
                                _add_tc(test_data, binname, coverpoint, covergroup),
                                *_config_etrigger(cfg_reg, trig_num, 1 << code, "Sm", privbits=privbits),
                                *(_set_medeleg(temp_reg, raised_code, bool(medeleg_en)) if raised_code == code else []),
                                *_set_medeleg(temp_reg, 3, False),  # Trigger -> Breakpoint handled in M-mode
                                goto_target,
                            ]
                        )
                        bp_token = _sdtrig_bp_arm(raised_code)
                        if is_pf:
                            lines.extend(_page_fault_setup(raised_code))
                        if bp_token:
                            lines.append(f"LI(a1, {bp_token}) # sdtrig: note for the handler if this becomes a bp")
                        lines.extend(_cause_exception(raised_code, target_mode, data_reg, temp_reg))
                        if bp_token:
                            lines.append("LI(a1, SDTRIG_BP_NONE) # sdtrig: clear the notessss")
                        if is_pf:
                            lines.extend(_page_fault_teardown())
                        lines.extend(
                            [
                                "RVTEST_GOTO_DELEGATED_MMODE" if code in (8, 9) else "RVTEST_TSBI_GOTO_MMODE",
                                _csr_access(f"csrr x{data_reg}, mtval # 0 iff matched", "Sm"),
                                write_sigupd(data_reg, test_data),
                                *(_set_medeleg(temp_reg, raised_code, False) if raised_code == code else []),
                            ]
                        )
                        lines.extend(_check_etrigger_hit(cfg_reg, data_reg, trig_num, "Sm", test_data))
            lines.append(f"#endif // UDB_EXCEPTION_{name.upper()}_SUPPORTED")
        lines.extend(_disable_trigger(temp_reg, trig_num, "Sm"))
        lines.append(f"#endif // UDB_SDTRIG_ETRIGGER_SUPPORTED{trig_num}")

    test_data.int_regs.return_registers([cfg_reg, data_reg, temp_reg])
    return [test_data.end_test_chunk()]


def _generate_textra_tests(test_data: TestData, mode: str) -> list[TestChunk]:
    """Generate textra32/64 (tdata3) context-matching tests."""
    covergroup = f"Sdtrig{mode}_textra_cg"
    tc = test_data.begin_test_chunk("Textra")
    lines: list[str] = tc.code

    trig_type4 = ("icount", "itrigger", "etrigger", "mcontrol6")
    # RV64 spelling; RV32 bins differ (see svh)
    mhvalue = ("match", "zero", "half")
    svalue = ("aaaaaaaa", "bbbbbbaa", "bbbbaabb", "bbaabbbb", "aabbbbbb", "bbbbbbbb")
    svalue_asid = ("below", "equal", "above")

    ######################################
    coverpoint = "cp_sdtrig_textra_mcontext"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "textra mhselect/mhvalue match against mcontext",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for tt in trig_type4:
            for mhv in mhvalue:
                binname = f"trig_num_{trig_num}_type_{tt}_mhvalue_{mhv}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_textra_scontext"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "textra sselect=scontext svalue/sbytemask match against scontext",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for tt in trig_type4:
            for sv in svalue:
                for mask in range(4):  # sbytemask (RV64: 4 bits; RV32: 2 bits -> range(4))
                    binname = f"trig_num_{trig_num}_type_{tt}_svalue_{sv}_mask_{mask:02b}"
                    lines.extend(
                        [
                            _add_tc(test_data, binname, coverpoint, covergroup),
                        ]
                    )

    ######################################
    coverpoint = "cp_sdtrig_textra_asid"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "textra sselect=asid match against satp.ASID",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        for tt in trig_type4:
            for sv in svalue_asid:
                binname = f"trig_num_{trig_num}_type_{tt}_asid_{sv}"
                lines.extend(
                    [
                        _add_tc(test_data, binname, coverpoint, covergroup),
                    ]
                )

    ######################################
    coverpoint = "cp_sdtrig_smode_fields_hardwired"
    ######################################
    lines.append(
        comment_banner(
            coverpoint,
            "svalue/sselect read 0 when S-mode is not supported",
        )
    )
    for trig_num in range(UDB_NUM_TRIGGERS):
        lines.extend(
            [
                _add_tc(test_data, f"trig_num_{trig_num}_hardwired", coverpoint, covergroup),
            ]
        )

    return [test_data.end_test_chunk()]


# ── Suite assembly ─────────────────────────────────────────────────────────


def generate_sdtrig_suite(test_data: TestData, mode: str) -> list[TestChunk]:
    """Assemble the full Sdtrig suite for ``mode`` ("Sm"/"S"/"U") as test chunks."""
    test_chunks: list[TestChunk] = []
    test_chunks.extend(_generate_access_tests(test_data, mode))
    test_chunks.extend(_generate_native_triggers_tests(test_data, mode))
    # test_chunks.extend(_generate_a_tests(test_data, mode))
    # test_chunks.extend(_generate_combined_accesses_tests(test_data, mode))
    # test_chunks.extend(_generate_cache_operations_tests(test_data, mode))
    # test_chunks.extend(_generate_address_matches_tests(test_data, mode))
    # test_chunks.extend(_generate_csr_tests(test_data, mode))
    test_chunks.extend(_generate_mcontrol6_tests(test_data, mode))
    test_chunks.extend(_generate_icount_tests(test_data, mode))
    test_chunks.extend(_generate_itrigger_tests(test_data, mode))
    test_chunks.extend(_generate_etrigger_tests(test_data, mode))
    if mode == "Sm":
        test_chunks.extend(etrigger_cross_priv_delegate_test(test_data, "S"))
        test_chunks.extend(etrigger_cross_priv_delegate_test(test_data, "U"))
    # test_chunks.extend(_generate_textra_tests(test_data, mode))
    return test_chunks
