#define ACCESS_FAULT_ADDRESS 0x00000000
#define RVMODEL_PMP_GRAIN 4
#define RVMODEL_NUM_PMPS 16
#define D_SUPPORTED
#define ZFA_SUPPORTED
#define F_SUPPORTED
#define ZFH_SUPPORTED
#define ZBB_SUPPORTED
#define ZBA_SUPPORTED
#define ZBS_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZCA_SUPPORTED
#define ZCB_SUPPORTED
#define ZCF_SUPPORTED
#define ZCD_SUPPORTED

#define TIME_CSR_IMPLEMENTED 1

#define SEW_MIN 8
#define ELEN 64
#define VECTOR_LS_INDEX_MAX_EEW 64
